document.write("<div id=प्रभाचन्द्राचार्य class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='001.html'><font size=4><font color=darkPurple><b>001</b></font> - <font color=darkBlue>﻿मंगलाचरण</font></font></a></li>");
document.write("        <li><a href='002.html'><font size=4><font color=darkPurple><b>002</b></font> - <font color=darkGreen>﻿आचार्य की प्रतिज्ञा</font></font></a></li>");
document.write("        <li><a href='003.html'><font size=4><font color=darkPurple><b>003</b></font> - <font color=darkBlue>﻿धर्म का लक्षण</font></font></a></li>");
document.write("        <li><a href='004.html'><font size=4><br><font size=5 color=black><b>﻿सम्यग्दर्शन-अधिकार </b></font><br><br><font color=darkPurple><b>004</b></font> - <font color=darkGreen>﻿सम्यग्दर्शन</font></font></a></li>");
document.write("        <li><a href='005.html'><font size=4><font color=darkPurple><b>005</b></font> - <font color=darkBlue>﻿आप्त का लक्षण</font></font></a></li>");
document.write("        <li><a href='006.html'><font size=4><font color=darkPurple><b>006</b></font> - <font color=darkGreen>﻿वीतराग का लक्षण</font></font></a></li>");
document.write("        <li><a href='008.html'><font size=4><font color=darkPurple><b>008</b></font> - <font color=darkBlue>﻿आगम का लक्षण</font></font></a></li>");
document.write("        <li><a href='009.html'><font size=4><font color=darkPurple><b>009</b></font> - <font color=darkGreen>﻿शास्त्र का लक्षण</font></font></a></li>");
document.write("        <li><a href='010.html'><font size=4><font color=darkPurple><b>010</b></font> - <font color=darkBlue>﻿गुरु का लक्षण</font></font></a></li>");
document.write("        <li><a href='011.html'><font size=4><font color=darkPurple><b>011</b></font> - <font color=darkGreen>﻿नि:शंकित अंग</font></font></a></li>");
document.write("        <li><a href='012.html'><font size=4><font color=darkPurple><b>012</b></font> - <font color=darkBlue>﻿नि:कांक्षित अंग</font></font></a></li>");
document.write("        <li><a href='013.html'><font size=4><font color=darkPurple><b>013</b></font> - <font color=darkGreen>﻿निर्विचिकित्सा अंग</font></font></a></li>");
document.write("        <li><a href='014.html'><font size=4><font color=darkPurple><b>014</b></font> - <font color=darkBlue>﻿अमूढ़दृष्टि अंग</font></font></a></li>");
document.write("        <li><a href='015.html'><font size=4><font color=darkPurple><b>015</b></font> - <font color=darkGreen>﻿उपगूहन अंग</font></font></a></li>");
document.write("        <li><a href='016.html'><font size=4><font color=darkPurple><b>016</b></font> - <font color=darkBlue>﻿स्थितिकरण अंग</font></font></a></li>");
document.write("        <li><a href='017.html'><font size=4><font color=darkPurple><b>017</b></font> - <font color=darkGreen>﻿वात्सल्य अंग</font></font></a></li>");
document.write("        <li><a href='018.html'><font size=4><font color=darkPurple><b>018</b></font> - <font color=darkBlue>﻿प्रभावना अंग</font></font></a></li>");
document.write("        <li><a href='019-020.html'><font size=4><font color=darkPurple><b>019-020</b></font> - <font color=darkGreen>﻿आठ अंगधारी के नाम</font></font></a></li>");
document.write("        <li><a href='021.html'><font size=4><font color=darkPurple><b>021</b></font> - <font color=darkBlue>﻿अंगहीन सम्यक्त्व व्यर्थ है</font></font></a></li>");
document.write("        <li><a href='022.html'><font size=4><font color=darkPurple><b>022</b></font> - <font color=darkGreen>﻿लोक मूढ़ता</font></font></a></li>");
document.write("        <li><a href='023.html'><font size=4><font color=darkPurple><b>023</b></font> - <font color=darkBlue>﻿देव मूढ़ता</font></font></a></li>");
document.write("        <li><a href='024.html'><font size=4><font color=darkPurple><b>024</b></font> - <font color=darkGreen>﻿अब सम्यग्दर्शन के स्वरूप में पाखण्डि मूढ़ता का स्वरूप दिखाते हुए कहते हैं-</font></font></a></li>");
document.write("        <li><a href='025.html'><font size=4><font color=darkPurple><b>025</b></font> - <font color=darkBlue>﻿आठमद के नाम</font></font></a></li>");
document.write("        <li><a href='026.html'><font size=4><font color=darkPurple><b>026</b></font> - <font color=darkGreen>﻿मद करने से हानि</font></font></a></li>");
document.write("        <li><a href='027.html'><font size=4><font color=darkPurple><b>027</b></font> - <font color=darkBlue>﻿पाप त्याग का उपदेश</font></font></a></li>");
document.write("        <li><a href='028.html'><font size=4><font color=darkPurple><b>028</b></font> - <font color=darkGreen>﻿सम्यग्दर्शन की महिमा</font></font></a></li>");
document.write("        <li><a href='029.html'><font size=4><font color=darkPurple><b>029</b></font> - <font color=darkBlue>﻿धर्म और अधर्म का फल</font></font></a></li>");
document.write("        <li><a href='030.html'><font size=4><font color=darkPurple><b>030</b></font> - <font color=darkGreen>﻿सम्यग्दृष्टि कुदेवादिक को नमन ना करे</font></font></a></li>");
document.write("        <li><a href='031.html'><font size=4><font color=darkPurple><b>031</b></font> - <font color=darkBlue>﻿सम्यग्दर्शन की श्रेष्ठता</font></font></a></li>");
document.write("        <li><a href='032.html'><font size=4><font color=darkPurple><b>032</b></font> - <font color=darkGreen>﻿सम्यग्दर्शन के बिना ज्ञान चारित्र की असम्भवता</font></font></a></li>");
document.write("        <li><a href='033.html'><font size=4><font color=darkPurple><b>033</b></font> - <font color=darkBlue>﻿मोही मुनि की अपेक्षा निर्मोही गृहस्थ श्रेष्ठ</font></font></a></li>");
document.write("        <li><a href='034.html'><font size=4><font color=darkPurple><b>034</b></font> - <font color=darkGreen>﻿श्रेय और अश्रेय का कथन</font></font></a></li>");
document.write("        <li><a href='035.html'><font size=4><font color=darkPurple><b>035</b></font> - <font color=darkBlue>﻿सम्यग्दृष्टि के अनुत्पत्ति के स्थान</font></font></a></li>");
document.write("        <li><a href='036.html'><font size=4><font color=darkPurple><b>036</b></font> - <font color=darkGreen>﻿सम्यग्दृष्टि जीव श्रेष्ठ मनुष्य होते हैं </font></font></a></li>");
document.write("        <li><a href='037.html'><font size=4><font color=darkPurple><b>037</b></font> - <font color=darkBlue>﻿सम्यग्दृष्टि जीव इंद्र पद पाते हैं</font></font></a></li>");
document.write("        <li><a href='038.html'><font size=4><font color=darkPurple><b>038</b></font> - <font color=darkGreen>﻿सम्यग्दृष्टि ही चक्रवर्ती होते हैं</font></font></a></li>");
document.write("        <li><a href='039.html'><font size=4><font color=darkPurple><b>039</b></font> - <font color=darkBlue>﻿सम्यग्दृष्टि ही तीर्थंकर होते हैं</font></font></a></li>");
document.write("        <li><a href='040.html'><font size=4><font color=darkPurple><b>040</b></font> - <font color=darkGreen>﻿सम्यग्दृष्टि ही मोक्ष-पद प्राप्त करते हैं</font></font></a></li>");
document.write("        <li><a href='041.html'><font size=4><font color=darkPurple><b>041</b></font> - <font color=darkBlue>﻿उपसंहार</font></font></a></li>");
document.write("        <li><a href='042.html'><font size=4><br><font size=5 color=black><b>﻿सम्यग्ज्ञान-अधिकार </b></font><br><br><font color=darkPurple><b>042</b></font> - <font color=darkGreen>﻿सम्यग्ज्ञान का लक्षण</font></font></a></li>");
document.write("        <li><a href='043.html'><font size=4><font color=darkPurple><b>043</b></font> - <font color=darkBlue>﻿प्रथमानुयोग</font></font></a></li>");
document.write("        <li><a href='044.html'><font size=4><font color=darkPurple><b>044</b></font> - <font color=darkGreen>﻿करणानुयोग</font></font></a></li>");
document.write("        <li><a href='045.html'><font size=4><font color=darkPurple><b>045</b></font> - <font color=darkBlue>﻿चरणानुयोग</font></font></a></li>");
document.write("        <li><a href='046.html'><font size=4><font color=darkPurple><b>046</b></font> - <font color=darkGreen>﻿द्रव्यानुयोग</font></font></a></li>");
document.write("        <li><a href='047.html'><font size=4><br><font size=5 color=black><b>﻿सम्यक-चारित्र-अधिकार </b></font><br><br><font color=darkPurple><b>047</b></font> - <font color=darkBlue>﻿चारित्र की आवश्यकता</font></font></a></li>");
document.write("        <li><a href='048.html'><font size=4><font color=darkPurple><b>048</b></font> - <font color=darkGreen>﻿चारित्र कब होता है?</font></font></a></li>");
document.write("        <li><a href='049.html'><font size=4><font color=darkPurple><b>049</b></font> - <font color=darkBlue>﻿चारित्र का लक्षण</font></font></a></li>");
document.write("        <li><a href='050.html'><font size=4><font color=darkPurple><b>050</b></font> - <font color=darkGreen>﻿चारित्र के भेद और उपासक</font></font></a></li>");
document.write("        <li><a href='051.html'><font size=4><font color=darkPurple><b>051</b></font> - <font color=darkBlue>﻿विकल चारित्र के भेद</font></font></a></li>");
document.write("        <li><a href='052.html'><font size=4><br><font size=5 color=black><b>﻿अणुव्रत-अधिकार </b></font><br><br><font color=darkPurple><b>052</b></font> - <font color=darkGreen>﻿अणुव्रत का लक्षण</font></font></a></li>");
document.write("        <li><a href='053.html'><font size=4><font color=darkPurple><b>053</b></font> - <font color=darkBlue>﻿अहिंसा अणुव्रत</font></font></a></li>");
document.write("        <li><a href='054.html'><font size=4><font color=darkPurple><b>054</b></font> - <font color=darkGreen>﻿अहिंसा अणुव्रत के अतिचार</font></font></a></li>");
document.write("        <li><a href='055.html'><font size=4><font color=darkPurple><b>055</b></font> - <font color=darkBlue>﻿सत्याणुव्रत</font></font></a></li>");
document.write("        <li><a href='056.html'><font size=4><font color=darkPurple><b>056</b></font> - <font color=darkGreen>﻿सत्याणुव्रत के अतिचार</font></font></a></li>");
document.write("        <li><a href='057.html'><font size=4><font color=darkPurple><b>057</b></font> - <font color=darkBlue>﻿अचौर्याणुव्रत</font></font></a></li>");
document.write("        <li><a href='058.html'><font size=4><font color=darkPurple><b>058</b></font> - <font color=darkGreen>﻿अचौर्याणुव्रत के अतिचार</font></font></a></li>");
document.write("        <li><a href='059.html'><font size=4><font color=darkPurple><b>059</b></font> - <font color=darkBlue>﻿ब्रह्मचर्य अणुव्रत</font></font></a></li>");
document.write("        <li><a href='060.html'><font size=4><font color=darkPurple><b>060</b></font> - <font color=darkGreen>﻿ब्रह्मचर्याणुव्रत के अतिचार</font></font></a></li>");
document.write("        <li><a href='061.html'><font size=4><font color=darkPurple><b>061</b></font> - <font color=darkBlue>﻿परिग्रह परिमाण अणुव्रत</font></font></a></li>");
document.write("        <li><a href='062.html'><font size=4><font color=darkPurple><b>062</b></font> - <font color=darkGreen>﻿परिग्रह परिमाण अणुव्रत के अतिचार</font></font></a></li>");
document.write("        <li><a href='063.html'><font size=4><font color=darkPurple><b>063</b></font> - <font color=darkBlue>﻿पंचाणु व्रत का फल</font></font></a></li>");
document.write("        <li><a href='064.html'><font size=4><font color=darkPurple><b>064</b></font> - <font color=darkGreen>﻿पंचाणुव्रत में प्रसिद्ध नाम</font></font></a></li>");
document.write("        <li><a href='065.html'><font size=4><font color=darkPurple><b>065</b></font> - <font color=darkBlue>﻿पांच पाप में प्रसिद्ध नाम</font></font></a></li>");
document.write("        <li><a href='066.html'><font size=4><font color=darkPurple><b>066</b></font> - <font color=darkGreen>﻿श्रावक के आठ मूलगुण</font></font></a></li>");
document.write("        <li><a href='067.html'><font size=4><br><font size=5 color=black><b>﻿गुणव्रत-अधिकार </b></font><br><br><font color=darkPurple><b>067</b></font> - <font color=darkBlue>﻿गुणव्रतों के नाम</font></font></a></li>");
document.write("        <li><a href='068.html'><font size=4><font color=darkPurple><b>068</b></font> - <font color=darkGreen>﻿दिग्व्रत का लक्षण</font></font></a></li>");
document.write("        <li><a href='069.html'><font size=4><font color=darkPurple><b>069</b></font> - <font color=darkBlue>﻿मर्यादा की विधि</font></font></a></li>");
document.write("        <li><a href='070.html'><font size=4><font color=darkPurple><b>070</b></font> - <font color=darkGreen>﻿दिग्व्रत की मर्यादा के बाहर अणुव्रतों के महाव्रतपना</font></font></a></li>");
document.write("        <li><a href='071.html'><font size=4><font color=darkPurple><b>071</b></font> - <font color=darkBlue>﻿सो कैसे ? उसका समाधान</font></font></a></li>");
document.write("        <li><a href='072.html'><font size=4><font color=darkPurple><b>072</b></font> - <font color=darkGreen>﻿महाव्रत का लक्षण</font></font></a></li>");
document.write("        <li><a href='073.html'><font size=4><font color=darkPurple><b>073</b></font> - <font color=darkBlue>﻿दिग्व्रत के अतिचार</font></font></a></li>");
document.write("        <li><a href='074.html'><font size=4><font color=darkPurple><b>074</b></font> - <font color=darkGreen>﻿अनर्थदण्ड व्रत</font></font></a></li>");
document.write("        <li><a href='075.html'><font size=4><font color=darkPurple><b>075</b></font> - <font color=darkBlue>﻿अनर्थदण्ड के भेद</font></font></a></li>");
document.write("        <li><a href='076.html'><font size=4><font color=darkPurple><b>076</b></font> - <font color=darkGreen>﻿पापोपदेश का लक्षण</font></font></a></li>");
document.write("        <li><a href='077.html'><font size=4><font color=darkPurple><b>077</b></font> - <font color=darkBlue>﻿हिंसादान अनर्थदण्ड</font></font></a></li>");
document.write("        <li><a href='078.html'><font size=4><font color=darkPurple><b>078</b></font> - <font color=darkGreen>﻿अपध्यान अनर्थदण्ड</font></font></a></li>");
document.write("        <li><a href='079.html'><font size=4><font color=darkPurple><b>079</b></font> - <font color=darkBlue>﻿दु:श्रुति अनर्थदण्ड</font></font></a></li>");
document.write("        <li><a href='080.html'><font size=4><font color=darkPurple><b>080</b></font> - <font color=darkGreen>﻿प्रमादचर्या अनर्थदण्ड</font></font></a></li>");
document.write("        <li><a href='081.html'><font size=4><font color=darkPurple><b>081</b></font> - <font color=darkBlue>﻿अनर्थदण्डव्रत के अतिचार</font></font></a></li>");
document.write("        <li><a href='082.html'><font size=4><font color=darkPurple><b>082</b></font> - <font color=darkGreen>﻿भोगोपभोग परिमाण गुणव्रत</font></font></a></li>");
document.write("        <li><a href='083.html'><font size=4><font color=darkPurple><b>083</b></font> - <font color=darkBlue>﻿भोग-उपभोग के लक्षण</font></font></a></li>");
document.write("        <li><a href='084.html'><font size=4><font color=darkPurple><b>084</b></font> - <font color=darkGreen>﻿सर्वथा त्याज्य पदार्थ</font></font></a></li>");
document.write("        <li><a href='085.html'><font size=4><font color=darkPurple><b>085</b></font> - <font color=darkBlue>﻿अन्य त्याज्य पदार्थ</font></font></a></li>");
document.write("        <li><a href='086.html'><font size=4><font color=darkPurple><b>086</b></font> - <font color=darkGreen>﻿व्रत का स्वरूप</font></font></a></li>");
document.write("        <li><a href='087.html'><font size=4><font color=darkPurple><b>087</b></font> - <font color=darkBlue>﻿यम और नियम</font></font></a></li>");
document.write("        <li><a href='088-89.html'><font size=4><font color=darkPurple><b>088-89</b></font> - <font color=darkGreen>﻿भोगोपभोग सामग्री</font></font></a></li>");
document.write("        <li><a href='090.html'><font size=4><font color=darkPurple><b>090</b></font> - <font color=darkBlue>﻿भोगोपभोग परिमाण व्रत के अतिचार</font></font></a></li>");
document.write("        <li><a href='091.html'><font size=4><br><font size=5 color=black><b>﻿शिक्षाव्रत-अधिकार </b></font><br><br><font color=darkPurple><b>091</b></font> - <font color=darkGreen>﻿शिक्षाव्रत</font></font></a></li>");
document.write("        <li><a href='092.html'><font size=4><font color=darkPurple><b>092</b></font> - <font color=darkBlue>﻿देशावकाशिक शिक्षाव्रत</font></font></a></li>");
document.write("        <li><a href='093.html'><font size=4><font color=darkPurple><b>093</b></font> - <font color=darkGreen>﻿देशव्रत में मर्यादा की विधि</font></font></a></li>");
document.write("        <li><a href='094.html'><font size=4><font color=darkPurple><b>094</b></font> - <font color=darkBlue>﻿देशव्रत में काल मर्यादा</font></font></a></li>");
document.write("        <li><a href='095.html'><font size=4><font color=darkPurple><b>095</b></font> - <font color=darkGreen>﻿यह व्रत भी उपचार से महाव्रत है</font></font></a></li>");
document.write("        <li><a href='096.html'><font size=4><font color=darkPurple><b>096</b></font> - <font color=darkBlue>﻿देशावकाशिक व्रत के अतिचार</font></font></a></li>");
document.write("        <li><a href='097.html'><font size=4><font color=darkPurple><b>097</b></font> - <font color=darkGreen>﻿सामायिक शिक्षाव्रत</font></font></a></li>");
document.write("        <li><a href='098.html'><font size=4><font color=darkPurple><b>098</b></font> - <font color=darkBlue>﻿समय शब्द की व्युत्पत्ति</font></font></a></li>");
document.write("        <li><a href='099.html'><font size=4><font color=darkPurple><b>099</b></font> - <font color=darkGreen>﻿सामायिक योग्य स्थान</font></font></a></li>");
document.write("        <li><a href='100.html'><font size=4><font color=darkPurple><b>100</b></font> - <font color=darkBlue>﻿व्रत के दिन सामायिक का उपदेश</font></font></a></li>");
document.write("        <li><a href='101.html'><font size=4><font color=darkPurple><b>101</b></font> - <font color=darkGreen>﻿प्रातिदिन सामायिक का उपदेश</font></font></a></li>");
document.write("        <li><a href='102.html'><font size=4><font color=darkPurple><b>102</b></font> - <font color=darkBlue>﻿सामायिक के समय मुनितुल्यता</font></font></a></li>");
document.write("        <li><a href='103.html'><font size=4><font color=darkPurple><b>103</b></font> - <font color=darkGreen>﻿परीषह—उपसग सहन का उपदेश</font></font></a></li>");
document.write("        <li><a href='104.html'><font size=4><font color=darkPurple><b>104</b></font> - <font color=darkBlue>﻿सामायिक के समय चतन</font></font></a></li>");
document.write("        <li><a href='105.html'><font size=4><font color=darkPurple><b>105</b></font> - <font color=darkGreen>﻿सामायिक के अतिचार</font></font></a></li>");
document.write("        <li><a href='106.html'><font size=4><font color=darkPurple><b>106</b></font> - <font color=darkBlue>﻿प्रोषधोपवास शिक्षाव्रत</font></font></a></li>");
document.write("        <li><a href='107.html'><font size=4><font color=darkPurple><b>107</b></font> - <font color=darkGreen>﻿उपवास के दिन व्याज्या कार्य</font></font></a></li>");
document.write("        <li><a href='108.html'><font size=4><font color=darkPurple><b>108</b></font> - <font color=darkBlue>﻿उपवास के दिन कर्तव्य</font></font></a></li>");
document.write("        <li><a href='109.html'><font size=4><font color=darkPurple><b>109</b></font> - <font color=darkGreen>﻿प्रोषध और उपवास का लक्षण</font></font></a></li>");
document.write("        <li><a href='110.html'><font size=4><font color=darkPurple><b>110</b></font> - <font color=darkBlue>﻿प्रोषधोपवासव्रत के अतिचार</font></font></a></li>");
document.write("        <li><a href='111.html'><font size=4><font color=darkPurple><b>111</b></font> - <font color=darkGreen>﻿वैयावृत्य का लक्षण</font></font></a></li>");
document.write("        <li><a href='112.html'><font size=4><font color=darkPurple><b>112</b></font> - <font color=darkBlue>﻿वैयावृत्य का दूसरा लक्षण</font></font></a></li>");
document.write("        <li><a href='113.html'><font size=4><font color=darkPurple><b>113</b></font> - <font color=darkGreen>﻿दान का लक्षण</font></font></a></li>");
document.write("        <li><a href='114.html'><font size=4><font color=darkPurple><b>114</b></font> - <font color=darkBlue>﻿दान का फल</font></font></a></li>");
document.write("        <li><a href='115.html'><font size=4><font color=darkPurple><b>115</b></font> - <font color=darkGreen>﻿नवधा भक्ति का फल</font></font></a></li>");
document.write("        <li><a href='116.html'><font size=4><font color=darkPurple><b>116</b></font> - <font color=darkBlue>﻿अल्पदान से महाफल</font></font></a></li>");
document.write("        <li><a href='117.html'><font size=4><font color=darkPurple><b>117</b></font> - <font color=darkGreen>﻿दान के भेद</font></font></a></li>");
document.write("        <li><a href='118.html'><font size=4><font color=darkPurple><b>118</b></font> - <font color=darkBlue>﻿वैयावृत्य में अर्हंत पूजा</font></font></a></li>");
document.write("        <li><a href='119.html'><font size=4><font color=darkPurple><b>119</b></font> - <font color=darkGreen>﻿दानों में प्रसिद्ध नाम</font></font></a></li>");
document.write("        <li><a href='120.html'><font size=4><font color=darkPurple><b>120</b></font> - <font color=darkBlue>﻿पूजा का माहात्म्य</font></font></a></li>");
document.write("        <li><a href='121.html'><font size=4><font color=darkPurple><b>121</b></font> - <font color=darkGreen>﻿वैयावृत्य के अतिचार</font></font></a></li>");
document.write("        <li><a href='122.html'><font size=4><br><font size=5 color=black><b>﻿सल्लेखना-अधिकार </b></font><br><br><font color=darkPurple><b>122</b></font> - <font color=darkBlue>﻿सल्लेखना का लक्षण</font></font></a></li>");
document.write("        <li><a href='123.html'><font size=4><font color=darkPurple><b>123</b></font> - <font color=darkGreen>﻿सल्लेखना की आवश्यकता</font></font></a></li>");
document.write("        <li><a href='124-125.html'><font size=4><font color=darkPurple><b>124-125</b></font> - <font color=darkBlue>﻿सल्लेखना की विधि और महाव्रत धारण का उपदेश</font></font></a></li>");
document.write("        <li><a href='126.html'><font size=4><font color=darkPurple><b>126</b></font> - <font color=darkGreen>﻿स्वाध्याय का उपदेश</font></font></a></li>");
document.write("        <li><a href='127.html'><font size=4><font color=darkPurple><b>127</b></font> - <font color=darkBlue>﻿भोजन के त्याग का क्रम</font></font></a></li>");
document.write("        <li><a href='128.html'><font size=4><font color=darkPurple><b>128</b></font> - <font color=darkGreen>﻿सल्लेखना में शेष आहार त्याग का क्रम</font></font></a></li>");
document.write("        <li><a href='129.html'><font size=4><font color=darkPurple><b>129</b></font> - <font color=darkBlue>﻿सल्लेखना के पांच अतिचार</font></font></a></li>");
document.write("        <li><a href='130.html'><font size=4><font color=darkPurple><b>130</b></font> - <font color=darkGreen>﻿सल्लेखना का फल</font></font></a></li>");
document.write("        <li><a href='131.html'><font size=4><font color=darkPurple><b>131</b></font> - <font color=darkBlue>﻿मोक्ष का लक्षण</font></font></a></li>");
document.write("        <li><a href='132.html'><font size=4><font color=darkPurple><b>132</b></font> - <font color=darkGreen>﻿मुक्तजीवों का लक्षण</font></font></a></li>");
document.write("        <li><a href='133.html'><font size=4><font color=darkPurple><b>133</b></font> - <font color=darkBlue>﻿विकार का अभाव</font></font></a></li>");
document.write("        <li><a href='134.html'><font size=4><font color=darkPurple><b>134</b></font> - <font color=darkGreen>﻿मुक्तजीव कहाँ रहते हैं ?</font></font></a></li>");
document.write("        <li><a href='135.html'><font size=4><font color=darkPurple><b>135</b></font> - <font color=darkBlue>﻿सद्धर्म का फल</font></font></a></li>");
document.write("        <li><a href='136.html'><font size=4><br><font size=5 color=black><b>﻿श्रावकपद-अधिकार </b></font><br><br><font color=darkPurple><b>136</b></font> - <font color=darkGreen>﻿ग्यारह प्रतिमा</font></font></a></li>");
document.write("        <li><a href='137.html'><font size=4><font color=darkPurple><b>137</b></font> - <font color=darkBlue>﻿दर्शन प्रतिमा</font></font></a></li>");
document.write("        <li><a href='138.html'><font size=4><font color=darkPurple><b>138</b></font> - <font color=darkGreen>﻿व्रत प्रतिमा</font></font></a></li>");
document.write("        <li><a href='139.html'><font size=4><font color=darkPurple><b>139</b></font> - <font color=darkBlue>﻿सामायिक प्रतिमा</font></font></a></li>");
document.write("        <li><a href='140.html'><font size=4><font color=darkPurple><b>140</b></font> - <font color=darkGreen>﻿प्रोषध प्रतिमा</font></font></a></li>");
document.write("        <li><a href='141.html'><font size=4><font color=darkPurple><b>141</b></font> - <font color=darkBlue>﻿सचित्त त्याग प्रतिमा</font></font></a></li>");
document.write("        <li><a href='142.html'><font size=4><font color=darkPurple><b>142</b></font> - <font color=darkGreen>﻿रात्रि भुक्ति त्याग प्रतिमा</font></font></a></li>");
document.write("        <li><a href='143.html'><font size=4><font color=darkPurple><b>143</b></font> - <font color=darkBlue>﻿ब्रह्मचर्य प्रतिमा</font></font></a></li>");
document.write("        <li><a href='144.html'><font size=4><font color=darkPurple><b>144</b></font> - <font color=darkGreen>﻿आरम्भ त्याग प्रतिमा</font></font></a></li>");
document.write("        <li><a href='145.html'><font size=4><font color=darkPurple><b>145</b></font> - <font color=darkBlue>﻿परिग्रह त्याग प्रतिमा</font></font></a></li>");
document.write("        <li><a href='146.html'><font size=4><font color=darkPurple><b>146</b></font> - <font color=darkGreen>﻿अनुमति त्याग प्रतिमा</font></font></a></li>");
document.write("        <li><a href='147.html'><font size=4><font color=darkPurple><b>147</b></font> - <font color=darkBlue>﻿उद्दिष्ट त्याग प्रतिमा</font></font></a></li>");
document.write("        <li><a href='148.html'><font size=4><font color=darkPurple><b>148</b></font> - <font color=darkGreen>﻿श्रेष्ठ ज्ञाता कौन है ?</font></font></a></li>");
document.write("        <li><a href='149.html'><font size=4><font color=darkPurple><b>149</b></font> - <font color=darkBlue>﻿रत्नत्रय का फल</font></font></a></li>");
document.write("        <li><a href='150.html'><font size=4><font color=darkPurple><b>150</b></font> - <font color=darkGreen>﻿इष्ट प्रार्थना</font></font></a></li>");
document.write("</ul></div>");
document.write("<div id=आर्यिका-आदिमति class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='001.html'><font size=4><font color=darkPurple><b>001</b></font> - <font color=darkBlue>﻿मंगलाचरण</font></font></a></li>");
document.write("        <li><a href='002.html'><font size=4><font color=darkPurple><b>002</b></font> - <font color=darkGreen>﻿आचार्य की प्रतिज्ञा</font></font></a></li>");
document.write("        <li><a href='003.html'><font size=4><font color=darkPurple><b>003</b></font> - <font color=darkBlue>﻿धर्म का लक्षण</font></font></a></li>");
document.write("        <li><a href='004.html'><font size=4><br><font size=5 color=black><b>﻿सम्यग्दर्शन-अधिकार </b></font><br><br><font color=darkPurple><b>004</b></font> - <font color=darkGreen>﻿सम्यग्दर्शन</font></font></a></li>");
document.write("        <li><a href='005.html'><font size=4><font color=darkPurple><b>005</b></font> - <font color=darkBlue>﻿आप्त का लक्षण</font></font></a></li>");
document.write("        <li><a href='006.html'><font size=4><font color=darkPurple><b>006</b></font> - <font color=darkGreen>﻿वीतराग का लक्षण</font></font></a></li>");
document.write("        <li><a href='008.html'><font size=4><font color=darkPurple><b>008</b></font> - <font color=darkBlue>﻿आगम का लक्षण</font></font></a></li>");
document.write("        <li><a href='009.html'><font size=4><font color=darkPurple><b>009</b></font> - <font color=darkGreen>﻿शास्त्र का लक्षण</font></font></a></li>");
document.write("        <li><a href='010.html'><font size=4><font color=darkPurple><b>010</b></font> - <font color=darkBlue>﻿गुरु का लक्षण</font></font></a></li>");
document.write("        <li><a href='011.html'><font size=4><font color=darkPurple><b>011</b></font> - <font color=darkGreen>﻿नि:शंकित अंग</font></font></a></li>");
document.write("        <li><a href='012.html'><font size=4><font color=darkPurple><b>012</b></font> - <font color=darkBlue>﻿नि:कांक्षित अंग</font></font></a></li>");
document.write("        <li><a href='013.html'><font size=4><font color=darkPurple><b>013</b></font> - <font color=darkGreen>﻿निर्विचिकित्सा अंग</font></font></a></li>");
document.write("        <li><a href='014.html'><font size=4><font color=darkPurple><b>014</b></font> - <font color=darkBlue>﻿अमूढ़दृष्टि अंग</font></font></a></li>");
document.write("        <li><a href='015.html'><font size=4><font color=darkPurple><b>015</b></font> - <font color=darkGreen>﻿उपगूहन अंग</font></font></a></li>");
document.write("        <li><a href='016.html'><font size=4><font color=darkPurple><b>016</b></font> - <font color=darkBlue>﻿स्थितिकरण अंग</font></font></a></li>");
document.write("        <li><a href='017.html'><font size=4><font color=darkPurple><b>017</b></font> - <font color=darkGreen>﻿वात्सल्य अंग</font></font></a></li>");
document.write("        <li><a href='018.html'><font size=4><font color=darkPurple><b>018</b></font> - <font color=darkBlue>﻿प्रभावना अंग</font></font></a></li>");
document.write("        <li><a href='019-020.html'><font size=4><font color=darkPurple><b>019-020</b></font> - <font color=darkGreen>﻿आठ अंगधारी के नाम</font></font></a></li>");
document.write("        <li><a href='021.html'><font size=4><font color=darkPurple><b>021</b></font> - <font color=darkBlue>﻿अंगहीन सम्यक्त्व व्यर्थ है</font></font></a></li>");
document.write("        <li><a href='022.html'><font size=4><font color=darkPurple><b>022</b></font> - <font color=darkGreen>﻿लोक मूढ़ता</font></font></a></li>");
document.write("        <li><a href='023.html'><font size=4><font color=darkPurple><b>023</b></font> - <font color=darkBlue>﻿देव मूढ़ता</font></font></a></li>");
document.write("        <li><a href='024.html'><font size=4><font color=darkPurple><b>024</b></font> - <font color=darkGreen>﻿अब सम्यग्दर्शन के स्वरूप में पाखण्डि मूढ़ता का स्वरूप दिखाते हुए कहते हैं-</font></font></a></li>");
document.write("        <li><a href='025.html'><font size=4><font color=darkPurple><b>025</b></font> - <font color=darkBlue>﻿आठमद के नाम</font></font></a></li>");
document.write("        <li><a href='026.html'><font size=4><font color=darkPurple><b>026</b></font> - <font color=darkGreen>﻿मद करने से हानि</font></font></a></li>");
document.write("        <li><a href='027.html'><font size=4><font color=darkPurple><b>027</b></font> - <font color=darkBlue>﻿पाप त्याग का उपदेश</font></font></a></li>");
document.write("        <li><a href='028.html'><font size=4><font color=darkPurple><b>028</b></font> - <font color=darkGreen>﻿सम्यग्दर्शन की महिमा</font></font></a></li>");
document.write("        <li><a href='029.html'><font size=4><font color=darkPurple><b>029</b></font> - <font color=darkBlue>﻿धर्म और अधर्म का फल</font></font></a></li>");
document.write("        <li><a href='030.html'><font size=4><font color=darkPurple><b>030</b></font> - <font color=darkGreen>﻿सम्यग्दृष्टि कुदेवादिक को नमन ना करे</font></font></a></li>");
document.write("        <li><a href='031.html'><font size=4><font color=darkPurple><b>031</b></font> - <font color=darkBlue>﻿सम्यग्दर्शन की श्रेष्ठता</font></font></a></li>");
document.write("        <li><a href='032.html'><font size=4><font color=darkPurple><b>032</b></font> - <font color=darkGreen>﻿सम्यग्दर्शन के बिना ज्ञान चारित्र की असम्भवता</font></font></a></li>");
document.write("        <li><a href='033.html'><font size=4><font color=darkPurple><b>033</b></font> - <font color=darkBlue>﻿मोही मुनि की अपेक्षा निर्मोही गृहस्थ श्रेष्ठ</font></font></a></li>");
document.write("        <li><a href='034.html'><font size=4><font color=darkPurple><b>034</b></font> - <font color=darkGreen>﻿श्रेय और अश्रेय का कथन</font></font></a></li>");
document.write("        <li><a href='035.html'><font size=4><font color=darkPurple><b>035</b></font> - <font color=darkBlue>﻿सम्यग्दृष्टि के अनुत्पत्ति के स्थान</font></font></a></li>");
document.write("        <li><a href='036.html'><font size=4><font color=darkPurple><b>036</b></font> - <font color=darkGreen>﻿सम्यग्दृष्टि जीव श्रेष्ठ मनुष्य होते हैं </font></font></a></li>");
document.write("        <li><a href='037.html'><font size=4><font color=darkPurple><b>037</b></font> - <font color=darkBlue>﻿सम्यग्दृष्टि जीव इंद्र पद पाते हैं</font></font></a></li>");
document.write("        <li><a href='038.html'><font size=4><font color=darkPurple><b>038</b></font> - <font color=darkGreen>﻿सम्यग्दृष्टि ही चक्रवर्ती होते हैं</font></font></a></li>");
document.write("        <li><a href='039.html'><font size=4><font color=darkPurple><b>039</b></font> - <font color=darkBlue>﻿सम्यग्दृष्टि ही तीर्थंकर होते हैं</font></font></a></li>");
document.write("        <li><a href='040.html'><font size=4><font color=darkPurple><b>040</b></font> - <font color=darkGreen>﻿सम्यग्दृष्टि ही मोक्ष-पद प्राप्त करते हैं</font></font></a></li>");
document.write("        <li><a href='041.html'><font size=4><font color=darkPurple><b>041</b></font> - <font color=darkBlue>﻿उपसंहार</font></font></a></li>");
document.write("        <li><a href='042.html'><font size=4><br><font size=5 color=black><b>﻿सम्यग्ज्ञान-अधिकार </b></font><br><br><font color=darkPurple><b>042</b></font> - <font color=darkGreen>﻿सम्यग्ज्ञान का लक्षण</font></font></a></li>");
document.write("        <li><a href='043.html'><font size=4><font color=darkPurple><b>043</b></font> - <font color=darkBlue>﻿प्रथमानुयोग</font></font></a></li>");
document.write("        <li><a href='044.html'><font size=4><font color=darkPurple><b>044</b></font> - <font color=darkGreen>﻿करणानुयोग</font></font></a></li>");
document.write("        <li><a href='045.html'><font size=4><font color=darkPurple><b>045</b></font> - <font color=darkBlue>﻿चरणानुयोग</font></font></a></li>");
document.write("        <li><a href='046.html'><font size=4><font color=darkPurple><b>046</b></font> - <font color=darkGreen>﻿द्रव्यानुयोग</font></font></a></li>");
document.write("        <li><a href='047.html'><font size=4><br><font size=5 color=black><b>﻿सम्यक-चारित्र-अधिकार </b></font><br><br><font color=darkPurple><b>047</b></font> - <font color=darkBlue>﻿चारित्र की आवश्यकता</font></font></a></li>");
document.write("        <li><a href='048.html'><font size=4><font color=darkPurple><b>048</b></font> - <font color=darkGreen>﻿चारित्र कब होता है?</font></font></a></li>");
document.write("        <li><a href='049.html'><font size=4><font color=darkPurple><b>049</b></font> - <font color=darkBlue>﻿चारित्र का लक्षण</font></font></a></li>");
document.write("        <li><a href='050.html'><font size=4><font color=darkPurple><b>050</b></font> - <font color=darkGreen>﻿चारित्र के भेद और उपासक</font></font></a></li>");
document.write("        <li><a href='051.html'><font size=4><font color=darkPurple><b>051</b></font> - <font color=darkBlue>﻿विकल चारित्र के भेद</font></font></a></li>");
document.write("        <li><a href='052.html'><font size=4><br><font size=5 color=black><b>﻿अणुव्रत-अधिकार </b></font><br><br><font color=darkPurple><b>052</b></font> - <font color=darkGreen>﻿अणुव्रत का लक्षण</font></font></a></li>");
document.write("        <li><a href='053.html'><font size=4><font color=darkPurple><b>053</b></font> - <font color=darkBlue>﻿अहिंसा अणुव्रत</font></font></a></li>");
document.write("        <li><a href='054.html'><font size=4><font color=darkPurple><b>054</b></font> - <font color=darkGreen>﻿अहिंसा अणुव्रत के अतिचार</font></font></a></li>");
document.write("        <li><a href='055.html'><font size=4><font color=darkPurple><b>055</b></font> - <font color=darkBlue>﻿सत्याणुव्रत</font></font></a></li>");
document.write("        <li><a href='056.html'><font size=4><font color=darkPurple><b>056</b></font> - <font color=darkGreen>﻿सत्याणुव्रत के अतिचार</font></font></a></li>");
document.write("        <li><a href='057.html'><font size=4><font color=darkPurple><b>057</b></font> - <font color=darkBlue>﻿अचौर्याणुव्रत</font></font></a></li>");
document.write("        <li><a href='058.html'><font size=4><font color=darkPurple><b>058</b></font> - <font color=darkGreen>﻿अचौर्याणुव्रत के अतिचार</font></font></a></li>");
document.write("        <li><a href='059.html'><font size=4><font color=darkPurple><b>059</b></font> - <font color=darkBlue>﻿ब्रह्मचर्य अणुव्रत</font></font></a></li>");
document.write("        <li><a href='060.html'><font size=4><font color=darkPurple><b>060</b></font> - <font color=darkGreen>﻿ब्रह्मचर्याणुव्रत के अतिचार</font></font></a></li>");
document.write("        <li><a href='061.html'><font size=4><font color=darkPurple><b>061</b></font> - <font color=darkBlue>﻿परिग्रह परिमाण अणुव्रत</font></font></a></li>");
document.write("        <li><a href='062.html'><font size=4><font color=darkPurple><b>062</b></font> - <font color=darkGreen>﻿परिग्रह परिमाण अणुव्रत के अतिचार</font></font></a></li>");
document.write("        <li><a href='063.html'><font size=4><font color=darkPurple><b>063</b></font> - <font color=darkBlue>﻿पंचाणु व्रत का फल</font></font></a></li>");
document.write("        <li><a href='064.html'><font size=4><font color=darkPurple><b>064</b></font> - <font color=darkGreen>﻿पंचाणुव्रत में प्रसिद्ध नाम</font></font></a></li>");
document.write("        <li><a href='065.html'><font size=4><font color=darkPurple><b>065</b></font> - <font color=darkBlue>﻿पांच पाप में प्रसिद्ध नाम</font></font></a></li>");
document.write("        <li><a href='066.html'><font size=4><font color=darkPurple><b>066</b></font> - <font color=darkGreen>﻿श्रावक के आठ मूलगुण</font></font></a></li>");
document.write("        <li><a href='067.html'><font size=4><br><font size=5 color=black><b>﻿गुणव्रत-अधिकार </b></font><br><br><font color=darkPurple><b>067</b></font> - <font color=darkBlue>﻿गुणव्रतों के नाम</font></font></a></li>");
document.write("        <li><a href='068.html'><font size=4><font color=darkPurple><b>068</b></font> - <font color=darkGreen>﻿दिग्व्रत का लक्षण</font></font></a></li>");
document.write("        <li><a href='069.html'><font size=4><font color=darkPurple><b>069</b></font> - <font color=darkBlue>﻿मर्यादा की विधि</font></font></a></li>");
document.write("        <li><a href='070.html'><font size=4><font color=darkPurple><b>070</b></font> - <font color=darkGreen>﻿दिग्व्रत की मर्यादा के बाहर अणुव्रतों के महाव्रतपना</font></font></a></li>");
document.write("        <li><a href='071.html'><font size=4><font color=darkPurple><b>071</b></font> - <font color=darkBlue>﻿सो कैसे ? उसका समाधान</font></font></a></li>");
document.write("        <li><a href='072.html'><font size=4><font color=darkPurple><b>072</b></font> - <font color=darkGreen>﻿महाव्रत का लक्षण</font></font></a></li>");
document.write("        <li><a href='073.html'><font size=4><font color=darkPurple><b>073</b></font> - <font color=darkBlue>﻿दिग्व्रत के अतिचार</font></font></a></li>");
document.write("        <li><a href='074.html'><font size=4><font color=darkPurple><b>074</b></font> - <font color=darkGreen>﻿अनर्थदण्ड व्रत</font></font></a></li>");
document.write("        <li><a href='075.html'><font size=4><font color=darkPurple><b>075</b></font> - <font color=darkBlue>﻿अनर्थदण्ड के भेद</font></font></a></li>");
document.write("        <li><a href='076.html'><font size=4><font color=darkPurple><b>076</b></font> - <font color=darkGreen>﻿पापोपदेश का लक्षण</font></font></a></li>");
document.write("        <li><a href='077.html'><font size=4><font color=darkPurple><b>077</b></font> - <font color=darkBlue>﻿हिंसादान अनर्थदण्ड</font></font></a></li>");
document.write("        <li><a href='078.html'><font size=4><font color=darkPurple><b>078</b></font> - <font color=darkGreen>﻿अपध्यान अनर्थदण्ड</font></font></a></li>");
document.write("        <li><a href='079.html'><font size=4><font color=darkPurple><b>079</b></font> - <font color=darkBlue>﻿दु:श्रुति अनर्थदण्ड</font></font></a></li>");
document.write("        <li><a href='080.html'><font size=4><font color=darkPurple><b>080</b></font> - <font color=darkGreen>﻿प्रमादचर्या अनर्थदण्ड</font></font></a></li>");
document.write("        <li><a href='081.html'><font size=4><font color=darkPurple><b>081</b></font> - <font color=darkBlue>﻿अनर्थदण्डव्रत के अतिचार</font></font></a></li>");
document.write("        <li><a href='082.html'><font size=4><font color=darkPurple><b>082</b></font> - <font color=darkGreen>﻿भोगोपभोग परिमाण गुणव्रत</font></font></a></li>");
document.write("        <li><a href='083.html'><font size=4><font color=darkPurple><b>083</b></font> - <font color=darkBlue>﻿भोग-उपभोग के लक्षण</font></font></a></li>");
document.write("        <li><a href='084.html'><font size=4><font color=darkPurple><b>084</b></font> - <font color=darkGreen>﻿सर्वथा त्याज्य पदार्थ</font></font></a></li>");
document.write("        <li><a href='085.html'><font size=4><font color=darkPurple><b>085</b></font> - <font color=darkBlue>﻿अन्य त्याज्य पदार्थ</font></font></a></li>");
document.write("        <li><a href='086.html'><font size=4><font color=darkPurple><b>086</b></font> - <font color=darkGreen>﻿व्रत का स्वरूप</font></font></a></li>");
document.write("        <li><a href='087.html'><font size=4><font color=darkPurple><b>087</b></font> - <font color=darkBlue>﻿यम और नियम</font></font></a></li>");
document.write("        <li><a href='088-89.html'><font size=4><font color=darkPurple><b>088-89</b></font> - <font color=darkGreen>﻿भोगोपभोग सामग्री</font></font></a></li>");
document.write("        <li><a href='090.html'><font size=4><font color=darkPurple><b>090</b></font> - <font color=darkBlue>﻿भोगोपभोग परिमाण व्रत के अतिचार</font></font></a></li>");
document.write("        <li><a href='091.html'><font size=4><br><font size=5 color=black><b>﻿शिक्षाव्रत-अधिकार </b></font><br><br><font color=darkPurple><b>091</b></font> - <font color=darkGreen>﻿शिक्षाव्रत</font></font></a></li>");
document.write("        <li><a href='092.html'><font size=4><font color=darkPurple><b>092</b></font> - <font color=darkBlue>﻿देशावकाशिक शिक्षाव्रत</font></font></a></li>");
document.write("        <li><a href='093.html'><font size=4><font color=darkPurple><b>093</b></font> - <font color=darkGreen>﻿देशव्रत में मर्यादा की विधि</font></font></a></li>");
document.write("        <li><a href='094.html'><font size=4><font color=darkPurple><b>094</b></font> - <font color=darkBlue>﻿देशव्रत में काल मर्यादा</font></font></a></li>");
document.write("        <li><a href='095.html'><font size=4><font color=darkPurple><b>095</b></font> - <font color=darkGreen>﻿यह व्रत भी उपचार से महाव्रत है</font></font></a></li>");
document.write("        <li><a href='096.html'><font size=4><font color=darkPurple><b>096</b></font> - <font color=darkBlue>﻿देशावकाशिक व्रत के अतिचार</font></font></a></li>");
document.write("        <li><a href='097.html'><font size=4><font color=darkPurple><b>097</b></font> - <font color=darkGreen>﻿सामायिक शिक्षाव्रत</font></font></a></li>");
document.write("        <li><a href='098.html'><font size=4><font color=darkPurple><b>098</b></font> - <font color=darkBlue>﻿समय शब्द की व्युत्पत्ति</font></font></a></li>");
document.write("        <li><a href='099.html'><font size=4><font color=darkPurple><b>099</b></font> - <font color=darkGreen>﻿सामायिक योग्य स्थान</font></font></a></li>");
document.write("        <li><a href='100.html'><font size=4><font color=darkPurple><b>100</b></font> - <font color=darkBlue>﻿व्रत के दिन सामायिक का उपदेश</font></font></a></li>");
document.write("        <li><a href='101.html'><font size=4><font color=darkPurple><b>101</b></font> - <font color=darkGreen>﻿प्रातिदिन सामायिक का उपदेश</font></font></a></li>");
document.write("        <li><a href='102.html'><font size=4><font color=darkPurple><b>102</b></font> - <font color=darkBlue>﻿सामायिक के समय मुनितुल्यता</font></font></a></li>");
document.write("        <li><a href='103.html'><font size=4><font color=darkPurple><b>103</b></font> - <font color=darkGreen>﻿परीषह—उपसग सहन का उपदेश</font></font></a></li>");
document.write("        <li><a href='104.html'><font size=4><font color=darkPurple><b>104</b></font> - <font color=darkBlue>﻿सामायिक के समय चतन</font></font></a></li>");
document.write("        <li><a href='105.html'><font size=4><font color=darkPurple><b>105</b></font> - <font color=darkGreen>﻿सामायिक के अतिचार</font></font></a></li>");
document.write("        <li><a href='106.html'><font size=4><font color=darkPurple><b>106</b></font> - <font color=darkBlue>﻿प्रोषधोपवास शिक्षाव्रत</font></font></a></li>");
document.write("        <li><a href='107.html'><font size=4><font color=darkPurple><b>107</b></font> - <font color=darkGreen>﻿उपवास के दिन व्याज्या कार्य</font></font></a></li>");
document.write("        <li><a href='108.html'><font size=4><font color=darkPurple><b>108</b></font> - <font color=darkBlue>﻿उपवास के दिन कर्तव्य</font></font></a></li>");
document.write("        <li><a href='109.html'><font size=4><font color=darkPurple><b>109</b></font> - <font color=darkGreen>﻿प्रोषध और उपवास का लक्षण</font></font></a></li>");
document.write("        <li><a href='110.html'><font size=4><font color=darkPurple><b>110</b></font> - <font color=darkBlue>﻿प्रोषधोपवासव्रत के अतिचार</font></font></a></li>");
document.write("        <li><a href='111.html'><font size=4><font color=darkPurple><b>111</b></font> - <font color=darkGreen>﻿वैयावृत्य का लक्षण</font></font></a></li>");
document.write("        <li><a href='112.html'><font size=4><font color=darkPurple><b>112</b></font> - <font color=darkBlue>﻿वैयावृत्य का दूसरा लक्षण</font></font></a></li>");
document.write("        <li><a href='113.html'><font size=4><font color=darkPurple><b>113</b></font> - <font color=darkGreen>﻿दान का लक्षण</font></font></a></li>");
document.write("        <li><a href='114.html'><font size=4><font color=darkPurple><b>114</b></font> - <font color=darkBlue>﻿दान का फल</font></font></a></li>");
document.write("        <li><a href='115.html'><font size=4><font color=darkPurple><b>115</b></font> - <font color=darkGreen>﻿नवधा भक्ति का फल</font></font></a></li>");
document.write("        <li><a href='116.html'><font size=4><font color=darkPurple><b>116</b></font> - <font color=darkBlue>﻿अल्पदान से महाफल</font></font></a></li>");
document.write("        <li><a href='117.html'><font size=4><font color=darkPurple><b>117</b></font> - <font color=darkGreen>﻿दान के भेद</font></font></a></li>");
document.write("        <li><a href='118.html'><font size=4><font color=darkPurple><b>118</b></font> - <font color=darkBlue>﻿वैयावृत्य में अर्हंत पूजा</font></font></a></li>");
document.write("        <li><a href='119.html'><font size=4><font color=darkPurple><b>119</b></font> - <font color=darkGreen>﻿दानों में प्रसिद्ध नाम</font></font></a></li>");
document.write("        <li><a href='120.html'><font size=4><font color=darkPurple><b>120</b></font> - <font color=darkBlue>﻿पूजा का माहात्म्य</font></font></a></li>");
document.write("        <li><a href='121.html'><font size=4><font color=darkPurple><b>121</b></font> - <font color=darkGreen>﻿वैयावृत्य के अतिचार</font></font></a></li>");
document.write("        <li><a href='122.html'><font size=4><br><font size=5 color=black><b>﻿सल्लेखना-अधिकार </b></font><br><br><font color=darkPurple><b>122</b></font> - <font color=darkBlue>﻿सल्लेखना का लक्षण</font></font></a></li>");
document.write("        <li><a href='123.html'><font size=4><font color=darkPurple><b>123</b></font> - <font color=darkGreen>﻿सल्लेखना की आवश्यकता</font></font></a></li>");
document.write("        <li><a href='124-125.html'><font size=4><font color=darkPurple><b>124-125</b></font> - <font color=darkBlue>﻿सल्लेखना की विधि और महाव्रत धारण का उपदेश</font></font></a></li>");
document.write("        <li><a href='126.html'><font size=4><font color=darkPurple><b>126</b></font> - <font color=darkGreen>﻿स्वाध्याय का उपदेश</font></font></a></li>");
document.write("        <li><a href='127.html'><font size=4><font color=darkPurple><b>127</b></font> - <font color=darkBlue>﻿भोजन के त्याग का क्रम</font></font></a></li>");
document.write("        <li><a href='128.html'><font size=4><font color=darkPurple><b>128</b></font> - <font color=darkGreen>﻿सल्लेखना में शेष आहार त्याग का क्रम</font></font></a></li>");
document.write("        <li><a href='129.html'><font size=4><font color=darkPurple><b>129</b></font> - <font color=darkBlue>﻿सल्लेखना के पांच अतिचार</font></font></a></li>");
document.write("        <li><a href='130.html'><font size=4><font color=darkPurple><b>130</b></font> - <font color=darkGreen>﻿सल्लेखना का फल</font></font></a></li>");
document.write("        <li><a href='131.html'><font size=4><font color=darkPurple><b>131</b></font> - <font color=darkBlue>﻿मोक्ष का लक्षण</font></font></a></li>");
document.write("        <li><a href='132.html'><font size=4><font color=darkPurple><b>132</b></font> - <font color=darkGreen>﻿मुक्तजीवों का लक्षण</font></font></a></li>");
document.write("        <li><a href='133.html'><font size=4><font color=darkPurple><b>133</b></font> - <font color=darkBlue>﻿विकार का अभाव</font></font></a></li>");
document.write("        <li><a href='134.html'><font size=4><font color=darkPurple><b>134</b></font> - <font color=darkGreen>﻿मुक्तजीव कहाँ रहते हैं ?</font></font></a></li>");
document.write("        <li><a href='135.html'><font size=4><font color=darkPurple><b>135</b></font> - <font color=darkBlue>﻿सद्धर्म का फल</font></font></a></li>");
document.write("        <li><a href='136.html'><font size=4><br><font size=5 color=black><b>﻿श्रावकपद-अधिकार </b></font><br><br><font color=darkPurple><b>136</b></font> - <font color=darkGreen>﻿ग्यारह प्रतिमा</font></font></a></li>");
document.write("        <li><a href='137.html'><font size=4><font color=darkPurple><b>137</b></font> - <font color=darkBlue>﻿दर्शन प्रतिमा</font></font></a></li>");
document.write("        <li><a href='138.html'><font size=4><font color=darkPurple><b>138</b></font> - <font color=darkGreen>﻿व्रत प्रतिमा</font></font></a></li>");
document.write("        <li><a href='139.html'><font size=4><font color=darkPurple><b>139</b></font> - <font color=darkBlue>﻿सामायिक प्रतिमा</font></font></a></li>");
document.write("        <li><a href='140.html'><font size=4><font color=darkPurple><b>140</b></font> - <font color=darkGreen>﻿प्रोषध प्रतिमा</font></font></a></li>");
document.write("        <li><a href='141.html'><font size=4><font color=darkPurple><b>141</b></font> - <font color=darkBlue>﻿सचित्त त्याग प्रतिमा</font></font></a></li>");
document.write("        <li><a href='142.html'><font size=4><font color=darkPurple><b>142</b></font> - <font color=darkGreen>﻿रात्रि भुक्ति त्याग प्रतिमा</font></font></a></li>");
document.write("        <li><a href='143.html'><font size=4><font color=darkPurple><b>143</b></font> - <font color=darkBlue>﻿ब्रह्मचर्य प्रतिमा</font></font></a></li>");
document.write("        <li><a href='144.html'><font size=4><font color=darkPurple><b>144</b></font> - <font color=darkGreen>﻿आरम्भ त्याग प्रतिमा</font></font></a></li>");
document.write("        <li><a href='145.html'><font size=4><font color=darkPurple><b>145</b></font> - <font color=darkBlue>﻿परिग्रह त्याग प्रतिमा</font></font></a></li>");
document.write("        <li><a href='146.html'><font size=4><font color=darkPurple><b>146</b></font> - <font color=darkGreen>﻿अनुमति त्याग प्रतिमा</font></font></a></li>");
document.write("        <li><a href='147.html'><font size=4><font color=darkPurple><b>147</b></font> - <font color=darkBlue>﻿उद्दिष्ट त्याग प्रतिमा</font></font></a></li>");
document.write("        <li><a href='148.html'><font size=4><font color=darkPurple><b>148</b></font> - <font color=darkGreen>﻿श्रेष्ठ ज्ञाता कौन है ?</font></font></a></li>");
document.write("        <li><a href='149.html'><font size=4><font color=darkPurple><b>149</b></font> - <font color=darkBlue>﻿रत्नत्रय का फल</font></font></a></li>");
document.write("        <li><a href='150.html'><font size=4><font color=darkPurple><b>150</b></font> - <font color=darkGreen>﻿इष्ट प्रार्थना</font></font></a></li>");
document.write("</ul></div>");
document.write("<div id=पं-सदासुखदास class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='002.html'><font size=4><font color=darkPurple><b>002</b></font> - <font color=darkBlue>﻿आचार्य की प्रतिज्ञा</font></font></a></li>");
document.write("        <li><a href='003.html'><font size=4><font color=darkPurple><b>003</b></font> - <font color=darkGreen>﻿धर्म का लक्षण</font></font></a></li>");
document.write("        <li><a href='004.html'><font size=4><br><font size=5 color=black><b>﻿सम्यग्दर्शन-अधिकार </b></font><br><br><font color=darkPurple><b>004</b></font> - <font color=darkBlue>﻿सम्यग्दर्शन</font></font></a></li>");
document.write("        <li><a href='005.html'><font size=4><font color=darkPurple><b>005</b></font> - <font color=darkGreen>﻿आप्त का लक्षण</font></font></a></li>");
document.write("        <li><a href='007.html'><font size=4><font color=darkPurple><b>007</b></font> - <font color=darkBlue>﻿हितोपदेशी का लक्षण</font></font></a></li>");
document.write("        <li><a href='010.html'><font size=4><font color=darkPurple><b>010</b></font> - <font color=darkGreen>﻿गुरु का लक्षण</font></font></a></li>");
document.write("</ul></div>");
