  var curGathaSz=2.4;
  var curGadyaSz=2;
  var curArthSz=2;
  var curTableSz=1.4;
  var curTeekaSz=2;
  var curTableTitle=2;
  var curTableNotes=1;
  var curOrgChartSz=1;
$(function() {
  $('.head1').css('background-color', '#ffe0b3');
  $('.head2').css('background-color', '#b3ffff');
  $('.head3').css('background-color', '#e6ccff');
  $('.head4').css('background-color', '#b3d9ff');
  $(".tableTitle").css("font-size", curTableTitle+"vw");
  $(".orgchart").css("font-size", curOrgChartSz+"vw");
  $('.incFontSz').click(function() {
      curGathaSz+=0.2;
      curArthSz+=0.2;
      curGadyaSz+=0.2;
      curTeekaSz+=0.2;
      curTableSz+=0.2;
      curTableTitle+=0.2;
      curTableNotes+=0.2;
      curOrgChartSz+=0.2;
      $(".gatha").css("font-size", curGathaSz+"vw");
      $(".arth").css("font-size", curArthSz+"vw");
      $(".gadya").css("font-size", curGadyaSz+"vw");
      $(".teeka").css("font-size", curTeekaSz+"vw");
      $(".myTable td").css("font-size", curTableSz+"vw");
      $(".myTable th").css("font-size", curTableSz+"vw");
      $(".myAltTable td").css("font-size", curTableSz+"vw");
      $(".myAltTable th").css("font-size", curTableSz+"vw");
      $(".myAltColTable td").css("font-size", curTableSz+"vw");
      $(".myAltColTable th").css("font-size", curTableSz+"vw");
      $(".tableNotes").css("font-size", curTableNotes+"vw");
      $(".tableTitle").css("font-size", curTableTitle+"vw");
      $(".orgchart").css("font-size", curOrgChartSz+"vw");
  });
  $('.decFontSz').click(function() {
      curGathaSz-=0.2;
      curArthSz-=0.2;
      curGadyaSz-=0.2;
      curTeekaSz-=0.2;
      curTableSz-=0.2;
      curTableTitle-=0.2;
      curTableNotes-=0.2;
      curOrgChartSz-=0.2;
      $(".gatha").css("font-size", curGathaSz+"vw");
      $(".arth").css("font-size", curArthSz+"vw");
      $(".gadya").css("font-size", curGadyaSz+"vw");
      $(".teeka").css("font-size", curTeekaSz+"vw");
      $(".myTable td").css("font-size", curTableSz+"vw");
      $(".myTable th").css("font-size", curTableSz+"vw");
      $(".myAltTable td").css("font-size", curTableSz+"vw");
      $(".myAltTable th").css("font-size", curTableSz+"vw");
      $(".myAltColTable td").css("font-size", curTableSz+"vw");
      $(".myAltColTable th").css("font-size", curTableSz+"vw");
      $(".tableTitle").css("font-size", curTableTitle+"vw");
      $(".tableNotes").css("font-size", curTableNotes+"vw");
      $(".orgchart").css("font-size", curOrgChartSz+"vw");
  });
});
