$(document).on( 'pagecontainershow', function(){
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-1.html data-rel=dialog data-ajax=false>अशरीरी सिद्ध भगवान</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-2.html data-rel=dialog data-ajax=false>आ गया... आ गया...</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-3.html data-rel=dialog data-ajax=false>आओ जिनमंदिर में आओ</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-4.html data-rel=dialog data-ajax=false>आज मैं महावीर जी</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-5.html data-rel=dialog data-ajax=false>आज सी सुहानी</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-6.html data-rel=dialog data-ajax=false>आज हम जिनराज</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-7.html data-rel=dialog data-ajax=false>आया कहां से</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-8.html data-rel=dialog data-ajax=false>आया तेरे दरबार में</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-9.html data-rel=dialog data-ajax=false>आये तेरे द्वार</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-10.html data-rel=dialog data-ajax=false>आयो आयो रे हमारो</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-11.html data-rel=dialog data-ajax=false>एक तुम्हीं आधार हो</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-12.html data-rel=dialog data-ajax=false>ओ जगत के शांति दाता</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-13.html data-rel=dialog data-ajax=false>कभी वीर बनके</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-14.html data-rel=dialog data-ajax=false>कर लो जिनवर का गुणगान</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-15.html data-rel=dialog data-ajax=false>करता हूं तुम्हारा सुमिरन</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-16.html data-rel=dialog data-ajax=false>करुणा सागर भगवान</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-17.html data-rel=dialog data-ajax=false>केसरिया केसरिया</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-18.html data-rel=dialog data-ajax=false>कोई इत आओ जी</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-19.html data-rel=dialog data-ajax=false>गा रे भैया</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-20.html data-rel=dialog data-ajax=false>गाएँ जी गाएँ आदिनाथ</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-21.html data-rel=dialog data-ajax=false>घडी घडी पल पल</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-22.html data-rel=dialog data-ajax=false>चंद्रानन</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-23.html data-rel=dialog data-ajax=false>चरणों में आया हूं</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-24.html data-rel=dialog data-ajax=false>चवलेश्वर पारसनाथ</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-25.html data-rel=dialog data-ajax=false>चाह मुझे है दर्शन की</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-26.html data-rel=dialog data-ajax=false>छोटा सा मंदिर</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-27.html data-rel=dialog data-ajax=false>जगदानंदन</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-28.html data-rel=dialog data-ajax=false>जब कोई नहीं आता मेरे बाबा</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-29.html data-rel=dialog data-ajax=false>जयवंतो जिनबिम्ब</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-30.html data-rel=dialog data-ajax=false>जिन ध्याना गुण गाना</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-31.html data-rel=dialog data-ajax=false>जिनवर आनन भान</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-32.html data-rel=dialog data-ajax=false>जिनवर दरबार तुम्हारा</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-33.html data-rel=dialog data-ajax=false>झीनी झीनी उडे रे</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-34.html data-rel=dialog data-ajax=false>तिहारे ध्यान की मूरत</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-35.html data-rel=dialog data-ajax=false>तुझे प्रभु वीर कहते हैं</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-36.html data-rel=dialog data-ajax=false>तुम जैसा मैं भी</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-37.html data-rel=dialog data-ajax=false>तुमसे लागी लगन</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-38.html data-rel=dialog data-ajax=false>तुम्हारे दर्श बिन स्वामी</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-39.html data-rel=dialog data-ajax=false>तुम्ही हो ज्ञाता</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-40.html data-rel=dialog data-ajax=false>तू ज्ञान का सागर है</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-41.html data-rel=dialog data-ajax=false>तेरी शांत छवि</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-42.html data-rel=dialog data-ajax=false>तेरी शीतल शीतल मूरत</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-43.html data-rel=dialog data-ajax=false>तेरी सुंदर मूरत</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-44.html data-rel=dialog data-ajax=false>तेरे दर्शन से मेरा</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-45.html data-rel=dialog data-ajax=false>तोरी पल पल</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-46.html data-rel=dialog data-ajax=false>दरबार तुम्हारा मनहर है</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-47.html data-rel=dialog data-ajax=false>दिन रात स्वामी तेरे गीत</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-48.html data-rel=dialog data-ajax=false>देखो जी आदिश्वर स्वामी</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-49.html data-rel=dialog data-ajax=false>धन्य धन्य आज घडी</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-50.html data-rel=dialog data-ajax=false>नाथ तुम्हारी पूजा</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-51.html data-rel=dialog data-ajax=false>नाम तुम्हारा तारणहारा कब तेरा</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-52.html data-rel=dialog data-ajax=false>निरखत जिन चंद्रवदन</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-53.html data-rel=dialog data-ajax=false>निरखी निरखी मनहर</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-54.html data-rel=dialog data-ajax=false>निरखो अंग अंग</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-55.html data-rel=dialog data-ajax=false>नेमि जिनेश्वर</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-56.html data-rel=dialog data-ajax=false>पंचपरम परमेष्ठी</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-57.html data-rel=dialog data-ajax=false>पद्मासद्म</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-58.html data-rel=dialog data-ajax=false>पारस प्यारा लागो</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-59.html data-rel=dialog data-ajax=false>पारस प्रभु का दर्शन</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-60.html data-rel=dialog data-ajax=false>प्रभु दर्शन कर जीवन की</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-61.html data-rel=dialog data-ajax=false>प्रभु हम सब का एक</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-62.html data-rel=dialog data-ajax=false>प्रभुजी अब ना भटकेंगे</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-63.html data-rel=dialog data-ajax=false>बाहुबली भगवान</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-64.html data-rel=dialog data-ajax=false>भटके हुए राही को</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-65.html data-rel=dialog data-ajax=false>भव भव रुले हैं</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-66.html data-rel=dialog data-ajax=false>भावना की चूनरी</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-67.html data-rel=dialog data-ajax=false>मन भाये चित हुलसाये</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-68.html data-rel=dialog data-ajax=false>मनहर तेरी मूरतियाँ</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-69.html data-rel=dialog data-ajax=false>महाराजा स्वामी</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-70.html data-rel=dialog data-ajax=false>महावीर स्वामी</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-71.html data-rel=dialog data-ajax=false>मिलता है सच्चा सुख केवल</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-72.html data-rel=dialog data-ajax=false>मेरे मन मंदिर में आन</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-73.html data-rel=dialog data-ajax=false>मेरे महावीर झूले पलना</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-74.html data-rel=dialog data-ajax=false>मेरे सर पर रख दो भगवन</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-75.html data-rel=dialog data-ajax=false>मैं तेरे ढिंग आया रे</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-76.html data-rel=dialog data-ajax=false>म्हारा आदीश्वर जी</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-77.html data-rel=dialog data-ajax=false>रंगमा रंगमा</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-78.html data-rel=dialog data-ajax=false>रोम रोम पुलकित हो जाये</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-79.html data-rel=dialog data-ajax=false>रोम रोम में नेमिकुंवर के</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-80.html data-rel=dialog data-ajax=false>रोम रोम से निकले</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-81.html data-rel=dialog data-ajax=false>वन्दों अद्भुत चन्द्रवीर जिन</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-82.html data-rel=dialog data-ajax=false>वर्तमान को वर्धमान की</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-83.html data-rel=dialog data-ajax=false>वर्धमान ललना से</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-84.html data-rel=dialog data-ajax=false>वीतरागी देव</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-85.html data-rel=dialog data-ajax=false>वीर प्रभु के ये बोल</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-86.html data-rel=dialog data-ajax=false>शुद्धात्मा का श्रद्धान</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-87.html data-rel=dialog data-ajax=false>शौरीपुर वाले</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-88.html data-rel=dialog data-ajax=false>श्री अरिहंत छवि लखिके</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-89.html data-rel=dialog data-ajax=false>श्री जिनवर पद ध्यावें जे नर</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-90.html data-rel=dialog data-ajax=false>सीमंधर स्वामी</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-91.html data-rel=dialog data-ajax=false>सुरपति ले अपने शीश</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-92.html data-rel=dialog data-ajax=false>स्वामी तेरा मुखडा</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-93.html data-rel=dialog data-ajax=false>हम यही कामना करते हैं</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-94.html data-rel=dialog data-ajax=false>हरो पीर मेरी</a></li>');
  $('#bhajanListView-01-देव').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/01-देव/html/bhajan-95.html data-rel=dialog data-ajax=false>हे प्रभो चरणों में</a></li>');
  $("\#bhajanListView-01-देव").listview('refresh');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-1.html data-rel=dialog data-ajax=false>आज मैं परम पदारथ</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-2.html data-rel=dialog data-ajax=false>ओंकारमयी वाणी तेरी</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-3.html data-rel=dialog data-ajax=false>करता हूं मैं अभिनंदन</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-4.html data-rel=dialog data-ajax=false>चरणों में आ पडा हूं</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-5.html data-rel=dialog data-ajax=false>जब एक रत्न अनमोल</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-6.html data-rel=dialog data-ajax=false>जिनवाणी अमृत रसाल</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-7.html data-rel=dialog data-ajax=false>जिनवाणी की सुनै सो</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-8.html data-rel=dialog data-ajax=false>जिनवाणी जग मैया</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-9.html data-rel=dialog data-ajax=false>जिनवाणी माँ जिनवाणी माँ</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-10.html data-rel=dialog data-ajax=false>जिनवाणी माता दर्शन की</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-11.html data-rel=dialog data-ajax=false>जिनवाणी माता रत्नत्रय निधि</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-12.html data-rel=dialog data-ajax=false>जिनवैन सुनत, मोरी भूल भगी</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-13.html data-rel=dialog data-ajax=false>धन्य धन्य जिनवाणी माता शरण</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-14.html data-rel=dialog data-ajax=false>धन्य धन्य वीतराग वाणी</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-15.html data-rel=dialog data-ajax=false>महिमा है अगम</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-16.html data-rel=dialog data-ajax=false>माँ जिनवाणी तेरो नाम</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-17.html data-rel=dialog data-ajax=false>माँ जिनवाणी बसो हृदय में</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-18.html data-rel=dialog data-ajax=false>माता तू दया करके</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-19.html data-rel=dialog data-ajax=false>म्हारी माँ जिनवाणी</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-20.html data-rel=dialog data-ajax=false>ये शाश्वत सुख का प्याला</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-21.html data-rel=dialog data-ajax=false>शरण कोई नहीं जग में</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-22.html data-rel=dialog data-ajax=false>शांती सुधा बरसाये</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-23.html data-rel=dialog data-ajax=false>सांची तो गंगा</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-24.html data-rel=dialog data-ajax=false>सीमंधर मुख से</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-25.html data-rel=dialog data-ajax=false>सुनकर वाणी जिनवर की</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-26.html data-rel=dialog data-ajax=false>हे जिनवाणी माता तुमको लाखों प्रणाम</a></li>');
  $('#bhajanListView-02-शास्त्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/02-शास्त्र/html/bhajan-27.html data-rel=dialog data-ajax=false>हे शारदे माँ</a></li>');
  $("\#bhajanListView-02-शास्त्र").listview('refresh');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-1.html data-rel=dialog data-ajax=false>ऐसा योगी क्यों न अभयपद पावै</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-2.html data-rel=dialog data-ajax=false>ऐसे मुनिवर देखें</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-3.html data-rel=dialog data-ajax=false>ऐसे साधु सुगुरु कब मिलि हैं</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-4.html data-rel=dialog data-ajax=false>कबधौं मिलै मोहि श्रीगुरु</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-5.html data-rel=dialog data-ajax=false>गुरु रत्नत्रय के धारी</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-6.html data-rel=dialog data-ajax=false>धन धन जैनी साधु…</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-7.html data-rel=dialog data-ajax=false>धनि मुनि जिन यह</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-8.html data-rel=dialog data-ajax=false>धनि मुनि निज आतमहित कीना</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-9.html data-rel=dialog data-ajax=false>धन्य मुनिराज हमारे हैं</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-10.html data-rel=dialog data-ajax=false>धन्य मुनीश्वर आतम हित में</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-11.html data-rel=dialog data-ajax=false>नित उठ ध्याऊँ, गुण गाऊँ</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-12.html data-rel=dialog data-ajax=false>निर्ग्रंथों का मार्ग</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-13.html data-rel=dialog data-ajax=false>परम गुरु बरसत ज्ञान झरी</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-14.html data-rel=dialog data-ajax=false>परम दिगम्बर मुनिवर देखे</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-15.html data-rel=dialog data-ajax=false>परम दिगम्बर यती</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-16.html data-rel=dialog data-ajax=false>बधाई आज मिल गाओ</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-17.html data-rel=dialog data-ajax=false>मुनिवर आज मेरी कुटिया में</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-18.html data-rel=dialog data-ajax=false>मुनिवर को आहार</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-19.html data-rel=dialog data-ajax=false>म्हारा परम दिगम्बर मुनिवर आया</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-20.html data-rel=dialog data-ajax=false>वे मुनिवर कब मिली हैं उपगारी</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-21.html data-rel=dialog data-ajax=false>वेष दिगम्बर धार</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-22.html data-rel=dialog data-ajax=false>शान्ति सुधा बरसा गये</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-23.html data-rel=dialog data-ajax=false>शुद्धातम तत्व विलासी रे</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-24.html data-rel=dialog data-ajax=false>श्री मुनि राजत समता संग</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-25.html data-rel=dialog data-ajax=false>संत साधु बन के विचरूँ</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-26.html data-rel=dialog data-ajax=false>सिद्धों की श्रेणी में आने वाला</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-27.html data-rel=dialog data-ajax=false>है परम-दिगम्बर मुद्रा जिनकी</a></li>');
  $('#bhajanListView-03-गुरु').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/03-गुरु/html/bhajan-28.html data-rel=dialog data-ajax=false>होली खेलें मुनिराज शिखर वन में</a></li>');
  $("\#bhajanListView-03-गुरु").listview('refresh');
  $('#bhajanListView-04-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-1.html data-rel=dialog data-ajax=false>आजा अपने धर्म की तू राह में</a></li>');
  $('#bhajanListView-04-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-2.html data-rel=dialog data-ajax=false>उठे सब के कदम</a></li>');
  $('#bhajanListView-04-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-3.html data-rel=dialog data-ajax=false>जय जिनेन्द्र बोलिए</a></li>');
  $('#bhajanListView-04-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-4.html data-rel=dialog data-ajax=false>जहाँ रागद्वेष से रहित निराकुल</a></li>');
  $('#bhajanListView-04-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-5.html data-rel=dialog data-ajax=false>जैन धर्म के हीरे मोती</a></li>');
  $('#bhajanListView-04-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-6.html data-rel=dialog data-ajax=false>बडे भाग्य से हमको मिला जिन धर्म</a></li>');
  $('#bhajanListView-04-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-7.html data-rel=dialog data-ajax=false>भावों में सरलता रहती है</a></li>');
  $('#bhajanListView-04-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-8.html data-rel=dialog data-ajax=false>मैं महापुण्य उदय से जिनधर्म</a></li>');
  $('#bhajanListView-04-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-9.html data-rel=dialog data-ajax=false>ये धरम है आतम ज्ञानी का</a></li>');
  $('#bhajanListView-04-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-10.html data-rel=dialog data-ajax=false>लहर लहर लहराये, केसरिया झंडा</a></li>');
  $('#bhajanListView-04-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-11.html data-rel=dialog data-ajax=false>लहरायेगा-लहरायेगा झंडा</a></li>');
  $('#bhajanListView-04-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-12.html data-rel=dialog data-ajax=false>श्रीजिनधर्म सदा जयवन्त</a></li>');
  $('#bhajanListView-04-धर्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/04-धर्म/html/bhajan-13.html data-rel=dialog data-ajax=false>सब जैन धर्म की जय बोलो</a></li>');
  $("\#bhajanListView-04-धर्म").listview('refresh');
  $('#bhajanListView-05-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-1.html data-rel=dialog data-ajax=false>ऊंचे ऊंचे शिखरों वाला 1</a></li>');
  $('#bhajanListView-05-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-2.html data-rel=dialog data-ajax=false>ऊंचे ऊंचे शिखरों वाला 2</a></li>');
  $('#bhajanListView-05-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-3.html data-rel=dialog data-ajax=false>ऊंचे शिखरों पे बसा है</a></li>');
  $('#bhajanListView-05-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-4.html data-rel=dialog data-ajax=false>गगन मंडल में उड जाऊं</a></li>');
  $('#bhajanListView-05-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-5.html data-rel=dialog data-ajax=false>चलो सब मिल सिधगिरी</a></li>');
  $('#bhajanListView-05-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-6.html data-rel=dialog data-ajax=false>जीयरा...जीयरा...जीयरा</a></li>');
  $('#bhajanListView-05-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-7.html data-rel=dialog data-ajax=false>मधुबन के मंदिरों में</a></li>');
  $('#bhajanListView-05-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-8.html data-rel=dialog data-ajax=false>रे मन भज ले प्रभु का नाम</a></li>');
  $('#bhajanListView-05-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-9.html data-rel=dialog data-ajax=false>विश्व तीर्थ बडा प्यारा</a></li>');
  $('#bhajanListView-05-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-10.html data-rel=dialog data-ajax=false>सम्मेद शिखर पर मैं जाऊंगा</a></li>');
  $('#bhajanListView-05-तीर्थ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/05-तीर्थ/html/bhajan-11.html data-rel=dialog data-ajax=false>सांवरिया पारसनाथ शिखर पर</a></li>');
  $("\#bhajanListView-05-तीर्थ").listview('refresh');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-1.html data-rel=dialog data-ajax=false>आज तो बधाई राजा नाभि</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-2.html data-rel=dialog data-ajax=false>आनंद अवसर आज सुरगण आये</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-3.html data-rel=dialog data-ajax=false>आया पंच कल्याणक महान</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-4.html data-rel=dialog data-ajax=false>कल्पद्रुम यह समवसरण है</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-5.html data-rel=dialog data-ajax=false>कुण्डलपुर में वीर हैं जन्मे</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-6.html data-rel=dialog data-ajax=false>कुण्डलपुर वाले कुण्डलपुर वाले वीरजी</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-7.html data-rel=dialog data-ajax=false>गर्भ कल्याणक आ गया</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-8.html data-rel=dialog data-ajax=false>गावो री बधाईयां</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-9.html data-rel=dialog data-ajax=false>गिरनारी पर तप कल्याणक</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-10.html data-rel=dialog data-ajax=false>घर घर आनंद छायो</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-11.html data-rel=dialog data-ajax=false>चन्द्रोज्वल अविकार स्वामी जी</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-12.html data-rel=dialog data-ajax=false>जनम लिया है महावीर ने</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-13.html data-rel=dialog data-ajax=false>झुलाय दइयो पलना</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-14.html data-rel=dialog data-ajax=false>तेरे पांच हुये कल्याण प्रभु</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-15.html data-rel=dialog data-ajax=false>दिन-आयो दिन-आयो</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-16.html data-rel=dialog data-ajax=false>दिव्य ध्वनि वीरा खिराई</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-17.html data-rel=dialog data-ajax=false>नाचे रे इन्दर देव</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-18.html data-rel=dialog data-ajax=false>पंखिड़ा तू उड़ के जाना स्वर्ग</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-19.html data-rel=dialog data-ajax=false>पंखिडा रे उड के आओ कुंड्लपुर में</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-20.html data-rel=dialog data-ajax=false>पंचकल्याण मनाओ मेरे साथी</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-21.html data-rel=dialog data-ajax=false>पालकी उठाने का हमें अधिकार है</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-22.html data-rel=dialog data-ajax=false>बाजे कुण्डलपुर में बधाई</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-23.html data-rel=dialog data-ajax=false>मणियों के पलने में स्वामी महावीर</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-24.html data-rel=dialog data-ajax=false>महावीरा झूले पलना</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-25.html data-rel=dialog data-ajax=false>मेरा पलने में</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-26.html data-rel=dialog data-ajax=false>ये महामहोत्सव पंच कल्याणक</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-27.html data-rel=dialog data-ajax=false>रोम रोम में नेमिकुंवर के</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-28.html data-rel=dialog data-ajax=false>लिया आज प्रभु जी ने जनम सखी</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-29.html data-rel=dialog data-ajax=false>लिया प्रभू अवतार जयजयकार</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-30.html data-rel=dialog data-ajax=false>लिया रिषभ देव अवतार</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-31.html data-rel=dialog data-ajax=false>विषयों की तृष्णा को छोड</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-32.html data-rel=dialog data-ajax=false>सुरपति ले अपने शीश</a></li>');
  $('#bhajanListView-06-कल्याणक').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/06-कल्याणक/html/bhajan-33.html data-rel=dialog data-ajax=false>हो संसार लगने लगा अब</a></li>');
  $("\#bhajanListView-06-कल्याणक").listview('refresh');
  $('#bhajanListView-07-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-1.html data-rel=dialog data-ajax=false>करना मन ध्यान महामंत्र</a></li>');
  $('#bhajanListView-07-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-2.html data-rel=dialog data-ajax=false>जप जप रे नवकार मंत्र</a></li>');
  $('#bhajanListView-07-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-3.html data-rel=dialog data-ajax=false>जय जय जय कार परमेष्ठी</a></li>');
  $('#bhajanListView-07-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-4.html data-rel=dialog data-ajax=false>जो मंगल चार जगत में हैं</a></li>');
  $('#bhajanListView-07-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-5.html data-rel=dialog data-ajax=false>णमोकार नाम का ये कौन मंत्र</a></li>');
  $('#bhajanListView-07-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-6.html data-rel=dialog data-ajax=false>णमोकार मन्त्र को प्रणाम हो</a></li>');
  $('#bhajanListView-07-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-7.html data-rel=dialog data-ajax=false>नमन हमारा अरिहंतों को</a></li>');
  $('#bhajanListView-07-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-8.html data-rel=dialog data-ajax=false>पंच परम परमेष्ठी देखे</a></li>');
  $('#bhajanListView-07-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-9.html data-rel=dialog data-ajax=false>बने जीवन का मेरा आधार रे</a></li>');
  $('#bhajanListView-07-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-10.html data-rel=dialog data-ajax=false>मंत्र जपो नवकार मनुवा</a></li>');
  $('#bhajanListView-07-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-11.html data-rel=dialog data-ajax=false>मंत्र नवकार हमें प्राणों से प्यारा</a></li>');
  $('#bhajanListView-07-महामंत्र').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/07-महामंत्र/html/bhajan-12.html data-rel=dialog data-ajax=false>मंत्र नवकारा हृदय में धर</a></li>');
  $("\#bhajanListView-07-महामंत्र").listview('refresh');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-1.html data-rel=dialog data-ajax=false>अपनी सुधि पाय आप</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-2.html data-rel=dialog data-ajax=false>अपनी सुधि भूल आप</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-3.html data-rel=dialog data-ajax=false>अपने में अपना परमातम</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-4.html data-rel=dialog data-ajax=false>अब गतियों में नाहीं रुलेंगे</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-5.html data-rel=dialog data-ajax=false>अब मेरे समकित सावन</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-6.html data-rel=dialog data-ajax=false>अरे जिया जग धोखे की टाटी</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-7.html data-rel=dialog data-ajax=false>आओ रे आओ रे ज्ञानानंद की डगरिया</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-8.html data-rel=dialog data-ajax=false>आतम रूप अनूपम अद्भुत</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-9.html data-rel=dialog data-ajax=false>ऐसा मोही क्यों न अधोगति जावै</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-10.html data-rel=dialog data-ajax=false>ओ जीवड़ा तू थारी</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-11.html data-rel=dialog data-ajax=false>और अबै न कुदेव सुहावै</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-12.html data-rel=dialog data-ajax=false>कबधौं सर पर धर डोलेगा</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-13.html data-rel=dialog data-ajax=false>कबै निरग्रंथ स्वरूप धरूंगा</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-14.html data-rel=dialog data-ajax=false>करलो आतम ज्ञान परमातम</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-15.html data-rel=dialog data-ajax=false>कहा मानले ओ मेरे भैया</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-16.html data-rel=dialog data-ajax=false>काहे पाप करे काहे छल</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-17.html data-rel=dialog data-ajax=false>कैसो सुंदर अवसर आयो है</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-18.html data-rel=dialog data-ajax=false>कोई लाख करे चतुराई</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-19.html data-rel=dialog data-ajax=false>क्यूं करे अभिमान जीवन</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-20.html data-rel=dialog data-ajax=false>गाडी खडी रे खडी रे तैयार</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-21.html data-rel=dialog data-ajax=false>चेतन अपनो रूप निहारो</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-22.html data-rel=dialog data-ajax=false>चेतन तूँ तिहुँ काल अकेला</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-23.html data-rel=dialog data-ajax=false>जब चले आत्माराम</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-24.html data-rel=dialog data-ajax=false>जिया कब तक उलझेगा</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-25.html data-rel=dialog data-ajax=false>जीव! तू भ्रमत सदैव अकेला</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-26.html data-rel=dialog data-ajax=false>जीवन के किसी भी पल में</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-27.html data-rel=dialog data-ajax=false>जैन धरम के हीरे मोती</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-28.html data-rel=dialog data-ajax=false>जो अपना नहीं उसके अपनेपन</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-29.html data-rel=dialog data-ajax=false>जो आज दिन है वो, कल ना रहेगा</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-30.html data-rel=dialog data-ajax=false>जो जो देखी वीतराग</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-31.html data-rel=dialog data-ajax=false>ज्ञाता दृष्टा राही हूं</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-32.html data-rel=dialog data-ajax=false>तन पिंजरे के अन्दर बैठा</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-33.html data-rel=dialog data-ajax=false>तू जाग रे चेतन देव तुझे जिनदेव</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-34.html data-rel=dialog data-ajax=false>तू जाग रे चेतन प्राणी</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-35.html data-rel=dialog data-ajax=false>तोड़ विषियों से मन जोड़</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-36.html data-rel=dialog data-ajax=false>देखा जब अपने अंतर को</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-37.html data-rel=dialog data-ajax=false>धोली हो गई रे काली कामली</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-38.html data-rel=dialog data-ajax=false>ध्यान धर ले प्रभू को</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-39.html data-rel=dialog data-ajax=false>निजपुर में आज मची रे होरी</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-40.html data-rel=dialog data-ajax=false>निजपुर में आज मची होरी</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-41.html data-rel=dialog data-ajax=false>पाना नहीं जीवन को</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-42.html data-rel=dialog data-ajax=false>पाप मिटाता चल ओ बंधू</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-43.html data-rel=dialog data-ajax=false>भजन बिन योंही जनम गमायो</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-44.html data-rel=dialog data-ajax=false>भाया थारी बावली जवानी</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-45.html data-rel=dialog data-ajax=false>भूल के अपना घर</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-46.html data-rel=dialog data-ajax=false>मन महल में दो दो भाव जगे</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-47.html data-rel=dialog data-ajax=false>ममता की पतवार ना तोडी</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-48.html data-rel=dialog data-ajax=false>माया में फ़ंसे इंसान</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-49.html data-rel=dialog data-ajax=false>मेरे कब ह्वै वा दिन की सुघरी</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-50.html data-rel=dialog data-ajax=false>मैं ज्ञानानंद स्वभावी हूं</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-51.html data-rel=dialog data-ajax=false>मैं दर्शन ज्ञान स्वरूपी हूं</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-52.html data-rel=dialog data-ajax=false>मैं हूँ आतमराम</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-53.html data-rel=dialog data-ajax=false>मोक्ष पद मिलता है धीरे धीरे</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-54.html data-rel=dialog data-ajax=false>मोह की महिमा देखो</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-55.html data-rel=dialog data-ajax=false>मोहे भावे न भैया थारो देश</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-56.html data-rel=dialog data-ajax=false>ये शाश्वत सुख का प्याला</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-57.html data-rel=dialog data-ajax=false>वीर भज ले रे भाया</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-58.html data-rel=dialog data-ajax=false>शास्त्रों की बातों को मन</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-59.html data-rel=dialog data-ajax=false>संसार महा अघसागर</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-60.html data-rel=dialog data-ajax=false>सजधज के जिस दिन</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-61.html data-rel=dialog data-ajax=false>सिद्धों से मिलने का मार्ग</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-62.html data-rel=dialog data-ajax=false>सुन रे जिया चिरकाल गया</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-63.html data-rel=dialog data-ajax=false>सुनो जिया ये सतगुरु की बातैं</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-64.html data-rel=dialog data-ajax=false>सोते सोते ही निकल</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-65.html data-rel=dialog data-ajax=false>हम तो कबहुँ न निज घर आये</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-66.html data-rel=dialog data-ajax=false>हम तो कबहुँ न निजगुन भाये</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-67.html data-rel=dialog data-ajax=false>हम तो कबहूँ न हित उपजाये</a></li>');
  $('#bhajanListView-08-अध्यात्म').append('<li data-theme="b"><a href='+relPath+'jainDataBase/bhajans/08-अध्यात्म/html/bhajan-68.html data-rel=dialog data-ajax=false>हम न किसीके कोई न हमारा</a></li>');
  $("\#bhajanListView-08-अध्यात्म").listview('refresh');
})
$(document).on( 'pagecontainershow', function(){
  $('#poojaListView-प्रारम्भ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/01_प्रारम्भ/001_श्री-मंगलाष्टक-स्तोत्र/html/index.html data-rel=dialog data-ajax=false>श्री-मंगलाष्टक-स्तोत्र</a></li>');
  $('#poojaListView-प्रारम्भ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/01_प्रारम्भ/004_दर्शनं-देव-देवस्य/html/index.html data-rel=dialog data-ajax=false>दर्शनं-देव-देवस्य</a></li>');
  $('#poojaListView-प्रारम्भ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/01_प्रारम्भ/005_दर्शन-पाठ---बुधजनजी/html/index.html data-rel=dialog data-ajax=false>दर्शन-पाठ---बुधजनजी</a></li>');
  $('#poojaListView-प्रारम्भ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/01_प्रारम्भ/006_दर्शन-पाठ/html/index.html data-rel=dialog data-ajax=false>दर्शन-पाठ</a></li>');
  $('#poojaListView-प्रारम्भ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/01_प्रारम्भ/007_प्रतिमा-प्रक्षाल-विधि-पाठ/html/index.html data-rel=dialog data-ajax=false>प्रतिमा-प्रक्षाल-विधि-पाठ</a></li>');
  $('#poojaListView-प्रारम्भ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/01_प्रारम्भ/008_अभिषेक-पाठ-भाषा--हरजसरायजी/html/index.html data-rel=dialog data-ajax=false>अभिषेक-पाठ-भाषा--हरजसरायजी</a></li>');
  $('#poojaListView-प्रारम्भ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/01_प्रारम्भ/009_अभिषेक-पाठ-लघु/html/index.html data-rel=dialog data-ajax=false>अभिषेक-पाठ-लघु</a></li>');
  $('#poojaListView-प्रारम्भ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/01_प्रारम्भ/010_अमृत-से-गगरी-भरो/html/index.html data-rel=dialog data-ajax=false>अमृत-से-गगरी-भरो</a></li>');
  $('#poojaListView-प्रारम्भ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/01_प्रारम्भ/011_महावीर-की-मूंगावरणी/html/index.html data-rel=dialog data-ajax=false>महावीर-की-मूंगावरणी</a></li>');
  $('#poojaListView-प्रारम्भ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/01_प्रारम्भ/012_विनय-पाठ-दोहावली/html/index.html data-rel=dialog data-ajax=false>विनय-पाठ-दोहावली</a></li>');
  $('#poojaListView-प्रारम्भ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/01_प्रारम्भ/012_विनय-पाठ-लघु--सफ़ल-जन्म/html/index.html data-rel=dialog data-ajax=false>विनय-पाठ-लघु--सफ़ल-जन्म</a></li>');
  $('#poojaListView-प्रारम्भ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/01_प्रारम्भ/013_मंगलपाठ/html/index.html data-rel=dialog data-ajax=false>मंगलपाठ</a></li>');
  $('#poojaListView-प्रारम्भ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/01_प्रारम्भ/014_भजन-मैं-थाने-पूजन-आयो/html/index.html data-rel=dialog data-ajax=false>भजन-मैं-थाने-पूजन-आयो</a></li>');
  $('#poojaListView-प्रारम्भ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/01_प्रारम्भ/016_पूजा-विधि-प्रारंभ/html/index.html data-rel=dialog data-ajax=false>पूजा-विधि-प्रारंभ</a></li>');
  $('#poojaListView-प्रारम्भ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/01_प्रारम्भ/018_अर्घ/html/index.html data-rel=dialog data-ajax=false>अर्घ</a></li>');
  $('#poojaListView-प्रारम्भ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/01_प्रारम्भ/020_स्वस्ति-मंगल-विधान/html/index.html data-rel=dialog data-ajax=false>स्वस्ति-मंगल-विधान</a></li>');
  $('#poojaListView-प्रारम्भ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/01_प्रारम्भ/023_चतुर्विंशति-तीर्थंकर-स्वस्ति-विधान/html/index.html data-rel=dialog data-ajax=false>चतुर्विंशति-तीर्थंकर-स्वस्ति-विधान</a></li>');
  $('#poojaListView-प्रारम्भ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/01_प्रारम्भ/026_अथ-परमर्षि-स्वस्ति-मंगल-विधान/html/index.html data-rel=dialog data-ajax=false>अथ-परमर्षि-स्वस्ति-मंगल-विधान</a></li>');
  $('#poojaListView-प्रारम्भ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/01_प्रारम्भ/030_स्तुति-बुधजनजी/html/index.html data-rel=dialog data-ajax=false>स्तुति-बुधजनजी</a></li>');
  $("\#poojaListView-प्रारम्भ").listview('refresh');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/01_देव-शास्त्र-गुरु-युगलजी/html/index.html data-rel=dialog data-ajax=false>देव-शास्त्र-गुरु-युगलजी</a></li>');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/02_देव-शास्त्र-गुरु-द्यानतरायजी/html/index.html data-rel=dialog data-ajax=false>देव-शास्त्र-गुरु-द्यानतरायजी</a></li>');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/03_पंचपरमेष्ठी-पवैयाजी/html/index.html data-rel=dialog data-ajax=false>पंचपरमेष्ठी-पवैयाजी</a></li>');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/04_नवदेवता-पूजन-आर्यिका-ज्ञानमती/html/index.html data-rel=dialog data-ajax=false>नवदेवता-पूजन-आर्यिका-ज्ञानमती</a></li>');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/05_सिद्धपूजा-युगलजी/html/index.html data-rel=dialog data-ajax=false>सिद्धपूजा-युगलजी</a></li>');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/05_सिद्धपूजा--हीराचंद/html/index.html data-rel=dialog data-ajax=false>सिद्धपूजा--हीराचंद</a></li>');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/06_सम्यकदर्शन/html/index.html data-rel=dialog data-ajax=false>सम्यकदर्शन</a></li>');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/07_सम्यकज्ञान/html/index.html data-rel=dialog data-ajax=false>सम्यकज्ञान</a></li>');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/08_सम्यकचारित्र/html/index.html data-rel=dialog data-ajax=false>सम्यकचारित्र</a></li>');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/09_चौबीस-तीर्थंकर-वृन्दावनदास/html/index.html data-rel=dialog data-ajax=false>चौबीस-तीर्थंकर-वृन्दावनदास</a></li>');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/10_समुच्च-पूजा-ब्र.सरदारमलजी/html/index.html data-rel=dialog data-ajax=false>समुच्च-पूजा-ब्र.सरदारमलजी</a></li>');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/11_बाहुबली-भगवान-पवैयाजी/html/index.html data-rel=dialog data-ajax=false>बाहुबली-भगवान-पवैयाजी</a></li>');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/12_सीमन्धर-भगवान-हुकमचन्द-भारिल्ल/html/index.html data-rel=dialog data-ajax=false>सीमन्धर-भगवान-हुकमचन्द-भारिल्ल</a></li>');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/13_दशलक्षण-धर्म-द्यानतरायजी/html/index.html data-rel=dialog data-ajax=false>दशलक्षण-धर्म-द्यानतरायजी</a></li>');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/14_पंचमेरु-पूजन/html/index.html data-rel=dialog data-ajax=false>पंचमेरु-पूजन</a></li>');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/15_विद्यमान-बीस-तीर्थंकर-द्यानतरायजी/html/index.html data-rel=dialog data-ajax=false>विद्यमान-बीस-तीर्थंकर-द्यानतरायजी</a></li>');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/16_सोलहकारण-भावना-द्यानतरायजी/html/index.html data-rel=dialog data-ajax=false>सोलहकारण-भावना-द्यानतरायजी</a></li>');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/17_नंदीश्वर-द्वीप-पूजन/html/index.html data-rel=dialog data-ajax=false>नंदीश्वर-द्वीप-पूजन</a></li>');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/18_निर्वाणक्षेत्र-पवैयाजी/html/index.html data-rel=dialog data-ajax=false>निर्वाणक्षेत्र-पवैयाजी</a></li>');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/19_सरस्वती-पूजन--द्यानतरायजी/html/index.html data-rel=dialog data-ajax=false>सरस्वती-पूजन--द्यानतरायजी</a></li>');
  $('#poojaListView-नित्य-पूजा').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/02_नित्य-पूजा/20_आदिनाथ-भगवान--जिनेश्वरदासजी/html/index.html data-rel=dialog data-ajax=false>आदिनाथ-भगवान--जिनेश्वरदासजी</a></li>');
  $("\#poojaListView-नित्य-पूजा").listview('refresh');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/01_श्रीआदिनाथ-पूजन/html/index.html data-rel=dialog data-ajax=false>श्रीआदिनाथ-पूजन</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/02_श्रीअजितनाथ-पूजन/html/index.html data-rel=dialog data-ajax=false>श्रीअजितनाथ-पूजन</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/03_श्रीसंभवनाथ-पूजन/html/index.html data-rel=dialog data-ajax=false>श्रीसंभवनाथ-पूजन</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/04_श्रीअभिनन्दननाथ-पूजन/html/index.html data-rel=dialog data-ajax=false>श्रीअभिनन्दननाथ-पूजन</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/05_श्रीसुमतिनाथ-पूजन/html/index.html data-rel=dialog data-ajax=false>श्रीसुमतिनाथ-पूजन</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/06_श्रीपद्मप्रभ-पूजन/html/index.html data-rel=dialog data-ajax=false>श्रीपद्मप्रभ-पूजन</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/07_श्रीसुपार्श्वनाथ-पूजन/html/index.html data-rel=dialog data-ajax=false>श्रीसुपार्श्वनाथ-पूजन</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/08_श्रीचन्द्रप्रभनाथ-पूजन--वृन्दावनदासजी/html/index.html data-rel=dialog data-ajax=false>श्रीचन्द्रप्रभनाथ-पूजन--वृन्दावनदासजी</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/09_श्रीपुष्पदन्त-पूजन/html/index.html data-rel=dialog data-ajax=false>श्रीपुष्पदन्त-पूजन</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/10_श्रीशीतलनाथ-पूजन/html/index.html data-rel=dialog data-ajax=false>श्रीशीतलनाथ-पूजन</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/11_श्रीश्रेयांसनाथ-पूजन/html/index.html data-rel=dialog data-ajax=false>श्रीश्रेयांसनाथ-पूजन</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/12_श्रीवासुपूज्य-पूजन/html/index.html data-rel=dialog data-ajax=false>श्रीवासुपूज्य-पूजन</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/13_श्रीविमलनाथ-पूजन/html/index.html data-rel=dialog data-ajax=false>श्रीविमलनाथ-पूजन</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/14_श्रीअनन्तनाथ-पूजन/html/index.html data-rel=dialog data-ajax=false>श्रीअनन्तनाथ-पूजन</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/15_श्रीधर्मनाथ-पूजन/html/index.html data-rel=dialog data-ajax=false>श्रीधर्मनाथ-पूजन</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/16_श्रीशांतिनाथ-पूजन--बख्तावरजी/html/index.html data-rel=dialog data-ajax=false>श्रीशांतिनाथ-पूजन--बख्तावरजी</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/16_श्रीशांतिनाथ-पूजन--वृन्दावनदासजी/html/index.html data-rel=dialog data-ajax=false>श्रीशांतिनाथ-पूजन--वृन्दावनदासजी</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/17_श्रीकुंथुनाथ-पूजन/html/index.html data-rel=dialog data-ajax=false>श्रीकुंथुनाथ-पूजन</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/18_श्रीअरहनाथ-पूजन/html/index.html data-rel=dialog data-ajax=false>श्रीअरहनाथ-पूजन</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/19_श्रीमल्लिनाथ-पूजन/html/index.html data-rel=dialog data-ajax=false>श्रीमल्लिनाथ-पूजन</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/20_श्रीमुनिसुव्रतनाथ-पूजन/html/index.html data-rel=dialog data-ajax=false>श्रीमुनिसुव्रतनाथ-पूजन</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/21_श्रीनमिनाथ-पूजन/html/index.html data-rel=dialog data-ajax=false>श्रीनमिनाथ-पूजन</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/22_श्रीनेमिनाथ-पूजन/html/index.html data-rel=dialog data-ajax=false>श्रीनेमिनाथ-पूजन</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/23_श्रीपार्श्वनाथ-पूजन-बख्तावरजी/html/index.html data-rel=dialog data-ajax=false>श्रीपार्श्वनाथ-पूजन-बख्तावरजी</a></li>');
  $('#poojaListView-तीर्थंकर').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/03_तीर्थंकर/24_श्रीमहावीर-पूजन--वृन्दावनदासजी/html/index.html data-rel=dialog data-ajax=false>श्रीमहावीर-पूजन--वृन्दावनदासजी</a></li>');
  $("\#poojaListView-तीर्थंकर").listview('refresh');
  $('#poojaListView-पर्व-पूजन').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/04_पर्व-पूजन/01_अक्षय-तृतीया-पवैयाजी/html/index.html data-rel=dialog data-ajax=false>अक्षय-तृतीया-पवैयाजी</a></li>');
  $('#poojaListView-पर्व-पूजन').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/04_पर्व-पूजन/02_दीपावली-पवैयाजी/html/index.html data-rel=dialog data-ajax=false>दीपावली-पवैयाजी</a></li>');
  $('#poojaListView-पर्व-पूजन').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/04_पर्व-पूजन/03_वीरशासन-जयन्ती-पवैयाजी/html/index.html data-rel=dialog data-ajax=false>वीरशासन-जयन्ती-पवैयाजी</a></li>');
  $('#poojaListView-पर्व-पूजन').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/04_पर्व-पूजन/04_क्षमावाणी-पवैयाजी/html/index.html data-rel=dialog data-ajax=false>क्षमावाणी-पवैयाजी</a></li>');
  $('#poojaListView-पर्व-पूजन').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/04_पर्व-पूजन/05_रक्षाबन्धन-पवैयाजी/html/index.html data-rel=dialog data-ajax=false>रक्षाबन्धन-पवैयाजी</a></li>');
  $('#poojaListView-पर्व-पूजन').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/04_पर्व-पूजन/06_श्रुतपंचमी-पवैयाजी/html/index.html data-rel=dialog data-ajax=false>श्रुतपंचमी-पवैयाजी</a></li>');
  $("\#poojaListView-पर्व-पूजन").listview('refresh');
  $('#poojaListView-विसर्जन').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/05_विसर्जन/01_महाअर्घ्य/html/index.html data-rel=dialog data-ajax=false>महाअर्घ्य</a></li>');
  $('#poojaListView-विसर्जन').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/05_विसर्जन/02_शांति-पाठ/html/index.html data-rel=dialog data-ajax=false>शांति-पाठ</a></li>');
  $('#poojaListView-विसर्जन').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/05_विसर्जन/03_शांति-पाठ-भाषा/html/index.html data-rel=dialog data-ajax=false>शांति-पाठ-भाषा</a></li>');
  $('#poojaListView-विसर्जन').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/05_विसर्जन/04_विसर्जन-पाठ/html/index.html data-rel=dialog data-ajax=false>विसर्जन-पाठ</a></li>');
  $('#poojaListView-विसर्जन').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/05_विसर्जन/05_भगवान-महावीर-आरती/html/index.html data-rel=dialog data-ajax=false>भगवान-महावीर-आरती</a></li>');
  $('#poojaListView-विसर्जन').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/05_विसर्जन/06_पंच-परमेष्ठी-आरती/html/index.html data-rel=dialog data-ajax=false>पंच-परमेष्ठी-आरती</a></li>');
  $('#poojaListView-विसर्जन').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/05_विसर्जन/07_भगवान-आदिनाथ-चालीसा/html/index.html data-rel=dialog data-ajax=false>भगवान-आदिनाथ-चालीसा</a></li>');
  $('#poojaListView-विसर्जन').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/05_विसर्जन/08_भगवान-महावीर-चालीसा/html/index.html data-rel=dialog data-ajax=false>भगवान-महावीर-चालीसा</a></li>');
  $("\#poojaListView-विसर्जन").listview('refresh');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/01_देव-स्तुति--भूधरदासजी/html/index.html data-rel=dialog data-ajax=false>देव-स्तुति--भूधरदासजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/02_मेरी-भावना--मुख्तारजी/html/index.html data-rel=dialog data-ajax=false>मेरी-भावना--मुख्तारजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/03_बारह-भावना--जयचंदजी/html/index.html data-rel=dialog data-ajax=false>बारह-भावना--जयचंदजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/04_बारह-भावना--भूधरदासजी/html/index.html data-rel=dialog data-ajax=false>बारह-भावना--भूधरदासजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/05_बारह-भावना--मंगतरायजी/html/index.html data-rel=dialog data-ajax=false>बारह-भावना--मंगतरायजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/06_महावीर-वंदना--हुकमचंदजी/html/index.html data-rel=dialog data-ajax=false>महावीर-वंदना--हुकमचंदजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/06_समाधिमरण--द्यानतरायजी/html/index.html data-rel=dialog data-ajax=false>समाधिमरण--द्यानतरायजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/07_समाधि-भावना--शिवरामजी/html/index.html data-rel=dialog data-ajax=false>समाधि-भावना--शिवरामजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/08_समाधिमरण-भाषा--सूरचंदजी/html/index.html data-rel=dialog data-ajax=false>समाधिमरण-भाषा--सूरचंदजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/09_दर्शन-स्तुति--दौलतरामजी/html/index.html data-rel=dialog data-ajax=false>दर्शन-स्तुति--दौलतरामजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/10_जिनवाणी-स्तुति/html/index.html data-rel=dialog data-ajax=false>जिनवाणी-स्तुति</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/11_आराधना-पाठ--द्यानतरायजी/html/index.html data-rel=dialog data-ajax=false>आराधना-पाठ--द्यानतरायजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/13_आलोचना-पाठ--जौहरिलालजी/html/index.html data-rel=dialog data-ajax=false>आलोचना-पाठ--जौहरिलालजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/14_दुखहरन-विनती--वृन्दावनदासजी/html/index.html data-rel=dialog data-ajax=false>दुखहरन-विनती--वृन्दावनदासजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/15_अमूल्य-तत्त्व-विचार--युगलजी/html/index.html data-rel=dialog data-ajax=false>अमूल्य-तत्त्व-विचार--युगलजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/16_बाईस-परीषह--आ.ज्ञानमती/html/index.html data-rel=dialog data-ajax=false>बाईस-परीषह--आ.ज्ञानमती</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/17_सामायिक-पाठ--आ.अमितगति/html/index.html data-rel=dialog data-ajax=false>सामायिक-पाठ--आ.अमितगति</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/19_सामायिक-पाठ--युगलजी/html/index.html data-rel=dialog data-ajax=false>सामायिक-पाठ--युगलजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/21_सामायिक-पाठ--महाचंद्रजी/html/index.html data-rel=dialog data-ajax=false>सामायिक-पाठ--महाचंद्रजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/22_सामायिक-पाठ--रविन्द्रजी/html/index.html data-rel=dialog data-ajax=false>सामायिक-पाठ--रविन्द्रजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/23_निर्वाण-कांड--भगवतीदास/html/index.html data-rel=dialog data-ajax=false>निर्वाण-कांड--भगवतीदास</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/25_वैराग्य-भावना--भूधरदासजी/html/index.html data-rel=dialog data-ajax=false>वैराग्य-भावना--भूधरदासजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/27_स्वयंभू-स्तोत्र--आ.विद्यासागर/html/index.html data-rel=dialog data-ajax=false>स्वयंभू-स्तोत्र--आ.विद्यासागर</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/29_स्वयंभू-स्तोत्र-भाषा--द्यानतरायजी/html/index.html data-rel=dialog data-ajax=false>स्वयंभू-स्तोत्र-भाषा--द्यानतरायजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/30_आत्मबोध-शतक--आर्यिका-पूर्णमति/html/index.html data-rel=dialog data-ajax=false>आत्मबोध-शतक--आर्यिका-पूर्णमति</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/33_पार्श्वनाथ-स्त्रोत्र--द्यनतरायजी/html/index.html data-rel=dialog data-ajax=false>पार्श्वनाथ-स्त्रोत्र--द्यनतरायजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/34_महावीराष्टक-स्तोत्र--पं.भागचन्द्र/html/index.html data-rel=dialog data-ajax=false>महावीराष्टक-स्तोत्र--पं.भागचन्द्र</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/35_महावीराष्टक-स्तोत्र--हिंदी/html/index.html data-rel=dialog data-ajax=false>महावीराष्टक-स्तोत्र--हिंदी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/37_कल्याणमन्दिरस्तोत्रम/html/index.html data-rel=dialog data-ajax=false>कल्याणमन्दिरस्तोत्रम</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/39_कल्याणमन्दिर-स्तोत्र-हिंदी/html/index.html data-rel=dialog data-ajax=false>कल्याणमन्दिर-स्तोत्र-हिंदी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/41_भक्तामर--आ.मानतुंग/html/index.html data-rel=dialog data-ajax=false>भक्तामर--आ.मानतुंग</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/43_भक्तामर--कमलकुमारजी/html/index.html data-rel=dialog data-ajax=false>भक्तामर--कमलकुमारजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/45_भक्तामर--हेमराजजी/html/index.html data-rel=dialog data-ajax=false>भक्तामर--हेमराजजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/47_भक्तामर--मु.श्रीरसागर/html/index.html data-rel=dialog data-ajax=false>भक्तामर--मु.श्रीरसागर</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/49_एकीभाव-स्तोत्र--आ.वादीराज/html/index.html data-rel=dialog data-ajax=false>एकीभाव-स्तोत्र--आ.वादीराज</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/50_विषापहारस्तोत्रम्--श्रीधनञ्जय/html/index.html data-rel=dialog data-ajax=false>विषापहारस्तोत्रम्--श्रीधनञ्जय</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/51_विषापहारस्तोत्र--श्रीशांतिदास/html/index.html data-rel=dialog data-ajax=false>विषापहारस्तोत्र--श्रीशांतिदास</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/52_मृत्युमहोत्सव/html/index.html data-rel=dialog data-ajax=false>मृत्युमहोत्सव</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/53_अपूर्व-अवसर--श्री.राजचंद्र/html/index.html data-rel=dialog data-ajax=false>अपूर्व-अवसर--श्री.राजचंद्र</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/55_कुंदकुंद-शतक/html/index.html data-rel=dialog data-ajax=false>कुंदकुंद-शतक</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/59_ध्यान-सूत्र-शतक--आ.माघनंदी/html/index.html data-rel=dialog data-ajax=false>ध्यान-सूत्र-शतक--आ.माघनंदी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/61_छहढाला--बुधजनजी/html/index.html data-rel=dialog data-ajax=false>छहढाला--बुधजनजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/63_छहढाला--द्यानतरायजी/html/index.html data-rel=dialog data-ajax=false>छहढाला--द्यानतरायजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/65_श्री-गोम्टेश्वर-स्तुति/html/index.html data-rel=dialog data-ajax=false>श्री-गोम्टेश्वर-स्तुति</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/67_सहस्रनाम-स्तोत्र/html/index.html data-rel=dialog data-ajax=false>सहस्रनाम-स्तोत्र</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/69_रत्नाकर-पंचविंशतिका--रामचरितजी/html/index.html data-rel=dialog data-ajax=false>रत्नाकर-पंचविंशतिका--रामचरितजी</a></li>');
  $('#poojaListView-पाठ').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/06_पाठ/70_भूपाल-पंचविंशतिका--भूधरदासजी/html/index.html data-rel=dialog data-ajax=false>भूपाल-पंचविंशतिका--भूधरदासजी</a></li>');
  $("\#poojaListView-पाठ").listview('refresh');
  $('#poojaListView-छहढाला').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/07_छहढाला/00_मंगलाचरण/html/index.html data-rel=dialog data-ajax=false>मंगलाचरण</a></li>');
  $('#poojaListView-छहढाला').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/07_छहढाला/01_पहली-ढाल/html/index.html data-rel=dialog data-ajax=false>पहली-ढाल</a></li>');
  $('#poojaListView-छहढाला').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/07_छहढाला/02_दूसरी-ढाल/html/index.html data-rel=dialog data-ajax=false>दूसरी-ढाल</a></li>');
  $('#poojaListView-छहढाला').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/07_छहढाला/03_तीसरी-ढाल/html/index.html data-rel=dialog data-ajax=false>तीसरी-ढाल</a></li>');
  $('#poojaListView-छहढाला').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/07_छहढाला/04_चौथी-ढाल/html/index.html data-rel=dialog data-ajax=false>चौथी-ढाल</a></li>');
  $('#poojaListView-छहढाला').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/07_छहढाला/05_पांचवी-ढाल/html/index.html data-rel=dialog data-ajax=false>पांचवी-ढाल</a></li>');
  $('#poojaListView-छहढाला').append('<li data-theme="b"><a href='+relPath+'jainDataBase/poojas/07_छहढाला/06_छठी-ढाल/html/index.html data-rel=dialog data-ajax=false>छठी-ढाल</a></li>');
  $("\#poojaListView-छहढाला").listview('refresh');
})
$(document).on( 'pagecontainershow', function(){
  $('#granthListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/01_द्रव्यानुयोग/01_समयसार--कुन्दकुंदाचार्य/html/index.html data-rel=dialog data-ajax=false>समयसार--कुन्दकुंदाचार्य</a></li>');
  $('#shastraListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/01_द्रव्यानुयोग/01_समयसार--कुन्दकुंदाचार्य/html/0000_introduction.html data-rel=dialog data-ajax=false>समयसार--कुन्दकुंदाचार्य</a></li>');
  $('#granthListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/01_द्रव्यानुयोग/02_प्रवचनसार--कुन्दकुंदाचार्य/html/index.html data-rel=dialog data-ajax=false>प्रवचनसार--कुन्दकुंदाचार्य</a></li>');
  $('#shastraListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/01_द्रव्यानुयोग/02_प्रवचनसार--कुन्दकुंदाचार्य/html/0000_introduction.html data-rel=dialog data-ajax=false>प्रवचनसार--कुन्दकुंदाचार्य</a></li>');
  $('#granthListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/01_द्रव्यानुयोग/05_पन्चास्तिकाय--कुन्दकुंदाचार्य/html/index.html data-rel=dialog data-ajax=false>पन्चास्तिकाय--कुन्दकुंदाचार्य</a></li>');
  $('#shastraListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/01_द्रव्यानुयोग/05_पन्चास्तिकाय--कुन्दकुंदाचार्य/html/0000_introduction.html data-rel=dialog data-ajax=false>पन्चास्तिकाय--कुन्दकुंदाचार्य</a></li>');
  $('#granthListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/01_द्रव्यानुयोग/06_द्रव्यसंग्रह--नेमिचंद्र-सिद्धांतचक्रवर्ती/html/index.html data-rel=dialog data-ajax=false>द्रव्यसंग्रह--नेमिचंद्र-सिद्धांतचक्रवर्ती</a></li>');
  $('#shastraListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/01_द्रव्यानुयोग/06_द्रव्यसंग्रह--नेमिचंद्र-सिद्धांतचक्रवर्ती/html/0000_introduction.html data-rel=dialog data-ajax=false>द्रव्यसंग्रह--नेमिचंद्र-सिद्धांतचक्रवर्ती</a></li>');
  $('#granthListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/01_द्रव्यानुयोग/07_समाधितन्त्र--आचार्य‌-पूज्यपाद/html/index.html data-rel=dialog data-ajax=false>समाधितन्त्र--आचार्य‌-पूज्यपाद</a></li>');
  $('#shastraListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/01_द्रव्यानुयोग/07_समाधितन्त्र--आचार्य‌-पूज्यपाद/html/0000_introduction.html data-rel=dialog data-ajax=false>समाधितन्त्र--आचार्य‌-पूज्यपाद</a></li>');
  $('#granthListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/01_द्रव्यानुयोग/08_स्वरूप-संबोधन--अकलंक-देव/html/index.html data-rel=dialog data-ajax=false>स्वरूप-संबोधन--अकलंक-देव</a></li>');
  $('#shastraListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/01_द्रव्यानुयोग/08_स्वरूप-संबोधन--अकलंक-देव/html/0000_introduction.html data-rel=dialog data-ajax=false>स्वरूप-संबोधन--अकलंक-देव</a></li>');
  $('#granthListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/01_द्रव्यानुयोग/09_इष्टोपदेश--आचार्य‌-पूज्यपाद/html/index.html data-rel=dialog data-ajax=false>इष्टोपदेश--आचार्य‌-पूज्यपाद</a></li>');
  $('#shastraListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/01_द्रव्यानुयोग/09_इष्टोपदेश--आचार्य‌-पूज्यपाद/html/0000_introduction.html data-rel=dialog data-ajax=false>इष्टोपदेश--आचार्य‌-पूज्यपाद</a></li>');
  $('#granthListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/01_द्रव्यानुयोग/10_परमात्मप्रकाश--योगींदुदेव/html/index.html data-rel=dialog data-ajax=false>परमात्मप्रकाश--योगींदुदेव</a></li>');
  $('#shastraListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/01_द्रव्यानुयोग/10_परमात्मप्रकाश--योगींदुदेव/html/0000_introduction.html data-rel=dialog data-ajax=false>परमात्मप्रकाश--योगींदुदेव</a></li>');
  $('#granthListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/01_द्रव्यानुयोग/11_ज्ञानार्णव/html/index.html data-rel=dialog data-ajax=false>ज्ञानार्णव</a></li>');
  $('#shastraListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/01_द्रव्यानुयोग/11_ज्ञानार्णव/html/0000_introduction.html data-rel=dialog data-ajax=false>ज्ञानार्णव</a></li>');
  $('#granthListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/01_द्रव्यानुयोग/12_योगसार-प्राभृत--अमितगति-आचार्य/html/index.html data-rel=dialog data-ajax=false>योगसार-प्राभृत--अमितगति-आचार्य</a></li>');
  $('#shastraListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/01_द्रव्यानुयोग/12_योगसार-प्राभृत--अमितगति-आचार्य/html/0000_introduction.html data-rel=dialog data-ajax=false>योगसार-प्राभृत--अमितगति-आचार्य</a></li>');
  $('#granthListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/01_द्रव्यानुयोग/13_तत्त्वार्थसूत्र--आचार्य-उमास्वामी/html/index.html data-rel=dialog data-ajax=false>तत्त्वार्थसूत्र--आचार्य-उमास्वामी</a></li>');
  $('#shastraListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/01_द्रव्यानुयोग/13_तत्त्वार्थसूत्र--आचार्य-उमास्वामी/html/0000_introduction.html data-rel=dialog data-ajax=false>तत्त्वार्थसूत्र--आचार्य-उमास्वामी</a></li>');
  $('#granthListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/01_द्रव्यानुयोग/14_योगसार--योगींदुदेव/html/index.html data-rel=dialog data-ajax=false>योगसार--योगींदुदेव</a></li>');
  $('#shastraListView-द्रव्यानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/01_द्रव्यानुयोग/14_योगसार--योगींदुदेव/html/0000_introduction.html data-rel=dialog data-ajax=false>योगसार--योगींदुदेव</a></li>');
  $("\#granthListView-द्रव्यानुयोग").listview('refresh');
  $("\#shastraListView-द्रव्यानुयोग").listview('refresh');
  $('#granthListView-चरणानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/02_चरणानुयोग/01_नियमसार--कुन्दकुंदाचार्य/html/index.html data-rel=dialog data-ajax=false>नियमसार--कुन्दकुंदाचार्य</a></li>');
  $('#shastraListView-चरणानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/02_चरणानुयोग/01_नियमसार--कुन्दकुंदाचार्य/html/0000_introduction.html data-rel=dialog data-ajax=false>नियमसार--कुन्दकुंदाचार्य</a></li>');
  $('#granthListView-चरणानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/02_चरणानुयोग/02_श्रीअष्टपाहुड--कुन्दकुंदाचार्य/html/index.html data-rel=dialog data-ajax=false>श्रीअष्टपाहुड--कुन्दकुंदाचार्य</a></li>');
  $('#shastraListView-चरणानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/02_चरणानुयोग/02_श्रीअष्टपाहुड--कुन्दकुंदाचार्य/html/0000_introduction.html data-rel=dialog data-ajax=false>श्रीअष्टपाहुड--कुन्दकुंदाचार्य</a></li>');
  $('#granthListView-चरणानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/02_चरणानुयोग/03_मूलाचार--वट्टकेराचार्य/html/index.html data-rel=dialog data-ajax=false>मूलाचार--वट्टकेराचार्य</a></li>');
  $('#shastraListView-चरणानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/02_चरणानुयोग/03_मूलाचार--वट्टकेराचार्य/html/0000_introduction.html data-rel=dialog data-ajax=false>मूलाचार--वट्टकेराचार्य</a></li>');
  $('#granthListView-चरणानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/02_चरणानुयोग/04_वारासाणुवेक्खा--स्वामि-कार्तिकेय/html/index.html data-rel=dialog data-ajax=false>वारासाणुवेक्खा--स्वामि-कार्तिकेय</a></li>');
  $('#shastraListView-चरणानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/02_चरणानुयोग/04_वारासाणुवेक्खा--स्वामि-कार्तिकेय/html/0000_introduction.html data-rel=dialog data-ajax=false>वारासाणुवेक्खा--स्वामि-कार्तिकेय</a></li>');
  $('#granthListView-चरणानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/02_चरणानुयोग/09_रत्नकरण्ड-श्रावकाचार--समन्तभद्राचार्य/html/index.html data-rel=dialog data-ajax=false>रत्नकरण्ड-श्रावकाचार--समन्तभद्राचार्य</a></li>');
  $('#shastraListView-चरणानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/02_चरणानुयोग/09_रत्नकरण्ड-श्रावकाचार--समन्तभद्राचार्य/html/0000_introduction.html data-rel=dialog data-ajax=false>रत्नकरण्ड-श्रावकाचार--समन्तभद्राचार्य</a></li>');
  $('#granthListView-चरणानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/02_चरणानुयोग/17_भगवती-आराधना--शिवाचार्य/html/index.html data-rel=dialog data-ajax=false>भगवती-आराधना--शिवाचार्य</a></li>');
  $('#shastraListView-चरणानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/02_चरणानुयोग/17_भगवती-आराधना--शिवाचार्य/html/0000_introduction.html data-rel=dialog data-ajax=false>भगवती-आराधना--शिवाचार्य</a></li>');
  $('#granthListView-चरणानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/02_चरणानुयोग/18_पद्म्नंदी-पंचविन्शतिका--आ-पद्म्नंदी/html/index.html data-rel=dialog data-ajax=false>पद्म्नंदी-पंचविन्शतिका--आ-पद्म्नंदी</a></li>');
  $('#shastraListView-चरणानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/02_चरणानुयोग/18_पद्म्नंदी-पंचविन्शतिका--आ-पद्म्नंदी/html/0000_introduction.html data-rel=dialog data-ajax=false>पद्म्नंदी-पंचविन्शतिका--आ-पद्म्नंदी</a></li>');
  $("\#granthListView-चरणानुयोग").listview('refresh');
  $("\#shastraListView-चरणानुयोग").listview('refresh');
  $('#granthListView-करणानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/03_करणानुयोग/01_लब्धिसार--नेमिचंद्र-आचार्य/html/index.html data-rel=dialog data-ajax=false>लब्धिसार--नेमिचंद्र-आचार्य</a></li>');
  $('#shastraListView-करणानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/03_करणानुयोग/01_लब्धिसार--नेमिचंद्र-आचार्य/html/0000_introduction.html data-rel=dialog data-ajax=false>लब्धिसार--नेमिचंद्र-आचार्य</a></li>');
  $('#granthListView-करणानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/03_करणानुयोग/03_गोम्मटसार-जीवकांड--नेमिचंद्र-आचार्य/html/index.html data-rel=dialog data-ajax=false>गोम्मटसार-जीवकांड--नेमिचंद्र-आचार्य</a></li>');
  $('#shastraListView-करणानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/03_करणानुयोग/03_गोम्मटसार-जीवकांड--नेमिचंद्र-आचार्य/html/0000_introduction.html data-rel=dialog data-ajax=false>गोम्मटसार-जीवकांड--नेमिचंद्र-आचार्य</a></li>');
  $("\#granthListView-करणानुयोग").listview('refresh');
  $("\#shastraListView-करणानुयोग").listview('refresh');
  $('#granthListView-प्रथमानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/05_प्रथमानुयोग/01_आराधना-कथा-कोश--ब्र-नेमिदत्त/html/index.html data-rel=dialog data-ajax=false>आराधना-कथा-कोश--ब्र-नेमिदत्त</a></li>');
  $('#shastraListView-प्रथमानुयोग').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/05_प्रथमानुयोग/01_आराधना-कथा-कोश--ब्र-नेमिदत्त/html/0000_introduction.html data-rel=dialog data-ajax=false>आराधना-कथा-कोश--ब्र-नेमिदत्त</a></li>');
  $("\#granthListView-प्रथमानुयोग").listview('refresh');
  $("\#shastraListView-प्रथमानुयोग").listview('refresh');
  $('#granthListView-न्याय').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/06_न्याय/01_आप्त-मीमांसा/html/index.html data-rel=dialog data-ajax=false>आप्त-मीमांसा</a></li>');
  $('#shastraListView-न्याय').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/06_न्याय/01_आप्त-मीमांसा/html/0000_introduction.html data-rel=dialog data-ajax=false>आप्त-मीमांसा</a></li>');
  $('#granthListView-न्याय').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/06_न्याय/02_लघीयस्त्रय/html/index.html data-rel=dialog data-ajax=false>लघीयस्त्रय</a></li>');
  $('#shastraListView-न्याय').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/06_न्याय/02_लघीयस्त्रय/html/0000_introduction.html data-rel=dialog data-ajax=false>लघीयस्त्रय</a></li>');
  $('#granthListView-न्याय').append('<li data-theme="b"><a href='+relPath+'jainDataBase/teeka/06_न्याय/03_परीक्षामुख/html/index.html data-rel=dialog data-ajax=false>परीक्षामुख</a></li>');
  $('#shastraListView-न्याय').append('<li data-theme="b"><a href='+relPath+'jainDataBase/shastra/06_न्याय/03_परीक्षामुख/html/0000_introduction.html data-rel=dialog data-ajax=false>परीक्षामुख</a></li>');
  $("\#granthListView-न्याय").listview('refresh');
  $("\#shastraListView-न्याय").listview('refresh');
  $("\#granthListView-भजन-पाठ").listview('refresh');
  $("\#shastraListView-भजन-पाठ").listview('refresh');
})
