document.write("<div id=पं-हुकमचंद-भारिल्ल class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='001.html'><font size=4><br><font size=5 color=black><b>﻿मंगलाचरण </b></font><br><br><font color=darkPurple><b>001</b></font> - <font color=darkBlue>﻿सिद्धों को नमस्कार</font></font></a></li>");
document.write("        <li><a href='002.html'><font size=4><font color=darkPurple><b>002</b></font> - <font color=darkGreen>﻿अरहंत भगवान को नमस्कार</font></font></a></li>");
document.write("        <li><a href='003.html'><font size=4><font color=darkPurple><b>003</b></font> - <font color=darkBlue>﻿ग्रन्थ को कहने का प्रयोजन</font></font></a></li>");
document.write("        <li><a href='004.html'><font size=4><font color=darkPurple><b>004</b></font> - <font color=darkGreen>﻿मिथ्यादर्शन संसार का कारण है</font></font></a></li>");
document.write("        <li><a href='005.html'><font size=4><font color=darkPurple><b>005</b></font> - <font color=darkBlue>﻿मोक्ष-सुख का कारण आत्मध्यान है</font></font></a></li>");
document.write("        <li><a href='006.html'><font size=4><font color=darkPurple><b>006</b></font> - <font color=darkGreen>﻿आत्मा तीन प्रकार है</font></font></a></li>");
document.write("        <li><a href='007.html'><font size=4><font color=darkPurple><b>007</b></font> - <font color=darkBlue>﻿बहिरात्मा का स्वरूप</font></font></a></li>");
document.write("        <li><a href='008.html'><font size=4><font color=darkPurple><b>008</b></font> - <font color=darkGreen>﻿अन्तरात्मा का स्वरूप</font></font></a></li>");
document.write("        <li><a href='009.html'><font size=4><font color=darkPurple><b>009</b></font> - <font color=darkBlue>﻿परमात्मा का स्वरूप</font></font></a></li>");
document.write("        <li><a href='010.html'><font size=4><font color=darkPurple><b>010</b></font> - <font color=darkGreen>﻿बहिरात्मा का लक्षण</font></font></a></li>");
document.write("        <li><a href='011.html'><font size=4><font color=darkPurple><b>011</b></font> - <font color=darkBlue>﻿भेद-ज्ञान की प्रेरणा</font></font></a></li>");
document.write("        <li><a href='012.html'><font size=4><font color=darkPurple><b>012</b></font> - <font color=darkGreen>﻿आत्म-ज्ञानी ही निर्वाण पाता है</font></font></a></li>");
document.write("        <li><a href='013.html'><font size=4><font color=darkPurple><b>013</b></font> - <font color=darkBlue>﻿इच्छा रहित ताप ही निर्वाण का कारण</font></font></a></li>");
document.write("        <li><a href='014.html'><font size=4><font color=darkPurple><b>014</b></font> - <font color=darkGreen>﻿परिणामों से ही बंध व मोक्ष</font></font></a></li>");
document.write("        <li><a href='015.html'><font size=4><font color=darkPurple><b>015</b></font> - <font color=darkBlue>﻿आत्म-ज्ञान शून्य पुण्य कर्म से मोक्ष नहीं </font></font></a></li>");
document.write("        <li><a href='016.html'><font size=4><font color=darkPurple><b>016</b></font> - <font color=darkGreen>﻿आत्म-दर्शन ही मोक्ष का कारण</font></font></a></li>");
document.write("        <li><a href='017.html'><font size=4><font color=darkPurple><b>017</b></font> - <font color=darkBlue>﻿मार्गणा व गुणस्थान आत्मा नहीं</font></font></a></li>");
document.write("        <li><a href='018.html'><font size=4><font color=darkPurple><b>018</b></font> - <font color=darkGreen>﻿गृहस्थी भी मोक्षमार्गी</font></font></a></li>");
document.write("        <li><a href='019.html'><font size=4><font color=darkPurple><b>019</b></font> - <font color=darkBlue>﻿जिनेन्द्र का स्मरण परम पद का कारण है</font></font></a></li>");
document.write("        <li><a href='020.html'><font size=4><font color=darkPurple><b>020</b></font> - <font color=darkGreen>﻿अपनी आत्मा और जिनेन्द्र में भेद नहीं</font></font></a></li>");
document.write("        <li><a href='021.html'><font size=4><font color=darkPurple><b>021</b></font> - <font color=darkBlue>﻿आत्मा ही जिन है, यही सिद्धांत का सार है</font></font></a></li>");
document.write("        <li><a href='022.html'><font size=4><font color=darkPurple><b>022</b></font> - <font color=darkGreen>﻿मैं ही परमात्मा हूँ</font></font></a></li>");
document.write("        <li><a href='023-024.html'><font size=4><font color=darkPurple><b>023-024</b></font> - <font color=darkBlue>﻿आत्मा निश्चय से असंख्यात-प्रदेशी लोकप्रमाण, व्यवहार से शरीरप्रमाण </font></font></a></li>");
document.write("        <li><a href='025.html'><font size=4><font color=darkPurple><b>025</b></font> - <font color=darkGreen>﻿सम्यक्त्व बिना अनन्त संसार में भ्रमण</font></font></a></li>");
document.write("        <li><a href='026-027.html'><font size=4><font color=darkPurple><b>026-027</b></font> - <font color=darkBlue>﻿शुद्धात्मा का चिंतन ही मोक्षमार्ग</font></font></a></li>");
document.write("        <li><a href='028.html'><font size=4><font color=darkPurple><b>028</b></font> - <font color=darkGreen>﻿त्रिलोक-पूज्य जिन शुद्धात्मा ही है</font></font></a></li>");
document.write("        <li><a href='029.html'><font size=4><font color=darkPurple><b>029</b></font> - <font color=darkBlue>﻿आत्मानुभव बिना मिथ्यादृष्टि के व्रत-संयम द्वारा मोक्ष नहीं</font></font></a></li>");
document.write("        <li><a href='030.html'><font size=4><font color=darkPurple><b>030</b></font> - <font color=darkGreen>﻿व्रत-संयम युक्त शुद्धात्मा के ध्यान से सिद्धि</font></font></a></li>");
document.write("        <li><a href='031.html'><font size=4><font color=darkPurple><b>031</b></font> - <font color=darkBlue>﻿अकेला व्यवहार चारित्र वृथा है</font></font></a></li>");
document.write("        <li><a href='032.html'><font size=4><font color=darkPurple><b>032</b></font> - <font color=darkGreen>﻿शुद्धोपयोग में पुण्य-पाप हेय</font></font></a></li>");
document.write("        <li><a href='033.html'><font size=4><font color=darkPurple><b>033</b></font> - <font color=darkBlue>﻿निश्चय चारित्र ही मोक्ष का कारण</font></font></a></li>");
document.write("        <li><a href='034.html'><font size=4><font color=darkPurple><b>034</b></font> - <font color=darkGreen>﻿आपसे आपको ध्याओ</font></font></a></li>");
document.write("        <li><a href='035.html'><font size=4><font color=darkPurple><b>035</b></font> - <font color=darkBlue>﻿व्यवहार में नौ पदार्थों का ज्ञान आवश्यक</font></font></a></li>");
document.write("        <li><a href='036.html'><font size=4><font color=darkPurple><b>036</b></font> - <font color=darkGreen>﻿सारभूत चेतानेवाला एक जीव ही है</font></font></a></li>");
document.write("        <li><a href='037.html'><font size=4><font color=darkPurple><b>037</b></font> - <font color=darkBlue>﻿सर्व व्यवहार को त्यागकर शुद्धात्मा को ध्याओ</font></font></a></li>");
document.write("        <li><a href='038.html'><font size=4><font color=darkPurple><b>038</b></font> - <font color=darkGreen>﻿जीव-अजीव का भेद जानो</font></font></a></li>");
document.write("        <li><a href='039.html'><font size=4><font color=darkPurple><b>039</b></font> - <font color=darkBlue>﻿आत्मा केवलज्ञान स्वाभावी है</font></font></a></li>");
document.write("        <li><a href='040.html'><font size=4><font color=darkPurple><b>040</b></font> - <font color=darkGreen>﻿ज्ञानी को हर जगह आत्मा ही दिखता है</font></font></a></li>");
document.write("        <li><a href='041.html'><font size=4><font color=darkPurple><b>041</b></font> - <font color=darkBlue>﻿अनात्मज्ञानी कुतीर्थों में भ्रमता है</font></font></a></li>");
document.write("        <li><a href='042.html'><font size=4><font color=darkPurple><b>042</b></font> - <font color=darkGreen>﻿निज शरीर रुपी मंदिर में ही निश्चय से देव रहता है  </font></font></a></li>");
document.write("        <li><a href='043.html'><font size=4><font color=darkPurple><b>043</b></font> - <font color=darkBlue>﻿देवालय में साक्षात् देव नहीं है</font></font></a></li>");
document.write("        <li><a href='044.html'><font size=4><font color=darkPurple><b>044</b></font> - <font color=darkGreen>﻿समभावरूप चित्त से अपने देह में जिनदेव को देख</font></font></a></li>");
document.write("        <li><a href='045.html'><font size=4><font color=darkPurple><b>045</b></font> - <font color=darkBlue>﻿ज्ञानी ही शरीररुपी मंदिर में परमात्मा को देखता है</font></font></a></li>");
document.write("        <li><a href='046.html'><font size=4><font color=darkPurple><b>046</b></font> - <font color=darkGreen>﻿धर्मामृत के पान से अमरता</font></font></a></li>");
document.write("        <li><a href='047.html'><font size=4><font color=darkPurple><b>047</b></font> - <font color=darkBlue>﻿बाहरी क्रिया में धर्म नहीं</font></font></a></li>");
document.write("        <li><a href='048.html'><font size=4><font color=darkPurple><b>048</b></font> - <font color=darkGreen>﻿राग-द्वेष रहित आत्मस्थ होना ही धर्म</font></font></a></li>");
document.write("        <li><a href='049.html'><font size=4><font color=darkPurple><b>049</b></font> - <font color=darkBlue>﻿आशा तृष्णा ही संसार-भ्रमण का कारण है</font></font></a></li>");
document.write("        <li><a href='050.html'><font size=4><font color=darkPurple><b>050</b></font> - <font color=darkGreen>﻿आत्म-प्रेमी ही निर्वाण का पात्र</font></font></a></li>");
document.write("        <li><a href='051.html'><font size=4><font color=darkPurple><b>051</b></font> - <font color=darkBlue>﻿शरीर को नरक सामान जानो</font></font></a></li>");
document.write("        <li><a href='052.html'><font size=4><font color=darkPurple><b>052</b></font> - <font color=darkGreen>﻿जगत के धंधों में मत उलझ</font></font></a></li>");
document.write("        <li><a href='053.html'><font size=4><font color=darkPurple><b>053</b></font> - <font color=darkBlue>﻿शास्त्र पाठ आत्मज्ञान बिना निष्फल है</font></font></a></li>");
document.write("        <li><a href='054.html'><font size=4><font color=darkPurple><b>054</b></font> - <font color=darkGreen>﻿इन्द्रिय और मन को छोड़कर सहज आत्मज्ञान</font></font></a></li>");
document.write("        <li><a href='055.html'><font size=4><font color=darkPurple><b>055</b></font> - <font color=darkBlue>﻿पुद्गल व जगत के व्यवहार से आत्मा को भिन्न जानो </font></font></a></li>");
document.write("        <li><a href='056.html'><font size=4><font color=darkPurple><b>056</b></font> - <font color=darkGreen>﻿आत्मानुभवी ही संसार से मुक्त होता है</font></font></a></li>");
document.write("        <li><a href='057.html'><font size=4><font color=darkPurple><b>057</b></font> - <font color=darkBlue>﻿आत्मा के ज्ञान के लिए नौ दृष्टांत</font></font></a></li>");
document.write("        <li><a href='058.html'><font size=4><font color=darkPurple><b>058</b></font> - <font color=darkGreen>﻿देहादिरूप मैं नहीं -- यही ज्ञान मोक्ष का बीज है</font></font></a></li>");
document.write("        <li><a href='059.html'><font size=4><font color=darkPurple><b>059</b></font> - <font color=darkBlue>﻿आकाश के सामान होकर भी मैं सचेतन हूँ</font></font></a></li>");
document.write("        <li><a href='060.html'><font size=4><font color=darkPurple><b>060</b></font> - <font color=darkGreen>﻿अपने भीतर ही मोक्ष-मार्ग है</font></font></a></li>");
document.write("        <li><a href='061.html'><font size=4><font color=darkPurple><b>061</b></font> - <font color=darkBlue>﻿निर्मोही होकर अपने अमूर्तिक आत्मा को देखें</font></font></a></li>");
document.write("        <li><a href='062.html'><font size=4><font color=darkPurple><b>062</b></font> - <font color=darkGreen>﻿आत्मानुभव का फल केवलज्ञान व अविनाशी सुख</font></font></a></li>");
document.write("        <li><a href='063.html'><font size=4><font color=darkPurple><b>063</b></font> - <font color=darkBlue>﻿परभाव का त्याग संसार त्याग का कारण है</font></font></a></li>");
document.write("        <li><a href='064.html'><font size=4><font color=darkPurple><b>064</b></font> - <font color=darkGreen>﻿धन्य हैं वे जिन्होंने समस्त पर-भावों को त्याग दिया</font></font></a></li>");
document.write("        <li><a href='065.html'><font size=4><font color=darkPurple><b>065</b></font> - <font color=darkBlue>﻿गृहस्थ हो या मुनि आत्मा में वास की प्रेरणा </font></font></a></li>");
document.write("        <li><a href='066.html'><font size=4><font color=darkPurple><b>066</b></font> - <font color=darkGreen>﻿तत्त्वश्रद्धानी विरले होते हैं</font></font></a></li>");
document.write("        <li><a href='067.html'><font size=4><font color=darkPurple><b>067</b></font> - <font color=darkBlue>﻿कुटुम्ब मोह त्यागने योग्य है</font></font></a></li>");
document.write("        <li><a href='068.html'><font size=4><font color=darkPurple><b>068</b></font> - <font color=darkGreen>﻿अशरण भावना</font></font></a></li>");
document.write("        <li><a href='069-070.html'><font size=4><font color=darkPurple><b>069-070</b></font> - <font color=darkBlue>﻿एकत्व भावना</font></font></a></li>");
document.write("        <li><a href='071.html'><font size=4><font color=darkPurple><b>071</b></font> - <font color=darkGreen>﻿पुण्य को भी पाप जाने वही ज्ञानी</font></font></a></li>");
document.write("        <li><a href='072.html'><font size=4><font color=darkPurple><b>072</b></font> - <font color=darkBlue>﻿पुण्य और पाप में बन्ध की अपेक्षा समानता</font></font></a></li>");
document.write("        <li><a href='073.html'><font size=4><font color=darkPurple><b>073</b></font> - <font color=darkGreen>﻿भाव से नग्न हो सच्चा मोक्ष-मार्गी</font></font></a></li>");
document.write("        <li><a href='074.html'><font size=4><font color=darkPurple><b>074</b></font> - <font color=darkBlue>﻿इसी देह में त्रिलोक-प्रधान भगवान रहता है</font></font></a></li>");
document.write("        <li><a href='075.html'><font size=4><font color=darkPurple><b>075</b></font> - <font color=darkGreen>﻿आप स्वयं ही जिन है -- यही भावना मोक्ष का उपाय</font></font></a></li>");
document.write("        <li><a href='076.html'><font size=4><font color=darkPurple><b>076</b></font> - <font color=darkBlue>﻿आत्मा को लक्षण द्वारा जान</font></font></a></li>");
document.write("        <li><a href='077.html'><font size=4><font color=darkPurple><b>077</b></font> - <font color=darkGreen>﻿दो को छोड़ दो गुण सहित आत्मा में वास करो</font></font></a></li>");
document.write("        <li><a href='078.html'><font size=4><font color=darkPurple><b>078</b></font> - <font color=darkBlue>﻿तीन को छोड़ तीन गुण सहित आत्मा में वास करो</font></font></a></li>");
document.write("        <li><a href='079.html'><font size=4><font color=darkPurple><b>079</b></font> - <font color=darkGreen>﻿चार को छोड़ चार गुण सहित आत्मा में वास करो</font></font></a></li>");
document.write("        <li><a href='080.html'><font size=4><font color=darkPurple><b>080</b></font> - <font color=darkBlue>﻿पांच-पांच को छोड़ पांच-पांच गुण सहित आत्मा में वास करो</font></font></a></li>");
document.write("        <li><a href='081.html'><font size=4><font color=darkPurple><b>081</b></font> - <font color=darkGreen>﻿आत्मरमण में तप-त्यागादि सब कुछ है</font></font></a></li>");
document.write("        <li><a href='082.html'><font size=4><font color=darkPurple><b>082</b></font> - <font color=darkBlue>﻿पर-भावों का त्याग ही संन्यास है</font></font></a></li>");
document.write("        <li><a href='083.html'><font size=4><font color=darkPurple><b>083</b></font> - <font color=darkGreen>﻿रत्नत्रय धर्म ही उत्तम तीर्थ है</font></font></a></li>");
document.write("        <li><a href='084.html'><font size=4><font color=darkPurple><b>084</b></font> - <font color=darkBlue>﻿रत्नत्रय का स्वरूप</font></font></a></li>");
document.write("        <li><a href='085.html'><font size=4><font color=darkPurple><b>085</b></font> - <font color=darkGreen>﻿आत्मानुभव में सब गुण हैं</font></font></a></li>");
document.write("        <li><a href='086.html'><font size=4><font color=darkPurple><b>086</b></font> - <font color=darkBlue>﻿एकाकी होकर एक आत्मा का ही मनन कर</font></font></a></li>");
document.write("        <li><a href='087.html'><font size=4><font color=darkPurple><b>087</b></font> - <font color=darkGreen>﻿सहज स्वरूप में रमण कर</font></font></a></li>");
document.write("        <li><a href='088.html'><font size=4><font color=darkPurple><b>088</b></font> - <font color=darkBlue>﻿सम्यग्दृष्टि सुगति पाता है</font></font></a></li>");
document.write("        <li><a href='089.html'><font size=4><font color=darkPurple><b>089</b></font> - <font color=darkGreen>﻿सर्व व्यवहार छोड़कर आत्मा में रमण ही सम्यग्दर्शन</font></font></a></li>");
document.write("        <li><a href='090.html'><font size=4><font color=darkPurple><b>090</b></font> - <font color=darkBlue>﻿सम्यक्त्वी ही पंडित व प्रधान है</font></font></a></li>");
document.write("        <li><a href='091.html'><font size=4><font color=darkPurple><b>091</b></font> - <font color=darkGreen>﻿आत्मा में स्थिरता संवर व निर्जरा का कारण है</font></font></a></li>");
document.write("        <li><a href='092.html'><font size=4><font color=darkPurple><b>092</b></font> - <font color=darkBlue>﻿अलिप्त भाव ही कर्मों से अलिप्तता का कारण</font></font></a></li>");
document.write("        <li><a href='093.html'><font size=4><font color=darkPurple><b>093</b></font> - <font color=darkGreen>﻿सम-सुख भोगी निर्वाण का पात्र है</font></font></a></li>");
document.write("        <li><a href='094.html'><font size=4><font color=darkPurple><b>094</b></font> - <font color=darkBlue>﻿आत्मा को पुरुषाकार पवित्र गुणों की खान जानो</font></font></a></li>");
document.write("        <li><a href='095.html'><font size=4><font color=darkPurple><b>095</b></font> - <font color=darkGreen>﻿जो आत्मा को जानता है वह सब शास्त्रों का ज्ञाता होता है</font></font></a></li>");
document.write("        <li><a href='096.html'><font size=4><font color=darkPurple><b>096</b></font> - <font color=darkBlue>﻿भेद-विज्ञान ही कार्यकारी है</font></font></a></li>");
document.write("        <li><a href='097.html'><font size=4><font color=darkPurple><b>097</b></font> - <font color=darkGreen>﻿परम समाधि शिव-सुख का कारण है</font></font></a></li>");
document.write("        <li><a href='098.html'><font size=4><font color=darkPurple><b>098</b></font> - <font color=darkBlue>﻿आत्म-ध्यान चार प्रकार का</font></font></a></li>");
document.write("        <li><a href='099-100.html'><font size=4><font color=darkPurple><b>099-100</b></font> - <font color=darkGreen>﻿सामायिक चारित्र कथन</font></font></a></li>");
document.write("        <li><a href='101.html'><font size=4><font color=darkPurple><b>101</b></font> - <font color=darkBlue>﻿छेदोपस्थापना चारित्र कथन</font></font></a></li>");
document.write("        <li><a href='102.html'><font size=4><font color=darkPurple><b>102</b></font> - <font color=darkGreen>﻿परिहार-विशुद्धि चारित्र कथन</font></font></a></li>");
document.write("        <li><a href='103.html'><font size=4><font color=darkPurple><b>103</b></font> - <font color=darkBlue>﻿यथाख्यात चारित्र कथन</font></font></a></li>");
document.write("        <li><a href='104-105.html'><font size=4><font color=darkPurple><b>104-105</b></font> - <font color=darkGreen>﻿शुद्धात्मा के कई नाम</font></font></a></li>");
document.write("        <li><a href='106.html'><font size=4><font color=darkPurple><b>106</b></font> - <font color=darkBlue>﻿परमात्मा अपनी ही देह में स्थित है</font></font></a></li>");
document.write("        <li><a href='107.html'><font size=4><font color=darkPurple><b>107</b></font> - <font color=darkGreen>﻿आत्म-दर्शन ही सिद्ध होने का उपाय</font></font></a></li>");
document.write("        <li><a href='108.html'><font size=4><font color=darkPurple><b>108</b></font> - <font color=darkBlue>﻿ग्रंथकर्त्ता की अंतिम भावना</font></font></a></li>");
document.write("</ul></div>");
