document.write("<div id=पं-जचंदजी-छाबडा class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='001.html'><font size=4><br><font size=5 color=black><b>﻿दर्शन-पाहुड </b></font><br><br><font color=darkPurple><b>001</b></font> - <font color=darkBlue>﻿मंगलाचरण</font></font></a></li>");
document.write("        <li><a href='002.html'><font size=4><font color=darkPurple><b>002</b></font> - <font color=darkGreen>﻿दर्शन-रहित अवन्दनीय</font></font></a></li>");
document.write("        <li><a href='003.html'><font size=4><font color=darkPurple><b>003</b></font> - <font color=darkBlue>﻿दर्शन रहित चारित्र से निर्वाण नहीं</font></font></a></li>");
document.write("        <li><a href='004.html'><font size=4><font color=darkPurple><b>004</b></font> - <font color=darkGreen>﻿ज्ञान से भी दर्शन को अधिकता</font></font></a></li>");
document.write("        <li><a href='005.html'><font size=4><font color=darkPurple><b>005</b></font> - <font color=darkBlue>﻿सम्यक्त्वरहित तप से भी स्वरूप-लाभ नहीं</font></font></a></li>");
document.write("        <li><a href='006.html'><font size=4><font color=darkPurple><b>006</b></font> - <font color=darkGreen>﻿सम्यक्त्व सहित सभी प्रवृत्ति सफल है</font></font></a></li>");
document.write("        <li><a href='007.html'><font size=4><font color=darkPurple><b>007</b></font> - <font color=darkBlue>﻿सम्यक्त्व आत्मा को कर्मरज नहीं लगने देता</font></font></a></li>");
document.write("        <li><a href='008.html'><font size=4><font color=darkPurple><b>008</b></font> - <font color=darkGreen>﻿दर्शनभ्रष्ट भ्रष्ट हैं</font></font></a></li>");
document.write("        <li><a href='009.html'><font size=4><font color=darkPurple><b>009</b></font> - <font color=darkBlue>﻿दर्शन-भ्रष्ट द्वारा धर्मात्मा पुरुषों को दोष लगाना</font></font></a></li>");
document.write("        <li><a href='010.html'><font size=4><font color=darkPurple><b>010</b></font> - <font color=darkGreen>﻿दर्शन-भ्रष्ट को फल-प्राप्ति नहीं</font></font></a></li>");
document.write("        <li><a href='011.html'><font size=4><font color=darkPurple><b>011</b></font> - <font color=darkBlue>﻿जिनदर्शन ही मूल मोक्षमार्ग है</font></font></a></li>");
document.write("        <li><a href='012.html'><font size=4><font color=darkPurple><b>012</b></font> - <font color=darkGreen>﻿दर्शन-भ्रष्ट दर्शन-धारकों की करें</font></font></a></li>");
document.write("        <li><a href='013.html'><font size=4><font color=darkPurple><b>013</b></font> - <font color=darkBlue>﻿दर्शन-भ्रष्ट की विनय नहीं</font></font></a></li>");
document.write("        <li><a href='014.html'><font size=4><font color=darkPurple><b>014</b></font> - <font color=darkGreen>﻿सम्यक्त्व के पात्र</font></font></a></li>");
document.write("        <li><a href='015.html'><font size=4><font color=darkPurple><b>015</b></font> - <font color=darkBlue>﻿सम्यग्दर्शन से ही कल्याण-अकल्याण का निश्चय</font></font></a></li>");
document.write("        <li><a href='016.html'><font size=4><font color=darkPurple><b>016</b></font> - <font color=darkGreen>﻿कल्याण-अकल्याण को जानने का प्रयोजन</font></font></a></li>");
document.write("        <li><a href='017.html'><font size=4><font color=darkPurple><b>017</b></font> - <font color=darkBlue>﻿सम्यक्त्व जिनवचन से प्राप्त होता है</font></font></a></li>");
document.write("        <li><a href='018.html'><font size=4><font color=darkPurple><b>018</b></font> - <font color=darkGreen>﻿जिनवचन में दर्शन का लिंग</font></font></a></li>");
document.write("        <li><a href='019.html'><font size=4><font color=darkPurple><b>019</b></font> - <font color=darkBlue>﻿बाह्यलिंग सहित अन्तरंग श्रद्धान ही सम्यग्दृष्टि</font></font></a></li>");
document.write("        <li><a href='020.html'><font size=4><font color=darkPurple><b>020</b></font> - <font color=darkGreen>﻿सम्यक्त्व के दो प्रकार</font></font></a></li>");
document.write("        <li><a href='021.html'><font size=4><font color=darkPurple><b>021</b></font> - <font color=darkBlue>﻿सम्यग्दर्शन ही सब गुणों में सार</font></font></a></li>");
document.write("        <li><a href='022.html'><font size=4><font color=darkPurple><b>022</b></font> - <font color=darkGreen>﻿श्रद्धानी के ही सम्यक्त्व</font></font></a></li>");
document.write("        <li><a href='023.html'><font size=4><font color=darkPurple><b>023</b></font> - <font color=darkBlue>﻿दर्शन-ज्ञान-चारित्र में स्थित की वंदना</font></font></a></li>");
document.write("        <li><a href='024.html'><font size=4><font color=darkPurple><b>024</b></font> - <font color=darkGreen>﻿यथाजातरूप को मत्सरभाव से वन्दना नहीं करते, वे मिथ्यादृष्टि</font></font></a></li>");
document.write("        <li><a href='025.html'><font size=4><font color=darkPurple><b>025</b></font> - <font color=darkBlue>﻿इसी को दृढ़ करते हैं</font></font></a></li>");
document.write("        <li><a href='026.html'><font size=4><font color=darkPurple><b>026</b></font> - <font color=darkGreen>﻿असंयमी वंदने योग्य नहीं</font></font></a></li>");
document.write("        <li><a href='027.html'><font size=4><font color=darkPurple><b>027</b></font> - <font color=darkBlue>﻿इस ही अर्थ को दृढ़ करते हैं </font></font></a></li>");
document.write("        <li><a href='028.html'><font size=4><font color=darkPurple><b>028</b></font> - <font color=darkGreen>﻿तप आदि से संयुक्त को नमस्कार</font></font></a></li>");
document.write("        <li><a href='029.html'><font size=4><font color=darkPurple><b>029</b></font> - <font color=darkBlue>﻿समवसरण सहित तीर्थंकर वंदने योग्य हैं या नहीं</font></font></a></li>");
document.write("        <li><a href='030.html'><font size=4><font color=darkPurple><b>030</b></font> - <font color=darkGreen>﻿मोक्ष किससे होता है?</font></font></a></li>");
document.write("        <li><a href='031.html'><font size=4><font color=darkPurple><b>031</b></font> - <font color=darkBlue>﻿ज्ञान आदि के उत्तरोत्तर सारपना</font></font></a></li>");
document.write("        <li><a href='032.html'><font size=4><font color=darkPurple><b>032</b></font> - <font color=darkGreen>﻿इसी अर्थ को दृढ़ करते हैं</font></font></a></li>");
document.write("        <li><a href='033.html'><font size=4><font color=darkPurple><b>033</b></font> - <font color=darkBlue>﻿सम्यग्दर्शनरूप रत्न देवों द्वारा पूज्य</font></font></a></li>");
document.write("        <li><a href='034.html'><font size=4><font color=darkPurple><b>034</b></font> - <font color=darkGreen>﻿सम्यक्त्व का माहात्म्य</font></font></a></li>");
document.write("        <li><a href='035.html'><font size=4><font color=darkPurple><b>035</b></font> - <font color=darkBlue>﻿स्थावर प्रतिमा </font></font></a></li>");
document.write("        <li><a href='036.html'><font size=4><font color=darkPurple><b>036</b></font> - <font color=darkGreen>﻿जंगम प्रतिमा</font></font></a></li>");
document.write("        <li><a href='037.html'><font size=4><br><font size=5 color=black><b>﻿सूत्र-पाहुड </b></font><br><br><font color=darkPurple><b>037</b></font> - <font color=darkBlue>﻿सूत्र का स्वरूप</font></font></a></li>");
document.write("        <li><a href='038.html'><font size=4><font color=darkPurple><b>038</b></font> - <font color=darkGreen>﻿सूत्रानुसार प्रवर्तनेवाला भव्य</font></font></a></li>");
document.write("        <li><a href='039.html'><font size=4><font color=darkPurple><b>039</b></font> - <font color=darkBlue>﻿सूत्र-प्रवीण के संसार नाश</font></font></a></li>");
document.write("        <li><a href='040.html'><font size=4><font color=darkPurple><b>040</b></font> - <font color=darkGreen>﻿सूई का दृष्टान्त</font></font></a></li>");
document.write("        <li><a href='041.html'><font size=4><font color=darkPurple><b>041</b></font> - <font color=darkBlue>﻿सूत्र का जानकार सम्यक्त्वी</font></font></a></li>");
document.write("        <li><a href='042.html'><font size=4><font color=darkPurple><b>042</b></font> - <font color=darkGreen>﻿दो प्रकार से सूत्र-निरूपण </font></font></a></li>");
document.write("        <li><a href='043.html'><font size=4><font color=darkPurple><b>043</b></font> - <font color=darkBlue>﻿सूत्र और पद से भ्रष्ट मिथ्यादृष्टि</font></font></a></li>");
document.write("        <li><a href='044.html'><font size=4><font color=darkPurple><b>044</b></font> - <font color=darkGreen>﻿जिनूसत्र से भ्रष्ट हरि-हरादिक भी हो तो भी मोक्ष नहीं</font></font></a></li>");
document.write("        <li><a href='045.html'><font size=4><font color=darkPurple><b>045</b></font> - <font color=darkBlue>﻿जिनसूत्र से च्युत, स्वच्छंद प्रवर्तते हैं, वे मिथ्यादृष्टि</font></font></a></li>");
document.write("        <li><a href='046.html'><font size=4><font color=darkPurple><b>046</b></font> - <font color=darkGreen>﻿जिनसूत्र में मोक्षमार्ग ऐसा</font></font></a></li>");
document.write("        <li><a href='047.html'><font size=4><font color=darkPurple><b>047</b></font> - <font color=darkBlue>﻿मोक्षमार्ग में प्रवृत्ति</font></font></a></li>");
document.write("        <li><a href='048.html'><font size=4><font color=darkPurple><b>048</b></font> - <font color=darkGreen>﻿उनकी प्रवृत्ति का विशेष</font></font></a></li>");
document.write("        <li><a href='049.html'><font size=4><font color=darkPurple><b>049</b></font> - <font color=darkBlue>﻿शेष सम्यग्दर्शन ज्ञान से युक्त वस्त्रधारी इच्छाकार योग्य</font></font></a></li>");
document.write("        <li><a href='050.html'><font size=4><font color=darkPurple><b>050</b></font> - <font color=darkGreen>﻿इच्छाकार योग्य श्रावक का स्वरूप</font></font></a></li>");
document.write("        <li><a href='051.html'><font size=4><font color=darkPurple><b>051</b></font> - <font color=darkBlue>﻿इच्छाकार के अर्थ को नहीं जान, अन्य धर्म का आचरण से सिद्धि नहीं</font></font></a></li>");
document.write("        <li><a href='052.html'><font size=4><font color=darkPurple><b>052</b></font> - <font color=darkGreen>﻿इस ही अर्थ को दृढ़ करके उपदेश</font></font></a></li>");
document.write("        <li><a href='053.html'><font size=4><font color=darkPurple><b>053</b></font> - <font color=darkBlue>﻿जिनसूत्र के जानकार मुनि का स्वरूप</font></font></a></li>");
document.write("        <li><a href='054.html'><font size=4><font color=darkPurple><b>054</b></font> - <font color=darkGreen>﻿अल्प परिग्रह ग्रहण में दोष</font></font></a></li>");
document.write("        <li><a href='055.html'><font size=4><font color=darkPurple><b>055</b></font> - <font color=darkBlue>﻿इस ही का समर्थन करते हैं</font></font></a></li>");
document.write("        <li><a href='056.html'><font size=4><font color=darkPurple><b>056</b></font> - <font color=darkGreen>﻿जिनवचन में ऐसा मुनि वन्दने योग्य</font></font></a></li>");
document.write("        <li><a href='057.html'><font size=4><font color=darkPurple><b>057</b></font> - <font color=darkBlue>﻿दूसरा भेष उत्कृष्ट श्रावक का</font></font></a></li>");
document.write("        <li><a href='058.html'><font size=4><font color=darkPurple><b>058</b></font> - <font color=darkGreen>﻿तीसरा लिंग स्त्री का</font></font></a></li>");
document.write("        <li><a href='059.html'><font size=4><font color=darkPurple><b>059</b></font> - <font color=darkBlue>﻿वस्त्र धारक के मोक्ष नहीं</font></font></a></li>");
document.write("        <li><a href='060.html'><font size=4><font color=darkPurple><b>060</b></font> - <font color=darkGreen>﻿स्त्रियों को दीक्षा नहीं है इसका कारण</font></font></a></li>");
document.write("        <li><a href='061.html'><font size=4><font color=darkPurple><b>061</b></font> - <font color=darkBlue>﻿दर्शन से शुद्ध स्त्री पापरहित</font></font></a></li>");
document.write("        <li><a href='062.html'><font size=4><font color=darkPurple><b>062</b></font> - <font color=darkGreen>﻿स्त्रियों के निशंक ध्यान नहीं</font></font></a></li>");
document.write("        <li><a href='063.html'><font size=4><font color=darkPurple><b>063</b></font> - <font color=darkBlue>﻿सूत्रपाहुड का उपसंहार</font></font></a></li>");
document.write("        <li><a href='064-065.html'><font size=4><br><font size=5 color=black><b>﻿चारित्र-पाहुड </b></font><br><br><font color=darkPurple><b>064-065</b></font> - <font color=darkGreen>﻿नमस्कृति तथा चारित्र-पाहुड लिखने की प्रतिज्ञा </font></font></a></li>");
document.write("        <li><a href='066.html'><font size=4><font color=darkPurple><b>066</b></font> - <font color=darkBlue>﻿सम्यग्दर्शनादि तीन भावों का स्वरूप</font></font></a></li>");
document.write("        <li><a href='067.html'><font size=4><font color=darkPurple><b>067</b></font> - <font color=darkGreen>﻿जो तीन भाव जीव के हैं उनकी शुद्धता के लिए चारित्र दो प्रकार का कहा है</font></font></a></li>");
document.write("        <li><a href='068.html'><font size=4><font color=darkPurple><b>068</b></font> - <font color=darkBlue>﻿दो प्रकार का चारित्र</font></font></a></li>");
document.write("        <li><a href='069.html'><font size=4><font color=darkPurple><b>069</b></font> - <font color=darkGreen>﻿सम्यक्त्वचरण चारित्र के मल दोषों का परिहार</font></font></a></li>");
document.write("        <li><a href='070.html'><font size=4><font color=darkPurple><b>070</b></font> - <font color=darkBlue>﻿ सम्यक्त्व के आठ अंग</font></font></a></li>");
document.write("        <li><a href='071.html'><font size=4><font color=darkPurple><b>071</b></font> - <font color=darkGreen>﻿इसप्रकार पहिला सम्यक्त्वाचरण चारित्र कहा</font></font></a></li>");
document.write("        <li><a href='072.html'><font size=4><font color=darkPurple><b>072</b></font> - <font color=darkBlue>﻿सम्यक्त्वाचरण चारित्र को अंगीकार करके संयमचरण चारित्र को अंगीकार करने की प्रेरणा</font></font></a></li>");
document.write("        <li><a href='073.html'><font size=4><font color=darkPurple><b>073</b></font> - <font color=darkGreen>﻿सम्यक्त्वाचरण से भ्रष्ट और वे संयमाचरण सहित को मोक्ष नहीं</font></font></a></li>");
document.write("        <li><a href='074-075.html'><font size=4><font color=darkPurple><b>074-075</b></font> - <font color=darkBlue>﻿सम्यक्त्वाचरण चारित्र के चिह्न</font></font></a></li>");
document.write("        <li><a href='076.html'><font size=4><font color=darkPurple><b>076</b></font> - <font color=darkGreen>﻿सम्यक्त्व कैसे छूटता है?</font></font></a></li>");
document.write("        <li><a href='077.html'><font size=4><font color=darkPurple><b>077</b></font> - <font color=darkBlue>﻿सम्यक्त्व से च्युत कब नहीं होता है?</font></font></a></li>");
document.write("        <li><a href='078.html'><font size=4><font color=darkPurple><b>078</b></font> - <font color=darkGreen>﻿अज्ञान मिथ्यात्व कुचारित्र के त्याग का उपदेश</font></font></a></li>");
document.write("        <li><a href='079.html'><font size=4><font color=darkPurple><b>079</b></font> - <font color=darkBlue>﻿फिर उपदेश करते हैं</font></font></a></li>");
document.write("        <li><a href='080.html'><font size=4><font color=darkPurple><b>080</b></font> - <font color=darkGreen>﻿यह जीव अज्ञान और मिथ्यात्व के दोष से मिथ्यामार्ग में प्रवर्तन करता है</font></font></a></li>");
document.write("        <li><a href='081.html'><font size=4><font color=darkPurple><b>081</b></font> - <font color=darkBlue>﻿सम्यग्दर्शन-ज्ञान-श्रद्धान से चारित्र के दोष दूर होते हैं</font></font></a></li>");
document.write("        <li><a href='082.html'><font size=4><font color=darkPurple><b>082</b></font> - <font color=darkGreen>﻿सम्यग्दर्शन-ज्ञान-चारित्र से शीघ्र मोक्ष</font></font></a></li>");
document.write("        <li><a href='083.html'><font size=4><font color=darkPurple><b>083</b></font> - <font color=darkBlue>﻿सम्यक्त्वाचरण चारित्र के कथन का संकोच करते हैं</font></font></a></li>");
document.write("        <li><a href='084.html'><font size=4><font color=darkPurple><b>084</b></font> - <font color=darkGreen>﻿संयमाचरण चारित्र</font></font></a></li>");
document.write("        <li><a href='085.html'><font size=4><font color=darkPurple><b>085</b></font> - <font color=darkBlue>﻿सागार संयमाचरण</font></font></a></li>");
document.write("        <li><a href='086.html'><font size=4><font color=darkPurple><b>086</b></font> - <font color=darkGreen>﻿इन स्थानों में संयम का आचरण किसप्रकार से है?</font></font></a></li>");
document.write("        <li><a href='087.html'><font size=4><font color=darkPurple><b>087</b></font> - <font color=darkBlue>﻿पाँच अणुव्रतों का स्वरूप</font></font></a></li>");
document.write("        <li><a href='088.html'><font size=4><font color=darkPurple><b>088</b></font> - <font color=darkGreen>﻿तीन गुणव्रत</font></font></a></li>");
document.write("        <li><a href='089.html'><font size=4><font color=darkPurple><b>089</b></font> - <font color=darkBlue>﻿चार शिक्षाव्रत</font></font></a></li>");
document.write("        <li><a href='090.html'><font size=4><font color=darkPurple><b>090</b></font> - <font color=darkGreen>﻿यतिधर्म </font></font></a></li>");
document.write("        <li><a href='091.html'><font size=4><font color=darkPurple><b>091</b></font> - <font color=darkBlue>﻿यतिधर्म की सामग्री</font></font></a></li>");
document.write("        <li><a href='092.html'><font size=4><font color=darkPurple><b>092</b></font> - <font color=darkGreen>﻿पाँच इन्द्रियों के संवरण का स्वरूप</font></font></a></li>");
document.write("        <li><a href='093.html'><font size=4>093</font></a></li>");
document.write("        <li><a href='094.html'><font size=4><font color=darkPurple><b>094</b></font> - <font color=darkGreen>﻿इनको महाव्रत क्यों कहते हैं?</font></font></a></li>");
document.write("        <li><a href='095.html'><font size=4><font color=darkPurple><b>095</b></font> - <font color=darkBlue>﻿अहिंसाव्रत की पाँच भावना</font></font></a></li>");
document.write("        <li><a href='096.html'><font size=4><font color=darkPurple><b>096</b></font> - <font color=darkGreen>﻿सत्य महाव्रत की भावना</font></font></a></li>");
document.write("        <li><a href='097.html'><font size=4><font color=darkPurple><b>097</b></font> - <font color=darkBlue>﻿अचौर्य महाव्रत की भावना </font></font></a></li>");
document.write("        <li><a href='098.html'><font size=4><font color=darkPurple><b>098</b></font> - <font color=darkGreen>﻿ब्रह्मचर्य महाव्रत की भावना</font></font></a></li>");
document.write("        <li><a href='099.html'><font size=4><font color=darkPurple><b>099</b></font> - <font color=darkBlue>﻿पाँच अपरिग्रह महाव्रत की भावना</font></font></a></li>");
document.write("        <li><a href='100.html'><font size=4><font color=darkPurple><b>100</b></font> - <font color=darkGreen>﻿पाँच समिति</font></font></a></li>");
document.write("        <li><a href='101.html'><font size=4><font color=darkPurple><b>101</b></font> - <font color=darkBlue>﻿ज्ञान का स्वरूप</font></font></a></li>");
document.write("        <li><a href='102.html'><font size=4><font color=darkPurple><b>102</b></font> - <font color=darkGreen>﻿जो इसप्रकार ज्ञान से ऐसे जानता है, वह सम्यग्ज्ञानी</font></font></a></li>");
document.write("        <li><a href='103.html'><font size=4><font color=darkPurple><b>103</b></font> - <font color=darkBlue>﻿मोक्षमार्ग को जानकर श्रद्धा सहित इसमें प्रवृत्ति करता है, वह शीघ्र ही मोक्ष को प्राप्त करता है</font></font></a></li>");
document.write("        <li><a href='104.html'><font size=4><font color=darkPurple><b>104</b></font> - <font color=darkGreen>﻿निश्चयचारित्ररूप ज्ञान का स्वरूप कि महिमा</font></font></a></li>");
document.write("        <li><a href='105.html'><font size=4><font color=darkPurple><b>105</b></font> - <font color=darkBlue>﻿गुण दोष को जानने के लिए ज्ञान को भले प्रकार से जानना</font></font></a></li>");
document.write("        <li><a href='106.html'><font size=4><font color=darkPurple><b>106</b></font> - <font color=darkGreen>﻿जो सम्यग्ज्ञान सहित चारित्र धारण करता है, वह थोड़े ही काल में अनुपम सुख को पाता है</font></font></a></li>");
document.write("        <li><a href='107.html'><font size=4><font color=darkPurple><b>107</b></font> - <font color=darkBlue>﻿चारित्र के कथन का संकोच</font></font></a></li>");
document.write("        <li><a href='108.html'><font size=4><font color=darkPurple><b>108</b></font> - <font color=darkGreen>﻿चारित्रपाहुड़ को भाने का उपदेश और इसका फल </font></font></a></li>");
document.write("        <li><a href='109-110.html'><font size=4><br><font size=5 color=black><b>﻿बोध-पाहुड </b></font><br><br><font color=darkPurple><b>109-110</b></font> - <font color=darkBlue>﻿ग्रन्थ करने की मंगलपूर्वक प्रतिज्ञा </font></font></a></li>");
document.write("        <li><a href='111-112.html'><font size=4><font color=darkPurple><b>111-112</b></font> - <font color=darkGreen>﻿'बोधपाहुड' में ग्यारह स्थलों के नाम </font></font></a></li>");
document.write("        <li><a href='113.html'><font size=4><font color=darkPurple><b>113</b></font> - <font color=darkBlue>﻿आयतन का निरूपण </font></font></a></li>");
document.write("        <li><a href='114.html'><font size=4>114</font></a></li>");
document.write("        <li><a href='115.html'><font size=4>115</font></a></li>");
document.write("        <li><a href='116.html'><font size=4><font color=darkPurple><b>116</b></font> - <font color=darkGreen>﻿चैत्यगृह का निरूपण</font></font></a></li>");
document.write("        <li><a href='117.html'><font size=4>117</font></a></li>");
document.write("        <li><a href='118.html'><font size=4><font color=darkPurple><b>118</b></font> - <font color=darkGreen>﻿जिनप्रतिमा का निरूपण</font></font></a></li>");
document.write("        <li><a href='119.html'><font size=4>119</font></a></li>");
document.write("        <li><a href='120-121.html'><font size=4>120-121</font></a></li>");
document.write("        <li><a href='122.html'><font size=4><font color=darkPurple><b>122</b></font> - <font color=darkBlue>﻿दर्शन का स्वरूप </font></font></a></li>");
document.write("        <li><a href='123.html'><font size=4>123</font></a></li>");
document.write("        <li><a href='124.html'><font size=4><font color=darkPurple><b>124</b></font> - <font color=darkBlue>﻿जिनबिंब का निरूपण</font></font></a></li>");
document.write("        <li><a href='125.html'><font size=4>125</font></a></li>");
document.write("        <li><a href='126.html'><font size=4>126</font></a></li>");
document.write("        <li><a href='127.html'><font size=4><font color=darkPurple><b>127</b></font> - <font color=darkGreen>﻿जिनमुद्रा का स्वरूप </font></font></a></li>");
document.write("        <li><a href='128.html'><font size=4><font color=darkPurple><b>128</b></font> - <font color=darkBlue>﻿ज्ञान का निरूपण</font></font></a></li>");
document.write("        <li><a href='129.html'><font size=4><font color=darkPurple><b>129</b></font> - <font color=darkGreen>﻿इसी को दृष्टान्त द्वारा दृढ़ करते हैं</font></font></a></li>");
document.write("        <li><a href='130.html'><font size=4><font color=darkPurple><b>130</b></font> - <font color=darkBlue>﻿इसप्रकार ज्ञान-विनय-संयुक्त पुरुष होवे वही मोक्ष को प्राप्त करता है</font></font></a></li>");
document.write("        <li><a href='131.html'><font size=4>131</font></a></li>");
document.write("        <li><a href='132.html'><font size=4><font color=darkPurple><b>132</b></font> - <font color=darkBlue>﻿देव का स्वरूप</font></font></a></li>");
document.write("        <li><a href='133.html'><font size=4><font color=darkPurple><b>133</b></font> - <font color=darkGreen>﻿धर्मादिक का स्वरूप</font></font></a></li>");
document.write("        <li><a href='134.html'><font size=4><font color=darkPurple><b>134</b></font> - <font color=darkBlue>﻿तीर्थ का स्वरूप</font></font></a></li>");
document.write("        <li><a href='135.html'><font size=4>135</font></a></li>");
document.write("        <li><a href='136.html'><font size=4><font color=darkPurple><b>136</b></font> - <font color=darkBlue>﻿अरहंत का स्वरूप </font></font></a></li>");
document.write("        <li><a href='137.html'><font size=4><font color=darkPurple><b>137</b></font> - <font color=darkGreen>﻿नाम को प्रधान करके कहते हैं</font></font></a></li>");
document.write("        <li><a href='138.html'><font size=4>138</font></a></li>");
document.write("        <li><a href='139.html'><font size=4><font color=darkPurple><b>139</b></font> - <font color=darkGreen>﻿स्थापना द्वारा अरहंत का वर्णन</font></font></a></li>");
document.write("        <li><a href='140.html'><font size=4><font color=darkPurple><b>140</b></font> - <font color=darkBlue>﻿गुणस्थान में अरिहंत की स्थापना</font></font></a></li>");
document.write("        <li><a href='141.html'><font size=4><font color=darkPurple><b>141</b></font> - <font color=darkGreen>﻿मार्गणा में अरिहंत की स्थापना</font></font></a></li>");
document.write("        <li><a href='142.html'><font size=4><font color=darkPurple><b>142</b></font> - <font color=darkBlue>﻿पर्याप्ति में अरिहंत की स्थापना</font></font></a></li>");
document.write("        <li><a href='143.html'><font size=4><font color=darkPurple><b>143</b></font> - <font color=darkGreen>﻿प्राण में अरिहंत की स्थापना </font></font></a></li>");
document.write("        <li><a href='144.html'><font size=4><font color=darkPurple><b>144</b></font> - <font color=darkBlue>﻿जीवस्थान में अरिहंत की स्थापना</font></font></a></li>");
document.write("        <li><a href='145-148.html'><font size=4><font color=darkPurple><b>145-148</b></font> - <font color=darkGreen>﻿द्रव्य की प्रधानता से अरहंत का निरूपण</font></font></a></li>");
document.write("        <li><a href='146-147.html'><font size=4>146-147</font></a></li>");
document.write("        <li><a href='148-149-150.html'><font size=4><font color=darkPurple><b>148-149-150</b></font> - <font color=darkGreen>﻿प्रव्रज्या (दीक्षा) का निरूपण</font></font></a></li>");
document.write("        <li><a href='151.html'><font size=4><font color=darkPurple><b>151</b></font> - <font color=darkBlue>﻿प्रव्रज्या का स्वरूप</font></font></a></li>");
document.write("        <li><a href='152.html'><font size=4>152</font></a></li>");
document.write("        <li><a href='153.html'><font size=4>153</font></a></li>");
document.write("        <li><a href='154.html'><font size=4>154</font></a></li>");
document.write("        <li><a href='155.html'><font size=4>155</font></a></li>");
document.write("        <li><a href='156.html'><font size=4>156</font></a></li>");
document.write("        <li><a href='157.html'><font size=4><font color=darkPurple><b>157</b></font> - <font color=darkBlue>﻿दीक्षा का बाह्यस्वरूप</font></font></a></li>");
document.write("        <li><a href='158.html'><font size=4>158</font></a></li>");
document.write("        <li><a href='159.html'><font size=4>159</font></a></li>");
document.write("        <li><a href='160.html'><font size=4>160</font></a></li>");
document.write("        <li><a href='161.html'><font size=4>161</font></a></li>");
document.write("        <li><a href='162.html'><font size=4>162</font></a></li>");
document.write("        <li><a href='163.html'><font size=4><font color=darkPurple><b>163</b></font> - <font color=darkBlue>﻿अन्य विशेष</font></font></a></li>");
document.write("        <li><a href='164.html'><font size=4>164</font></a></li>");
document.write("        <li><a href='165.html'><font size=4>165</font></a></li>");
document.write("        <li><a href='166.html'><font size=4><font color=darkPurple><b>166</b></font> - <font color=darkGreen>﻿बोधपाहुड का संकोच</font></font></a></li>");
document.write("        <li><a href='167.html'><font size=4><font color=darkPurple><b>167</b></font> - <font color=darkBlue>﻿बोधपाहुड पूर्वाचार्यों के अनुसार कहा है</font></font></a></li>");
document.write("        <li><a href='168.html'><font size=4><font color=darkPurple><b>168</b></font> - <font color=darkGreen>﻿भद्रबाहु स्वामी की स्तुतिरूप वचन</font></font></a></li>");
document.write("        <li><a href='169.html'><font size=4><br><font size=5 color=black><b>﻿भाव-पाहुड </b></font><br><br><font color=darkPurple><b>169</b></font> - <font color=darkBlue>﻿मंगलाचरण कर ग्रन्थ करने की प्रतिज्ञा</font></font></a></li>");
document.write("        <li><a href='170.html'><font size=4><font color=darkPurple><b>170</b></font> - <font color=darkGreen>﻿दो प्रकार के लिंग में भावलिंग परमार्थ</font></font></a></li>");
document.write("        <li><a href='171.html'><font size=4><font color=darkPurple><b>171</b></font> - <font color=darkBlue>﻿बाह्यद्रव्य के त्याग की प्रेरणा </font></font></a></li>");
document.write("        <li><a href='172.html'><font size=4><font color=darkPurple><b>172</b></font> - <font color=darkGreen>﻿करोडों भवों के भाव रहित तप द्वारा भी सिद्धि नहीं  </font></font></a></li>");
document.write("        <li><a href='173.html'><font size=4><font color=darkPurple><b>173</b></font> - <font color=darkBlue>﻿इस ही अर्थ को दृढ़ करते हैं </font></font></a></li>");
document.write("        <li><a href='174.html'><font size=4><font color=darkPurple><b>174</b></font> - <font color=darkGreen>﻿भाव को परमार्थ जानकर इसी को अंगीकार करो </font></font></a></li>");
document.write("        <li><a href='175.html'><font size=4><font color=darkPurple><b>175</b></font> - <font color=darkBlue>﻿भाव-रहित द्रव्य-लिंग बहुत बार धारण किये, परन्तु सिद्धि नहीं हुई </font></font></a></li>");
document.write("        <li><a href='176.html'><font size=4><font color=darkPurple><b>176</b></font> - <font color=darkGreen>﻿भाव-रहितपने के कारण चारों गतियों में दुःख प्राप्ति</font></font></a></li>");
document.write("        <li><a href='177.html'><font size=4><font color=darkPurple><b>177</b></font> - <font color=darkBlue>﻿नरकगति के दुःख</font></font></a></li>");
document.write("        <li><a href='178.html'><font size=4><font color=darkPurple><b>178</b></font> - <font color=darkGreen>﻿मनुष्यगति के दुःख</font></font></a></li>");
document.write("        <li><a href='180.html'><font size=4><font color=darkPurple><b>180</b></font> - <font color=darkBlue>﻿देवगति के दुःख</font></font></a></li>");
document.write("        <li><a href='181.html'><font size=4><font color=darkPurple><b>181</b></font> - <font color=darkGreen>﻿अशुभ भावना द्वारा देवों में भी दुःख </font></font></a></li>");
document.write("        <li><a href='182.html'><font size=4><font color=darkPurple><b>182</b></font> - <font color=darkBlue>﻿पार्श्वस्थ भावना से दुःख</font></font></a></li>");
document.write("        <li><a href='184.html'><font size=4><font color=darkPurple><b>184</b></font> - <font color=darkGreen>﻿अशुभ भावना से नीच देव होकर दुःख पाते हैं</font></font></a></li>");
document.write("        <li><a href='185.html'><font size=4><font color=darkPurple><b>185</b></font> - <font color=darkBlue>﻿मनुष्य-तिर्यंच होवे, वहाँ गर्भ के दुःख</font></font></a></li>");
document.write("        <li><a href='186.html'><font size=4><font color=darkPurple><b>186</b></font> - <font color=darkGreen>﻿अनंतों बार गर्भवास के दुःख प्राप्त किये</font></font></a></li>");
document.write("        <li><a href='189.html'><font size=4><font color=darkPurple><b>189</b></font> - <font color=darkBlue>﻿जल-थल आदि स्थानों में सब जगह रहा</font></font></a></li>");
document.write("        <li><a href='191.html'><font size=4><font color=darkPurple><b>191</b></font> - <font color=darkGreen>﻿समस्त जल पीया फिर भी प्यासा रहा </font></font></a></li>");
document.write("        <li><a href='192.html'><font size=4><font color=darkPurple><b>192</b></font> - <font color=darkBlue>﻿अनेक बार शरीर ग्रहण किया</font></font></a></li>");
document.write("        <li><a href='193-195.html'><font size=4><font color=darkPurple><b>193-195</b></font> - <font color=darkGreen>﻿आयुकर्म अनेक प्रकार से क्षीण हो जाता है </font></font></a></li>");
document.write("        <li><a href='196.html'><font size=4><font color=darkPurple><b>196</b></font> - <font color=darkBlue>﻿निगोद के दुःख</font></font></a></li>");
document.write("        <li><a href='197.html'><font size=4><font color=darkPurple><b>197</b></font> - <font color=darkGreen>﻿क्षुद्रभव -- अंतर्मुहूर्त्त के जन्म-मरण</font></font></a></li>");
document.write("        <li><a href='198.html'><font size=4><font color=darkPurple><b>198</b></font> - <font color=darkBlue>﻿इसलिए अब रत्नत्रय धारण कर </font></font></a></li>");
document.write("        <li><a href='199.html'><font size=4><font color=darkPurple><b>199</b></font> - <font color=darkGreen>﻿रत्नत्रय इसप्रकार है</font></font></a></li>");
document.write("        <li><a href='200.html'><font size=4><font color=darkPurple><b>200</b></font> - <font color=darkBlue>﻿सुमरण का उपदेश</font></font></a></li>");
document.write("        <li><a href='201.html'><font size=4><font color=darkPurple><b>201</b></font> - <font color=darkGreen>﻿क्षेत्र-परावर्तन</font></font></a></li>");
document.write("        <li><a href='202.html'><font size=4><font color=darkPurple><b>202</b></font> - <font color=darkBlue>﻿काल-परावर्तन</font></font></a></li>");
document.write("        <li><a href='203.html'><font size=4><font color=darkPurple><b>203</b></font> - <font color=darkGreen>﻿द्रव्य-परावर्तन</font></font></a></li>");
document.write("        <li><a href='204.html'><font size=4><font color=darkPurple><b>204</b></font> - <font color=darkBlue>﻿क्षेत्र परावर्तन</font></font></a></li>");
document.write("        <li><a href='205.html'><font size=4><font color=darkPurple><b>205</b></font> - <font color=darkGreen>﻿शरीर में रोग का वर्णन</font></font></a></li>");
document.write("        <li><a href='206.html'><font size=4><font color=darkPurple><b>206</b></font> - <font color=darkBlue>﻿उन रोगों का दुःख तूने बहुत सहा </font></font></a></li>");
document.write("        <li><a href='207.html'><font size=4><font color=darkPurple><b>207</b></font> - <font color=darkGreen>﻿अपवित्र गर्भवास में भी रहा </font></font></a></li>");
document.write("        <li><a href='208.html'><font size=4><font color=darkPurple><b>208</b></font> - <font color=darkBlue>﻿फिर इसी को कहते हैं</font></font></a></li>");
document.write("        <li><a href='209.html'><font size=4><font color=darkPurple><b>209</b></font> - <font color=darkGreen>﻿बालकपन में भी अज्ञान-जनित दुःख </font></font></a></li>");
document.write("        <li><a href='210.html'><font size=4><font color=darkPurple><b>210</b></font> - <font color=darkBlue>﻿देह के स्वरूप का विचार करो </font></font></a></li>");
document.write("        <li><a href='211.html'><font size=4><font color=darkPurple><b>211</b></font> - <font color=darkGreen>﻿अन्तरंग से छोड़ने का उपदेश</font></font></a></li>");
document.write("        <li><a href='212.html'><font size=4><font color=darkPurple><b>212</b></font> - <font color=darkBlue>﻿भावशुद्धि बिना सिद्धि नहीं -- उदाहरण बाहुबली</font></font></a></li>");
document.write("        <li><a href='213.html'><font size=4><font color=darkPurple><b>213</b></font> - <font color=darkGreen>﻿मधुपिंगल मुनि का उदाहरण करते हैं</font></font></a></li>");
document.write("        <li><a href='214.html'><font size=4><font color=darkPurple><b>214</b></font> - <font color=darkBlue>﻿भावशुद्धि बिना सिद्धि नहीं -- वशिष्ठ मुनि</font></font></a></li>");
document.write("        <li><a href='215.html'><font size=4><font color=darkPurple><b>215</b></font> - <font color=darkGreen>﻿भावरहित चौरासी लाख योनियों में भ्रमण</font></font></a></li>");
document.write("        <li><a href='216.html'><font size=4><font color=darkPurple><b>216</b></font> - <font color=darkBlue>﻿द्रव्य-मात्र से लिंगी नहीं, भाव से होता है </font></font></a></li>");
document.write("        <li><a href='217.html'><font size=4><font color=darkPurple><b>217</b></font> - <font color=darkGreen>﻿द्रव्यलिंगधारक को उलटा उपद्रव हुआ -- उदाहरण</font></font></a></li>");
document.write("        <li><a href='218.html'><font size=4><font color=darkPurple><b>218</b></font> - <font color=darkBlue>﻿दीपायन मुनि का उदाहरण</font></font></a></li>");
document.write("        <li><a href='219.html'><font size=4><font color=darkPurple><b>219</b></font> - <font color=darkGreen>﻿भाव-शुद्धि सहित मुनि हुए उन्होंने सिद्धि पाई, उसका उदाहरण</font></font></a></li>");
document.write("        <li><a href='220.html'><font size=4><font color=darkPurple><b>220</b></font> - <font color=darkBlue>﻿भाव-शुद्धि बिना शास्त्र भी पढ़े तो सिद्धि नहीं -- उदाहरण अभव्यसेन</font></font></a></li>");
document.write("        <li><a href='221.html'><font size=4><font color=darkPurple><b>221</b></font> - <font color=darkGreen>﻿शास्त्र पढ़े बिना भी भाव-विशुद्धि द्वारा सिद्धी -- उदाहरण शिवभूति मुनि</font></font></a></li>");
document.write("        <li><a href='222.html'><font size=4><font color=darkPurple><b>222</b></font> - <font color=darkBlue>﻿इसी अर्थ को सामान्यरूप से कहते हैं </font></font></a></li>");
document.write("        <li><a href='223.html'><font size=4><font color=darkPurple><b>223</b></font> - <font color=darkGreen>﻿इसी अर्थ को दृढ़ करते हैं </font></font></a></li>");
document.write("        <li><a href='224.html'><font size=4><font color=darkPurple><b>224</b></font> - <font color=darkBlue>﻿भावलिंग का निरूपण करते हैं </font></font></a></li>");
document.write("        <li><a href='225.html'><font size=4><font color=darkPurple><b>225</b></font> - <font color=darkGreen>﻿इसी अर्थ को स्पष्ट कर कहते हैं </font></font></a></li>");
document.write("        <li><a href='226.html'><font size=4><font color=darkPurple><b>226</b></font> - <font color=darkBlue>﻿ज्ञान, दर्शन, संयम, त्याग संवर और योग इनमें अभेद के अनुभव की प्रेरणा</font></font></a></li>");
document.write("        <li><a href='227.html'><font size=4><font color=darkPurple><b>227</b></font> - <font color=darkGreen>﻿इसी अर्थ को दृढ़ करते हैं </font></font></a></li>");
document.write("        <li><a href='228.html'><font size=4><font color=darkPurple><b>228</b></font> - <font color=darkBlue>﻿जो मोक्ष चाहे वह इसप्रकार आत्मा की भावना करे </font></font></a></li>");
document.write("        <li><a href='229.html'><font size=4><font color=darkPurple><b>229</b></font> - <font color=darkGreen>﻿जो आत्मा को भावे वह इसके स्वभाव को जानकर भावे, वही मोक्ष पाता है </font></font></a></li>");
document.write("        <li><a href='230.html'><font size=4><font color=darkPurple><b>230</b></font> - <font color=darkBlue>﻿जीव का स्वरूप</font></font></a></li>");
document.write("        <li><a href='231.html'><font size=4><font color=darkPurple><b>231</b></font> - <font color=darkGreen>﻿जो पुरुष जीव का अस्तित्व मानते हैं वे सिद्ध होते हैं :</font></font></a></li>");
document.write("        <li><a href='232.html'><font size=4><font color=darkPurple><b>232</b></font> - <font color=darkBlue>﻿वचन के अगोचर है और अनुभवगम्य जीव का स्वरूप इसप्रकार है </font></font></a></li>");
document.write("        <li><a href='233.html'><font size=4><font color=darkPurple><b>233</b></font> - <font color=darkGreen>﻿जीव का स्वभाव -- ज्ञानस्वरूप</font></font></a></li>");
document.write("        <li><a href='234.html'><font size=4><font color=darkPurple><b>234</b></font> - <font color=darkBlue>﻿पढ़ना, सुनना भी भाव बिना कुछ नहीं है </font></font></a></li>");
document.write("        <li><a href='235.html'><font size=4><font color=darkPurple><b>235</b></font> - <font color=darkGreen>﻿यदि बाह्य नग्नपने से ही सिद्धि हो तो नग्न तो सब ही होते हैं</font></font></a></li>");
document.write("        <li><a href='236.html'><font size=4><font color=darkPurple><b>236</b></font> - <font color=darkBlue>﻿केवल नग्नपने की निष्फलता दिखाते हैं </font></font></a></li>");
document.write("        <li><a href='237.html'><font size=4><font color=darkPurple><b>237</b></font> - <font color=darkGreen>﻿भाव-रहित द्रव्य-नग्न होकर मुनि कहलावे उसका अपयश होता है </font></font></a></li>");
document.write("        <li><a href='238.html'><font size=4><font color=darkPurple><b>238</b></font> - <font color=darkBlue>﻿भावलिंगी होने का उपदेश करते हैं </font></font></a></li>");
document.write("        <li><a href='239.html'><font size=4><font color=darkPurple><b>239</b></font> - <font color=darkGreen>﻿भावरहित नग्न मुनि है वह हास्य का स्थान है </font></font></a></li>");
document.write("        <li><a href='240.html'><font size=4><font color=darkPurple><b>240</b></font> - <font color=darkBlue>﻿द्रव्यलिंगी बोधि-समाधि जैसी जिनमार्ग में कही है वैसी नहीं पाता है </font></font></a></li>");
document.write("        <li><a href='241.html'><font size=4><font color=darkPurple><b>241</b></font> - <font color=darkGreen>﻿पहिले भाव से नग्न हो, पीछे द्रव्यमुनि बने यह मार्ग है </font></font></a></li>");
document.write("        <li><a href='242.html'><font size=4><font color=darkPurple><b>242</b></font> - <font color=darkBlue>﻿शुद्ध भाव ही स्वर्ग-मोक्ष का कारण है, मलिनभाव संसार का कारण है</font></font></a></li>");
document.write("        <li><a href='243.html'><font size=4><font color=darkPurple><b>243</b></font> - <font color=darkGreen>﻿भाव के फल का माहात्म्य</font></font></a></li>");
document.write("        <li><a href='244.html'><font size=4><font color=darkPurple><b>244</b></font> - <font color=darkBlue>﻿भावों के भेद</font></font></a></li>");
document.write("        <li><a href='245.html'><font size=4><font color=darkPurple><b>245</b></font> - <font color=darkGreen>﻿भाव -- शुभ, अशुभ और शुद्ध । आर्त्त और रौद्र ये अशुभ ध्यान हैं तथा धर्मध्यान शुभ है </font></font></a></li>");
document.write("        <li><a href='246.html'><font size=4><font color=darkPurple><b>246</b></font> - <font color=darkBlue>﻿जिनशासन का इसप्रकार माहात्म्य है </font></font></a></li>");
document.write("        <li><a href='247.html'><font size=4><font color=darkPurple><b>247</b></font> - <font color=darkGreen>﻿ऐसा मुनि ही तीर्थंकर-प्रकृति बाँधता है </font></font></a></li>");
document.write("        <li><a href='248.html'><font size=4><font color=darkPurple><b>248</b></font> - <font color=darkBlue>﻿भाव की विशुद्धता के लिए निमित्त आचरण कहते हैं</font></font></a></li>");
document.write("        <li><a href='249.html'><font size=4><font color=darkPurple><b>249</b></font> - <font color=darkGreen>﻿द्रव्य-भावरूप सामान्यरूप से जिनलिंग का स्वरूप</font></font></a></li>");
document.write("        <li><a href='250.html'><font size=4><font color=darkPurple><b>250</b></font> - <font color=darkBlue>﻿जिनधर्म की महिमा</font></font></a></li>");
document.write("        <li><a href='251.html'><font size=4><font color=darkPurple><b>251</b></font> - <font color=darkGreen>﻿धर्म का स्वरूप</font></font></a></li>");
document.write("        <li><a href='252.html'><font size=4><font color=darkPurple><b>252</b></font> - <font color=darkBlue>﻿पुण्य ही को धर्म मानना केवल भोग का निमित्त, कर्मक्षय का नहीं</font></font></a></li>");
document.write("        <li><a href='253.html'><font size=4><font color=darkPurple><b>253</b></font> - <font color=darkGreen>﻿आत्मा का स्वभावरूप धर्म ही मोक्ष का कारण</font></font></a></li>");
document.write("        <li><a href='254.html'><font size=4><font color=darkPurple><b>254</b></font> - <font color=darkBlue>﻿आत्मा के लिए इष्ट बिना समस्त पुण्य के आचरण से सिद्धि नहीं</font></font></a></li>");
document.write("        <li><a href='255.html'><font size=4><font color=darkPurple><b>255</b></font> - <font color=darkGreen>﻿आत्मा ही का श्रद्धान करो, प्रयत्न-पूर्वक जानो, मोक्ष प्राप्त करो </font></font></a></li>");
document.write("        <li><a href='256.html'><font size=4><font color=darkPurple><b>256</b></font> - <font color=darkBlue>﻿बाह्य-हिंसादिक क्रिया के बिना, अशुद्ध-भाव से तंदुल मत्स्य नरक को गया</font></font></a></li>");
document.write("        <li><a href='257.html'><font size=4><font color=darkPurple><b>257</b></font> - <font color=darkGreen>﻿भावरहित के बाह्य परिग्रह का त्यागादिक निष्प्रयोजन </font></font></a></li>");
document.write("        <li><a href='258.html'><font size=4><font color=darkPurple><b>258</b></font> - <font color=darkBlue>﻿भावशुद्धि के लिये इन्द्रियादिक को वश करो, भावशुद्धि-रहित बाह्यभेष का आडम्बर मत करो</font></font></a></li>");
document.write("        <li><a href='259.html'><font size=4><font color=darkPurple><b>259</b></font> - <font color=darkGreen>﻿फिर उपदेश कहते हैं </font></font></a></li>");
document.write("        <li><a href='260.html'><font size=4><font color=darkPurple><b>260</b></font> - <font color=darkBlue>﻿फिर कहते हैं </font></font></a></li>");
document.write("        <li><a href='261.html'><font size=4><font color=darkPurple><b>261</b></font> - <font color=darkGreen>﻿ऐसा करने से क्या होता है ?</font></font></a></li>");
document.write("        <li><a href='262.html'><font size=4><font color=darkPurple><b>262</b></font> - <font color=darkBlue>﻿भावशुद्धि के लिए फिर उपदेश</font></font></a></li>");
document.write("        <li><a href='263.html'><font size=4><font color=darkPurple><b>263</b></font> - <font color=darkGreen>﻿परीषह जय की प्रेरणा</font></font></a></li>");
document.write("        <li><a href='264.html'><font size=4>264</font></a></li>");
document.write("        <li><a href='265.html'><font size=4><font color=darkPurple><b>265</b></font> - <font color=darkGreen>﻿भाव-शुद्ध रखने के लिए ज्ञान का अभ्यास</font></font></a></li>");
document.write("        <li><a href='266.html'><font size=4><font color=darkPurple><b>266</b></font> - <font color=darkBlue>﻿भाव-शुद्धि के लिए अन्य उपाय</font></font></a></li>");
document.write("        <li><a href='267.html'><font size=4><font color=darkPurple><b>267</b></font> - <font color=darkGreen>﻿भावसहित आराधना के चतुष्क को पाता है, भाव बिना संसार में भ्रमण</font></font></a></li>");
document.write("        <li><a href='268.html'><font size=4><font color=darkPurple><b>268</b></font> - <font color=darkBlue>﻿आगे भाव ही के फल का विशेषरूप से कथन </font></font></a></li>");
document.write("        <li><a href='269.html'><font size=4><font color=darkPurple><b>269</b></font> - <font color=darkGreen>﻿अशुद्ध-भाव से अशुद्ध ही आहार किया, इसलिये दुर्गति ही पाई </font></font></a></li>");
document.write("        <li><a href='270.html'><font size=4><font color=darkPurple><b>270</b></font> - <font color=darkBlue>﻿सचित्त भोजन पान -- अशुद्ध-भाव</font></font></a></li>");
document.write("        <li><a href='271.html'><font size=4><font color=darkPurple><b>271</b></font> - <font color=darkGreen>﻿कंद-मूल-पुष्प आदि सचित्त भोजन -- अशुद्ध-भाव </font></font></a></li>");
document.write("        <li><a href='272.html'><font size=4><font color=darkPurple><b>272</b></font> - <font color=darkBlue>﻿विनय का वर्णन </font></font></a></li>");
document.write("        <li><a href='273.html'><font size=4><font color=darkPurple><b>273</b></font> - <font color=darkGreen>﻿वैयावृत्य का उपदेश</font></font></a></li>");
document.write("        <li><a href='274.html'><font size=4><font color=darkPurple><b>274</b></font> - <font color=darkBlue>﻿गर्हा का उपदेश</font></font></a></li>");
document.write("        <li><a href='275.html'><font size=4><font color=darkPurple><b>275</b></font> - <font color=darkGreen>﻿क्षमा का उपदेश</font></font></a></li>");
document.write("        <li><a href='276.html'><font size=4><font color=darkPurple><b>276</b></font> - <font color=darkBlue>﻿क्षमा का फल</font></font></a></li>");
document.write("        <li><a href='277.html'><font size=4><font color=darkPurple><b>277</b></font> - <font color=darkGreen>﻿क्षमा करना और क्रोध छोड़ना</font></font></a></li>");
document.write("        <li><a href='278.html'><font size=4><font color=darkPurple><b>278</b></font> - <font color=darkBlue>﻿दीक्षाकालादिक की भावना का उपदेश</font></font></a></li>");
document.write("        <li><a href='279.html'><font size=4><font color=darkPurple><b>279</b></font> - <font color=darkGreen>﻿भावलिंग शुद्ध करके द्रव्यलिंग सेवन का उपदेश</font></font></a></li>");
document.write("        <li><a href='280.html'><font size=4><font color=darkPurple><b>280</b></font> - <font color=darkBlue>﻿चार संज्ञा का फल संसार-भ्रमण</font></font></a></li>");
document.write("        <li><a href='281.html'><font size=4><font color=darkPurple><b>281</b></font> - <font color=darkGreen>﻿बाह्य उत्तरगुण की प्रेरणा</font></font></a></li>");
document.write("        <li><a href='282.html'><font size=4><font color=darkPurple><b>282</b></font> - <font color=darkBlue>﻿तत्त्व की भावना का उपदेश</font></font></a></li>");
document.write("        <li><a href='283.html'><font size=4><font color=darkPurple><b>283</b></font> - <font color=darkGreen>﻿तत्त्व की भावना बिना मोक्ष नहीं</font></font></a></li>");
document.write("        <li><a href='284.html'><font size=4><font color=darkPurple><b>284</b></font> - <font color=darkBlue>﻿पाप-पुण्य का और बन्ध-मोक्ष का कारण जीव के परिणाम</font></font></a></li>");
document.write("        <li><a href='285.html'><font size=4><font color=darkPurple><b>285</b></font> - <font color=darkGreen>﻿पाप-बंध के परिणाम </font></font></a></li>");
document.write("        <li><a href='286.html'><font size=4><font color=darkPurple><b>286</b></font> - <font color=darkBlue>﻿इससे उलटा जीव है वह पुण्य बाँधता है</font></font></a></li>");
document.write("        <li><a href='287.html'><font size=4><font color=darkPurple><b>287</b></font> - <font color=darkGreen>﻿आठों कर्मों से मुक्त होने की भावना</font></font></a></li>");
document.write("        <li><a href='288.html'><font size=4><font color=darkPurple><b>288</b></font> - <font color=darkBlue>﻿कर्मों का नाश के लिये उपदेश</font></font></a></li>");
document.write("        <li><a href='289.html'><font size=4><font color=darkPurple><b>289</b></font> - <font color=darkGreen>﻿भेदों के विकल्प से रहित होकर ध्यान का उपदेश</font></font></a></li>");
document.write("        <li><a href='290.html'><font size=4><font color=darkPurple><b>290</b></font> - <font color=darkBlue>﻿यह ध्यान भावलिंगी मुनियों का मोक्ष करता है </font></font></a></li>");
document.write("        <li><a href='291.html'><font size=4><font color=darkPurple><b>291</b></font> - <font color=darkGreen>﻿दृष्टांत</font></font></a></li>");
document.write("        <li><a href='292.html'><font size=4><font color=darkPurple><b>292</b></font> - <font color=darkBlue>﻿पंच परमेष्ठी का ध्यान करने का उपदेश</font></font></a></li>");
document.write("        <li><a href='293.html'><font size=4><font color=darkPurple><b>293</b></font> - <font color=darkGreen>﻿ज्ञान के अनुभवन का उपदेश</font></font></a></li>");
document.write("        <li><a href='294.html'><font size=4><font color=darkPurple><b>294</b></font> - <font color=darkBlue>﻿ध्यानरूप अग्नि से आठों कर्म नष्ट होते हैं</font></font></a></li>");
document.write("        <li><a href='295.html'><font size=4><font color=darkPurple><b>295</b></font> - <font color=darkGreen>﻿उपसंहार - भाव श्रमण हो</font></font></a></li>");
document.write("        <li><a href='296.html'><font size=4><font color=darkPurple><b>296</b></font> - <font color=darkBlue>﻿भाव-श्रमण का फल प्राप्त कर</font></font></a></li>");
document.write("        <li><a href='297.html'><font size=4><font color=darkPurple><b>297</b></font> - <font color=darkGreen>﻿भावश्रमण धन्य है, उनको हमारा नमस्कार</font></font></a></li>");
document.write("        <li><a href='298.html'><font size=4><font color=darkPurple><b>298</b></font> - <font color=darkBlue>﻿भावश्रमण देवादिक की ऋद्धि देखकर मोह को प्राप्त नहीं होते</font></font></a></li>");
document.write("        <li><a href='299.html'><font size=4><font color=darkPurple><b>299</b></font> - <font color=darkGreen>﻿भाव-श्रमण को सांसारिक सुख की कामना नहीं</font></font></a></li>");
document.write("        <li><a href='300.html'><font size=4><font color=darkPurple><b>300</b></font> - <font color=darkBlue>﻿बुढापा आए उससे पहले अपना हित कर लो</font></font></a></li>");
document.write("        <li><a href='301.html'><font size=4><font color=darkPurple><b>301</b></font> - <font color=darkGreen>﻿अहिंसाधर्म के उपदेश का वर्णन</font></font></a></li>");
document.write("        <li><a href='302.html'><font size=4><font color=darkPurple><b>302</b></font> - <font color=darkBlue>﻿अज्ञान-पूर्वक भूत-काल में त्रस-स्थावर जीवों का भक्षण</font></font></a></li>");
document.write("        <li><a href='303.html'><font size=4><font color=darkPurple><b>303</b></font> - <font color=darkGreen>﻿प्राणि-हिंसा से संसार में भ्रमण कर दुःख पाया</font></font></a></li>");
document.write("        <li><a href='304.html'><font size=4><font color=darkPurple><b>304</b></font> - <font color=darkBlue>﻿दया का उपदेश</font></font></a></li>");
document.write("        <li><a href='305.html'><font size=4><font color=darkPurple><b>305</b></font> - <font color=darkGreen>﻿मिथ्यात्व से संसार में भ्रमण । मिथ्यात्व के भेद</font></font></a></li>");
document.write("        <li><a href='306.html'><font size=4><font color=darkPurple><b>306</b></font> - <font color=darkBlue>﻿अभव्यजीव अपनी प्रकृति को नहीं छोड़ता, उसका मिथ्यात्व नहीं मिटता</font></font></a></li>");
document.write("        <li><a href='307.html'><font size=4><font color=darkPurple><b>307</b></font> - <font color=darkGreen>﻿एकान्त मिथ्यात्व के त्याग की प्रेरणा </font></font></a></li>");
document.write("        <li><a href='308.html'><font size=4><font color=darkPurple><b>308</b></font> - <font color=darkBlue>﻿कुगुरु के त्याग की प्रेरणा</font></font></a></li>");
document.write("        <li><a href='309.html'><font size=4><font color=darkPurple><b>309</b></font> - <font color=darkGreen>﻿अनायातन त्याग की प्रेरणा</font></font></a></li>");
document.write("        <li><a href='310.html'><font size=4><font color=darkPurple><b>310</b></font> - <font color=darkBlue>﻿सर्व मिथ्या मत को छोड़ने की प्रेरणा</font></font></a></li>");
document.write("        <li><a href='311.html'><font size=4><font color=darkPurple><b>311</b></font> - <font color=darkGreen>﻿सम्यग्दर्शन-रहित प्राणी चलता हुआ मृतक है</font></font></a></li>");
document.write("        <li><a href='312.html'><font size=4><font color=darkPurple><b>312</b></font> - <font color=darkBlue>﻿सम्यक्त्व का महानपना</font></font></a></li>");
document.write("        <li><a href='313.html'><font size=4><font color=darkPurple><b>313</b></font> - <font color=darkGreen>﻿सम्यक्त्व ही जीव को विशिष्ट बनाता है  </font></font></a></li>");
document.write("        <li><a href='314.html'><font size=4><font color=darkPurple><b>314</b></font> - <font color=darkBlue>﻿सम्यग्दर्शन-सहित लिंग की महिमा</font></font></a></li>");
document.write("        <li><a href='315.html'><font size=4><font color=darkPurple><b>315</b></font> - <font color=darkGreen>﻿ऐसा जानकर दर्शनरत्न को धारण करो</font></font></a></li>");
document.write("        <li><a href='316.html'><font size=4><font color=darkPurple><b>316</b></font> - <font color=darkBlue>﻿जीवपदार्थ का स्वरूप</font></font></a></li>");
document.write("        <li><a href='317.html'><font size=4><font color=darkPurple><b>317</b></font> - <font color=darkGreen>﻿सम्यक्त्व सहित भावना से घातिया कर्मों का क्षय</font></font></a></li>");
document.write("        <li><a href='318.html'><font size=4><font color=darkPurple><b>318</b></font> - <font color=darkBlue>﻿घातिया कर्मों के नाश से अनन्त-चतुष्टय </font></font></a></li>");
document.write("        <li><a href='319.html'><font size=4><font color=darkPurple><b>319</b></font> - <font color=darkGreen>﻿अनन्तचतुष्टय धारी परमात्मा के अनेक नाम</font></font></a></li>");
document.write("        <li><a href='320.html'><font size=4><font color=darkPurple><b>320</b></font> - <font color=darkBlue>﻿अरिहंत भगवान मुझे उत्तम बोधि देवे </font></font></a></li>");
document.write("        <li><a href='321.html'><font size=4><font color=darkPurple><b>321</b></font> - <font color=darkGreen>﻿अरहंत जिनेश्वर को नमस्कार से संसार की जन्मरूप बेल का नाश</font></font></a></li>");
document.write("        <li><a href='322.html'><font size=4><font color=darkPurple><b>322</b></font> - <font color=darkBlue>﻿जिनसम्यक्त्व को प्राप्त पुरुष आगामी कर्म से लिप्त नहीं होता</font></font></a></li>");
document.write("        <li><a href='323.html'><font size=4><font color=darkPurple><b>323</b></font> - <font color=darkGreen>﻿भाव सहित सम्यग्दृष्टि हैं वे ही सकल शील संयमादि गुणों से संयुक्त हैं, अन्य नहीं</font></font></a></li>");
document.write("        <li><a href='324.html'><font size=4><font color=darkPurple><b>324</b></font> - <font color=darkBlue>﻿सम्यग्दृष्टि होकर जिनने कषायरूप सुभट जीते वे ही धीरवीर</font></font></a></li>");
document.write("        <li><a href='325.html'><font size=4><font color=darkPurple><b>325</b></font> - <font color=darkGreen>﻿आप दर्शन-ज्ञान-चारित्ररूप होकर अन्य को भी उन सहित करते हैं, उनको धन्य है</font></font></a></li>");
document.write("        <li><a href='326.html'><font size=4><font color=darkPurple><b>326</b></font> - <font color=darkBlue>﻿ऐसे मुनियों की महिमा करते हैं</font></font></a></li>");
document.write("        <li><a href='327.html'><font size=4><font color=darkPurple><b>327</b></font> - <font color=darkGreen>﻿उन मुनियों के सामर्थ्य कहते हैं</font></font></a></li>");
document.write("        <li><a href='328.html'><font size=4><font color=darkPurple><b>328</b></font> - <font color=darkBlue>﻿इसप्रकार मूलगुण और उत्तरगुणों से मंडित मुनि हैं वे जिनमत में शोभा पाते हैं</font></font></a></li>");
document.write("        <li><a href='329.html'><font size=4><font color=darkPurple><b>329</b></font> - <font color=darkGreen>﻿इसप्रकार विशुद्ध-भाव द्वारा तीर्थंकर आदि पद के सुखों पाते हैं</font></font></a></li>");
document.write("        <li><a href='330.html'><font size=4><font color=darkPurple><b>330</b></font> - <font color=darkBlue>﻿मोक्ष का सुख भी ऐसे ही पाते हैं</font></font></a></li>");
document.write("        <li><a href='331.html'><font size=4><font color=darkPurple><b>331</b></font> - <font color=darkGreen>﻿सिद्ध-सुख को प्राप्त सिद्ध-भगवान मुझे भावों की शुद्धता देवें </font></font></a></li>");
document.write("        <li><a href='332.html'><font size=4><font color=darkPurple><b>332</b></font> - <font color=darkBlue>﻿भाव के कथन का संकोच</font></font></a></li>");
document.write("        <li><a href='333.html'><font size=4><font color=darkPurple><b>333</b></font> - <font color=darkGreen>﻿भावपाहुड़ को पढ़ने-सुनने व भावना करने का उपदेश</font></font></a></li>");
document.write("        <li><a href='334.html'><font size=4><br><font size=5 color=black><b>﻿मोक्ष-पाहुड </b></font><br><br><font color=darkPurple><b>334</b></font> - <font color=darkBlue>﻿मंगलाचरण और ग्रन्थ लिखने की प्रतिज्ञा</font></font></a></li>");
document.write("        <li><a href='335.html'><font size=4><font color=darkPurple><b>335</b></font> - <font color=darkGreen>﻿मंगलाचरण कर ग्रंथ करने की प्रतिज्ञा</font></font></a></li>");
document.write("        <li><a href='336.html'><font size=4><font color=darkPurple><b>336</b></font> - <font color=darkBlue>﻿ध्यानी उस परमात्मा का ध्यान कर परम पद को प्राप्त करते हैं</font></font></a></li>");
document.write("        <li><a href='337.html'><font size=4><font color=darkPurple><b>337</b></font> - <font color=darkGreen>﻿आत्मा के तीन प्रकार</font></font></a></li>");
document.write("        <li><a href='338.html'><font size=4><font color=darkPurple><b>338</b></font> - <font color=darkBlue>﻿तीन प्रकार के आत्मा का स्वरूप</font></font></a></li>");
document.write("        <li><a href='339.html'><font size=4><font color=darkPurple><b>339</b></font> - <font color=darkGreen>﻿परमात्मा का विशेषण द्वारा स्वरूप</font></font></a></li>");
document.write("        <li><a href='340.html'><font size=4><font color=darkPurple><b>340</b></font> - <font color=darkBlue>﻿अंतरात्मपन द्वारा बहिरात्मपन को छोड़कर परमात्मा बनो</font></font></a></li>");
document.write("        <li><a href='341.html'><font size=4><font color=darkPurple><b>341</b></font> - <font color=darkGreen>﻿बहिरात्मा की प्रवृत्ति</font></font></a></li>");
document.write("        <li><a href='342.html'><font size=4><font color=darkPurple><b>342</b></font> - <font color=darkBlue>﻿मिथ्यादृष्टि का लक्षण</font></font></a></li>");
document.write("        <li><a href='343.html'><font size=4><font color=darkPurple><b>343</b></font> - <font color=darkGreen>﻿मिथ्यादृष्टि पर में मोह करता है</font></font></a></li>");
document.write("        <li><a href='344.html'><font size=4><font color=darkPurple><b>344</b></font> - <font color=darkBlue>﻿मिथ्याज्ञान और मिथ्याभाव से आगामी भव में भी यह मनुष्य देह को चाहता है</font></font></a></li>");
document.write("        <li><a href='345.html'><font size=4><font color=darkPurple><b>345</b></font> - <font color=darkGreen>﻿देह में निर्मम निर्वाण को पाता है</font></font></a></li>");
document.write("        <li><a href='346.html'><font size=4><font color=darkPurple><b>346</b></font> - <font color=darkBlue>﻿बंध और मोक्ष के कारण का संक्षेप</font></font></a></li>");
document.write("        <li><a href='347.html'><font size=4><font color=darkPurple><b>347</b></font> - <font color=darkGreen>﻿स्वद्रव्य में रत सम्यग्दृष्टि कर्मों का नाश करता है</font></font></a></li>");
document.write("        <li><a href='348.html'><font size=4><font color=darkPurple><b>348</b></font> - <font color=darkBlue>﻿परद्रव्य में रत मिथ्यादृष्टि कर्मों को बाँधता है</font></font></a></li>");
document.write("        <li><a href='349.html'><font size=4><font color=darkPurple><b>349</b></font> - <font color=darkGreen>﻿पर-द्रव्य से दुर्गति और स्व-द्रव्य से ही सुगति होती है</font></font></a></li>");
document.write("        <li><a href='350.html'><font size=4><font color=darkPurple><b>350</b></font> - <font color=darkBlue>﻿पर-द्रव्य का स्वरूप</font></font></a></li>");
document.write("        <li><a href='351.html'><font size=4><font color=darkPurple><b>351</b></font> - <font color=darkGreen>﻿स्व-द्रव्य (आत्म-स्वभाव) ऐसा होता है</font></font></a></li>");
document.write("        <li><a href='352.html'><font size=4><font color=darkPurple><b>352</b></font> - <font color=darkBlue>﻿ऐसे निज-द्रव्य के ध्यान से निर्वाण</font></font></a></li>");
document.write("        <li><a href='353.html'><font size=4><font color=darkPurple><b>353</b></font> - <font color=darkGreen>﻿शुद्धात्मा के ध्यान से स्वर्ग की भी प्राप्ति</font></font></a></li>");
document.write("        <li><a href='354.html'><font size=4><font color=darkPurple><b>354</b></font> - <font color=darkBlue>﻿दृष्टांत</font></font></a></li>");
document.write("        <li><a href='355.html'><font size=4><font color=darkPurple><b>355</b></font> - <font color=darkGreen>﻿अन्य दृष्टान्त</font></font></a></li>");
document.write("        <li><a href='356.html'><font size=4><font color=darkPurple><b>356</b></font> - <font color=darkBlue>﻿ध्यान के योग से स्वर्ग / मोक्ष की प्राप्ति</font></font></a></li>");
document.write("        <li><a href='357.html'><font size=4><font color=darkPurple><b>357</b></font> - <font color=darkGreen>﻿दृष्टांत / दार्ष्टान्त</font></font></a></li>");
document.write("        <li><a href='358.html'><font size=4><font color=darkPurple><b>358</b></font> - <font color=darkBlue>﻿अव्रतादिक श्रेष्ठ नहीं है</font></font></a></li>");
document.write("        <li><a href='359.html'><font size=4><font color=darkPurple><b>359</b></font> - <font color=darkGreen>﻿संसार से निकलने के लिए आत्मा का ध्यान करे</font></font></a></li>");
document.write("        <li><a href='360.html'><font size=4><font color=darkPurple><b>360</b></font> - <font color=darkBlue>﻿आत्मा का ध्यान करने की विधि</font></font></a></li>");
document.write("        <li><a href='361.html'><font size=4><font color=darkPurple><b>361</b></font> - <font color=darkGreen>﻿इसी को विशेषरूप से कहते हैं</font></font></a></li>");
document.write("        <li><a href='362.html'><font size=4><font color=darkPurple><b>362</b></font> - <font color=darkBlue>﻿क्या विचारकर ध्यान करनेवाला मौन धारण करता है ?</font></font></a></li>");
document.write("        <li><a href='363.html'><font size=4><font color=darkPurple><b>363</b></font> - <font color=darkGreen>﻿ध्यान द्वारा संवर और निर्जरा</font></font></a></li>");
document.write("        <li><a href='364-365.html'><font size=4><font color=darkPurple><b>364-365</b></font> - <font color=darkBlue>﻿जो व्यवहार में तत्पर है उसके यह ध्यान नहीं</font></font></a></li>");
document.write("        <li><a href='366.html'><font size=4><font color=darkPurple><b>366</b></font> - <font color=darkGreen>﻿जिनदेवने द्वारा ध्यान अध्ययन में प्रवृत्ति की प्रेरणा</font></font></a></li>");
document.write("        <li><a href='367.html'><font size=4><font color=darkPurple><b>367</b></font> - <font color=darkBlue>﻿जो रत्नत्रय की आराधना करता है वह जीव आराधक ही है</font></font></a></li>");
document.write("        <li><a href='368.html'><font size=4><font color=darkPurple><b>368</b></font> - <font color=darkGreen>﻿शुद्धात्मा केवलज्ञान है और केवलज्ञान शुद्धात्मा है</font></font></a></li>");
document.write("        <li><a href='369.html'><font size=4><font color=darkPurple><b>369</b></font> - <font color=darkBlue>﻿रत्नत्रय का आराधक ही आत्मा का ध्यान करता है</font></font></a></li>");
document.write("        <li><a href='370-371.html'><font size=4><font color=darkPurple><b>370-371</b></font> - <font color=darkGreen>﻿आत्मा में रत्नत्रय कैसे है ?</font></font></a></li>");
document.write("        <li><a href='372-373.html'><font size=4><font color=darkPurple><b>372-373</b></font> - <font color=darkBlue>﻿सम्यग्दर्शन को प्रधान कर कहते हैं</font></font></a></li>");
document.write("        <li><a href='374.html'><font size=4><font color=darkPurple><b>374</b></font> - <font color=darkGreen>﻿सम्यग्ज्ञान का स्वरूप</font></font></a></li>");
document.write("        <li><a href='375.html'><font size=4><font color=darkPurple><b>375</b></font> - <font color=darkBlue>﻿सम्यक्चारित्र का स्वरूप</font></font></a></li>");
document.write("        <li><a href='376.html'><font size=4><font color=darkPurple><b>376</b></font> - <font color=darkGreen>﻿रत्नत्रय-सहित तप-संयम-समिति का पालन द्वारा शुद्धात्मा का ध्यान से निर्वाण की प्राप्ति</font></font></a></li>");
document.write("        <li><a href='377-378.html'><font size=4><font color=darkPurple><b>377-378</b></font> - <font color=darkBlue>﻿ध्यानी मुनि ऐसा बनकर परमात्मा का ध्यान करता है</font></font></a></li>");
document.write("        <li><a href='379.html'><font size=4><font color=darkPurple><b>379</b></font> - <font color=darkGreen>﻿विषय-कषायों में आसक्त परमात्मा की भावना से रहित है, उसे मोक्ष नहीं</font></font></a></li>");
document.write("        <li><a href='380.html'><font size=4><font color=darkPurple><b>380</b></font> - <font color=darkBlue>﻿जिनमुद्रा जिन जीवों को नहीं रुचती वे दीर्घ-संसारी</font></font></a></li>");
document.write("        <li><a href='381.html'><font size=4><font color=darkPurple><b>381</b></font> - <font color=darkGreen>﻿परमात्मा के ध्यान से लोभ-रहित होकर निरास्रव</font></font></a></li>");
document.write("        <li><a href='382.html'><font size=4><font color=darkPurple><b>382</b></font> - <font color=darkBlue>﻿ऐसा निर्लोभी दृढ़ रत्नत्रय सहित परमात्मा के ध्यान द्वारा परम-पद को पाता है</font></font></a></li>");
document.write("        <li><a href='383.html'><font size=4><font color=darkPurple><b>383</b></font> - <font color=darkGreen>﻿चारित्र क्या है ?</font></font></a></li>");
document.write("        <li><a href='384.html'><font size=4><font color=darkPurple><b>384</b></font> - <font color=darkBlue>﻿जीव के परिणाम की स्वच्छता को दृष्टांत पूर्वक दिखाते हैं</font></font></a></li>");
document.write("        <li><a href='385.html'><font size=4><font color=darkPurple><b>385</b></font> - <font color=darkGreen>﻿वह बाह्य में कैसा होता है?</font></font></a></li>");
document.write("        <li><a href='386.html'><font size=4><font color=darkPurple><b>386</b></font> - <font color=darkBlue>﻿तीन गुप्ति की महिमा</font></font></a></li>");
document.write("        <li><a href='387.html'><font size=4><font color=darkPurple><b>387</b></font> - <font color=darkGreen>﻿परद्रव्य में राग-द्वेष करे वह अज्ञानी, ज्ञानी इससे उल्टा है</font></font></a></li>");
document.write("        <li><a href='388.html'><font size=4><font color=darkPurple><b>388</b></font> - <font color=darkBlue>﻿ज्ञानी मोक्ष के निमित्त भी राग नहीं करता</font></font></a></li>");
document.write("        <li><a href='389.html'><font size=4><font color=darkPurple><b>389</b></font> - <font color=darkGreen>﻿कर्ममात्र से ही सिद्धि मानना अज्ञान</font></font></a></li>");
document.write("        <li><a href='390.html'><font size=4><font color=darkPurple><b>390</b></font> - <font color=darkBlue>﻿चारित्र रहित ज्ञान और सम्यक्त्व रहित तप अर्थ-क्रियाकारी नहीं</font></font></a></li>");
document.write("        <li><a href='391.html'><font size=4><font color=darkPurple><b>391</b></font> - <font color=darkGreen>﻿सांख्यमती आदि के आशय का निषेध</font></font></a></li>");
document.write("        <li><a href='392-393.html'><font size=4><font color=darkPurple><b>392-393</b></font> - <font color=darkBlue>﻿तप रहित ज्ञान और ज्ञान रहित तप अकार्य हैं, दोनों के संयुक्त होने पर ही निर्वाण है</font></font></a></li>");
document.write("        <li><a href='394.html'><font size=4><font color=darkPurple><b>394</b></font> - <font color=darkGreen>﻿बाह्यलिंग-सहित और अभ्यंतरलिंग-रहित मोक्षमार्ग नहीं</font></font></a></li>");
document.write("        <li><a href='395.html'><font size=4><font color=darkPurple><b>395</b></font> - <font color=darkBlue>﻿तपश्चरण सहित ज्ञान को भाना</font></font></a></li>");
document.write("        <li><a href='396.html'><font size=4><font color=darkPurple><b>396</b></font> - <font color=darkGreen>﻿आहार, आसन, निद्रा को जीतकर आत्मा का ध्यान करना</font></font></a></li>");
document.write("        <li><a href='397.html'><font size=4><font color=darkPurple><b>397</b></font> - <font color=darkBlue>﻿ध्येय का स्वरूप</font></font></a></li>");
document.write("        <li><a href='398.html'><font size=4><font color=darkPurple><b>398</b></font> - <font color=darkGreen>﻿आत्मा का जानना, भाना और विषयों से विरक्त होना ये उत्तरोत्तर दुर्लभ</font></font></a></li>");
document.write("        <li><a href='399.html'><font size=4><font color=darkPurple><b>399</b></font> - <font color=darkBlue>﻿जब तक विषयों में प्रवर्तता है तब तक आत्म-ज्ञान नहीं होता</font></font></a></li>");
document.write("        <li><a href='400.html'><font size=4><font color=darkPurple><b>400</b></font> - <font color=darkGreen>﻿आत्मा को जानकर भी भावना बिना संसार में ही रहना है</font></font></a></li>");
document.write("        <li><a href='401.html'><font size=4><font color=darkPurple><b>401</b></font> - <font color=darkBlue>﻿जो विषयों से विरक्त होकर आत्मा को जानकर भाते हैं वे संसार को छोड़ते हैं</font></font></a></li>");
document.write("        <li><a href='402.html'><font size=4><font color=darkPurple><b>402</b></font> - <font color=darkGreen>﻿पर-द्रव्य में लेशमात्र भी राग हो तो वह अज्ञानी</font></font></a></li>");
document.write("        <li><a href='403.html'><font size=4><font color=darkPurple><b>403</b></font> - <font color=darkBlue>﻿इस अर्थ को संक्षेप से कहते हैं</font></font></a></li>");
document.write("        <li><a href='404.html'><font size=4><font color=darkPurple><b>404</b></font> - <font color=darkGreen>﻿राग संसार का कारण होने से योगीश्वर आत्मा में भावना करते हैं</font></font></a></li>");
document.write("        <li><a href='405.html'><font size=4><font color=darkPurple><b>405</b></font> - <font color=darkBlue>﻿रागद्वेष से रहित ही चारित्र होता है</font></font></a></li>");
document.write("        <li><a href='406-407.html'><font size=4><font color=darkPurple><b>406-407</b></font> - <font color=darkGreen>﻿पंचमकाल आत्मध्यान का काल नहीं है, उसका निषेध</font></font></a></li>");
document.write("        <li><a href='408.html'><font size=4><font color=darkPurple><b>408</b></font> - <font color=darkBlue>﻿जो ऐसा कहता है कि पंचम-काल ध्यान का काल नहीं, उसको कहते हैं</font></font></a></li>");
document.write("        <li><a href='409.html'><font size=4><font color=darkPurple><b>409</b></font> - <font color=darkGreen>﻿अभी इस पंचमकाल में धर्मध्यान होता है, यह नहीं मानता है वह अज्ञानी है</font></font></a></li>");
document.write("        <li><a href='410.html'><font size=4><font color=darkPurple><b>410</b></font> - <font color=darkBlue>﻿इस काल में भी रत्नत्रय का धारक मुनि स्वर्ग प्राप्त करके वहाँ से चयकर मोक्ष जाता है</font></font></a></li>");
document.write("        <li><a href='411.html'><font size=4><font color=darkPurple><b>411</b></font> - <font color=darkGreen>﻿ध्यान का अभाव मानकर मुनिलिंग ग्रहण कर पाप में प्रवृत्ति करने का निषेध</font></font></a></li>");
document.write("        <li><a href='412.html'><font size=4><font color=darkPurple><b>412</b></font> - <font color=darkBlue>﻿मोक्षमार्ग से च्युत वे कैसे हैं</font></font></a></li>");
document.write("        <li><a href='413.html'><font size=4><font color=darkPurple><b>413</b></font> - <font color=darkGreen>﻿मोक्षमार्गी कैसे होते हैं ?</font></font></a></li>");
document.write("        <li><a href='414.html'><font size=4><font color=darkPurple><b>414</b></font> - <font color=darkBlue>﻿मोक्षमार्गी की प्रवृत्ति</font></font></a></li>");
document.write("        <li><a href='415.html'><font size=4><font color=darkPurple><b>415</b></font> - <font color=darkGreen>﻿फिर कहते हैं</font></font></a></li>");
document.write("        <li><a href='416.html'><font size=4><font color=darkPurple><b>416</b></font> - <font color=darkBlue>﻿निश्चयनय से ध्यान इस प्रकार करना</font></font></a></li>");
document.write("        <li><a href='417.html'><font size=4><font color=darkPurple><b>417</b></font> - <font color=darkGreen>﻿इस ही अर्थ को दृढ़ करते हुए कहते हैं</font></font></a></li>");
document.write("        <li><a href='418.html'><font size=4><font color=darkPurple><b>418</b></font> - <font color=darkBlue>﻿अब श्रावकों को प्रवर्तने के लिए कहते हैं</font></font></a></li>");
document.write("        <li><a href='419.html'><font size=4><font color=darkPurple><b>419</b></font> - <font color=darkGreen>﻿श्रावकों को पहिले क्या करना, वह कहते हैं</font></font></a></li>");
document.write("        <li><a href='420-421.html'><font size=4><font color=darkPurple><b>420-421</b></font> - <font color=darkBlue>﻿सम्यक्त्व के ध्यान की ही महिमा</font></font></a></li>");
document.write("        <li><a href='422.html'><font size=4><font color=darkPurple><b>422</b></font> - <font color=darkGreen>﻿जो निरन्तर सम्यक्त्व का पालन करते हैं उनको धन्य है</font></font></a></li>");
document.write("        <li><a href='423.html'><font size=4><font color=darkPurple><b>423</b></font> - <font color=darkBlue>﻿इस सम्यक्त्व के बाह्य चिह्न बताते हैं</font></font></a></li>");
document.write("        <li><a href='424.html'><font size=4><font color=darkPurple><b>424</b></font> - <font color=darkGreen>﻿इसी अर्थ को दृढ़ करते हैं</font></font></a></li>");
document.write("        <li><a href='425-426-427.html'><font size=4><font color=darkPurple><b>425-426-427</b></font> - <font color=darkBlue>﻿मिथ्यादृष्टि के चिह्न कहते हैं</font></font></a></li>");
document.write("        <li><a href='428.html'><font size=4><font color=darkPurple><b>428</b></font> - <font color=darkGreen>﻿मिथ्यादृष्टि जीव संसार में दुःख-सहित भ्रमण करता है</font></font></a></li>");
document.write("        <li><a href='429.html'><font size=4><font color=darkPurple><b>429</b></font> - <font color=darkBlue>﻿सम्यक्त्व-मिथ्यात्व भाव के कथन का संकोच</font></font></a></li>");
document.write("        <li><a href='430.html'><font size=4><font color=darkPurple><b>430</b></font> - <font color=darkGreen>﻿यदि मिथ्यात्व-भाव नहीं छोड़ा तब बाह्य भेष से कुछ लाभ नहीं</font></font></a></li>");
document.write("        <li><a href='431.html'><font size=4><font color=darkPurple><b>431</b></font> - <font color=darkBlue>﻿मूलगुण बिगाड़े उसके सम्यक्त्व नहीं रहता ?</font></font></a></li>");
document.write("        <li><a href='432-433.html'><font size=4><font color=darkPurple><b>432-433</b></font> - <font color=darkGreen>﻿आत्म-स्वभाव से विपरीत को बाह्य क्रिया-कर्म निष्फल</font></font></a></li>");
document.write("        <li><a href='434-435.html'><font size=4><font color=darkPurple><b>434-435</b></font> - <font color=darkBlue>﻿ऐसा साधु मोक्ष पाता है</font></font></a></li>");
document.write("        <li><a href='436.html'><font size=4><font color=darkPurple><b>436</b></font> - <font color=darkGreen>﻿सब से उत्तम पदार्थ -- शुद्ध-आत्मा इस देह में ही रह रहा है, उसको जानो</font></font></a></li>");
document.write("        <li><a href='437-438.html'><font size=4><font color=darkPurple><b>437-438</b></font> - <font color=darkBlue>﻿आत्मा ही मुझे शरण है</font></font></a></li>");
document.write("        <li><a href='439.html'><font size=4><font color=darkPurple><b>439</b></font> - <font color=darkGreen>﻿मोक्षपाहुड़ पढ़ने, सुनने, भाने का फल कहते हैं</font></font></a></li>");
document.write("        <li><a href='440.html'><font size=4><br><font size=5 color=black><b>﻿लिंग-पाहुड </b></font><br><br><font color=darkPurple><b>440</b></font> - <font color=darkBlue>﻿इष्ट को नमस्कार कर ग्रन्थ करने की प्रतिज्ञा</font></font></a></li>");
document.write("        <li><a href='441.html'><font size=4><font color=darkPurple><b>441</b></font> - <font color=darkGreen>﻿बाह्यभेष अंतरंग-धर्म सहित कार्यकारी है </font></font></a></li>");
document.write("        <li><a href='442.html'><font size=4><font color=darkPurple><b>442</b></font> - <font color=darkBlue>﻿निर्ग्रंथ लिंग ग्रहणकर कुक्रिया करके हँसी करावे, वे पापबुद्धि </font></font></a></li>");
document.write("        <li><a href='443.html'><font size=4><font color=darkPurple><b>443</b></font> - <font color=darkGreen>﻿लिंग धारण करके कुक्रिया करे उसको प्रगट कहते हैं </font></font></a></li>");
document.write("        <li><a href='444.html'><font size=4><font color=darkPurple><b>444</b></font> - <font color=darkBlue>﻿फिर कहते हैं </font></font></a></li>");
document.write("        <li><a href='445.html'><font size=4><font color=darkPurple><b>445</b></font> - <font color=darkGreen>﻿फिर कहते हैं </font></font></a></li>");
document.write("        <li><a href='446.html'><font size=4><font color=darkPurple><b>446</b></font> - <font color=darkBlue>﻿फिर कहते हैं </font></font></a></li>");
document.write("        <li><a href='447.html'><font size=4><font color=darkPurple><b>447</b></font> - <font color=darkGreen>﻿फिर कहते हैं </font></font></a></li>");
document.write("        <li><a href='448.html'><font size=4><font color=darkPurple><b>448</b></font> - <font color=darkBlue>﻿यदि भावशुद्धि के बिना गृहस्थपद छोड़े तो यह प्रवृत्ति होती है </font></font></a></li>");
document.write("        <li><a href='449.html'><font size=4><font color=darkPurple><b>449</b></font> - <font color=darkGreen>﻿फिर कहते हैं </font></font></a></li>");
document.write("        <li><a href='450.html'><font size=4><font color=darkPurple><b>450</b></font> - <font color=darkBlue>﻿लिंग धारण करके दुःखी रहता है, आदर नहीं करता, वह भी नरक में जाता है</font></font></a></li>");
document.write("        <li><a href='451.html'><font size=4><font color=darkPurple><b>451</b></font> - <font color=darkGreen>﻿जो भोजन में भी रसों का लोलुपी होता है वह भी लिंग को लजाता है</font></font></a></li>");
document.write("        <li><a href='452.html'><font size=4><font color=darkPurple><b>452</b></font> - <font color=darkBlue>﻿इसी को विशेषरूप से कहते हैं </font></font></a></li>");
document.write("        <li><a href='453.html'><font size=4><font color=darkPurple><b>453</b></font> - <font color=darkGreen>﻿फिर कहते हैं </font></font></a></li>");
document.write("        <li><a href='454.html'><font size=4><font color=darkPurple><b>454</b></font> - <font color=darkBlue>﻿जो लिंग धारण करके ऐसे प्रवर्तते हैं वे श्रमण नहीं हैं </font></font></a></li>");
document.write("        <li><a href='455.html'><font size=4><font color=darkPurple><b>455</b></font> - <font color=darkGreen>﻿लिंग ग्रहणकर वनस्पति आदि स्थावर जीवों की हिंसा का निषेध</font></font></a></li>");
document.write("        <li><a href='456.html'><font size=4><font color=darkPurple><b>456</b></font> - <font color=darkBlue>﻿लिंग धारण करके स्त्रियों से राग करने का निषेध</font></font></a></li>");
document.write("        <li><a href='457.html'><font size=4><font color=darkPurple><b>457</b></font> - <font color=darkGreen>﻿फिर कहते हैं </font></font></a></li>");
document.write("        <li><a href='458.html'><font size=4><font color=darkPurple><b>458</b></font> - <font color=darkBlue>﻿उपसंहार</font></font></a></li>");
document.write("        <li><a href='459.html'><font size=4><font color=darkPurple><b>459</b></font> - <font color=darkGreen>﻿श्रमण को स्त्रियों के संसर्ग का निषेध</font></font></a></li>");
document.write("        <li><a href='460.html'><font size=4><font color=darkPurple><b>460</b></font> - <font color=darkBlue>﻿फिर कहते हैं </font></font></a></li>");
document.write("        <li><a href='461.html'><font size=4><font color=darkPurple><b>461</b></font> - <font color=darkGreen>﻿जो धर्म का यथार्थरूप से पालन करता है वह उत्तम सुख पाता है</font></font></a></li>");
document.write("        <li><a href='462.html'><font size=4><br><font size=5 color=black><b>﻿शील-पाहुड </b></font><br><br><font color=darkPurple><b>462</b></font> - <font color=darkBlue>﻿नमस्काररूप मंगल</font></font></a></li>");
document.write("        <li><a href='463.html'><font size=4><font color=darkPurple><b>463</b></font> - <font color=darkGreen>﻿शील का रूप</font></font></a></li>");
document.write("        <li><a href='464.html'><font size=4><font color=darkPurple><b>464</b></font> - <font color=darkBlue>﻿ज्ञान की भावना करना और विषयों से विरक्त होना दुर्लभ</font></font></a></li>");
document.write("        <li><a href='465.html'><font size=4><font color=darkPurple><b>465</b></font> - <font color=darkGreen>﻿विषयों में प्रवर्तता है तबतक ज्ञान को नहीं जानता है</font></font></a></li>");
document.write("        <li><a href='466.html'><font size=4><font color=darkPurple><b>466</b></font> - <font color=darkBlue>﻿ज्ञान का, लिंगग्रहण का तथा तप का अनुक्रम </font></font></a></li>");
document.write("        <li><a href='467.html'><font size=4><font color=darkPurple><b>467</b></font> - <font color=darkGreen>﻿ऐसा करके थोड़ा भी करे तो बड़ा फल होता है</font></font></a></li>");
document.write("        <li><a href='468.html'><font size=4><font color=darkPurple><b>468</b></font> - <font color=darkBlue>﻿विषयासक्त रहते हैं वे संसार ही में भ्रमण करते हैं</font></font></a></li>");
document.write("        <li><a href='469.html'><font size=4><font color=darkPurple><b>469</b></font> - <font color=darkGreen>﻿ज्ञान प्राप्त करके इसप्रकार करे तब संसार कटे</font></font></a></li>");
document.write("        <li><a href='470.html'><font size=4><font color=darkPurple><b>470</b></font> - <font color=darkBlue>﻿शीलसहित ज्ञान से जीव शुद्ध होता है उसका दृष्टान्त </font></font></a></li>");
document.write("        <li><a href='471.html'><font size=4><font color=darkPurple><b>471</b></font> - <font color=darkGreen>﻿विषयासक्ति ज्ञान का दोष नहीं, कुपुरुष का दोष</font></font></a></li>");
document.write("        <li><a href='472.html'><font size=4><font color=darkPurple><b>472</b></font> - <font color=darkBlue>﻿इसप्रकार निर्वाण होता है</font></font></a></li>");
document.write("        <li><a href='473.html'><font size=4><font color=darkPurple><b>473</b></font> - <font color=darkGreen>﻿शील की मुख्यता द्वारा नियम से निर्वाण</font></font></a></li>");
document.write("        <li><a href='474.html'><font size=4><font color=darkPurple><b>474</b></font> - <font color=darkBlue>﻿अविरति को भी 'मार्ग' विषयों से विरक्त ही कहना योग्य</font></font></a></li>");
document.write("        <li><a href='475.html'><font size=4><font color=darkPurple><b>475</b></font> - <font color=darkGreen>﻿ज्ञान से भी शील की प्राथमिकता</font></font></a></li>");
document.write("        <li><a href='477.html'><font size=4><font color=darkPurple><b>477</b></font> - <font color=darkBlue>﻿बहुत शास्त्रों का ज्ञान होते हुए भी शील ही उत्तम</font></font></a></li>");
document.write("        <li><a href='478.html'><font size=4><font color=darkPurple><b>478</b></font> - <font color=darkGreen>﻿जो शील गुण से मंडित हैं, वे देवों के भी वल्लभ हैं</font></font></a></li>");
document.write("        <li><a href='479.html'><font size=4><font color=darkPurple><b>479</b></font> - <font color=darkBlue>﻿शील सहित का मनुष्यभव में जीना सफल</font></font></a></li>");
document.write("        <li><a href='480.html'><font size=4><font color=darkPurple><b>480</b></font> - <font color=darkGreen>﻿जितने भी भले कार्य हैं वे सब शील के परिवार हैं</font></font></a></li>");
document.write("        <li><a href='481.html'><font size=4><font color=darkPurple><b>481</b></font> - <font color=darkBlue>﻿शील ही तप आदिक हैं</font></font></a></li>");
document.write("        <li><a href='482.html'><font size=4><font color=darkPurple><b>482</b></font> - <font color=darkGreen>﻿विषयरूप विष महा प्रबल है</font></font></a></li>");
document.write("        <li><a href='483.html'><font size=4><font color=darkPurple><b>483</b></font> - <font color=darkBlue>﻿विषय-रूपी विष से संसार में बारबार भ्रमण</font></font></a></li>");
document.write("        <li><a href='484.html'><font size=4><font color=darkPurple><b>484</b></font> - <font color=darkGreen>﻿विषयों की आसक्ति से चतुर्गति में दु:ख</font></font></a></li>");
document.write("        <li><a href='485.html'><font size=4><font color=darkPurple><b>485</b></font> - <font color=darkBlue>﻿विषयों को छोड़ने से कुछ भी हानि नहीं है</font></font></a></li>");
document.write("        <li><a href='486.html'><font size=4><font color=darkPurple><b>486</b></font> - <font color=darkGreen>﻿सब अंगों में शील ही उत्तम है</font></font></a></li>");
document.write("        <li><a href='487.html'><font size=4><font color=darkPurple><b>487</b></font> - <font color=darkBlue>﻿विषयों में आसक्त, मूढ़, कुशील का  संसार में भ्रणम</font></font></a></li>");
document.write("        <li><a href='488.html'><font size=4><font color=darkPurple><b>488</b></font> - <font color=darkGreen>﻿जो कर्म की गांठ विषय सेवन करके आप ही बाँधी है उसको सत्पुरुष तपश्चरणादि करके आप ही काटते हैं</font></font></a></li>");
document.write("        <li><a href='489.html'><font size=4><font color=darkPurple><b>489</b></font> - <font color=darkBlue>﻿जो शील के द्वारा आत्मा शोभा पाता है उसको दृष्टान्त द्वारा दिखाते हैं</font></font></a></li>");
document.write("        <li><a href='490.html'><font size=4><font color=darkPurple><b>490</b></font> - <font color=darkGreen>﻿जो शीलवान पुरुष हैं वे ही मोक्ष को प्राप्त करते हैं</font></font></a></li>");
document.write("        <li><a href='491.html'><font size=4><font color=darkPurple><b>491</b></font> - <font color=darkBlue>﻿शील के बिना ज्ञान ही से मोक्ष नहीं है, इसका उदाहरण</font></font></a></li>");
document.write("        <li><a href='492.html'><font size=4><font color=darkPurple><b>492</b></font> - <font color=darkGreen>﻿शील के बिना ज्ञान से ही भाव की शुद्धता नहीं होती है</font></font></a></li>");
document.write("        <li><a href='493.html'><font size=4><font color=darkPurple><b>493</b></font> - <font color=darkBlue>﻿यदि नरक में भी शील हो जाय और विषयों में विरक्त हो जाय तो वहाँ से निकलकर तीर्थंकर पद को प्राप्त होता है</font></font></a></li>");
document.write("        <li><a href='494.html'><font size=4><font color=darkPurple><b>494</b></font> - <font color=darkGreen>﻿इस कथन का संकोच करते हैं</font></font></a></li>");
document.write("        <li><a href='495.html'><font size=4><font color=darkPurple><b>495</b></font> - <font color=darkBlue>﻿इस शील से निर्वाण होता है उसका बहुतप्रकार से वर्णन</font></font></a></li>");
document.write("        <li><a href='496.html'><font size=4><font color=darkPurple><b>496</b></font> - <font color=darkGreen>﻿ऐसे अष्टकर्मों को जिनने दग्ध किये वे सिद्ध हुए हैं</font></font></a></li>");
document.write("        <li><a href='497.html'><font size=4><font color=darkPurple><b>497</b></font> - <font color=darkBlue>﻿जो लावण्य और शीलयुक्त हैं वे मुनि प्रशंसा के योग्य होते हैं</font></font></a></li>");
document.write("        <li><a href='498.html'><font size=4><font color=darkPurple><b>498</b></font> - <font color=darkGreen>﻿जो ऐसा हो वह जिनमार्ग में रत्नत्रय की प्राप्तिरूप बोधि को प्राप्त होता है</font></font></a></li>");
document.write("        <li><a href='499.html'><font size=4><font color=darkPurple><b>499</b></font> - <font color=darkBlue>﻿यह प्राप्ति जिनवचन से होती है</font></font></a></li>");
document.write("        <li><a href='500.html'><font size=4><font color=darkPurple><b>500</b></font> - <font color=darkGreen>﻿अंतसमय में सल्लेखना कही है, उसमें दर्शन ज्ञान चारित्र तप इन चार आराधना का उपदेश है</font></font></a></li>");
document.write("        <li><a href='501.html'><font size=4><font color=darkPurple><b>501</b></font> - <font color=darkBlue>﻿ज्ञान से सर्वसिद्धि है यह सर्वजन प्रसिद्ध है वह ज्ञान तो ऐसा हो</font></font></a></li>");
document.write("</ul></div>");
