#!/bin/sh

#export dbDir=$(echo $PWD | perl -pe 's/(.*jaindb-dev).*/$1/g')
export dbDir=$(cd ../../.. && echo $PWD)
echo "DB Dir $dbDir"
. $dbDir/others/collaborate/shastra/common.sh
myHtml=$dbDir/index.html

## ---- Header -----
createHeader './'

cat << EOF >> $myHtml
<br><br>
  <div class=myCenter>जो ऐसा मानता है कि मैं दूसरों को दु:खी या सुखी करता हूँ, वह वस्तुत: अज्ञानी है। ज्ञानी ऐसा कभी नहीं मानते। -- कुन्दकुंदाचार्य </div><br><br>
  <div class=myBold>एक द्रव्य के द्वारा दोनों द्रव्यों का परिणमन किया जा रहा है, ऐसा मुझे प्रतिभासित मत होवे -- अमृतचंद्राचार्य</div><br><br>
  <div class=myCenter>यहाँ प्रत्येक जीव अपने—अपने कर्मफल को अकेला ही भोगता है। ऐसी स्थिति में यहाँ कौन किसका स्वजन है और कौन किसका परजन ?</div><br><br>
  <div class=myBold>धन, यौवन और जीवन को जल के बुलबुले के समान देखते हुए भी मनुष्य उन्हें नित्य मानता है, यह बड़ा आश्चर्य है। मोह का माहात्म्य अति बलवान है।</div><br><br>
  <div class=myCenter>इसी ध्‍यान से दिव्‍य चिंतामणि मिल सकता है, इसी से खली के टुकड़े भी मिल सकते हैं । जब कि ध्‍यान के द्वारा दोनों मिल सकते हैं, तब विवेकी लोग किस ओर आदरबुद्धि करेंगे ?</div>

  <!--div data-role="footer" data-position="fixed" data-fullscreen="true">
    <div align=right>nikkyjain@gmail.com</div>
  </div-->
</div>
</body>
</html>
EOF
