#!/bin/sh

#export dbDir=$(echo $PWD | perl -pe 's/(.*jaindb-dev).*/$1/g')
export dbDir=$(cd ../../.. && echo $PWD)
echo "DB Dir $dbDir"
. $dbDir/others/collaborate/shastra/common.sh
myHtml=$dbDir/index.html
myJs=$dbDir/js/myMobile.js

## ---- Header -----
createHeader './'

cat << EOF >> $myHtml
<br><br>
  <div class=myCenter>जो ऐसा मानता है कि मैं दूसरों को दु:खी या सुखी करता हूँ, वह वस्तुत: अज्ञानी है। ज्ञानी ऐसा कभी नहीं मानते। -- कुन्दकुंदाचार्य </div><br><br>
  <div class=myBold>एक द्रव्य के द्वारा दोनों द्रव्यों का परिणमन किया जा रहा है, ऐसा मुझे प्रतिभासित मत होवे -- अमृतचंद्राचार्य</div><br><br>
  <div class=myCenter>यहाँ प्रत्येक जीव अपने—अपने कर्मफल को अकेला ही भोगता है। ऐसी स्थिति में यहाँ कौन किसका स्वजन है और कौन किसका परजन ?</div><br><br>
  <div class=myBold>धन, यौवन और जीवन को जल के बुलबुले के समान देखते हुए भी मनुष्य उन्हें नित्य मानता है, यह बड़ा आश्चर्य है। मोह का माहात्म्य अति बलवान है।</div><br><br>
  <div class=myCenter>इसी ध्‍यान से दिव्‍य चिंतामणि मिल सकता है, इसी से खली के टुकड़े भी मिल सकते हैं । जब कि ध्‍यान के द्वारा दोनों मिल सकते हैं, तब विवेकी लोग किस ओर आदरबुद्धि करेंगे ?</div>

  <!--div data-role="footer" data-position="fixed" data-fullscreen="true">
    <div align=right>nikkyjain@gmail.com</div>
  </div-->
</div>
</body>
</html>
EOF

cat << EOF > $myJs

var myAudioFIles = [];

EOF

OIFS="$IFS"
IFS=$'\n'
declare -a myAudioFIles=()
for audio in $(find $dbDir/jainDataBase/bhajans/. -name '*.mp3')
do
  myAudioFile=$(echo $audio | perl -pe 's|.*?jainData|.|')
  echo "myAudioFIles.push(relPath+'$myAudioFile');" >> $myJs
done
for audio in $(find $dbDir/jainDataBase/poojas/. -name '*.mp3')
do
  myAudioFile=$(echo $audio | perl -pe 's|.*?jainData|.|')
  echo "myAudioFIles.push(relPath+'$myAudioFile');" >> $myJs
done
IFS="$OIFS"

cat << EOF >> $myJs

// Shuffle Array
function shuffle(array) {
    for (var i = array.length - 1; i > 0; i--) {
        var j = Math.floor(Math.random() * (i + 1));
        var temp = array[i];
        array[i] = array[j];
        array[j] = temp;
    }
}

\$(document).on( 'pagecontainershow', function(){
    //    // Swip Panel Code
    //    //\$( document ).on( "swipeleft swiperight", "#demo-page", function( e ) {
    //    \$( document ).on( "swiperight", "#demo-page", function( e ) {
    //        // We check if there is no open panel on the page because otherwise
    //        // a swipe to close the left panel would also open the right panel (and v.v.).
    //        // We do this by checking the data that the framework stores on the page element (panel: open).
    //        if ( \$( ".ui-page-active" ).jqmData( "panel" ) !== "open" ) {
    //            //if ( e.type === "swipeleft" ) {
    //            //    \$( "#right-panel" ).panel( "open" );
    //            //} else if ( e.type === "swiperight" ) {
    //            if ( e.type === "swiperight" ) {
    //                \$( "#leftPanel" ).panel( "open" );
    //            }
    //        }
    //    });
    var myAudio;
    var myAudioCntr=0;
    if(myAudioFIles.length>0) {
      \$('#myRadioIconDiv').show();
    }

    \$('#myRadioNextId').click(function() {
        if (myAudio) {
            myAudio.pause();
            myAudioCntr++;
            myAudio.setAttribute('src',myAudioFIles[myAudioCntr]);
            myAudio.play();
        }
    })

    \$('#myRadioId').click(function() {
        if(myAudioFIles.length==0) {
            alert("No Audio Files Detected");
        } else {
          shuffle(myAudioFIles);
          if (myAudio) {
              myAudioCntr=0;
              myAudio.pause();
              myAudio.remove();
              myAudio=null;
          } else {
              myAudio = document.createElement("AUDIO");
              myAudio.setAttribute('src',myAudioFIles[0]);
              myAudio.setAttribute('controls', 'controls');
              \$('#myRadio').html(myAudio);
              playAudio();
          }
      }
    });

    function playAudio() {
        myAudio.setAttribute('src',myAudioFIles[myAudioCntr]);
        myAudio.play();
        myAudio.addEventListener('ended', function() {
            myAudioCntr++;
            playAudio();
        });
    }
})

EOF
