#!/bin/sh

#export dbDir=$(echo $PWD | perl -pe 's/(.*jaindb-dev).*/$1/g')
export dbDir=$(cd ../../.. && echo $PWD)
echo "DB Dir $dbDir"
. $dbDir/others/collaborate/shastra/common.sh
myjsFile=myMobile.js
jsFile=$dbDir/js/$myjsFile
for category in $(ls -d $dbDir/jainDataBase/bhajans/*/)
do
    myCntr=1
    OIFS="$IFS"
    IFS=$'\n'
    [ ! -d $category/main ] && continue
    for bhajan in $(ls $category/main/*)
    do
      mkdir -p $category/html
      myBhajanName=bhajan-$myCntr
      myHtml=$category/html/${myBhajanName}.html
      ## ---- Header -----
      createHeader $myHtml '../../../../'
      ## ---- Bhajan Div -----
      createList 'bhajan' $dbDir/jainDataBase/bhajans $myHtml 
      ## ---- Pooja Div -----
      createList 'pooja'  $dbDir/others/collaborate/poojas  $myHtml
      ## ---- Granth Div -----
      createList 'granth'  $dbDir/others/collaborate/shastra  $myHtml
      ## ---- Shastra Div -----
      createList 'shastra'  $dbDir/others/collaborate/shastra  $myHtml
      ## ---- Granth Div -----
      createList 'granth'  $dbDir/others/collaborate/shastra  $myHtml
      ## ---- Misc Div ----
      createMiscList $myHtml '../../../../'


      echo "<br><div class=main>$(basename $bhajan | perl -pe 's/.txt//g')<br>" >> $myHtml
      audioFileName=$(basename $bhajan | perl -pe 's/\.txt/.mp3/g')
      if [ -f $category/audio/$audioFileName ]; then
        cat <<EOF >> $myHtml
        <audio controls>
            <source src="../audio/$audioFileName" type="audio/mpeg">
        </audio>
EOF
      fi
      c="$(cat $bhajan)"
      c=$(echo "$c" | perl -pe 's/\n/<br>/g')
      echo "<br><div class=pooja>$c" >>  $myHtml
      echo "</div></body></html>" >> $myHtml
      myCntr=$(($myCntr+1))
    done
    echo "Bhajan Category $(basename $category) Done"
done
