#!/bin/sh

#export dbDir=$(echo $PWD | perl -pe 's/(.*jaindb-dev).*/$1/g')
export dbDir=$(cd ../../.. && echo $PWD)
echo "DB Dir $dbDir"
. $dbDir/others/collaborate/shastra/common.sh
for group in $(ls -d $dbDir/jainDataBase/bhajans/*/)
do
    myCntr=1
    OIFS="$IFS"
    IFS=$'\n'
    [ ! -d $group/main ] && continue
    for bhajan in $(ls $group/main/*)
    do
      mkdir -p $group/html
      myBhajanName=bhajan-$myCntr
      myHtml=$group/html/${myBhajanName}.html
      if [ "$headerCreated" = "" ]; then
        ## ---- Header -----
        createHeader '../../../../'
        headerCreated=$(cat $myHtml)
      else
        echo "$headerCreated" > $myHtml
      fi


      echo "<br><div class=main>$(basename $bhajan | perl -pe 's/.txt//g')<br></div>" >> $myHtml
      audioFileName=$(basename $bhajan | perl -pe 's/\.txt/.mp3/g')
      if [ -f $group/audio/$audioFileName ]; then
        cat <<EOF >> $myHtml
        <audio controls>
            <source src="../audio/$audioFileName" type="audio/mpeg">
        </audio>
EOF
      fi
      c="$(cat $bhajan)"
      c=$(echo "$c" | perl -pe 's/\n/<br>/g')
      echo "<br>    <div class=pooja>$c" >>  $myHtml
      echo "  </div></div></body></html>" >> $myHtml
      myCntr=$(($myCntr+1))
    done
    echo "Bhajan group $(basename $group) Done"
done
