#!/bin/sh


#export dbDir=$(echo $PWD | perl -pe 's/(.*jaindb-dev).*/$1/g')
export dbDir=$(cd ../../.. && echo $PWD)
echo "DB Dir $dbDir"
. $dbDir/others/collaborate/shastra/common.sh
myjsFile=myMobile.js
jsFile=$dbDir/js/$myjsFile
for group in $(ls -d $dbDir/others/collaborate/poojas/*/)
do
    mygroup=$(basename $group)
    OIFS="$IFS"
    IFS=$'\n'
    for pooja in $(ls -d $group/*/)
    do
      myPooja=$(basename $pooja)
      myInDir=$dbDir/others/collaborate/poojas/$mygroup/$myPooja
      myOutDir=$dbDir/jainDataBase/poojas/$mygroup/$myPooja/html
      myHtml=$myOutDir/index.html
      echo $(dirname $myHtml)
      mkdir -p $(dirname $myHtml)
      if [ "$headerCreated" = "" ]; then
        ## ---- Header -----
        createHeader $myHtml '../../../../../'
        ## ---- Bhajan Div -----
        createBhajan '../../../../../'
        ## ---- Pooja Div -----
        createPooja '../../../../../'
        ## ---- Granth Div -----
        createGranth '../../../../../' 'teeka'
        ## ---- Shastra Div -----
        createGranth '../../../../../' 'shastra'
        ## ---- Misc Div ----
        createMiscList $myHtml '../../../../../'
        headerCreated=$(cat $myHtml)
      else
        echo "$headerCreated" > $myHtml
      fi

      echo "<div align=center><h1><font color=darkBlue>$(basename $pooja | perl -pe 's/.txt//g' | perl -pe 's/.*_//')</font></h1>" >> $myHtml
      audioFileName=$(basename $pooja | perl -pe 's/\.txt/.mp3/g')
      if [ -f $myOutDir/audio/$audioFileName ]; then
        cat <<EOF >> $myHtml
        <div><audio controls>
          <source src="../audio/$audioFileName" type="audio/mpeg">
        Your browser does not support the audio element.
        </audio><br><br><div>
EOF
      fi
      for cFile in $(ls $pooja/main/*)
      do
        curFile=$myInDir/main/$(basename $cFile)
        [ ! -f "$curFile" ] && echo "Didnt find $curFile" && exit 1
        curFile=$myInDir/title/$(basename $cFile)
        if [ -f $curFile ]; then
          echo "<div class=title>" >> $myHtml 
          cat $curFile >>  $myHtml 
          echo "</div>" >> $myHtml
        fi
        curFile=$myInDir/main/$(basename $cFile)
        echo "<div class=pooja>" >> $myHtml 
        c="$(cat $curFile)"
        c=$(echo "$c" | perl -pe 's/\n/<br>/g')
        c=$(echo "$c" | perl -pe 's/\n/<br>/g')
        c=$(echo "$c" | perl -pe 's/ॐ ह्रीं/<span class=om>ॐ ह्रीं/g')
        c=$(echo "$c" | perl -pe 's/निर्वपामीति स्वाहा/निर्वपामीति स्वाहा<\/span>/g')
        c=$(echo "$c" | perl -pe 's/संवौषट् आह्वाननं/संवौषट् आह्वाननं<\/span>/g')
        c=$(echo "$c" | perl -pe 's/ठः स्थापनं/ठः स्थापनं<\/span>/g')
        c=$(echo "$c" | perl -pe 's/वषट् सन्निधि करणं/वषट् सन्निधि करणं<\/span>/g')
        echo $c >>  $myHtml
        echo "</div>" >> $myHtml
        curFile=$myInDir/arth/$(basename $cFile)
        if [ -f $curFile ]; then
          c="$(cat $curFile)"
          echo "<div class=poojarth><font color=black>अन्वयार्थ : </font>$c</div><br>" >>  $myHtml
        fi
      done
      echo "</div></body></html>" >> $myHtml
    done
    echo "Pooja group $(basename $group) Done"
done
