#!/bin/sh

curDir=$PWD
convert=
[ "$1" = "-c" ] && convert="-c"
curCntr=1

indxFile="$curDir/goldenIndex.txt"
txtFile="$curDir/goldenTxt.txt"

function readDir {
  echo "$curObj" >> $txtFile
  while read file; do
    file=$(echo "$file" | sed -e 's/.txt//' | tr -d '\r')
    #echo "$file" >> $indxFile
    echo >> $txtFile
    cat "main/$file.txt" | sed 's/^\xEF\xBB\xBF//' >> $txtFile
	if [ -e bottom/$file.txt ]; then
	  echo >> $txtFile
      cat "bottom/$file.txt" | sed 's/^\xEF\xBB\xBF/अर्थ : /' >> $txtFile
	fi
    curCntr=$((curCntr+1))
  done < "index.txt"
}

/bin/rm -f $indxFile $txtFile
while read oDir; do
  oDir=$(echo "$oDir" | tr -d '\r')
  cd $curDir/$oDir
  if [ -d main ]; then
    echo $(echo "$oDir##" | sed -e 's/.*-/##/') >> $indxFile
	readDir
  else
    while read iDir; do
      iDir=$(echo "$iDir" | tr -d '\r')
      echo $(echo "$iDir" | sed -e 's/.*_//') >> $indxFile
	  curObj=$(echo "$iDir" | sed -e 's/.*_//')
      cd $curDir/$oDir/$iDir
      if [ -d main ]; then
        readDir
      else
        while read jDir; do
          jDir=$(echo "$jDir" | tr -d '\r')
          cd $curDir/$oDir/$iDir/$jDir
          readDir
        done < "index.txt"
        cd $curDir/$oDir
      fi
      cd $curDir
    done < "index.txt"
  fi
done < "index.txt"

unix2dos $indxFile
unix2dos $txtFile
echo "Processed $curCntr Files"
