document.write("<div id=अमृतचंद्राचार्य class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='001.html'><font size=4><br><font size=5 color=black><b>﻿मंगलाचरण </b></font><br><br><font color=darkPurple><b>001</b></font> - <font color=darkBlue>﻿सिद्धों को नमस्कार</font></font></a></li>");
document.write("        <li><a href='002.html'><font size=4><br><font size=5 color=black><b>﻿पीठिका </b></font><br><br><font color=darkPurple><b>002</b></font> - <font color=darkGreen>﻿स्वसमय और परसमय का लक्षण </font></font></a></li>");
document.write("        <li><a href='003.html'><font size=4><font color=darkPurple><b>003</b></font> - <font color=darkBlue>﻿'समय' की सुन्दरता</font></font></a></li>");
document.write("        <li><a href='004.html'><font size=4><font color=darkPurple><b>004</b></font> - <font color=darkGreen>﻿एकत्व की दुर्लभता</font></font></a></li>");
document.write("        <li><a href='005.html'><font size=4><font color=darkPurple><b>005</b></font> - <font color=darkBlue>﻿आचार्य की प्रतिज्ञा</font></font></a></li>");
document.write("        <li><a href='006.html'><font size=4><font color=darkPurple><b>006</b></font> - <font color=darkGreen>﻿शुद्धात्मा का स्वरूप</font></font></a></li>");
document.write("        <li><a href='007.html'><font size=4><font color=darkPurple><b>007</b></font> - <font color=darkBlue>﻿ज्ञानी आत्मा शुद्ध ज्ञायक है</font></font></a></li>");
document.write("        <li><a href='008.html'><font size=4><font color=darkPurple><b>008</b></font> - <font color=darkGreen>﻿व्यवहार की आवश्यकता</font></font></a></li>");
document.write("        <li><a href='009-010.html'><font size=4><font color=darkPurple><b>009-010</b></font> - <font color=darkBlue>﻿श्रुतकेवली</font></font></a></li>");
document.write("        <li><a href='013.html'><font size=4><br><font size=5 color=black><b>﻿नव-पदार्थ अधिकार </b></font><br><br><font color=darkPurple><b>011</b></font> - <font color=darkGreen>﻿निश्चयनय भूतार्थ है और व्यवहार नय अभूतार्थ है</font></font></a></li>");
document.write("        <li><a href='014.html'><font size=4><br><font size=5 color=black><b>﻿जीव अधिकार </b></font><br><br><font color=darkPurple><b>012</b></font> - <font color=darkBlue>﻿व्यवहार नय भी प्रयोजनवान है</font></font></a></li>");
document.write("        <li><a href='015.html'><font size=4><font color=darkPurple><b>013</b></font> - <font color=darkGreen>﻿शुद्धनय से जानना सम्यक्त्व है</font></font></a></li>");
document.write("        <li><a href='016.html'><font size=4><font color=darkPurple><b>014</b></font> - <font color=darkBlue>﻿शुद्धनय का लक्षण</font></font></a></li>");
document.write("        <li><a href='017.html'><font size=4><font color=darkPurple><b>015</b></font> - <font color=darkGreen>﻿जो आत्मा को देखता है वही जिनशासन को जानता है</font></font></a></li>");
document.write("        <li><a href='019.html'><font size=4><font color=darkPurple><b>016</b></font> - <font color=darkBlue>﻿रत्नत्रय ही आत्मा है</font></font></a></li>");
document.write("        <li><a href='020-021.html'><font size=4><font color=darkPurple><b>017-018</b></font> - <font color=darkGreen>﻿रत्नत्रय के सेवन का क्रम</font></font></a></li>");
document.write("        <li><a href='022.html'><font size=4><font color=darkPurple><b>019</b></font> - <font color=darkBlue>﻿आत्मा कब तक अज्ञानी रहता है?</font></font></a></li>");
document.write("        <li><a href='025-026-027.html'><font size=4><font color=darkPurple><b>020-021-022</b></font> - <font color=darkGreen>﻿अप्रतिबुद्ध - पर पदार्थ में अहंकार / ममकार</font></font></a></li>");
document.write("        <li><a href='028-029-030.html'><font size=4><font color=darkPurple><b>023-024-025</b></font> - <font color=darkBlue>﻿पर पदार्थ को जीव का कहना ठीक नहीं - तर्क</font></font></a></li>");
document.write("        <li><a href='031.html'><font size=4><font color=darkPurple><b>026</b></font> - <font color=darkGreen>﻿प्रश्न - आत्मा-शरीर एक नहीं तो शरीराश्रित स्तुति कैसे ? </font></font></a></li>");
document.write("        <li><a href='032.html'><font size=4><font color=darkPurple><b>027</b></font> - <font color=darkBlue>﻿व्यवहार से जीव और शरीर एक, निश्चय से नहीं </font></font></a></li>");
document.write("        <li><a href='033-034.html'><font size=4><font color=darkPurple><b>028-029</b></font> - <font color=darkGreen>﻿व्यवहार स्तुति निश्चय स्तुति नहीं</font></font></a></li>");
document.write("        <li><a href='035.html'><font size=4><font color=darkPurple><b>030</b></font> - <font color=darkBlue>﻿दृष्टांत - नगर का वर्णन राजा का वर्णन नहीं</font></font></a></li>");
document.write("        <li><a href='036.html'><font size=4><font color=darkPurple><b>031</b></font> - <font color=darkGreen>﻿निश्चय स्तुति - जितेन्द्रिय</font></font></a></li>");
document.write("        <li><a href='037.html'><font size=4><font color=darkPurple><b>032</b></font> - <font color=darkBlue>﻿निश्चय स्तुति - जितमोह</font></font></a></li>");
document.write("        <li><a href='038.html'><font size=4><font color=darkPurple><b>033</b></font> - <font color=darkGreen>﻿निश्चय स्तुति - क्षीणमोह</font></font></a></li>");
document.write("        <li><a href='039-040.html'><font size=4><font color=darkPurple><b>034-035</b></font> - <font color=darkBlue>﻿प्रतिबुद्ध द्वारा परभावों का त्याग - प्रत्याख्यान</font></font></a></li>");
document.write("        <li><a href='041.html'><font size=4><font color=darkPurple><b>036</b></font> - <font color=darkGreen>﻿मोह से निर्मम</font></font></a></li>");
document.write("        <li><a href='042.html'><font size=4><font color=darkPurple><b>037</b></font> - <font color=darkBlue>﻿धर्मादि ज्ञेय पदार्थ से निर्मम</font></font></a></li>");
document.write("        <li><a href='043.html'><font size=4><font color=darkPurple><b>038</b></font> - <font color=darkGreen>﻿मैं एक शुद्ध दर्शन-ज्ञानमयी</font></font></a></li>");
document.write("        <li><a href='044-048.html'><font size=4><br><font size=5 color=black><b>﻿अजीव अधिकार </b></font><br><br><font color=darkPurple><b>039-043</b></font> - <font color=darkBlue>﻿जीव-अजीव में एकता - मिथ्या-मत</font></font></a></li>");
document.write("        <li><a href='049.html'><font size=4><font color=darkPurple><b>044</b></font> - <font color=darkGreen>﻿जीव-अजीव में भिन्नता - मिथ्या-मत खण्डन</font></font></a></li>");
document.write("        <li><a href='050.html'><font size=4><font color=darkPurple><b>045</b></font> - <font color=darkBlue>﻿आठों कर्मों का फल -- अध्यवसान</font></font></a></li>");
document.write("        <li><a href='051.html'><font size=4><font color=darkPurple><b>046</b></font> - <font color=darkGreen>﻿अध्यवसान-भाव जीव है - व्यवहार  </font></font></a></li>");
document.write("        <li><a href='052-053.html'><font size=4><font color=darkPurple><b>047-048</b></font> - <font color=darkBlue>﻿इस व्यवहार को दृष्टांत द्वारा समझाते हैं</font></font></a></li>");
document.write("        <li><a href='054.html'><font size=4><font color=darkPurple><b>049</b></font> - <font color=darkGreen>﻿शुद्ध जीव कैसा होता है?</font></font></a></li>");
document.write("        <li><a href='055-060.html'><font size=4><font color=darkPurple><b>050-055</b></font> - <font color=darkBlue>﻿शुद्ध जीव कैसा नहीं होता है?</font></font></a></li>");
document.write("        <li><a href='061.html'><font size=4><font color=darkPurple><b>056</b></font> - <font color=darkGreen>﻿व्यवहार से वर्णादि भाव जीव के, निश्चय से नहीं</font></font></a></li>");
document.write("        <li><a href='062.html'><font size=4><font color=darkPurple><b>057</b></font> - <font color=darkBlue>﻿जीव का वर्णादि के साथ संयोग सम्बन्ध</font></font></a></li>");
document.write("        <li><a href='063-064-065.html'><font size=4><font color=darkPurple><b>058-059-060</b></font> - <font color=darkGreen>﻿दृष्टांत द्वारा सम्बन्ध को बतलाते हैं</font></font></a></li>");
document.write("        <li><a href='066.html'><font size=4><font color=darkPurple><b>061</b></font> - <font color=darkBlue>﻿वर्णादि भाव के साथ जीव का तादात्म्य नहीं</font></font></a></li>");
document.write("        <li><a href='067.html'><font size=4><font color=darkPurple><b>062</b></font> - <font color=darkGreen>﻿जीव का वर्णादि से तादात्म्य में दोष</font></font></a></li>");
document.write("        <li><a href='068-069.html'><font size=4><font color=darkPurple><b>063-064</b></font> - <font color=darkBlue>﻿संसार अवस्था में जीव के वर्णादि से तादात्म्य में दोष</font></font></a></li>");
document.write("        <li><a href='070-071.html'><font size=4><font color=darkPurple><b>065-066</b></font> - <font color=darkGreen>﻿अत: नाम-कर्म का उदय जीव नहीं है</font></font></a></li>");
document.write("        <li><a href='072.html'><font size=4><font color=darkPurple><b>067</b></font> - <font color=darkBlue>﻿देह को जीव कहना व्यवहार</font></font></a></li>");
document.write("        <li><a href='073.html'><font size=4><font color=darkPurple><b>068</b></font> - <font color=darkGreen>﻿अन्तरंग गुणस्थानादि भी जीव नहीं</font></font></a></li>");
document.write("        <li><a href='074-075.html'><font size=4><br><font size=5 color=black><b>﻿कर्त्ता-कर्म अधिकार </b></font><br><br><font color=darkPurple><b>069-070</b></font> - <font color=darkBlue>﻿आस्रव और जीव का भेद ना जानना - अप्रतिबुद्ध / अज्ञानी</font></font></a></li>");
document.write("        <li><a href='076.html'><font size=4><font color=darkPurple><b>071</b></font> - <font color=darkGreen>﻿अब कर्त्ता-कर्म रूप प्रवृत्ति की निवृत्ति किस प्रकार होती है उसे कहते हैं --</font></font></a></li>");
document.write("        <li><a href='077.html'><font size=4><font color=darkPurple><b>072</b></font> - <font color=darkBlue>﻿ज्ञानी निर्बंध कैसे होता है ?</font></font></a></li>");
document.write("        <li><a href='078.html'><font size=4><font color=darkPurple><b>073</b></font> - <font color=darkGreen>﻿आस्रवों से निवृत्ति का उपाय  </font></font></a></li>");
document.write("        <li><a href='079.html'><font size=4><font color=darkPurple><b>074</b></font> - <font color=darkBlue>﻿ज्ञान और आस्रवों से निवृत्ति का एक काल  </font></font></a></li>");
document.write("        <li><a href='080.html'><font size=4><font color=darkPurple><b>075</b></font> - <font color=darkGreen>﻿ज्ञानी की पहचान</font></font></a></li>");
document.write("        <li><a href='082.html'><font size=4><font color=darkPurple><b>076</b></font> - <font color=darkBlue>﻿कर्मों को जानते हुए इस जीव का पुद्गल के साथ अतादात्म्य</font></font></a></li>");
document.write("        <li><a href='083.html'><font size=4><font color=darkPurple><b>077</b></font> - <font color=darkGreen>﻿कर्मोदय के साथ अतादात्म्य</font></font></a></li>");
document.write("        <li><a href='084.html'><font size=4><font color=darkPurple><b>078</b></font> - <font color=darkBlue>﻿ज्ञानी के कर्म-फल में कर्ता-कर्म भाव नहीं</font></font></a></li>");
document.write("        <li><a href='085.html'><font size=4><font color=darkPurple><b>079</b></font> - <font color=darkGreen>﻿पुद्गल का भी जीव के साथ कर्ता-कर्मभाव नहीं</font></font></a></li>");
document.write("        <li><a href='086-088.html'><font size=4><font color=darkPurple><b>080-082</b></font> - <font color=darkBlue>﻿जीव-पुद्गल के निमित्त-नैमित्तिक संबंध होने पर भी कर्ता-कर्म का अभाव</font></font></a></li>");
document.write("        <li><a href='089.html'><font size=4><font color=darkPurple><b>083</b></font> - <font color=darkGreen>﻿जीव का कर्तृत्व और भोक्तृत्व अपने परिणामों के साथ ही</font></font></a></li>");
document.write("        <li><a href='090.html'><font size=4><font color=darkPurple><b>084</b></font> - <font color=darkBlue>﻿लोक-व्यवहार ऐसा होता है</font></font></a></li>");
document.write("        <li><a href='091.html'><font size=4><font color=darkPurple><b>085</b></font> - <font color=darkGreen>﻿द्विक्रियावादियों की मान्यता दूषित</font></font></a></li>");
document.write("        <li><a href='092.html'><font size=4><font color=darkPurple><b>086</b></font> - <font color=darkBlue>﻿द्विक्रियावादी मिथ्यादृष्टि क्यों ?</font></font></a></li>");
document.write("        <li><a href='094.html'><font size=4><font color=darkPurple><b>087</b></font> - <font color=darkGreen>﻿शुद्ध-चैतन्य स्वभावी जीव में मिथ्या-दर्शनादि विकारी भाव कैसे ?</font></font></a></li>");
document.write("        <li><a href='095.html'><font size=4><font color=darkPurple><b>088</b></font> - <font color=darkBlue>﻿मिथ्यात्वादिक जीव अजीव कहे हैं वे कौन हैं ?</font></font></a></li>");
document.write("        <li><a href='096.html'><font size=4><font color=darkPurple><b>089</b></font> - <font color=darkGreen>﻿आत्म-भावों का कर्त्ता आत्मा और द्रव्य-कर्मादिमय पर-भावों का कर्ता पुद्गल</font></font></a></li>");
document.write("        <li><a href='097.html'><font size=4><font color=darkPurple><b>090</b></font> - <font color=darkBlue>﻿आत्मा के तीन-विकारी परिणामों का कर्त्तापना है</font></font></a></li>");
document.write("        <li><a href='098.html'><font size=4><font color=darkPurple><b>091</b></font> - <font color=darkGreen>﻿कर्म-वर्गणा योग्य पुद्गल-द्रव्य अपने उपादान से कर्म-रूप में परिणत होता है</font></font></a></li>");
document.write("        <li><a href='099.html'><font size=4><font color=darkPurple><b>092</b></font> - <font color=darkBlue>﻿वीतराग-स्वसंवेदन-ज्ञान के नहीं होने से नूतन कर्म बंध</font></font></a></li>");
document.write("        <li><a href='100.html'><font size=4><font color=darkPurple><b>093</b></font> - <font color=darkGreen>﻿ज्ञान से कर्मों का बंध नहीं होता</font></font></a></li>");
document.write("        <li><a href='101-102.html'><font size=4><font color=darkPurple><b>094-095</b></font> - <font color=darkBlue>﻿अज्ञान से ही नूतन कर्मों का बंध क्यों ?</font></font></a></li>");
document.write("        <li><a href='103.html'><font size=4><font color=darkPurple><b>096</b></font> - <font color=darkGreen>﻿कर्तृत्व का मूल कारण अज्ञान</font></font></a></li>");
document.write("        <li><a href='104.html'><font size=4><font color=darkPurple><b>097</b></font> - <font color=darkBlue>﻿सम्यग्ज्ञान होने पर कर्ता-कर्म भाव नष्ट</font></font></a></li>");
document.write("        <li><a href='105-107.html'><font size=4><font color=darkPurple><b>098-100</b></font> - <font color=darkGreen>﻿पर-भावों को भी आत्मा करता है -- व्यवहारियों का मोह</font></font></a></li>");
document.write("        <li><a href='108.html'><font size=4><font color=darkPurple><b>101</b></font> - <font color=darkBlue>﻿ज्ञानी परभाव का अकर्ता, ज्ञान का ही कर्ता</font></font></a></li>");
document.write("        <li><a href='109.html'><font size=4><font color=darkPurple><b>102</b></font> - <font color=darkGreen>﻿अज्ञानी भी पर-द्रव्य के भाव का अकर्ता</font></font></a></li>");
document.write("        <li><a href='110.html'><font size=4><font color=darkPurple><b>103</b></font> - <font color=darkBlue>﻿किसी के द्वारा परभाव किया जाना अशक्य</font></font></a></li>");
document.write("        <li><a href='111.html'><font size=4><font color=darkPurple><b>104</b></font> - <font color=darkGreen>﻿आत्मा पुद्गल-कर्मों का अकर्ता क्यों ?</font></font></a></li>");
document.write("        <li><a href='112-113.html'><font size=4><font color=darkPurple><b>105-106</b></font> - <font color=darkBlue>﻿'आत्मा द्रव्य-कर्मों का कर्त्ता है' यह उपचार मात्र है</font></font></a></li>");
document.write("        <li><a href='114-115.html'><font size=4><font color=darkPurple><b>107-108</b></font> - <font color=darkGreen>﻿आत्मा पुद्गल कर्म का कर्त्ता-भोक्ता -- व्यवहार </font></font></a></li>");
document.write("        <li><a href='116-119.html'><font size=4><font color=darkPurple><b>109-112</b></font> - <font color=darkBlue>﻿पुद्गल के कथंचित परिणामी स्वभाव-पना</font></font></a></li>");
document.write("        <li><a href='120-122.html'><font size=4><font color=darkPurple><b>113-115</b></font> - <font color=darkGreen>﻿जीव और क्रोधादि प्रत्ययों का एकत्व नहीं</font></font></a></li>");
document.write("        <li><a href='123-125.html'><font size=4><font color=darkPurple><b>116-120</b></font> - <font color=darkBlue>﻿पुद्गल के कथंचित परिणामी स्वभावपना</font></font></a></li>");
document.write("        <li><a href='126-130.html'><font size=4><font color=darkPurple><b>121-125</b></font> - <font color=darkGreen>﻿जीव-द्रव्य में कथंचित परिणामित्व</font></font></a></li>");
document.write("        <li><a href='134.html'><font size=4><font color=darkPurple><b>126</b></font> - <font color=darkBlue>﻿अब उक्त अर्थ को लेकर भावों का विशेषकर कर्त्ता कहते हैं --</font></font></a></li>");
document.write("        <li><a href='135.html'><font size=4><font color=darkPurple><b>127</b></font> - <font color=darkGreen>﻿ज्ञानमय भाव से क्या होता है और अज्ञानमय भाव से क्या होता है, अब यह कहते हैं -- </font></font></a></li>");
document.write("        <li><a href='136-137.html'><font size=4><font color=darkPurple><b>128-129</b></font> - <font color=darkBlue>﻿ज्ञानी के ज्ञानमय और अज्ञानी के अज्ञानमय ही भाव कैसे ?</font></font></a></li>");
document.write("        <li><a href='138-139.html'><font size=4><font color=darkPurple><b>130-131</b></font> - <font color=darkGreen>﻿दृष्टांत</font></font></a></li>");
document.write("        <li><a href='140-144.html'><font size=4><font color=darkPurple><b>132-136</b></font> - <font color=darkBlue>﻿अज्ञानी अज्ञान-मय भावों द्वारा आगामी भाव-कर्म को प्राप्त होता है</font></font></a></li>");
document.write("        <li><a href='145-147.html'><font size=4><font color=darkPurple><b>137-140</b></font> - <font color=darkGreen>﻿जीव का परिणाम पुद्गल-द्रव्य से पृथक् ही है</font></font></a></li>");
document.write("        <li><a href='148.html'><font size=4><font color=darkPurple><b>141</b></font> - <font color=darkBlue>﻿आत्मा में कर्म बद्धस्पृष्ट है कि अबद्धस्पृष्ट ?</font></font></a></li>");
document.write("        <li><a href='149.html'><font size=4><font color=darkPurple><b>142</b></font> - <font color=darkGreen>﻿नयविभाग जानने से क्या होता है ?</font></font></a></li>");
document.write("        <li><a href='150.html'><font size=4><font color=darkPurple><b>143</b></font> - <font color=darkBlue>﻿पक्षातिक्रान्त ज्ञानी का क्या स्वरूप है ?</font></font></a></li>");
document.write("        <li><a href='151.html'><font size=4><font color=darkPurple><b>144</b></font> - <font color=darkGreen>﻿पक्ष से दूरवर्ती ही समयसार है</font></font></a></li>");
document.write("        <li><a href='152.html'><font size=4><br><font size=5 color=black><b>﻿पुण्य-पाप अधिकार </b></font><br><br><font color=darkPurple><b>145</b></font> - <font color=darkBlue>﻿शुभाशुभ कर्म के स्वभाव का वर्णन</font></font></a></li>");
document.write("        <li><a href='153.html'><font size=4><font color=darkPurple><b>146</b></font> - <font color=darkGreen>﻿शुभ-अशुभ दोनों अविशेषता से बंध के कारण</font></font></a></li>");
document.write("        <li><a href='154.html'><font size=4><font color=darkPurple><b>147</b></font> - <font color=darkBlue>﻿शुभ-अशुभ दोनों ही कर्मों का निषेध</font></font></a></li>");
document.write("        <li><a href='155-156.html'><font size=4><font color=darkPurple><b>148-149</b></font> - <font color=darkGreen>﻿दोनों कर्मों के निषेध का दृष्टान्त</font></font></a></li>");
document.write("        <li><a href='157.html'><font size=4><font color=darkPurple><b>150</b></font> - <font color=darkBlue>﻿दोनों ही प्रकार के कर्म बंध के कारण होने से निषेध्य</font></font></a></li>");
document.write("        <li><a href='158.html'><font size=4><font color=darkPurple><b>151</b></font> - <font color=darkGreen>﻿अब ज्ञान को मोक्षका कारण सिद्ध करते हैं --</font></font></a></li>");
document.write("        <li><a href='159-160.html'><font size=4><font color=darkPurple><b>152-153</b></font> - <font color=darkBlue>﻿उस ज्ञान की विधि</font></font></a></li>");
document.write("        <li><a href='161.html'><font size=4><font color=darkPurple><b>154</b></font> - <font color=darkGreen>﻿पुण्यकर्म के पक्षपाती को प्रतिबोधन</font></font></a></li>");
document.write("        <li><a href='162.html'><font size=4><font color=darkPurple><b>155</b></font> - <font color=darkBlue>﻿परमार्थस्वरूप मोक्ष का कारण दिखलाते हैं</font></font></a></li>");
document.write("        <li><a href='163.html'><font size=4><font color=darkPurple><b>156</b></font> - <font color=darkGreen>﻿परमार्थरूप मोक्ष के कारण से भिन्न कर्म का निषेध</font></font></a></li>");
document.write("        <li><a href='164-166.html'><font size=4><font color=darkPurple><b>157-159</b></font> - <font color=darkBlue>﻿मोक्ष के कारणभूत दर्शन, ज्ञान और चारित्र का आच्छादक कर्म</font></font></a></li>");
document.write("        <li><a href='167.html'><font size=4><font color=darkPurple><b>160</b></font> - <font color=darkGreen>﻿कर्म स्वयमेव बंध है</font></font></a></li>");
document.write("        <li><a href='168-170.html'><font size=4><font color=darkPurple><b>161-163</b></font> - <font color=darkBlue>﻿कर्म का मोक्ष-हेतु-तिरोधायीपना</font></font></a></li>");
document.write("        <li><a href='171-172.html'><font size=4><br><font size=5 color=black><b>﻿आस्रव अधिकार </b></font><br><br><font color=darkPurple><b>164-165</b></font> - <font color=darkGreen>﻿आस्रव का स्वरूप</font></font></a></li>");
document.write("        <li><a href='173.html'><font size=4><font color=darkPurple><b>166</b></font> - <font color=darkBlue>﻿ज्ञानी के उन आस्रवों का अभाव</font></font></a></li>");
document.write("        <li><a href='174.html'><font size=4><font color=darkPurple><b>167</b></font> - <font color=darkGreen>﻿राग, द्वेष, मोह भावों के ही आस्रवपना</font></font></a></li>");
document.write("        <li><a href='175.html'><font size=4><font color=darkPurple><b>168</b></font> - <font color=darkBlue>﻿रागादिक से न मिले ज्ञानमय भाव संभव</font></font></a></li>");
document.write("        <li><a href='176.html'><font size=4><font color=darkPurple><b>169</b></font> - <font color=darkGreen>﻿ज्ञानी के द्रव्यास्रव का अभाव</font></font></a></li>");
document.write("        <li><a href='177-178.html'><font size=4><font color=darkPurple><b>170-171</b></font> - <font color=darkBlue>﻿ज्ञानी निरास्रव किस तरह ? उत्तर</font></font></a></li>");
document.write("        <li><a href='179.html'><font size=4><font color=darkPurple><b>172</b></font> - <font color=darkGreen>﻿ज्ञान-गुण के जघन्य-भाव परिणमन के रहते ज्ञानी निरास्रव कैसे</font></font></a></li>");
document.write("        <li><a href='180-183.html'><font size=4><font color=darkPurple><b>173-176</b></font> - <font color=darkBlue>﻿सभी द्रव्यास्रव की संतति के रहने पर भी ज्ञानी नित्य ही निरास्रव कैसे</font></font></a></li>");
document.write("        <li><a href='184-185.html'><font size=4><font color=darkPurple><b>177-178</b></font> - <font color=darkGreen>﻿ज्ञानी के राग-देष-मोह नहीं अत: नवीन कर्मों का बंध नहीं</font></font></a></li>");
document.write("        <li><a href='186-187.html'><font size=4><font color=darkPurple><b>179-180</b></font> - <font color=darkBlue>﻿इसी का समर्थन दृष्टांत पूर्वक</font></font></a></li>");
document.write("        <li><a href='188-190.html'><font size=4><br><font size=5 color=black><b>﻿संवर अधिकार </b></font><br><br><font color=darkPurple><b>181-183</b></font> - <font color=darkGreen>﻿भेद-विज्ञान की अभिवन्दना</font></font></a></li>");
document.write("        <li><a href='191-192.html'><font size=4><font color=darkPurple><b>184-185</b></font> - <font color=darkBlue>﻿भेद-विज्ञान से ही शुद्धात्मा की प्राप्ति</font></font></a></li>");
document.write("        <li><a href='193.html'><font size=4><font color=darkPurple><b>186</b></font> - <font color=darkGreen>﻿शुद्ध आत्मा की प्राप्ति से ही संवर</font></font></a></li>");
document.write("        <li><a href='194-196.html'><font size=4><font color=darkPurple><b>187-189</b></font> - <font color=darkBlue>﻿संवर इस तरह से होता है</font></font></a></li>");
document.write("        <li><a href='199-201.html'><font size=4><font color=darkPurple><b>190-192</b></font> - <font color=darkGreen>﻿संवर के क्रम का व्याख्यान</font></font></a></li>");
document.write("        <li><a href='202.html'><font size=4><br><font size=5 color=black><b>﻿निर्जरा अधिकार </b></font><br><br><font color=darkPurple><b>193</b></font> - <font color=darkBlue>﻿द्रव्य-निर्जरा का स्वरूप</font></font></a></li>");
document.write("        <li><a href='203.html'><font size=4><font color=darkPurple><b>194</b></font> - <font color=darkGreen>﻿भाव-निर्जरा का भी स्वरूप</font></font></a></li>");
document.write("        <li><a href='204-205.html'><font size=4><font color=darkPurple><b>195-196</b></font> - <font color=darkBlue>﻿ज्ञान-शक्ति का वर्णन</font></font></a></li>");
document.write("        <li><a href='206.html'><font size=4><font color=darkPurple><b>197</b></font> - <font color=darkGreen>﻿दृष्टांत</font></font></a></li>");
document.write("        <li><a href='207.html'><font size=4><font color=darkPurple><b>199</b></font> - <font color=darkBlue>﻿अब कहते हैं कि सम्यग्दृष्टि अपने को और पर को विषेषरूप से इस प्रकार जानता है --</font></font></a></li>");
document.write("        <li><a href='209.html'><font size=4><font color=darkPurple><b>200</b></font> - <font color=darkGreen>﻿औपाधिक भावों की परभावता जानने का फल</font></font></a></li>");
document.write("        <li><a href='210.html'><font size=4><font color=darkPurple><b>198</b></font> - <font color=darkBlue>﻿सम्यग्दृष्टि अपने और पर के स्वभाव का ज्ञाता होता है</font></font></a></li>");
document.write("        <li><a href='211-212.html'><font size=4><font color=darkPurple><b>201-202</b></font> - <font color=darkGreen>﻿सम्यग्दृष्टि रागी कैसे नहीं होता? यदि ऐसा पूछें तो सुनिये --</font></font></a></li>");
document.write("        <li><a href='213.html'><font size=4><font color=darkPurple><b>216</b></font> - <font color=darkBlue>﻿ज्ञानी अनागत कर्मोदय के उपभोग की वांछा क्यों नहीं करता ?</font></font></a></li>");
document.write("        <li><a href='214.html'><font size=4><font color=darkPurple><b>217</b></font> - <font color=darkGreen>﻿इसका विस्तार करते हैं --</font></font></a></li>");
document.write("        <li><a href='215.html'><font size=4><font color=darkPurple><b>208</b></font> - <font color=darkBlue>﻿मिथ्यात्वादि अपध्यान मेरा परिग्रह नहीं</font></font></a></li>");
document.write("        <li><a href='216.html'><font size=4><font color=darkPurple><b>203</b></font> - <font color=darkGreen>﻿वह परामात्म-पद क्या है ? इसका समाधान आचार्य करते हैं --</font></font></a></li>");
document.write("        <li><a href='217.html'><font size=4><font color=darkPurple><b>207</b></font> - <font color=darkBlue>﻿अब पूछते हैं कि ज्ञानी पर-द्रव्य को क्यों नहीं ग्रहण करता ? उत्तर --</font></font></a></li>");
document.write("        <li><a href='218.html'><font size=4>209</font></a></li>");
document.write("        <li><a href='219.html'><font size=4><font color=darkPurple><b>206</b></font> - <font color=darkBlue>﻿और क्या ?</font></font></a></li>");
document.write("        <li><a href='220.html'><font size=4><font color=darkPurple><b>204</b></font> - <font color=darkGreen>﻿मत्यादि ज्ञान विशेष एक ज्ञान सामान्य के ही रूप</font></font></a></li>");
document.write("        <li><a href='221.html'><font size=4>205</font></a></li>");
document.write("        <li><a href='222-227.html'><font size=4><font color=darkPurple><b>210-214</b></font> - <font color=darkGreen>﻿इच्छा ही परिग्रह, जिसको इच्छा नहीं उसको परिग्रह नहीं</font></font></a></li>");
document.write("        <li><a href='228.html'><font size=4><font color=darkPurple><b>215</b></font> - <font color=darkBlue>﻿ज्ञानी के भोग का उदय वियोग बुद्धि पूर्वक, आगे भोगों की इच्छा नहीं   </font></font></a></li>");
document.write("        <li><a href='229-230.html'><font size=4><font color=darkPurple><b>218-219</b></font> - <font color=darkGreen>﻿ज्ञानी के अलिप्तता के कारण कर्म-बन्ध नहीं, और अज्ञानी के लिप्तता के कारण कर्म बन्ध</font></font></a></li>");
document.write("        <li><a href='234-238.html'><font size=4><font color=darkPurple><b>220-223</b></font> - <font color=darkBlue>﻿अब ज्ञानी के कर्म-बंध नहीं होता, उसे शंख के दृष्टांत से बतलाते हैं -- </font></font></a></li>");
document.write("        <li><a href='239-242.html'><font size=4><font color=darkPurple><b>224-227</b></font> - <font color=darkGreen>﻿आगे दृष्टांत और दार्ष्टान्त के द्वारा बतलाते हैं की सराग परिणाम से बंध और वीतराग परिणाम से मोक्ष होता है --</font></font></a></li>");
document.write("        <li><a href='243.html'><font size=4><font color=darkPurple><b>228</b></font> - <font color=darkBlue>﻿सम्यक्त्वी भय-रहित होता है </font></font></a></li>");
document.write("        <li><a href='244.html'><font size=4><font color=darkPurple><b>229</b></font> - <font color=darkGreen>﻿नि:शंकित अंग का स्वरूप</font></font></a></li>");
document.write("        <li><a href='245.html'><font size=4><font color=darkPurple><b>230</b></font> - <font color=darkBlue>﻿नि:कांक्षित अंग का स्वरूप</font></font></a></li>");
document.write("        <li><a href='246-247.html'><font size=4><font color=darkPurple><b>231-232</b></font> - <font color=darkGreen>﻿निर्वचिकित्सा व अमूढदृष्टि अंग का स्वरूप</font></font></a></li>");
document.write("        <li><a href='248-249.html'><font size=4><font color=darkPurple><b>233-234</b></font> - <font color=darkBlue>﻿उपगूहन और स्थितिकरण अंग का स्वरूप</font></font></a></li>");
document.write("        <li><a href='250-251.html'><font size=4><font color=darkPurple><b>235-236</b></font> - <font color=darkGreen>﻿वात्सल्य और प्रभावना अंग का धारी सम्यग्दृष्टि का वर्णन</font></font></a></li>");
document.write("        <li><a href='252-256.html'><font size=4><br><font size=5 color=black><b>﻿बंध अधिकार </b></font><br><br><font color=darkPurple><b>237-241</b></font> - <font color=darkBlue>﻿मिथ्या-ज्ञान श्रंगार-सहित प्रवेश कर रहा है</font></font></a></li>");
document.write("        <li><a href='257-261.html'><font size=4><font color=darkPurple><b>242-246</b></font> - <font color=darkGreen>﻿आगे वीतराग सम्यग्दृष्टि जीव के कर्म-बंध नहीं होता है, ऐसा पांच गाथाओं से बतलाते हैं --</font></font></a></li>");
document.write("        <li><a href='262-264.html'><font size=4><font color=darkPurple><b>247-252</b></font> - <font color=darkBlue>﻿हिंस्य-हिंसकभाव रूप परिणमन अज्ञानी का लक्षण ज्ञानी का नहीं</font></font></a></li>");
document.write("        <li><a href='265-268.html'><font size=4><font color=darkPurple><b>253-256</b></font> - <font color=darkGreen>﻿आगे कहते हैं कि सुख और दु:ख भी निश्चय से अपने ही कर्मों के उदय से होते हैं --</font></font></a></li>");
document.write("        <li><a href='269-270.html'><font size=4><font color=darkPurple><b>257-258</b></font> - <font color=darkBlue>﻿दूसरे को जिला, मार, सुखी कर सकना ऐसी मान्यता बहिरात्मपना</font></font></a></li>");
document.write("        <li><a href='271-273.html'><font size=4><font color=darkPurple><b>259-261</b></font> - <font color=darkGreen>﻿पूर्व के दो सूत्र में कहा हुआ मिथ्याज्ञानरूपी भाव मिथ्यादृष्टि के बंध का कारण होता है --</font></font></a></li>");
document.write("        <li><a href='274.html'><font size=4><font color=darkPurple><b>262</b></font> - <font color=darkBlue>﻿अध्यवसान से ही बंध प्राणियों को मारने अथवा न मारने से नहीं</font></font></a></li>");
document.write("        <li><a href='275-276.html'><font size=4><font color=darkPurple><b>263-264</b></font> - <font color=darkGreen>﻿अध्यवसाय ही पाप-पुण्य के बन्ध का कारण हैं, ऐसा दिखाते हैं</font></font></a></li>");
document.write("        <li><a href='277.html'><font size=4><font color=darkPurple><b>265</b></font> - <font color=darkBlue>﻿रागादिक-रूप परिणाम बंध का कारण होते हैं, बाह्य वस्तु नहीं</font></font></a></li>");
document.write("        <li><a href='278-279.html'><font size=4><font color=darkPurple><b>266-267</b></font> - <font color=darkGreen>﻿'मैं जीवों को सुखी-दुखी, बांधता-मुक्त करता हूँ', यह मानना मूढ़ता है</font></font></a></li>");
document.write("        <li><a href='285-286.html'><font size=4><font color=darkPurple><b>268-269</b></font> - <font color=darkBlue>﻿अध्यवसान से मोहित ही पर-द्रव्य से एकत्व करता है </font></font></a></li>");
document.write("        <li><a href='287.html'><font size=4><font color=darkPurple><b>270</b></font> - <font color=darkGreen>﻿तपोधन मोह भाव रहित </font></font></a></li>");
document.write("        <li><a href='289.html'><font size=4><font color=darkPurple><b>271</b></font> - <font color=darkBlue>﻿अध्यवसान के पर्यायवाची </font></font></a></li>");
document.write("        <li><a href='290.html'><font size=4><font color=darkPurple><b>272</b></font> - <font color=darkGreen>﻿निश्चयनय के द्वारा व्यवहार विकल्पों का निषेध</font></font></a></li>");
document.write("        <li><a href='291-293.html'><font size=4><font color=darkPurple><b>273-275</b></font> - <font color=darkBlue>﻿अभव्य जीव के अपने मिथ्या अभिप्राय के कारण सिद्धि नहीं </font></font></a></li>");
document.write("        <li><a href='294-295.html'><font size=4><font color=darkPurple><b>276-277</b></font> - <font color=darkGreen>﻿व्यवहार-नय व निश्चय-नय का स्वरूप</font></font></a></li>");
document.write("        <li><a href='296-297.html'><font size=4><font color=darkPurple><b>286-287</b></font> - <font color=darkBlue>﻿ज्ञानी के आहारकृत बन्ध नहीं</font></font></a></li>");
document.write("        <li><a href='300-301.html'><font size=4><font color=darkPurple><b>278-279</b></font> - <font color=darkGreen>﻿रागादि विकारी भाव कैसे बनते है ?</font></font></a></li>");
document.write("        <li><a href='302.html'><font size=4><font color=darkPurple><b>280</b></font> - <font color=darkBlue>﻿ज्ञानी जीव आस्रव का कर्त्ता नहीं होता</font></font></a></li>");
document.write("        <li><a href='303-304.html'><font size=4><font color=darkPurple><b>281-282</b></font> - <font color=darkGreen>﻿ज्ञानी के कर्म के उदय से राग द्वेष</font></font></a></li>");
document.write("        <li><a href='305-307.html'><font size=4><font color=darkPurple><b>283-285</b></font> - <font color=darkBlue>﻿ज्ञानी रागादि का अकर्ता कैसे ?</font></font></a></li>");
document.write("        <li><a href='308-310.html'><font size=4><br><font size=5 color=black><b>﻿मोक्ष अधिकार </b></font><br><br><font color=darkPurple><b>288-290</b></font> - <font color=darkGreen>﻿विशिष्ट भेद-ज्ञान के बल से बन्ध और आत्मा को पृथक् करना मोक्ष</font></font></a></li>");
document.write("        <li><a href='311-315.html'><font size=4><font color=darkPurple><b>291-293</b></font> - <font color=darkBlue>﻿इसी को और स्पष्ट करते हैं</font></font></a></li>");
document.write("        <li><a href='316.html'><font size=4><font color=darkPurple><b>294</b></font> - <font color=darkGreen>﻿आत्मा और बन्ध को भिन्न कैसे किया जाए ?</font></font></a></li>");
document.write("        <li><a href='317-319.html'><font size=4><font color=darkPurple><b>295-297</b></font> - <font color=darkBlue>﻿आत्मा और बन्ध के प्रथक्-करण कब होता है ?</font></font></a></li>");
document.write("        <li><a href='318.html'><font size=4>298</font></a></li>");
document.write("        <li><a href='320-322.html'><font size=4><font color=darkPurple><b>298-299</b></font> - <font color=darkBlue>﻿भेद-भावना -- मैं बस जानने देखने देखने वाला </font></font></a></li>");
document.write("        <li><a href='323.html'><font size=4><font color=darkPurple><b>300</b></font> - <font color=darkGreen>﻿शुद्धात्मा मात्र ज्ञाता, पर भाव मेरे नहीं </font></font></a></li>");
document.write("        <li><a href='324-326.html'><font size=4><font color=darkPurple><b>301-303</b></font> - <font color=darkBlue>﻿पर भावों को अपना मानने से बन्ध और वीतरागता से मुक्ति</font></font></a></li>");
document.write("        <li><a href='327.html'><font size=4><font color=darkPurple><b>304-305</b></font> - <font color=darkGreen>﻿अपराध शब्द का अर्थ</font></font></a></li>");
document.write("        <li><a href='328-329.html'><font size=4><font color=darkPurple><b>306-307</b></font> - <font color=darkBlue>﻿परमार्थ से प्रतिक्रमण विष-कुम्भ, अप्रतिक्रमण अमृत-कुम्भ</font></font></a></li>");
document.write("        <li><a href='330-333.html'><font size=4><br><font size=5 color=black><b>﻿सर्व-विशुद्ध अधिकार </b></font><br><br><font color=darkPurple><b>308-311</b></font> - <font color=darkGreen>﻿अब यहाँ कहते हैं कि निश्चय से यह जीव कर्मों का कर्त्ता नहीं है --</font></font></a></li>");
document.write("        <li><a href='334-335.html'><font size=4><font color=darkPurple><b>312-313</b></font> - <font color=darkBlue>﻿ज्ञानावरणादि कर्म-प्रकृतियों का आत्मा के साथ जो बंध है, वह अज्ञान का ही महात्म्य है, ऐसा बताते हैं --</font></font></a></li>");
document.write("        <li><a href='336-337.html'><font size=4><font color=darkPurple><b>314-315</b></font> - <font color=darkGreen>﻿जब तक कर्मोदय से होने वाले रागादि-भाव को नहीं छोडे तब तक अज्ञानी अन्यथा ज्ञानी</font></font></a></li>");
document.write("        <li><a href='338.html'><font size=4><font color=darkPurple><b>316</b></font> - <font color=darkBlue>﻿कर्म-फल को भोगते रहना जीव का स्वभाव नहीं, अज्ञान भाव</font></font></a></li>");
document.write("        <li><a href='340-341.html'><font size=4><font color=darkPurple><b>317-318</b></font> - <font color=darkGreen>﻿अब यहाँ बताते हैं कि अज्ञानी जीव नियम से कर्मों का वेदक ही होता है --</font></font></a></li>");
document.write("        <li><a href='342-343.html'><font size=4><font color=darkPurple><b>319-320</b></font> - <font color=darkBlue>﻿अब इसी कर्तृत्व व भोक्तृत्व के अभाव का दृष्टांत पूर्वक समर्थन करते हैं --</font></font></a></li>");
document.write("        <li><a href='344-346.html'><font size=4><font color=darkPurple><b>321-323</b></font> - <font color=darkGreen>﻿अब यहाँ बताते हैं कि जो एकान्त से आत्मा को कर्ता मानते हैं उनके भी अज्ञानी लोगों के समान मोक्ष नहीं है ऐसा उपदेश करते हैं --</font></font></a></li>");
document.write("        <li><a href='347-350.html'><font size=4><font color=darkPurple><b>324-327</b></font> - <font color=darkBlue>﻿अब पूर्व-पक्ष के उत्तर में कथन करते हैं कि निश्चय से आत्मा का पुदगलद्रव्य के साथ में कर्त्ता-कर्म सम्बन्ध नहीं है, तब आत्मा कैसे कर्त्ता बनता है ?</font></font></a></li>");
document.write("        <li><a href='351-354.html'><font size=4><font color=darkPurple><b>345-348</b></font> - <font color=darkGreen>﻿जो करता है वही भोगता है -- द्रव्यार्थिक-नय और अन्य ही कर्ता है और अन्य ही भोगता -- पर्यायार्थिक-नय</font></font></a></li>");
document.write("        <li><a href='355-359.html'><font size=4><font color=darkPurple><b>328-331</b></font> - <font color=darkBlue>﻿भाव-कर्म का कर्त्ता जीव ही है</font></font></a></li>");
document.write("        <li><a href='360-372.html'><font size=4><font color=darkPurple><b>332-344</b></font> - <font color=darkGreen>﻿आत्मा सर्वथा अकर्ता नहीं है, कथंचित् कर्त्ता भी है</font></font></a></li>");
document.write("        <li><a href='373-378.html'><font size=4><font color=darkPurple><b>366-371</b></font> - <font color=darkBlue>﻿सम्यग्दृष्टियों को विषयों के प्रति राग क्यों नहीं होता</font></font></a></li>");
document.write("        <li><a href='379.html'><font size=4><font color=darkPurple><b>372</b></font> - <font color=darkGreen>﻿शब्दादि अचेतन होने से रागादिक की उत्पत्ति में नियामक कारण नहीं</font></font></a></li>");
document.write("        <li><a href='380-386.html'><font size=4><font color=darkPurple><b>349-355</b></font> - <font color=darkBlue>﻿व्यवहार से कर्त्ता और कर्म भिन्न, निश्चय से अभिन्न</font></font></a></li>");
document.write("        <li><a href='387-396.html'><font size=4><font color=darkPurple><b>356-365</b></font> - <font color=darkGreen>﻿इस निश्चय-व्यवहार कथन का दृष्टांत</font></font></a></li>");
document.write("        <li><a href='397-400.html'><font size=4><font color=darkPurple><b>383-386</b></font> - <font color=darkBlue>﻿निश्चय-प्रतिक्रमण-प्रत्याख्यान-आलोचना ही अभेद-नय से निश्चय-चारित्र</font></font></a></li>");
document.write("        <li><a href='401-410.html'><font size=4><font color=darkPurple><b>373-382</b></font> - <font color=darkGreen>﻿आगे कहते हैं कि मिथ्या-ज्ञान में परिणमन करता हुआ यह जीव पंचेन्द्रिय और मन के विषयों में राग और द्वेष करता है --</font></font></a></li>");
document.write("        <li><a href='411-413.html'><font size=4><font color=darkPurple><b>387-389</b></font> - <font color=darkBlue>﻿आगे कहते  कि मिथ्यात्व व रागादि परिणत जीव के अज्ञान-चेतना होती है वह केवल-ज्ञानादि गुणों को प्रच्छादन करने वाले कर्म-बंध को पैदा करती है --</font></font></a></li>");
document.write("        <li><a href='414-428.html'><font size=4><font color=darkPurple><b>390-404</b></font> - <font color=darkGreen>﻿अब इसी अर्थ की गाथा कहते हैं --</font></font></a></li>");
document.write("        <li><a href='429-431.html'><font size=4><font color=darkPurple><b>405-407</b></font> - <font color=darkBlue>﻿परमात्मा शुद्ध-बुद्ध-रूप एक स्वभाव-वाला है, ऐसी हालत में जब परमात्मा के देह नहीं है तो उसके आहार कैसे होगा ? यह बतलाते हैं --</font></font></a></li>");
document.write("        <li><a href='432-435.html'><font size=4><font color=darkPurple><b>408-411</b></font> - <font color=darkGreen>﻿द्रव्य-लिंग भी निश्चय से मुक्ति का कारण नहीं</font></font></a></li>");
document.write("        <li><a href='436.html'><font size=4><font color=darkPurple><b>412</b></font> - <font color=darkBlue>﻿अब आचार्य यह उपदेश करते हैं कि मोक्षार्थी जीव को शुद्धात्मानुभूति रूप लक्षण वाले निश्चय-रत्नत्रयात्मक मोक्ष-मार्ग का सेवन करना चाहिए --</font></font></a></li>");
document.write("        <li><a href='437.html'><font size=4><font color=darkPurple><b>413</b></font> - <font color=darkGreen>﻿आगे कहते हैं कि जो सहज शुद्ध परमात्मानुभूति लक्षण वाले भाव-लिंग से तो रहित हैं, किन्त द्रव्य-लिंग में ही ममता करते हैं वे आज भी समयसार को नहीं जानते --</font></font></a></li>");
document.write("        <li><a href='438.html'><font size=4><font color=darkPurple><b>414</b></font> - <font color=darkBlue>﻿मुनि-लिंग और गृहस्थ-लिंग व्यवहार से मोक्ष-मार्ग, निश्चय से कोई भी लिंग मोक्षमार्ग नहीं</font></font></a></li>");
document.write("        <li><a href='439.html'><font size=4><font color=darkPurple><b>415</b></font> - <font color=darkGreen>﻿ग्रन्थ समाप्ति और इसके पढ़ने का फल</font></font></a></li>");
document.write("</ul></div>");
document.write("<div id=जयसेनाचार्य class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='001.html'><font size=4><br><font size=5 color=black><b>﻿मंगलाचरण </b></font><br><br><font color=darkPurple><b>001</b></font> - <font color=darkBlue>﻿सिद्धों को नमस्कार</font></font></a></li>");
document.write("        <li><a href='002.html'><font size=4><br><font size=5 color=black><b>﻿पीठिका </b></font><br><br><font color=darkPurple><b>002</b></font> - <font color=darkGreen>﻿स्वसमय और परसमय का लक्षण </font></font></a></li>");
document.write("        <li><a href='003.html'><font size=4><font color=darkPurple><b>003</b></font> - <font color=darkBlue>﻿'समय' की सुन्दरता</font></font></a></li>");
document.write("        <li><a href='004.html'><font size=4><font color=darkPurple><b>004</b></font> - <font color=darkGreen>﻿एकत्व की दुर्लभता</font></font></a></li>");
document.write("        <li><a href='005.html'><font size=4><font color=darkPurple><b>005</b></font> - <font color=darkBlue>﻿आचार्य की प्रतिज्ञा</font></font></a></li>");
document.write("        <li><a href='006.html'><font size=4><font color=darkPurple><b>006</b></font> - <font color=darkGreen>﻿शुद्धात्मा का स्वरूप</font></font></a></li>");
document.write("        <li><a href='007.html'><font size=4><font color=darkPurple><b>007</b></font> - <font color=darkBlue>﻿ज्ञानी आत्मा शुद्ध ज्ञायक है</font></font></a></li>");
document.write("        <li><a href='008.html'><font size=4><font color=darkPurple><b>008</b></font> - <font color=darkGreen>﻿व्यवहार की आवश्यकता</font></font></a></li>");
document.write("        <li><a href='009-010.html'><font size=4><font color=darkPurple><b>009-010</b></font> - <font color=darkBlue>﻿श्रुतकेवली</font></font></a></li>");
document.write("        <li><a href='011.html'><font size=4><font color=darkPurple><b>011</b></font> - <font color=darkGreen>﻿आत्म-भावना की प्रेरणा</font></font></a></li>");
document.write("        <li><a href='012.html'><font size=4><font color=darkPurple><b>012</b></font> - <font color=darkBlue>﻿आत्म-भावना से शीघ्र मुक्ति</font></font></a></li>");
document.write("        <li><a href='013.html'><font size=4><br><font size=5 color=black><b>﻿नव-पदार्थ अधिकार </b></font><br><br><font color=darkPurple><b>013</b></font> - <font color=darkGreen>﻿निश्चयनय भूतार्थ है और व्यवहार नय अभूतार्थ है</font></font></a></li>");
document.write("        <li><a href='014.html'><font size=4><br><font size=5 color=black><b>﻿जीव अधिकार </b></font><br><br><font color=darkPurple><b>014</b></font> - <font color=darkBlue>﻿व्यवहार नय भी प्रयोजनवान है</font></font></a></li>");
document.write("        <li><a href='015.html'><font size=4><font color=darkPurple><b>015</b></font> - <font color=darkGreen>﻿शुद्धनय से जानना सम्यक्त्व है</font></font></a></li>");
document.write("        <li><a href='016.html'><font size=4><font color=darkPurple><b>016</b></font> - <font color=darkBlue>﻿शुद्धनय का लक्षण</font></font></a></li>");
document.write("        <li><a href='017.html'><font size=4><font color=darkPurple><b>017</b></font> - <font color=darkGreen>﻿जो आत्मा को देखता है वही जिनशासन को जानता है</font></font></a></li>");
document.write("        <li><a href='018.html'><font size=4><font color=darkPurple><b>018</b></font> - <font color=darkBlue>﻿ध्यान में केवल आत्मा</font></font></a></li>");
document.write("        <li><a href='019.html'><font size=4><font color=darkPurple><b>019</b></font> - <font color=darkGreen>﻿रत्नत्रय ही आत्मा है</font></font></a></li>");
document.write("        <li><a href='020-021.html'><font size=4><font color=darkPurple><b>020-021</b></font> - <font color=darkBlue>﻿रत्नत्रय के सेवन का क्रम</font></font></a></li>");
document.write("        <li><a href='022.html'><font size=4><font color=darkPurple><b>022</b></font> - <font color=darkGreen>﻿आत्मा कब तक अज्ञानी रहता है?</font></font></a></li>");
document.write("        <li><a href='023.html'><font size=4><font color=darkPurple><b>023</b></font> - <font color=darkBlue>﻿आत्मा के बंध मोक्ष का कारण</font></font></a></li>");
document.write("        <li><a href='024.html'><font size=4><font color=darkPurple><b>024</b></font> - <font color=darkGreen>﻿निश्चय और व्यवहार से जीव का कर्तापना </font></font></a></li>");
document.write("        <li><a href='025-026-027.html'><font size=4><font color=darkPurple><b>025-026-027</b></font> - <font color=darkBlue>﻿अप्रतिबुद्ध - पर पदार्थ में अहंकार / ममकार</font></font></a></li>");
document.write("        <li><a href='028-029-030.html'><font size=4><font color=darkPurple><b>028-029-030</b></font> - <font color=darkGreen>﻿पर पदार्थ को जीव का कहना ठीक नहीं - तर्क</font></font></a></li>");
document.write("        <li><a href='031.html'><font size=4><font color=darkPurple><b>031</b></font> - <font color=darkBlue>﻿प्रश्न - आत्मा-शरीर एक नहीं तो शरीराश्रित स्तुति कैसे ? </font></font></a></li>");
document.write("        <li><a href='032.html'><font size=4><font color=darkPurple><b>032</b></font> - <font color=darkGreen>﻿व्यवहार से जीव और शरीर एक, निश्चय से नहीं </font></font></a></li>");
document.write("        <li><a href='033-034.html'><font size=4><font color=darkPurple><b>033-034</b></font> - <font color=darkBlue>﻿व्यवहार स्तुति निश्चय स्तुति नहीं</font></font></a></li>");
document.write("        <li><a href='035.html'><font size=4><font color=darkPurple><b>035</b></font> - <font color=darkGreen>﻿दृष्टांत - नगर का वर्णन राजा का वर्णन नहीं</font></font></a></li>");
document.write("        <li><a href='036.html'><font size=4><font color=darkPurple><b>036</b></font> - <font color=darkBlue>﻿निश्चय स्तुति - जितेन्द्रिय</font></font></a></li>");
document.write("        <li><a href='037.html'><font size=4><font color=darkPurple><b>037</b></font> - <font color=darkGreen>﻿निश्चय स्तुति - जितमोह</font></font></a></li>");
document.write("        <li><a href='038.html'><font size=4><font color=darkPurple><b>038</b></font> - <font color=darkBlue>﻿निश्चय स्तुति - क्षीणमोह</font></font></a></li>");
document.write("        <li><a href='039-040.html'><font size=4><font color=darkPurple><b>039-040</b></font> - <font color=darkGreen>﻿प्रतिबुद्ध द्वारा परभावों का त्याग - प्रत्याख्यान</font></font></a></li>");
document.write("        <li><a href='041.html'><font size=4><font color=darkPurple><b>041</b></font> - <font color=darkBlue>﻿मोह से निर्मम</font></font></a></li>");
document.write("        <li><a href='042.html'><font size=4><font color=darkPurple><b>042</b></font> - <font color=darkGreen>﻿धर्मादि ज्ञेय पदार्थ से निर्मम</font></font></a></li>");
document.write("        <li><a href='043.html'><font size=4><font color=darkPurple><b>043</b></font> - <font color=darkBlue>﻿मैं एक शुद्ध दर्शन-ज्ञानमयी</font></font></a></li>");
document.write("        <li><a href='044-048.html'><font size=4><br><font size=5 color=black><b>﻿अजीव अधिकार </b></font><br><br><font color=darkPurple><b>044-048</b></font> - <font color=darkGreen>﻿जीव-अजीव में एकता - मिथ्या-मत</font></font></a></li>");
document.write("        <li><a href='049.html'><font size=4><font color=darkPurple><b>049</b></font> - <font color=darkBlue>﻿जीव-अजीव में भिन्नता - मिथ्या-मत खण्डन</font></font></a></li>");
document.write("        <li><a href='050.html'><font size=4><font color=darkPurple><b>050</b></font> - <font color=darkGreen>﻿आठों कर्मों का फल -- अध्यवसान</font></font></a></li>");
document.write("        <li><a href='051.html'><font size=4><font color=darkPurple><b>051</b></font> - <font color=darkBlue>﻿अध्यवसान-भाव जीव है - व्यवहार  </font></font></a></li>");
document.write("        <li><a href='052-053.html'><font size=4><font color=darkPurple><b>052-053</b></font> - <font color=darkGreen>﻿इस व्यवहार को दृष्टांत द्वारा समझाते हैं</font></font></a></li>");
document.write("        <li><a href='054.html'><font size=4><font color=darkPurple><b>054</b></font> - <font color=darkBlue>﻿शुद्ध जीव कैसा होता है?</font></font></a></li>");
document.write("        <li><a href='055-060.html'><font size=4><font color=darkPurple><b>055-060</b></font> - <font color=darkGreen>﻿शुद्ध जीव कैसा नहीं होता है?</font></font></a></li>");
document.write("        <li><a href='061.html'><font size=4><font color=darkPurple><b>061</b></font> - <font color=darkBlue>﻿व्यवहार से वर्णादि भाव जीव के, निश्चय से नहीं</font></font></a></li>");
document.write("        <li><a href='062.html'><font size=4><font color=darkPurple><b>062</b></font> - <font color=darkGreen>﻿जीव का वर्णादि के साथ संयोग सम्बन्ध</font></font></a></li>");
document.write("        <li><a href='063-064-065.html'><font size=4><font color=darkPurple><b>063-064-065</b></font> - <font color=darkBlue>﻿दृष्टांत द्वारा सम्बन्ध को बतलाते हैं</font></font></a></li>");
document.write("        <li><a href='066.html'><font size=4><font color=darkPurple><b>066</b></font> - <font color=darkGreen>﻿वर्णादि भाव के साथ जीव का तादात्म्य नहीं</font></font></a></li>");
document.write("        <li><a href='067.html'><font size=4><font color=darkPurple><b>067</b></font> - <font color=darkBlue>﻿जीव का वर्णादि से तादात्म्य में दोष</font></font></a></li>");
document.write("        <li><a href='068-069.html'><font size=4><font color=darkPurple><b>068-069</b></font> - <font color=darkGreen>﻿संसार अवस्था में जीव के वर्णादि से तादात्म्य में दोष</font></font></a></li>");
document.write("        <li><a href='070-071.html'><font size=4><font color=darkPurple><b>070-071</b></font> - <font color=darkBlue>﻿अत: नाम-कर्म का उदय जीव नहीं है</font></font></a></li>");
document.write("        <li><a href='072.html'><font size=4><font color=darkPurple><b>072</b></font> - <font color=darkGreen>﻿देह को जीव कहना व्यवहार</font></font></a></li>");
document.write("        <li><a href='073.html'><font size=4><font color=darkPurple><b>073</b></font> - <font color=darkBlue>﻿अन्तरंग गुणस्थानादि भी जीव नहीं</font></font></a></li>");
document.write("        <li><a href='074-075.html'><font size=4><br><font size=5 color=black><b>﻿कर्त्ता-कर्म अधिकार </b></font><br><br><font color=darkPurple><b>074-075</b></font> - <font color=darkGreen>﻿आस्रव और जीव का भेद ना जानना - अप्रतिबुद्ध / अज्ञानी</font></font></a></li>");
document.write("        <li><a href='076.html'><font size=4><font color=darkPurple><b>076</b></font> - <font color=darkBlue>﻿अब कर्त्ता-कर्म रूप प्रवृत्ति की निवृत्ति किस प्रकार होती है उसे कहते हैं --</font></font></a></li>");
document.write("        <li><a href='077.html'><font size=4><font color=darkPurple><b>077</b></font> - <font color=darkGreen>﻿ज्ञानी निर्बंध कैसे होता है ?</font></font></a></li>");
document.write("        <li><a href='078.html'><font size=4><font color=darkPurple><b>078</b></font> - <font color=darkBlue>﻿आस्रवों से निवृत्ति का उपाय  </font></font></a></li>");
document.write("        <li><a href='079.html'><font size=4><font color=darkPurple><b>079</b></font> - <font color=darkGreen>﻿ज्ञान और आस्रवों से निवृत्ति का एक काल  </font></font></a></li>");
document.write("        <li><a href='080.html'><font size=4><font color=darkPurple><b>080</b></font> - <font color=darkBlue>﻿ज्ञानी की पहचान</font></font></a></li>");
document.write("        <li><a href='081.html'><font size=4><font color=darkPurple><b>081</b></font> - <font color=darkGreen>﻿आत्मा पृण्य-पापादि परिणामों का कर्त्ता -- व्यवहार</font></font></a></li>");
document.write("        <li><a href='082.html'><font size=4><font color=darkPurple><b>082</b></font> - <font color=darkBlue>﻿कर्मों को जानते हुए इस जीव का पुद्गल के साथ अतादात्म्य</font></font></a></li>");
document.write("        <li><a href='083.html'><font size=4><font color=darkPurple><b>083</b></font> - <font color=darkGreen>﻿कर्मोदय के साथ अतादात्म्य</font></font></a></li>");
document.write("        <li><a href='084.html'><font size=4><font color=darkPurple><b>084</b></font> - <font color=darkBlue>﻿ज्ञानी के कर्म-फल में कर्ता-कर्म भाव नहीं</font></font></a></li>");
document.write("        <li><a href='085.html'><font size=4><font color=darkPurple><b>085</b></font> - <font color=darkGreen>﻿पुद्गल का भी जीव के साथ कर्ता-कर्मभाव नहीं</font></font></a></li>");
document.write("        <li><a href='086-088.html'><font size=4><font color=darkPurple><b>086-088</b></font> - <font color=darkBlue>﻿जीव-पुद्गल के निमित्त-नैमित्तिक संबंध होने पर भी कर्ता-कर्म का अभाव</font></font></a></li>");
document.write("        <li><a href='089.html'><font size=4><font color=darkPurple><b>089</b></font> - <font color=darkGreen>﻿जीव का कर्तृत्व और भोक्तृत्व अपने परिणामों के साथ ही</font></font></a></li>");
document.write("        <li><a href='090.html'><font size=4><font color=darkPurple><b>090</b></font> - <font color=darkBlue>﻿लोक-व्यवहार ऐसा होता है</font></font></a></li>");
document.write("        <li><a href='091.html'><font size=4><font color=darkPurple><b>091</b></font> - <font color=darkGreen>﻿द्विक्रियावादियों की मान्यता दूषित</font></font></a></li>");
document.write("        <li><a href='092.html'><font size=4><font color=darkPurple><b>092</b></font> - <font color=darkBlue>﻿द्विक्रियावादी मिथ्यादृष्टि क्यों ?</font></font></a></li>");
document.write("        <li><a href='093.html'><font size=4><font color=darkPurple><b>093</b></font> - <font color=darkGreen>﻿द्विक्रियावादी का विशेष व्याख्यान</font></font></a></li>");
document.write("        <li><a href='094.html'><font size=4><font color=darkPurple><b>094</b></font> - <font color=darkBlue>﻿शुद्ध-चैतन्य स्वभावी जीव में मिथ्या-दर्शनादि विकारी भाव कैसे ?</font></font></a></li>");
document.write("        <li><a href='095.html'><font size=4><font color=darkPurple><b>095</b></font> - <font color=darkGreen>﻿मिथ्यात्वादिक जीव अजीव कहे हैं वे कौन हैं ?</font></font></a></li>");
document.write("        <li><a href='096.html'><font size=4><font color=darkPurple><b>096</b></font> - <font color=darkBlue>﻿आत्म-भावों का कर्त्ता आत्मा और द्रव्य-कर्मादिमय पर-भावों का कर्ता पुद्गल</font></font></a></li>");
document.write("        <li><a href='097.html'><font size=4><font color=darkPurple><b>097</b></font> - <font color=darkGreen>﻿आत्मा के तीन-विकारी परिणामों का कर्त्तापना है</font></font></a></li>");
document.write("        <li><a href='098.html'><font size=4><font color=darkPurple><b>098</b></font> - <font color=darkBlue>﻿कर्म-वर्गणा योग्य पुद्गल-द्रव्य अपने उपादान से कर्म-रूप में परिणत होता है</font></font></a></li>");
document.write("        <li><a href='099.html'><font size=4><font color=darkPurple><b>099</b></font> - <font color=darkGreen>﻿वीतराग-स्वसंवेदन-ज्ञान के नहीं होने से नूतन कर्म बंध</font></font></a></li>");
document.write("        <li><a href='100.html'><font size=4><font color=darkPurple><b>100</b></font> - <font color=darkBlue>﻿ज्ञान से कर्मों का बंध नहीं होता</font></font></a></li>");
document.write("        <li><a href='101-102.html'><font size=4><font color=darkPurple><b>101-102</b></font> - <font color=darkGreen>﻿अज्ञान से ही नूतन कर्मों का बंध क्यों ?</font></font></a></li>");
document.write("        <li><a href='103.html'><font size=4><font color=darkPurple><b>103</b></font> - <font color=darkBlue>﻿कर्तृत्व का मूल कारण अज्ञान</font></font></a></li>");
document.write("        <li><a href='104.html'><font size=4><font color=darkPurple><b>104</b></font> - <font color=darkGreen>﻿सम्यग्ज्ञान होने पर कर्ता-कर्म भाव नष्ट</font></font></a></li>");
document.write("        <li><a href='105-107.html'><font size=4><font color=darkPurple><b>105-107</b></font> - <font color=darkBlue>﻿पर-भावों को भी आत्मा करता है -- व्यवहारियों का मोह</font></font></a></li>");
document.write("        <li><a href='108.html'><font size=4><font color=darkPurple><b>108</b></font> - <font color=darkGreen>﻿ज्ञानी परभाव का अकर्ता, ज्ञान का ही कर्ता</font></font></a></li>");
document.write("        <li><a href='109.html'><font size=4><font color=darkPurple><b>109</b></font> - <font color=darkBlue>﻿अज्ञानी भी पर-द्रव्य के भाव का अकर्ता</font></font></a></li>");
document.write("        <li><a href='110.html'><font size=4><font color=darkPurple><b>110</b></font> - <font color=darkGreen>﻿किसी के द्वारा परभाव किया जाना अशक्य</font></font></a></li>");
document.write("        <li><a href='111.html'><font size=4><font color=darkPurple><b>111</b></font> - <font color=darkBlue>﻿आत्मा पुद्गल-कर्मों का अकर्ता क्यों ?</font></font></a></li>");
document.write("        <li><a href='112-113.html'><font size=4><font color=darkPurple><b>112-113</b></font> - <font color=darkGreen>﻿'आत्मा द्रव्य-कर्मों का कर्त्ता है' यह उपचार मात्र है</font></font></a></li>");
document.write("        <li><a href='114-115.html'><font size=4><font color=darkPurple><b>114-115</b></font> - <font color=darkBlue>﻿आत्मा पुद्गल कर्म का कर्त्ता-भोक्ता -- व्यवहार </font></font></a></li>");
document.write("        <li><a href='116-119.html'><font size=4><font color=darkPurple><b>116-119</b></font> - <font color=darkGreen>﻿पुद्गल के कथंचित परिणामी स्वभाव-पना</font></font></a></li>");
document.write("        <li><a href='120-122.html'><font size=4><font color=darkPurple><b>120-122</b></font> - <font color=darkBlue>﻿जीव और क्रोधादि प्रत्ययों का एकत्व नहीं</font></font></a></li>");
document.write("        <li><a href='123-125.html'><font size=4><font color=darkPurple><b>123-125</b></font> - <font color=darkGreen>﻿पुद्गल के कथंचित परिणामी स्वभावपना</font></font></a></li>");
document.write("        <li><a href='126-130.html'><font size=4><font color=darkPurple><b>126-130</b></font> - <font color=darkBlue>﻿जीव-द्रव्य में कथंचित परिणामित्व</font></font></a></li>");
document.write("        <li><a href='131-133.html'><font size=4><font color=darkPurple><b>131-133</b></font> - <font color=darkGreen>﻿ज्ञानी-जीव ज्ञानभाव का कर्ता</font></font></a></li>");
document.write("        <li><a href='134.html'><font size=4><font color=darkPurple><b>134</b></font> - <font color=darkBlue>﻿अब उक्त अर्थ को लेकर भावों का विशेषकर कर्त्ता कहते हैं --</font></font></a></li>");
document.write("        <li><a href='135.html'><font size=4><font color=darkPurple><b>135</b></font> - <font color=darkGreen>﻿ज्ञानमय भाव से क्या होता है और अज्ञानमय भाव से क्या होता है, अब यह कहते हैं -- </font></font></a></li>");
document.write("        <li><a href='136-137.html'><font size=4><font color=darkPurple><b>136-137</b></font> - <font color=darkBlue>﻿ज्ञानी के ज्ञानमय और अज्ञानी के अज्ञानमय ही भाव कैसे ?</font></font></a></li>");
document.write("        <li><a href='138-139.html'><font size=4><font color=darkPurple><b>138-139</b></font> - <font color=darkGreen>﻿दृष्टांत</font></font></a></li>");
document.write("        <li><a href='140-144.html'><font size=4><font color=darkPurple><b>140-144</b></font> - <font color=darkBlue>﻿अज्ञानी अज्ञान-मय भावों द्वारा आगामी भाव-कर्म को प्राप्त होता है</font></font></a></li>");
document.write("        <li><a href='145-147.html'><font size=4><font color=darkPurple><b>145-147</b></font> - <font color=darkGreen>﻿जीव का परिणाम पुद्गल-द्रव्य से पृथक् ही है</font></font></a></li>");
document.write("        <li><a href='148.html'><font size=4><font color=darkPurple><b>148</b></font> - <font color=darkBlue>﻿आत्मा में कर्म बद्धस्पृष्ट है कि अबद्धस्पृष्ट ?</font></font></a></li>");
document.write("        <li><a href='149.html'><font size=4><font color=darkPurple><b>149</b></font> - <font color=darkGreen>﻿नयविभाग जानने से क्या होता है ?</font></font></a></li>");
document.write("        <li><a href='150.html'><font size=4><font color=darkPurple><b>150</b></font> - <font color=darkBlue>﻿पक्षातिक्रान्त ज्ञानी का क्या स्वरूप है ?</font></font></a></li>");
document.write("        <li><a href='151.html'><font size=4><font color=darkPurple><b>151</b></font> - <font color=darkGreen>﻿पक्ष से दूरवर्ती ही समयसार है</font></font></a></li>");
document.write("        <li><a href='152.html'><font size=4><br><font size=5 color=black><b>﻿पुण्य-पाप अधिकार </b></font><br><br><font color=darkPurple><b>152</b></font> - <font color=darkBlue>﻿शुभाशुभ कर्म के स्वभाव का वर्णन</font></font></a></li>");
document.write("        <li><a href='153.html'><font size=4><font color=darkPurple><b>153</b></font> - <font color=darkGreen>﻿शुभ-अशुभ दोनों अविशेषता से बंध के कारण</font></font></a></li>");
document.write("        <li><a href='154.html'><font size=4><font color=darkPurple><b>154</b></font> - <font color=darkBlue>﻿शुभ-अशुभ दोनों ही कर्मों का निषेध</font></font></a></li>");
document.write("        <li><a href='155-156.html'><font size=4><font color=darkPurple><b>155-156</b></font> - <font color=darkGreen>﻿दोनों कर्मों के निषेध का दृष्टान्त</font></font></a></li>");
document.write("        <li><a href='157.html'><font size=4><font color=darkPurple><b>157</b></font> - <font color=darkBlue>﻿दोनों ही प्रकार के कर्म बंध के कारण होने से निषेध्य</font></font></a></li>");
document.write("        <li><a href='158.html'><font size=4><font color=darkPurple><b>158</b></font> - <font color=darkGreen>﻿अब ज्ञान को मोक्षका कारण सिद्ध करते हैं --</font></font></a></li>");
document.write("        <li><a href='159-160.html'><font size=4><font color=darkPurple><b>159-160</b></font> - <font color=darkBlue>﻿उस ज्ञान की विधि</font></font></a></li>");
document.write("        <li><a href='161.html'><font size=4><font color=darkPurple><b>161</b></font> - <font color=darkGreen>﻿पुण्यकर्म के पक्षपाती को प्रतिबोधन</font></font></a></li>");
document.write("        <li><a href='162.html'><font size=4><font color=darkPurple><b>162</b></font> - <font color=darkBlue>﻿परमार्थस्वरूप मोक्ष का कारण दिखलाते हैं</font></font></a></li>");
document.write("        <li><a href='163.html'><font size=4><font color=darkPurple><b>163</b></font> - <font color=darkGreen>﻿परमार्थरूप मोक्ष के कारण से भिन्न कर्म का निषेध</font></font></a></li>");
document.write("        <li><a href='164-166.html'><font size=4><font color=darkPurple><b>164-166</b></font> - <font color=darkBlue>﻿मोक्ष के कारणभूत दर्शन, ज्ञान और चारित्र का आच्छादक कर्म</font></font></a></li>");
document.write("        <li><a href='167.html'><font size=4><font color=darkPurple><b>167</b></font> - <font color=darkGreen>﻿कर्म स्वयमेव बंध है</font></font></a></li>");
document.write("        <li><a href='168-170.html'><font size=4><font color=darkPurple><b>168-170</b></font> - <font color=darkBlue>﻿कर्म का मोक्ष-हेतु-तिरोधायीपना</font></font></a></li>");
document.write("        <li><a href='171-172.html'><font size=4><br><font size=5 color=black><b>﻿आस्रव अधिकार </b></font><br><br><font color=darkPurple><b>171-172</b></font> - <font color=darkGreen>﻿आस्रव का स्वरूप</font></font></a></li>");
document.write("        <li><a href='173.html'><font size=4><font color=darkPurple><b>173</b></font> - <font color=darkBlue>﻿ज्ञानी के उन आस्रवों का अभाव</font></font></a></li>");
document.write("        <li><a href='174.html'><font size=4><font color=darkPurple><b>174</b></font> - <font color=darkGreen>﻿राग, द्वेष, मोह भावों के ही आस्रवपना</font></font></a></li>");
document.write("        <li><a href='175.html'><font size=4><font color=darkPurple><b>175</b></font> - <font color=darkBlue>﻿रागादिक से न मिले ज्ञानमय भाव संभव</font></font></a></li>");
document.write("        <li><a href='176.html'><font size=4><font color=darkPurple><b>176</b></font> - <font color=darkGreen>﻿ज्ञानी के द्रव्यास्रव का अभाव</font></font></a></li>");
document.write("        <li><a href='177-178.html'><font size=4><font color=darkPurple><b>177-178</b></font> - <font color=darkBlue>﻿ज्ञानी निरास्रव किस तरह ? उत्तर</font></font></a></li>");
document.write("        <li><a href='179.html'><font size=4><font color=darkPurple><b>179</b></font> - <font color=darkGreen>﻿ज्ञान-गुण के जघन्य-भाव परिणमन के रहते ज्ञानी निरास्रव कैसे</font></font></a></li>");
document.write("        <li><a href='180-183.html'><font size=4><font color=darkPurple><b>180-183</b></font> - <font color=darkBlue>﻿सभी द्रव्यास्रव की संतति के रहने पर भी ज्ञानी नित्य ही निरास्रव कैसे</font></font></a></li>");
document.write("        <li><a href='184-185.html'><font size=4><font color=darkPurple><b>184-185</b></font> - <font color=darkGreen>﻿ज्ञानी के राग-देष-मोह नहीं अत: नवीन कर्मों का बंध नहीं</font></font></a></li>");
document.write("        <li><a href='186-187.html'><font size=4><font color=darkPurple><b>186-187</b></font> - <font color=darkBlue>﻿इसी का समर्थन दृष्टांत पूर्वक</font></font></a></li>");
document.write("        <li><a href='188-190.html'><font size=4><br><font size=5 color=black><b>﻿संवर अधिकार </b></font><br><br><font color=darkPurple><b>188-190</b></font> - <font color=darkGreen>﻿भेद-विज्ञान की अभिवन्दना</font></font></a></li>");
document.write("        <li><a href='191-192.html'><font size=4><font color=darkPurple><b>191-192</b></font> - <font color=darkBlue>﻿भेद-विज्ञान से ही शुद्धात्मा की प्राप्ति</font></font></a></li>");
document.write("        <li><a href='193.html'><font size=4><font color=darkPurple><b>193</b></font> - <font color=darkGreen>﻿शुद्ध आत्मा की प्राप्ति से ही संवर</font></font></a></li>");
document.write("        <li><a href='194-196.html'><font size=4><font color=darkPurple><b>194-196</b></font> - <font color=darkBlue>﻿संवर इस तरह से होता है</font></font></a></li>");
document.write("        <li><a href='197.html'><font size=4><font color=darkPurple><b>197</b></font> - <font color=darkGreen>﻿आत्मा परोक्ष है, फिर उसका ध्यान कैसे</font></font></a></li>");
document.write("        <li><a href='198.html'><font size=4>198</font></a></li>");
document.write("        <li><a href='199-201.html'><font size=4><font color=darkPurple><b>199-201</b></font> - <font color=darkGreen>﻿संवर के क्रम का व्याख्यान</font></font></a></li>");
document.write("        <li><a href='202.html'><font size=4><br><font size=5 color=black><b>﻿निर्जरा अधिकार </b></font><br><br><font color=darkPurple><b>202</b></font> - <font color=darkBlue>﻿द्रव्य-निर्जरा का स्वरूप</font></font></a></li>");
document.write("        <li><a href='203.html'><font size=4><font color=darkPurple><b>203</b></font> - <font color=darkGreen>﻿भाव-निर्जरा का भी स्वरूप</font></font></a></li>");
document.write("        <li><a href='204-205.html'><font size=4><font color=darkPurple><b>204-205</b></font> - <font color=darkBlue>﻿ज्ञान-शक्ति का वर्णन</font></font></a></li>");
document.write("        <li><a href='206.html'><font size=4><font color=darkPurple><b>206</b></font> - <font color=darkGreen>﻿दृष्टांत</font></font></a></li>");
document.write("        <li><a href='207.html'><font size=4><font color=darkPurple><b>207</b></font> - <font color=darkBlue>﻿अब कहते हैं कि सम्यग्दृष्टि अपने को और पर को विषेषरूप से इस प्रकार जानता है --</font></font></a></li>");
document.write("        <li><a href='208.html'><font size=4><font color=darkPurple><b>208</b></font> - <font color=darkGreen>﻿विभाव भाव आत्म-स्वभाव क्यों नहीं ?</font></font></a></li>");
document.write("        <li><a href='209.html'><font size=4><font color=darkPurple><b>209</b></font> - <font color=darkBlue>﻿औपाधिक भावों की परभावता जानने का फल</font></font></a></li>");
document.write("        <li><a href='210.html'><font size=4><font color=darkPurple><b>210</b></font> - <font color=darkGreen>﻿सम्यग्दृष्टि अपने और पर के स्वभाव का ज्ञाता होता है</font></font></a></li>");
document.write("        <li><a href='211-212.html'><font size=4><font color=darkPurple><b>211-212</b></font> - <font color=darkBlue>﻿सम्यग्दृष्टि रागी कैसे नहीं होता? यदि ऐसा पूछें तो सुनिये --</font></font></a></li>");
document.write("        <li><a href='213.html'><font size=4><font color=darkPurple><b>213</b></font> - <font color=darkGreen>﻿ज्ञानी अनागत कर्मोदय के उपभोग की वांछा क्यों नहीं करता ?</font></font></a></li>");
document.write("        <li><a href='214.html'><font size=4><font color=darkPurple><b>214</b></font> - <font color=darkBlue>﻿इसका विस्तार करते हैं --</font></font></a></li>");
document.write("        <li><a href='215.html'><font size=4><font color=darkPurple><b>215</b></font> - <font color=darkGreen>﻿मिथ्यात्वादि अपध्यान मेरा परिग्रह नहीं</font></font></a></li>");
document.write("        <li><a href='216.html'><font size=4><font color=darkPurple><b>216</b></font> - <font color=darkBlue>﻿वह परामात्म-पद क्या है ? इसका समाधान आचार्य करते हैं --</font></font></a></li>");
document.write("        <li><a href='217.html'><font size=4><font color=darkPurple><b>217</b></font> - <font color=darkGreen>﻿अब पूछते हैं कि ज्ञानी पर-द्रव्य को क्यों नहीं ग्रहण करता ? उत्तर --</font></font></a></li>");
document.write("        <li><a href='218.html'><font size=4>218</font></a></li>");
document.write("        <li><a href='219.html'><font size=4><font color=darkPurple><b>219</b></font> - <font color=darkGreen>﻿और क्या ?</font></font></a></li>");
document.write("        <li><a href='220.html'><font size=4><font color=darkPurple><b>220</b></font> - <font color=darkBlue>﻿मत्यादि ज्ञान विशेष एक ज्ञान सामान्य के ही रूप</font></font></a></li>");
document.write("        <li><a href='221.html'><font size=4>221</font></a></li>");
document.write("        <li><a href='222-227.html'><font size=4><font color=darkPurple><b>222-227</b></font> - <font color=darkBlue>﻿इच्छा ही परिग्रह, जिसको इच्छा नहीं उसको परिग्रह नहीं</font></font></a></li>");
document.write("        <li><a href='228.html'><font size=4><font color=darkPurple><b>228</b></font> - <font color=darkGreen>﻿ज्ञानी के भोग का उदय वियोग बुद्धि पूर्वक, आगे भोगों की इच्छा नहीं   </font></font></a></li>");
document.write("        <li><a href='229-230.html'><font size=4><font color=darkPurple><b>229-230</b></font> - <font color=darkBlue>﻿ज्ञानी के अलिप्तता के कारण कर्म-बन्ध नहीं, और अज्ञानी के लिप्तता के कारण कर्म बन्ध</font></font></a></li>");
document.write("        <li><a href='231-233.html'><font size=4><font color=darkPurple><b>231-233</b></font> - <font color=darkGreen>﻿अब पूर्व-बद्ध कर्मों की निर्जरा न होकर, किस प्रकार मोक्ष होगा ? इस प्रश्न का उत्तर देते हैं --</font></font></a></li>");
document.write("        <li><a href='234-238.html'><font size=4><font color=darkPurple><b>234-238</b></font> - <font color=darkBlue>﻿अब ज्ञानी के कर्म-बंध नहीं होता, उसे शंख के दृष्टांत से बतलाते हैं -- </font></font></a></li>");
document.write("        <li><a href='239-242.html'><font size=4><font color=darkPurple><b>239-242</b></font> - <font color=darkGreen>﻿आगे दृष्टांत और दार्ष्टान्त के द्वारा बतलाते हैं की सराग परिणाम से बंध और वीतराग परिणाम से मोक्ष होता है --</font></font></a></li>");
document.write("        <li><a href='243.html'><font size=4><font color=darkPurple><b>243</b></font> - <font color=darkBlue>﻿सम्यक्त्वी भय-रहित होता है </font></font></a></li>");
document.write("        <li><a href='244.html'><font size=4><font color=darkPurple><b>244</b></font> - <font color=darkGreen>﻿नि:शंकित अंग का स्वरूप</font></font></a></li>");
document.write("        <li><a href='245.html'><font size=4><font color=darkPurple><b>245</b></font> - <font color=darkBlue>﻿नि:कांक्षित अंग का स्वरूप</font></font></a></li>");
document.write("        <li><a href='246-247.html'><font size=4><font color=darkPurple><b>246-247</b></font> - <font color=darkGreen>﻿निर्वचिकित्सा व अमूढदृष्टि अंग का स्वरूप</font></font></a></li>");
document.write("        <li><a href='248-249.html'><font size=4><font color=darkPurple><b>248-249</b></font> - <font color=darkBlue>﻿उपगूहन और स्थितिकरण अंग का स्वरूप</font></font></a></li>");
document.write("        <li><a href='250-251.html'><font size=4><font color=darkPurple><b>250-251</b></font> - <font color=darkGreen>﻿वात्सल्य और प्रभावना अंग का धारी सम्यग्दृष्टि का वर्णन</font></font></a></li>");
document.write("        <li><a href='252-256.html'><font size=4><br><font size=5 color=black><b>﻿बंध अधिकार </b></font><br><br><font color=darkPurple><b>252-256</b></font> - <font color=darkBlue>﻿मिथ्या-ज्ञान श्रंगार-सहित प्रवेश कर रहा है</font></font></a></li>");
document.write("        <li><a href='257-261.html'><font size=4><font color=darkPurple><b>257-261</b></font> - <font color=darkGreen>﻿आगे वीतराग सम्यग्दृष्टि जीव के कर्म-बंध नहीं होता है, ऐसा पांच गाथाओं से बतलाते हैं --</font></font></a></li>");
document.write("        <li><a href='262-264.html'><font size=4><font color=darkPurple><b>262-264</b></font> - <font color=darkBlue>﻿हिंस्य-हिंसकभाव रूप परिणमन अज्ञानी का लक्षण ज्ञानी का नहीं</font></font></a></li>");
document.write("        <li><a href='265-268.html'><font size=4><font color=darkPurple><b>265-268</b></font> - <font color=darkGreen>﻿आगे कहते हैं कि सुख और दु:ख भी निश्चय से अपने ही कर्मों के उदय से होते हैं --</font></font></a></li>");
document.write("        <li><a href='269-270.html'><font size=4><font color=darkPurple><b>269-270</b></font> - <font color=darkBlue>﻿दूसरे को जिला, मार, सुखी कर सकना ऐसी मान्यता बहिरात्मपना</font></font></a></li>");
document.write("        <li><a href='271-273.html'><font size=4><font color=darkPurple><b>271-273</b></font> - <font color=darkGreen>﻿पूर्व के दो सूत्र में कहा हुआ मिथ्याज्ञानरूपी भाव मिथ्यादृष्टि के बंध का कारण होता है --</font></font></a></li>");
document.write("        <li><a href='274.html'><font size=4><font color=darkPurple><b>274</b></font> - <font color=darkBlue>﻿अध्यवसान से ही बंध प्राणियों को मारने अथवा न मारने से नहीं</font></font></a></li>");
document.write("        <li><a href='275-276.html'><font size=4><font color=darkPurple><b>275-276</b></font> - <font color=darkGreen>﻿अध्यवसाय ही पाप-पुण्य के बन्ध का कारण हैं, ऐसा दिखाते हैं</font></font></a></li>");
document.write("        <li><a href='277.html'><font size=4><font color=darkPurple><b>277</b></font> - <font color=darkBlue>﻿रागादिक-रूप परिणाम बंध का कारण होते हैं, बाह्य वस्तु नहीं</font></font></a></li>");
document.write("        <li><a href='278-279.html'><font size=4><font color=darkPurple><b>278-279</b></font> - <font color=darkGreen>﻿'मैं जीवों को सुखी-दुखी, बांधता-मुक्त करता हूँ', यह मानना मूढ़ता है</font></font></a></li>");
document.write("        <li><a href='280-284.html'><font size=4><font color=darkPurple><b>280-284</b></font> - <font color=darkBlue>﻿इस प्रकार जो जीव दुखी होते है वे अपने पाप-कर्म के उदय से होते है, तुम्हारे विचारानुसार नहीं यह बतलाते हैं --</font></font></a></li>");
document.write("        <li><a href='285-286.html'><font size=4><font color=darkPurple><b>285-286</b></font> - <font color=darkGreen>﻿अध्यवसान से मोहित ही पर-द्रव्य से एकत्व करता है </font></font></a></li>");
document.write("        <li><a href='287.html'><font size=4><font color=darkPurple><b>287</b></font> - <font color=darkBlue>﻿तपोधन मोह भाव रहित </font></font></a></li>");
document.write("        <li><a href='288.html'><font size=4><font color=darkPurple><b>288</b></font> - <font color=darkGreen>﻿बाह्य वस्तुओं में संकल्प विकल्प कर्म का कारण </font></font></a></li>");
document.write("        <li><a href='289.html'><font size=4><font color=darkPurple><b>289</b></font> - <font color=darkBlue>﻿अध्यवसान के पर्यायवाची </font></font></a></li>");
document.write("        <li><a href='290.html'><font size=4><font color=darkPurple><b>290</b></font> - <font color=darkGreen>﻿निश्चयनय के द्वारा व्यवहार विकल्पों का निषेध</font></font></a></li>");
document.write("        <li><a href='291-293.html'><font size=4><font color=darkPurple><b>291-293</b></font> - <font color=darkBlue>﻿अभव्य जीव के अपने मिथ्या अभिप्राय के कारण सिद्धि नहीं </font></font></a></li>");
document.write("        <li><a href='294-295.html'><font size=4><font color=darkPurple><b>294-295</b></font> - <font color=darkGreen>﻿व्यवहार-नय व निश्चय-नय का स्वरूप</font></font></a></li>");
document.write("        <li><a href='296-297.html'><font size=4><font color=darkPurple><b>296-297</b></font> - <font color=darkBlue>﻿ज्ञानी के आहारकृत बन्ध नहीं</font></font></a></li>");
document.write("        <li><a href='298-299.html'><font size=4>298-299</font></a></li>");
document.write("        <li><a href='300-301.html'><font size=4><font color=darkPurple><b>300-301</b></font> - <font color=darkBlue>﻿रागादि विकारी भाव कैसे बनते है ?</font></font></a></li>");
document.write("        <li><a href='302.html'><font size=4><font color=darkPurple><b>302</b></font> - <font color=darkGreen>﻿ज्ञानी जीव आस्रव का कर्त्ता नहीं होता</font></font></a></li>");
document.write("        <li><a href='303-304.html'><font size=4><font color=darkPurple><b>303-304</b></font> - <font color=darkBlue>﻿ज्ञानी के कर्म के उदय से राग द्वेष</font></font></a></li>");
document.write("        <li><a href='305-307.html'><font size=4><font color=darkPurple><b>305-307</b></font> - <font color=darkGreen>﻿ज्ञानी रागादि का अकर्ता कैसे ?</font></font></a></li>");
document.write("        <li><a href='308-310.html'><font size=4><br><font size=5 color=black><b>﻿मोक्ष अधिकार </b></font><br><br><font color=darkPurple><b>308-310</b></font> - <font color=darkBlue>﻿विशिष्ट भेद-ज्ञान के बल से बन्ध और आत्मा को पृथक् करना मोक्ष</font></font></a></li>");
document.write("        <li><a href='311-315.html'><font size=4><font color=darkPurple><b>311-315</b></font> - <font color=darkGreen>﻿इसी को और स्पष्ट करते हैं</font></font></a></li>");
document.write("        <li><a href='316.html'><font size=4><font color=darkPurple><b>316</b></font> - <font color=darkBlue>﻿आत्मा और बन्ध को भिन्न कैसे किया जाए ?</font></font></a></li>");
document.write("        <li><a href='317-319.html'><font size=4><font color=darkPurple><b>317-319</b></font> - <font color=darkGreen>﻿आत्मा और बन्ध के प्रथक्-करण कब होता है ?</font></font></a></li>");
document.write("        <li><a href='320-322.html'><font size=4><font color=darkPurple><b>320-322</b></font> - <font color=darkBlue>﻿भेद-भावना -- मैं बस जानने देखने देखने वाला </font></font></a></li>");
document.write("        <li><a href='323.html'><font size=4><font color=darkPurple><b>323</b></font> - <font color=darkGreen>﻿शुद्धात्मा मात्र ज्ञाता, पर भाव मेरे नहीं </font></font></a></li>");
document.write("        <li><a href='324-326.html'><font size=4><font color=darkPurple><b>324-326</b></font> - <font color=darkBlue>﻿पर भावों को अपना मानने से बन्ध और वीतरागता से मुक्ति</font></font></a></li>");
document.write("        <li><a href='327.html'><font size=4><font color=darkPurple><b>327</b></font> - <font color=darkGreen>﻿अपराध शब्द का अर्थ</font></font></a></li>");
document.write("        <li><a href='328-329.html'><font size=4><font color=darkPurple><b>328-329</b></font> - <font color=darkBlue>﻿परमार्थ से प्रतिक्रमण विष-कुम्भ, अप्रतिक्रमण अमृत-कुम्भ</font></font></a></li>");
document.write("        <li><a href='330-333.html'><font size=4><br><font size=5 color=black><b>﻿सर्व-विशुद्ध अधिकार </b></font><br><br><font color=darkPurple><b>330-333</b></font> - <font color=darkGreen>﻿अब यहाँ कहते हैं कि निश्चय से यह जीव कर्मों का कर्त्ता नहीं है --</font></font></a></li>");
document.write("        <li><a href='334-335.html'><font size=4><font color=darkPurple><b>334-335</b></font> - <font color=darkBlue>﻿ज्ञानावरणादि कर्म-प्रकृतियों का आत्मा के साथ जो बंध है, वह अज्ञान का ही महात्म्य है, ऐसा बताते हैं --</font></font></a></li>");
document.write("        <li><a href='336-337.html'><font size=4><font color=darkPurple><b>336-337</b></font> - <font color=darkGreen>﻿जब तक कर्मोदय से होने वाले रागादि-भाव को नहीं छोडे तब तक अज्ञानी अन्यथा ज्ञानी</font></font></a></li>");
document.write("        <li><a href='338.html'><font size=4><font color=darkPurple><b>338</b></font> - <font color=darkBlue>﻿कर्म-फल को भोगते रहना जीव का स्वभाव नहीं, अज्ञान भाव</font></font></a></li>");
document.write("        <li><a href='339.html'><font size=4><font color=darkPurple><b>339</b></font> - <font color=darkGreen>﻿ज्ञानी नि:श्शंक होता हुआ कर्म-फल जानता हुआ आराधना में तत्पर रहता है</font></font></a></li>");
document.write("        <li><a href='340-341.html'><font size=4><font color=darkPurple><b>340-341</b></font> - <font color=darkBlue>﻿अब यहाँ बताते हैं कि अज्ञानी जीव नियम से कर्मों का वेदक ही होता है --</font></font></a></li>");
document.write("        <li><a href='342-343.html'><font size=4><font color=darkPurple><b>342-343</b></font> - <font color=darkGreen>﻿अब इसी कर्तृत्व व भोक्तृत्व के अभाव का दृष्टांत पूर्वक समर्थन करते हैं --</font></font></a></li>");
document.write("        <li><a href='344-346.html'><font size=4><font color=darkPurple><b>344-346</b></font> - <font color=darkBlue>﻿अब यहाँ बताते हैं कि जो एकान्त से आत्मा को कर्ता मानते हैं उनके भी अज्ञानी लोगों के समान मोक्ष नहीं है ऐसा उपदेश करते हैं --</font></font></a></li>");
document.write("        <li><a href='347-350.html'><font size=4><font color=darkPurple><b>347-350</b></font> - <font color=darkGreen>﻿अब पूर्व-पक्ष के उत्तर में कथन करते हैं कि निश्चय से आत्मा का पुदगलद्रव्य के साथ में कर्त्ता-कर्म सम्बन्ध नहीं है, तब आत्मा कैसे कर्त्ता बनता है ?</font></font></a></li>");
document.write("        <li><a href='351-354.html'><font size=4><font color=darkPurple><b>351-354</b></font> - <font color=darkBlue>﻿जो करता है वही भोगता है -- द्रव्यार्थिक-नय और अन्य ही कर्ता है और अन्य ही भोगता -- पर्यायार्थिक-नय</font></font></a></li>");
document.write("        <li><a href='355-359.html'><font size=4><font color=darkPurple><b>355-359</b></font> - <font color=darkGreen>﻿भाव-कर्म का कर्त्ता जीव ही है</font></font></a></li>");
document.write("        <li><a href='360-372.html'><font size=4><font color=darkPurple><b>360-372</b></font> - <font color=darkBlue>﻿आत्मा सर्वथा अकर्ता नहीं है, कथंचित् कर्त्ता भी है</font></font></a></li>");
document.write("        <li><a href='373-378.html'><font size=4><font color=darkPurple><b>373-378</b></font> - <font color=darkGreen>﻿सम्यग्दृष्टियों को विषयों के प्रति राग क्यों नहीं होता</font></font></a></li>");
document.write("        <li><a href='379.html'><font size=4><font color=darkPurple><b>379</b></font> - <font color=darkBlue>﻿शब्दादि अचेतन होने से रागादिक की उत्पत्ति में नियामक कारण नहीं</font></font></a></li>");
document.write("        <li><a href='380-386.html'><font size=4><font color=darkPurple><b>380-386</b></font> - <font color=darkGreen>﻿व्यवहार से कर्त्ता और कर्म भिन्न, निश्चय से अभिन्न</font></font></a></li>");
document.write("        <li><a href='387-396.html'><font size=4><font color=darkPurple><b>387-396</b></font> - <font color=darkBlue>﻿इस निश्चय-व्यवहार कथन का दृष्टांत</font></font></a></li>");
document.write("        <li><a href='397-400.html'><font size=4><font color=darkPurple><b>397-400</b></font> - <font color=darkGreen>﻿निश्चय-प्रतिक्रमण-प्रत्याख्यान-आलोचना ही अभेद-नय से निश्चय-चारित्र</font></font></a></li>");
document.write("        <li><a href='401-410.html'><font size=4><font color=darkPurple><b>401-410</b></font> - <font color=darkBlue>﻿आगे कहते हैं कि मिथ्या-ज्ञान में परिणमन करता हुआ यह जीव पंचेन्द्रिय और मन के विषयों में राग और द्वेष करता है --</font></font></a></li>");
document.write("        <li><a href='411-413.html'><font size=4><font color=darkPurple><b>411-413</b></font> - <font color=darkGreen>﻿आगे कहते  कि मिथ्यात्व व रागादि परिणत जीव के अज्ञान-चेतना होती है वह केवल-ज्ञानादि गुणों को प्रच्छादन करने वाले कर्म-बंध को पैदा करती है --</font></font></a></li>");
document.write("        <li><a href='414-428.html'><font size=4><font color=darkPurple><b>414-428</b></font> - <font color=darkBlue>﻿अब इसी अर्थ की गाथा कहते हैं --</font></font></a></li>");
document.write("        <li><a href='429-431.html'><font size=4><font color=darkPurple><b>429-431</b></font> - <font color=darkGreen>﻿परमात्मा शुद्ध-बुद्ध-रूप एक स्वभाव-वाला है, ऐसी हालत में जब परमात्मा के देह नहीं है तो उसके आहार कैसे होगा ? यह बतलाते हैं --</font></font></a></li>");
document.write("        <li><a href='432-435.html'><font size=4><font color=darkPurple><b>432-435</b></font> - <font color=darkBlue>﻿द्रव्य-लिंग भी निश्चय से मुक्ति का कारण नहीं</font></font></a></li>");
document.write("        <li><a href='436.html'><font size=4><font color=darkPurple><b>436</b></font> - <font color=darkGreen>﻿अब आचार्य यह उपदेश करते हैं कि मोक्षार्थी जीव को शुद्धात्मानुभूति रूप लक्षण वाले निश्चय-रत्नत्रयात्मक मोक्ष-मार्ग का सेवन करना चाहिए --</font></font></a></li>");
document.write("        <li><a href='437.html'><font size=4><font color=darkPurple><b>437</b></font> - <font color=darkBlue>﻿आगे कहते हैं कि जो सहज शुद्ध परमात्मानुभूति लक्षण वाले भाव-लिंग से तो रहित हैं, किन्त द्रव्य-लिंग में ही ममता करते हैं वे आज भी समयसार को नहीं जानते --</font></font></a></li>");
document.write("        <li><a href='438.html'><font size=4><font color=darkPurple><b>438</b></font> - <font color=darkGreen>﻿मुनि-लिंग और गृहस्थ-लिंग व्यवहार से मोक्ष-मार्ग, निश्चय से कोई भी लिंग मोक्षमार्ग नहीं</font></font></a></li>");
document.write("        <li><a href='439.html'><font size=4><font color=darkPurple><b>439</b></font> - <font color=darkBlue>﻿ग्रन्थ समाप्ति और इसके पढ़ने का फल</font></font></a></li>");
document.write("</ul></div>");
document.write("<div id=notes class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='001.html'><font size=4><br><font size=5 color=black><b>﻿मंगलाचरण </b></font><br><br><font color=darkPurple><b>001</b></font> - <font color=darkGreen>﻿सिद्धों को नमस्कार</font></font></a></li>");
document.write("        <li><a href='002.html'><font size=4><br><font size=5 color=black><b>﻿पीठिका </b></font><br><br><font color=darkPurple><b>002</b></font> - <font color=darkBlue>﻿स्वसमय और परसमय का लक्षण </font></font></a></li>");
document.write("        <li><a href='009-010.html'><font size=4><font color=darkPurple><b>009-010</b></font> - <font color=darkGreen>﻿श्रुतकेवली</font></font></a></li>");
document.write("        <li><a href='018.html'><font size=4><font color=darkPurple><b>018</b></font> - <font color=darkBlue>﻿ध्यान में केवल आत्मा</font></font></a></li>");
document.write("        <li><a href='023.html'><font size=4><font color=darkPurple><b>023</b></font> - <font color=darkGreen>﻿आत्मा के बंध मोक्ष का कारण</font></font></a></li>");
document.write("        <li><a href='036.html'><font size=4><font color=darkPurple><b>036</b></font> - <font color=darkBlue>﻿निश्चय स्तुति - जितेन्द्रिय</font></font></a></li>");
document.write("        <li><a href='054.html'><font size=4><font color=darkPurple><b>054</b></font> - <font color=darkGreen>﻿शुद्ध जीव कैसा होता है?</font></font></a></li>");
document.write("        <li><a href='082.html'><font size=4><font color=darkPurple><b>082</b></font> - <font color=darkBlue>﻿कर्मों को जानते हुए इस जीव का पुद्गल के साथ अतादात्म्य</font></font></a></li>");
document.write("        <li><a href='152.html'><font size=4><br><font size=5 color=black><b>﻿पुण्य-पाप अधिकार </b></font><br><br><font color=darkPurple><b>152</b></font> - <font color=darkGreen>﻿शुभाशुभ कर्म के स्वभाव का वर्णन</font></font></a></li>");
document.write("        <li><a href='161.html'><font size=4><font color=darkPurple><b>161</b></font> - <font color=darkBlue>﻿पुण्यकर्म के पक्षपाती को प्रतिबोधन</font></font></a></li>");
document.write("</ul></div>");
