document.write("<div id=पं-रत्नचन्द-मुख्तार class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='001.html'><font size=4><font color=darkPurple><b>001</b></font> - <font color=darkBlue>﻿आलापपद्धति का अर्थ</font></font></a></li>");
document.write("        <li><a href='005.html'><font size=4><font color=darkPurple><b>005</b></font> - <font color=darkGreen>﻿द्रव्यों के नाम</font></font></a></li>");
document.write("        <li><a href='007.html'><font size=4><font color=darkPurple><b>007</b></font> - <font color=darkBlue>﻿सत् का लक्षण</font></font></a></li>");
document.write("        <li><a href='008.html'><font size=4><br><font size=5 color=black><b>﻿गुणाधिकार </b></font><br><br><font color=darkPurple><b>008</b></font> - <font color=darkGreen>﻿द्रव्‍यों के लक्षण कौन-कौन से हैं ? </font></font></a></li>");
document.write("        <li><a href='009.html'><font size=4><font color=darkPurple><b>009</b></font> - <font color=darkBlue>﻿सामान्‍य गुणों के नाम</font></font></a></li>");
document.write("        <li><a href='010.html'><font size=4><font color=darkPurple><b>010</b></font> - <font color=darkGreen>﻿प्रत्येक द्रव्य के सामान्य गुण</font></font></a></li>");
document.write("        <li><a href='011.html'><font size=4><font color=darkPurple><b>011</b></font> - <font color=darkBlue>﻿द्रव्यों के विशेष गुण</font></font></a></li>");
document.write("        <li><a href='012.html'><font size=4><font color=darkPurple><b>012</b></font> - <font color=darkGreen>﻿जीव और पुद्गल के विशेष गुण</font></font></a></li>");
document.write("        <li><a href='013.html'><font size=4><font color=darkPurple><b>013</b></font> - <font color=darkBlue>﻿धर्मादिक चार द्रव्‍यों के विशेष गुण</font></font></a></li>");
document.write("        <li><a href='014.html'><font size=4><font color=darkPurple><b>014</b></font> - <font color=darkGreen>﻿कुछ गुण सामान्य भी और विशेष भी, कैसे?</font></font></a></li>");
document.write("        <li><a href='015.html'><font size=4><br><font size=5 color=black><b>﻿पर्याय अधिकार </b></font><br><br><font color=darkPurple><b>015</b></font> - <font color=darkBlue>﻿पर्याय और उसके भेद</font></font></a></li>");
document.write("        <li><a href='016.html'><font size=4><font color=darkPurple><b>016</b></font> - <font color=darkGreen>﻿अर्थ-पर्याय के भेद</font></font></a></li>");
document.write("        <li><a href='017.html'><font size=4><font color=darkPurple><b>017</b></font> - <font color=darkBlue>﻿स्वभाव अर्थ-पर्याय</font></font></a></li>");
document.write("        <li><a href='018.html'><font size=4><font color=darkPurple><b>018</b></font> - <font color=darkGreen>﻿जीव की विभाव अर्थ-पर्याय</font></font></a></li>");
document.write("        <li><a href='019.html'><font size=4><font color=darkPurple><b>019</b></font> - <font color=darkBlue>﻿जीव की विभाव द्रव्य व्यंजन पर्याय</font></font></a></li>");
document.write("        <li><a href='020.html'><font size=4><font color=darkPurple><b>020</b></font> - <font color=darkGreen>﻿जीव की विभाव गुण व्यंजन पर्याय</font></font></a></li>");
document.write("        <li><a href='021.html'><font size=4><font color=darkPurple><b>021</b></font> - <font color=darkBlue>﻿जीव की स्‍वभाव-द्रव्‍य-व्‍यंजनपर्याय</font></font></a></li>");
document.write("        <li><a href='022.html'><font size=4><font color=darkPurple><b>022</b></font> - <font color=darkGreen>﻿जीव की स्‍वभाव-गुण-व्‍यंजन-पर्याय</font></font></a></li>");
document.write("        <li><a href='023.html'><font size=4><font color=darkPurple><b>023</b></font> - <font color=darkBlue>﻿पुद्गल की विभाव-द्रव्‍य-व्‍यंजन-पर्याय</font></font></a></li>");
document.write("        <li><a href='024.html'><font size=4><font color=darkPurple><b>024</b></font> - <font color=darkGreen>﻿पुद्गल की विभाव-गुण-व्‍यंजनपर्याय</font></font></a></li>");
document.write("        <li><a href='025.html'><font size=4><font color=darkPurple><b>025</b></font> - <font color=darkBlue>﻿पुद्गल की स्‍वभाव-द्रव्‍य-व्यंजन-पर्याय </font></font></a></li>");
document.write("        <li><a href='026.html'><font size=4><font color=darkPurple><b>026</b></font> - <font color=darkGreen>﻿पुद्गल की स्‍वभाव-गुण-व्यंजन-पर्याय </font></font></a></li>");
document.write("        <li><a href='027.html'><font size=4><font color=darkPurple><b>027</b></font> - <font color=darkBlue>﻿प्रकारान्‍तर से द्रव्‍य, गुण व पर्याय का लक्षण</font></font></a></li>");
document.write("        <li><a href='028.html'><font size=4><br><font size=5 color=black><b>﻿स्वभाव अधिकार </b></font><br><br><font color=darkPurple><b>028</b></font> - <font color=darkGreen>﻿द्रव्‍यों के सामान्‍य व विशेष स्‍वभावों का कथन</font></font></a></li>");
document.write("        <li><a href='029.html'><font size=4><font color=darkPurple><b>029</b></font> - <font color=darkBlue>﻿जीव और पुद्गल के भावों की संख्‍या </font></font></a></li>");
document.write("        <li><a href='030.html'><font size=4><font color=darkPurple><b>030</b></font> - <font color=darkGreen>﻿धर्मादि तीन द्रव्‍यों में स्‍वभावों की संख्‍या </font></font></a></li>");
document.write("        <li><a href='031.html'><font size=4><font color=darkPurple><b>031</b></font> - <font color=darkBlue>﻿काल-द्रव्‍य में स्‍वभावों की संख्‍या</font></font></a></li>");
document.write("        <li><a href='032.html'><font size=4><font color=darkPurple><b>032</b></font> - <font color=darkGreen>﻿प्रश्न</font></font></a></li>");
document.write("        <li><a href='033.html'><font size=4><br><font size=5 color=black><b>﻿प्रमाण अधिकार </b></font><br><br><font color=darkPurple><b>033</b></font> - <font color=darkBlue>﻿उत्तर</font></font></a></li>");
document.write("        <li><a href='034.html'><font size=4><font color=darkPurple><b>034</b></font> - <font color=darkGreen>﻿प्रमाण का लक्षण</font></font></a></li>");
document.write("        <li><a href='035.html'><font size=4><font color=darkPurple><b>035</b></font> - <font color=darkBlue>﻿प्रमाण के भेद</font></font></a></li>");
document.write("        <li><a href='036.html'><font size=4><font color=darkPurple><b>036</b></font> - <font color=darkGreen>﻿एकदेश प्रत्‍यक्ष कितने</font></font></a></li>");
document.write("        <li><a href='037.html'><font size=4><font color=darkPurple><b>037</b></font> - <font color=darkBlue>﻿सकल-प्रत्‍यक्ष कितने</font></font></a></li>");
document.write("        <li><a href='038.html'><font size=4><font color=darkPurple><b>038</b></font> - <font color=darkGreen>﻿परोक्ष कितने</font></font></a></li>");
document.write("        <li><a href='039.html'><font size=4><br><font size=5 color=black><b>﻿नय अधिकार </b></font><br><br><font color=darkPurple><b>039</b></font> - <font color=darkBlue>﻿नय की परिभाषा</font></font></a></li>");
document.write("        <li><a href='040.html'><font size=4><font color=darkPurple><b>040</b></font> - <font color=darkGreen>﻿नय के भेद</font></font></a></li>");
document.write("        <li><a href='041.html'><font size=4><font color=darkPurple><b>041</b></font> - <font color=darkBlue>﻿नय के भेद</font></font></a></li>");
document.write("        <li><a href='042.html'><font size=4><font color=darkPurple><b>042</b></font> - <font color=darkGreen>﻿उपनयों का कथन</font></font></a></li>");
document.write("        <li><a href='043.html'><font size=4><font color=darkPurple><b>043</b></font> - <font color=darkBlue>﻿उपनय</font></font></a></li>");
document.write("        <li><a href='044.html'><font size=4><font color=darkPurple><b>044</b></font> - <font color=darkGreen>﻿उपनय के भेद</font></font></a></li>");
document.write("        <li><a href='045.html'><font size=4><font color=darkPurple><b>045</b></font> - <font color=darkBlue>﻿नयों और उपनयों के भेद</font></font></a></li>");
document.write("        <li><a href='046.html'><font size=4><font color=darkPurple><b>046</b></font> - <font color=darkGreen>﻿द्रव्‍यार्थिक-नय के भेद</font></font></a></li>");
document.write("        <li><a href='047.html'><font size=4><font color=darkPurple><b>047</b></font> - <font color=darkBlue>﻿कर्मोपाधिनिरपेक्ष शुद्ध-द्रव्‍यार्थिकनय</font></font></a></li>");
document.write("        <li><a href='048.html'><font size=4><font color=darkPurple><b>048</b></font> - <font color=darkGreen>﻿(उत्‍पाद-व्‍यय गौण) सत्ताग्राहक शुद्ध-द्रव्‍यार्थिकनय</font></font></a></li>");
document.write("        <li><a href='049.html'><font size=4><font color=darkPurple><b>049</b></font> - <font color=darkBlue>﻿भेद-कल्‍पना-निरपेक्ष शुद्ध-द्रव्‍यार्थिकनय</font></font></a></li>");
document.write("        <li><a href='050.html'><font size=4><font color=darkPurple><b>050</b></font> - <font color=darkGreen>﻿कर्मोपाधि-सापेक्ष अशुद्ध-द्रव्‍यार्थिकनय</font></font></a></li>");
document.write("        <li><a href='051.html'><font size=4><font color=darkPurple><b>051</b></font> - <font color=darkBlue>﻿उत्‍पादव्‍यय-सापेक्ष अशुद्ध-द्रव्‍यार्थिकनय</font></font></a></li>");
document.write("        <li><a href='052.html'><font size=4><font color=darkPurple><b>052</b></font> - <font color=darkGreen>﻿भेदकल्‍पना-सापेक्ष अशुद्ध-द्रव्‍यार्थिकनय</font></font></a></li>");
document.write("        <li><a href='053.html'><font size=4><font color=darkPurple><b>053</b></font> - <font color=darkBlue>﻿अन्‍वय-सापेक्ष द्रव्‍यार्थिकनय</font></font></a></li>");
document.write("        <li><a href='054.html'><font size=4><font color=darkPurple><b>054</b></font> - <font color=darkGreen>﻿स्‍वद्रव्‍यादिग्राहक दव्‍यार्थिकनय</font></font></a></li>");
document.write("        <li><a href='055.html'><font size=4><font color=darkPurple><b>055</b></font> - <font color=darkBlue>﻿परद्रव्‍यादिग्राहक द्रव्‍यार्थिकनय</font></font></a></li>");
document.write("        <li><a href='056.html'><font size=4><font color=darkPurple><b>056</b></font> - <font color=darkGreen>﻿परमभावग्राहक द्रव्‍यार्थिकनय</font></font></a></li>");
document.write("        <li><a href='057.html'><font size=4><font color=darkPurple><b>057</b></font> - <font color=darkBlue>﻿पर्यायार्थिक नय के छ: भेद</font></font></a></li>");
document.write("        <li><a href='058.html'><font size=4><font color=darkPurple><b>058</b></font> - <font color=darkGreen>﻿अनादि-नित्‍य पर्यायार्थिकनय</font></font></a></li>");
document.write("        <li><a href='059.html'><font size=4><font color=darkPurple><b>059</b></font> - <font color=darkBlue>﻿सादि नित्‍यपर्यायार्थिकनय</font></font></a></li>");
document.write("        <li><a href='060.html'><font size=4><font color=darkPurple><b>060</b></font> - <font color=darkGreen>﻿अनित्‍यशुद्ध पर्यायार्थिकनय</font></font></a></li>");
document.write("        <li><a href='061.html'><font size=4><font color=darkPurple><b>061</b></font> - <font color=darkBlue>﻿नित्‍य-अशुद्ध पर्यायार्थिक-नय</font></font></a></li>");
document.write("        <li><a href='062.html'><font size=4><font color=darkPurple><b>062</b></font> - <font color=darkGreen>﻿नित्‍य-शुद्ध पर्यायार्थिक-नय</font></font></a></li>");
document.write("        <li><a href='063.html'><font size=4><font color=darkPurple><b>063</b></font> - <font color=darkBlue>﻿अनित्‍य-अशुद्ध पर्यायार्थिकनय</font></font></a></li>");
document.write("        <li><a href='064.html'><font size=4><font color=darkPurple><b>064</b></font> - <font color=darkGreen>﻿नैगमनय के प्रकार</font></font></a></li>");
document.write("        <li><a href='065.html'><font size=4><font color=darkPurple><b>065</b></font> - <font color=darkBlue>﻿भूत नैगम-नय</font></font></a></li>");
document.write("        <li><a href='066.html'><font size=4><font color=darkPurple><b>066</b></font> - <font color=darkGreen>﻿भावि नैगम-नय</font></font></a></li>");
document.write("        <li><a href='067.html'><font size=4><font color=darkPurple><b>067</b></font> - <font color=darkBlue>﻿वर्तमान नैगम-नय</font></font></a></li>");
document.write("        <li><a href='068.html'><font size=4><font color=darkPurple><b>068</b></font> - <font color=darkGreen>﻿संग्रह-नय के प्रकार</font></font></a></li>");
document.write("        <li><a href='069.html'><font size=4><font color=darkPurple><b>069</b></font> - <font color=darkBlue>﻿सामान्‍य संग्रहनय</font></font></a></li>");
document.write("        <li><a href='070.html'><font size=4><font color=darkPurple><b>070</b></font> - <font color=darkGreen>﻿विशेष संग्रहनय</font></font></a></li>");
document.write("        <li><a href='071.html'><font size=4><font color=darkPurple><b>071</b></font> - <font color=darkBlue>﻿व्‍यवहारनय के प्रकार</font></font></a></li>");
document.write("        <li><a href='072A.html'><font size=4><font color=darkPurple><b>072A</b></font> - <font color=darkGreen>﻿सामान्‍य-संग्रहभेदक व्‍यवहार-नय</font></font></a></li>");
document.write("        <li><a href='072.html'><font size=4><font color=darkPurple><b>072</b></font> - <font color=darkBlue>﻿विशेष-संग्रहभेदक व्‍यवहारनय</font></font></a></li>");
document.write("        <li><a href='073.html'><font size=4><font color=darkPurple><b>073</b></font> - <font color=darkGreen>﻿ऋजुसूत्रनय के प्रकार</font></font></a></li>");
document.write("        <li><a href='074.html'><font size=4><font color=darkPurple><b>074</b></font> - <font color=darkBlue>﻿सूक्ष्‍म ऋजुसूत्रनय</font></font></a></li>");
document.write("        <li><a href='075.html'><font size=4><font color=darkPurple><b>075</b></font> - <font color=darkGreen>﻿स्‍थूल ऋजुसूत्रनय</font></font></a></li>");
document.write("        <li><a href='076.html'><font size=4><font color=darkPurple><b>076</b></font> - <font color=darkBlue>﻿शब्‍द, समभिरूढ और एवंभूत नय</font></font></a></li>");
document.write("        <li><a href='077.html'><font size=4><font color=darkPurple><b>077</b></font> - <font color=darkGreen>﻿शब्‍द नय</font></font></a></li>");
document.write("        <li><a href='078.html'><font size=4><font color=darkPurple><b>078</b></font> - <font color=darkBlue>﻿समभिरूढ नय</font></font></a></li>");
document.write("        <li><a href='079.html'><font size=4><font color=darkPurple><b>079</b></font> - <font color=darkGreen>﻿एवंभूत-नय</font></font></a></li>");
document.write("        <li><a href='080.html'><font size=4><font color=darkPurple><b>080</b></font> - <font color=darkBlue>﻿उपनय के भेद</font></font></a></li>");
document.write("        <li><a href='081.html'><font size=4><font color=darkPurple><b>081</b></font> - <font color=darkGreen>﻿सद्भूत व्‍यवहारनय के प्रकार</font></font></a></li>");
document.write("        <li><a href='082.html'><font size=4><font color=darkPurple><b>082</b></font> - <font color=darkBlue>﻿शुद्ध-सद्भूत व्‍यवहारनय</font></font></a></li>");
document.write("        <li><a href='083.html'><font size=4><font color=darkPurple><b>083</b></font> - <font color=darkGreen>﻿अशुद्ध-सद्भूत-व्‍यवहारनय</font></font></a></li>");
document.write("        <li><a href='084.html'><font size=4><font color=darkPurple><b>084</b></font> - <font color=darkBlue>﻿असद्भूत-व्‍यवहारनय के प्रकार</font></font></a></li>");
document.write("        <li><a href='085.html'><font size=4><font color=darkPurple><b>085</b></font> - <font color=darkGreen>﻿स्‍वजाति-असद्भूत-व्‍यवहार-उपनय</font></font></a></li>");
document.write("        <li><a href='086.html'><font size=4><font color=darkPurple><b>086</b></font> - <font color=darkBlue>﻿विजाति-असद्भूत-व्‍यवहार उपनय</font></font></a></li>");
document.write("        <li><a href='087.html'><font size=4><font color=darkPurple><b>087</b></font> - <font color=darkGreen>﻿स्‍वजाति-विजाति-असद्भूत-व्‍यवहार उपनय</font></font></a></li>");
document.write("        <li><a href='088.html'><font size=4><font color=darkPurple><b>088</b></font> - <font color=darkBlue>﻿उपचरित असद्भूत व्‍यवहारनय के प्रकार</font></font></a></li>");
document.write("        <li><a href='089.html'><font size=4><font color=darkPurple><b>089</b></font> - <font color=darkGreen>﻿स्‍वजात्‍युपचरितासद्भूत-व्‍यहार-उपनय</font></font></a></li>");
document.write("        <li><a href='090.html'><font size=4><font color=darkPurple><b>090</b></font> - <font color=darkBlue>﻿विजात्‍युपचरित-असद्भूत-व्‍यवहार उपनय</font></font></a></li>");
document.write("        <li><a href='091.html'><font size=4><font color=darkPurple><b>091</b></font> - <font color=darkGreen>﻿स्‍वजातिविजात्‍युपचरित-असद्भूतव्‍यवहार उपनय</font></font></a></li>");
document.write("        <li><a href='092.html'><font size=4><br><font size=5 color=black><b>﻿गुण-व्युत्पत्ति अधिकार </b></font><br><br><font color=darkPurple><b>092</b></font> - <font color=darkBlue>﻿गुण-पर्याय में अंतर</font></font></a></li>");
document.write("        <li><a href='093.html'><font size=4><font color=darkPurple><b>093</b></font> - <font color=darkGreen>﻿गुण</font></font></a></li>");
document.write("        <li><a href='094.html'><font size=4><font color=darkPurple><b>094</b></font> - <font color=darkBlue>﻿अस्तित्‍व गुण</font></font></a></li>");
document.write("        <li><a href='095.html'><font size=4><font color=darkPurple><b>095</b></font> - <font color=darkGreen>﻿वस्‍तुत्‍व गुण</font></font></a></li>");
document.write("        <li><a href='096.html'><font size=4><font color=darkPurple><b>096</b></font> - <font color=darkBlue>﻿द्रव्‍यत्‍व गुण</font></font></a></li>");
document.write("        <li><a href='097.html'><font size=4><font color=darkPurple><b>097</b></font> - <font color=darkGreen>﻿सत्</font></font></a></li>");
document.write("        <li><a href='098.html'><font size=4><font color=darkPurple><b>098</b></font> - <font color=darkBlue>﻿प्रमेयत्‍व गुण</font></font></a></li>");
document.write("        <li><a href='099.html'><font size=4><font color=darkPurple><b>099</b></font> - <font color=darkGreen>﻿अगुरूलघु गुण</font></font></a></li>");
document.write("        <li><a href='100.html'><font size=4><font color=darkPurple><b>100</b></font> - <font color=darkBlue>﻿प्रदेशत्‍व गुण</font></font></a></li>");
document.write("        <li><a href='101.html'><font size=4><font color=darkPurple><b>101</b></font> - <font color=darkGreen>﻿चेतेनत्‍व</font></font></a></li>");
document.write("        <li><a href='102.html'><font size=4><font color=darkPurple><b>102</b></font> - <font color=darkBlue>﻿अचेतनत्‍व</font></font></a></li>");
document.write("        <li><a href='103.html'><font size=4><font color=darkPurple><b>103</b></font> - <font color=darkGreen>﻿जीव स्यात् रूपी अरूपी</font></font></a></li>");
document.write("        <li><a href='104.html'><font size=4><font color=darkPurple><b>104</b></font> - <font color=darkBlue>﻿अमूर्तत्‍व</font></font></a></li>");
document.write("        <li><a href='105.html'><font size=4><br><font size=5 color=black><b>﻿पर्याय-व्युत्पत्ति अधिकार </b></font><br><br><font color=darkPurple><b>105</b></font> - <font color=darkGreen>﻿पर्याय</font></font></a></li>");
document.write("        <li><a href='106.html'><font size=4><br><font size=5 color=black><b>﻿स्वभाव-व्युत्पत्ति अधिकार </b></font><br><br><font color=darkPurple><b>106</b></font> - <font color=darkBlue>﻿अस्ति-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='107.html'><font size=4><font color=darkPurple><b>107</b></font> - <font color=darkGreen>﻿नास्ति-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='108.html'><font size=4><font color=darkPurple><b>108</b></font> - <font color=darkBlue>﻿नित्‍य-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='109.html'><font size=4><font color=darkPurple><b>109</b></font> - <font color=darkGreen>﻿अनित्‍य-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='110.html'><font size=4><font color=darkPurple><b>110</b></font> - <font color=darkBlue>﻿एक-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='111.html'><font size=4><font color=darkPurple><b>111</b></font> - <font color=darkGreen>﻿अनेक-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='112.html'><font size=4><font color=darkPurple><b>112</b></font> - <font color=darkBlue>﻿भेद-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='113.html'><font size=4><font color=darkPurple><b>113</b></font> - <font color=darkGreen>﻿अभेद-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='114.html'><font size=4><font color=darkPurple><b>114</b></font> - <font color=darkBlue>﻿भव्‍य-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='115.html'><font size=4><font color=darkPurple><b>115</b></font> - <font color=darkGreen>﻿अभव्‍य-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='116.html'><font size=4><font color=darkPurple><b>116</b></font> - <font color=darkBlue>﻿परम-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='117.html'><font size=4>117</font></a></li>");
document.write("        <li><a href='118.html'><font size=4><font color=darkPurple><b>118</b></font> - <font color=darkBlue>﻿स्‍वभाव गुण नहीं</font></font></a></li>");
document.write("        <li><a href='119.html'><font size=4><font color=darkPurple><b>119</b></font> - <font color=darkGreen>﻿गुण स्‍वभाव हैं</font></font></a></li>");
document.write("        <li><a href='120.html'><font size=4><font color=darkPurple><b>120</b></font> - <font color=darkBlue>﻿गुण द्रव्‍य हैं</font></font></a></li>");
document.write("        <li><a href='121.html'><font size=4><font color=darkPurple><b>121</b></font> - <font color=darkGreen>﻿विभाव</font></font></a></li>");
document.write("        <li><a href='122.html'><font size=4><font color=darkPurple><b>122</b></font> - <font color=darkBlue>﻿शुद्ध-अशुद्ध स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='123.html'><font size=4><font color=darkPurple><b>123</b></font> - <font color=darkGreen>﻿उपचरित-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='124.html'><font size=4><font color=darkPurple><b>124</b></font> - <font color=darkBlue>﻿उपचरित-स्‍वभाव के भेद</font></font></a></li>");
document.write("        <li><a href='125.html'><font size=4><font color=darkPurple><b>125</b></font> - <font color=darkGreen>﻿अन्‍य द्रव्‍यों में भी उपचरित-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='126.html'><font size=4><font color=darkPurple><b>126</b></font> - <font color=darkBlue>﻿प्रश्न</font></font></a></li>");
document.write("        <li><a href='127.html'><font size=4><br><font size=5 color=black><b>﻿एकान्त-पक्ष दोष </b></font><br><br><font color=darkPurple><b>127</b></font> - <font color=darkGreen>﻿उत्तर</font></font></a></li>");
document.write("        <li><a href='128.html'><font size=4><font color=darkPurple><b>128</b></font> - <font color=darkBlue>﻿सर्वथा असद्रूप मानने में दोष</font></font></a></li>");
document.write("        <li><a href='129.html'><font size=4><font color=darkPurple><b>129</b></font> - <font color=darkGreen>﻿सर्वथा नित्‍य मानने में दोष</font></font></a></li>");
document.write("        <li><a href='130.html'><font size=4><font color=darkPurple><b>130</b></font> - <font color=darkBlue>﻿सर्वथा अनित्‍य मानने में दोष</font></font></a></li>");
document.write("        <li><a href='131.html'><font size=4><font color=darkPurple><b>131</b></font> - <font color=darkGreen>﻿सर्वथा एक में दोष</font></font></a></li>");
document.write("        <li><a href='132.html'><font size=4><font color=darkPurple><b>132</b></font> - <font color=darkBlue>﻿सर्वथा अनेक में दोष</font></font></a></li>");
document.write("        <li><a href='133.html'><font size=4><font color=darkPurple><b>133</b></font> - <font color=darkGreen>﻿सर्वथा भेद में दोष</font></font></a></li>");
document.write("        <li><a href='134.html'><font size=4><font color=darkPurple><b>134</b></font> - <font color=darkBlue>﻿सर्वथा अभेद में दोष</font></font></a></li>");
document.write("        <li><a href='135.html'><font size=4><font color=darkPurple><b>135</b></font> - <font color=darkGreen>﻿सर्वथा भव्‍य में दोष</font></font></a></li>");
document.write("        <li><a href='136.html'><font size=4><font color=darkPurple><b>136</b></font> - <font color=darkBlue>﻿सर्वथा अभव्‍य में दोष</font></font></a></li>");
document.write("        <li><a href='137.html'><font size=4><font color=darkPurple><b>137</b></font> - <font color=darkGreen>﻿सर्वथा स्‍वभाव में दोष</font></font></a></li>");
document.write("        <li><a href='138.html'><font size=4><font color=darkPurple><b>138</b></font> - <font color=darkBlue>﻿सर्वथा विभाव में दोष</font></font></a></li>");
document.write("        <li><a href='139.html'><font size=4><font color=darkPurple><b>139</b></font> - <font color=darkGreen>﻿सर्वथा चैतन्‍य में दोष</font></font></a></li>");
document.write("        <li><a href='140.html'><font size=4><font color=darkPurple><b>140</b></font> - <font color=darkBlue>﻿सर्वथा में नियामकता दोषपूर्ण</font></font></a></li>");
document.write("        <li><a href='142.html'><font size=4><font color=darkPurple><b>142</b></font> - <font color=darkGreen>﻿सर्वथा मूर्त में दोष</font></font></a></li>");
document.write("        <li><a href='143.html'><font size=4><font color=darkPurple><b>143</b></font> - <font color=darkBlue>﻿सर्वथा अमूर्तिक में दोष</font></font></a></li>");
document.write("        <li><a href='144.html'><font size=4><font color=darkPurple><b>144</b></font> - <font color=darkGreen>﻿सर्वथा एकप्रदेश में दोष</font></font></a></li>");
document.write("        <li><a href='145.html'><font size=4><font color=darkPurple><b>145</b></font> - <font color=darkBlue>﻿सर्वथा अनेक प्रदेशत्‍व में दोष</font></font></a></li>");
document.write("        <li><a href='146.html'><font size=4><font color=darkPurple><b>146</b></font> - <font color=darkGreen>﻿सर्वथा शुद्धस्‍वभाव में दोष</font></font></a></li>");
document.write("        <li><a href='148.html'><font size=4><font color=darkPurple><b>148</b></font> - <font color=darkBlue>﻿सर्वथा उपचरित-स्‍वभाव में दोष</font></font></a></li>");
document.write("        <li><a href='149.html'><font size=4><font color=darkPurple><b>149</b></font> - <font color=darkGreen>﻿सर्वथा अनुपचरित में दोष</font></font></a></li>");
document.write("        <li><a href='150.html'><font size=4><br><font size=5 color=black><b>﻿नय योजना </b></font><br><br><font color=darkPurple><b>150</b></font> - <font color=darkBlue>﻿अस्तिस्‍वभाव</font></font></a></li>");
document.write("        <li><a href='151.html'><font size=4><font color=darkPurple><b>151</b></font> - <font color=darkGreen>﻿नास्ति-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='152.html'><font size=4><font color=darkPurple><b>152</b></font> - <font color=darkBlue>﻿नित्‍य-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='153.html'><font size=4><font color=darkPurple><b>153</b></font> - <font color=darkGreen>﻿अनित्‍य-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='154.html'><font size=4><font color=darkPurple><b>154</b></font> - <font color=darkBlue>﻿एक-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='155.html'><font size=4><font color=darkPurple><b>155</b></font> - <font color=darkGreen>﻿अनेक-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='156.html'><font size=4><font color=darkPurple><b>156</b></font> - <font color=darkBlue>﻿भेद-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='157.html'><font size=4><font color=darkPurple><b>157</b></font> - <font color=darkGreen>﻿अभेद-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='158.html'><font size=4><font color=darkPurple><b>158</b></font> - <font color=darkBlue>﻿पारिणामिक</font></font></a></li>");
document.write("        <li><a href='159.html'><font size=4><font color=darkPurple><b>159</b></font> - <font color=darkGreen>﻿जीव का चेतन-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='160.html'><font size=4><font color=darkPurple><b>160</b></font> - <font color=darkBlue>﻿पुद्गल का चेतन-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='161.html'><font size=4><font color=darkPurple><b>161</b></font> - <font color=darkGreen>﻿पुद्गल का अचेतन-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='162.html'><font size=4><font color=darkPurple><b>162</b></font> - <font color=darkBlue>﻿जीव में अचेतन-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='163.html'><font size=4><font color=darkPurple><b>163</b></font> - <font color=darkGreen>﻿पुद्गल में मूर्त-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='164.html'><font size=4><font color=darkPurple><b>164</b></font> - <font color=darkBlue>﻿जीव का मूर्त-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='165.html'><font size=4><font color=darkPurple><b>165</b></font> - <font color=darkGreen>﻿द्रव्यों का अमूर्त-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='166.html'><font size=4><font color=darkPurple><b>166</b></font> - <font color=darkBlue>﻿पुद्गल का अमूर्त-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='167.html'><font size=4><font color=darkPurple><b>167</b></font> - <font color=darkGreen>﻿द्रव्यों का एकप्रदेश-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='168.html'><font size=4><font color=darkPurple><b>168</b></font> - <font color=darkBlue>﻿द्रव्यों का एकप्रदेश-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='169.html'><font size=4><font color=darkPurple><b>169</b></font> - <font color=darkGreen>﻿द्रव्यों का नानाप्रदेश-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='170.html'><font size=4><font color=darkPurple><b>170</b></font> - <font color=darkBlue>﻿कालाणु के नानाप्रदेश-स्‍वभाव नहीं</font></font></a></li>");
document.write("        <li><a href='171.html'><font size=4><font color=darkPurple><b>171</b></font> - <font color=darkGreen>﻿कालाणु के उपचरित-स्‍वभाव नहीं</font></font></a></li>");
document.write("        <li><a href='172.html'><font size=4><font color=darkPurple><b>172</b></font> - <font color=darkBlue>﻿पुद्गल का अमूर्त-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='173.html'><font size=4><font color=darkPurple><b>173</b></font> - <font color=darkGreen>﻿स्‍वभाव विभाव</font></font></a></li>");
document.write("        <li><a href='174.html'><font size=4><font color=darkPurple><b>174</b></font> - <font color=darkBlue>﻿शुद्ध-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='175.html'><font size=4><font color=darkPurple><b>175</b></font> - <font color=darkGreen>﻿अशुद्ध-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='176.html'><font size=4><font color=darkPurple><b>176</b></font> - <font color=darkBlue>﻿उपचरित-स्‍वभाव</font></font></a></li>");
document.write("        <li><a href='177.html'><font size=4><br><font size=5 color=black><b>﻿प्रमाण लक्षण </b></font><br><br><font color=darkPurple><b>177</b></font> - <font color=darkGreen>﻿प्रमाण</font></font></a></li>");
document.write("        <li><a href='178.html'><font size=4><font color=darkPurple><b>178</b></font> - <font color=darkBlue>﻿प्रमाण के प्रकार</font></font></a></li>");
document.write("        <li><a href='179.html'><font size=4><font color=darkPurple><b>179</b></font> - <font color=darkGreen>﻿सविकल्‍प ज्ञान और उसके प्रकार</font></font></a></li>");
document.write("        <li><a href='180.html'><font size=4><font color=darkPurple><b>180</b></font> - <font color=darkBlue>﻿निर्विकल्‍प-ज्ञान</font></font></a></li>");
document.write("        <li><a href='181.html'><font size=4><br><font size=5 color=black><b>﻿नय का स्वरूप और भेद </b></font><br><br><font color=darkPurple><b>181</b></font> - <font color=darkGreen>﻿नय की परिभाषा</font></font></a></li>");
document.write("        <li><a href='182.html'><font size=4><font color=darkPurple><b>182</b></font> - <font color=darkBlue>﻿नय के प्रकार</font></font></a></li>");
document.write("        <li><a href='183.html'><font size=4><br><font size=5 color=black><b>﻿निक्षेप की व्युत्पत्ति </b></font><br><br><font color=darkPurple><b>183</b></font> - <font color=darkGreen>﻿निक्षेप और उसके प्रकार</font></font></a></li>");
document.write("        <li><a href='184.html'><font size=4><br><font size=5 color=black><b>﻿नय भेद व्युत्पत्ति </b></font><br><br><font color=darkPurple><b>184</b></font> - <font color=darkBlue>﻿द्रव्‍यार्थिक-नय</font></font></a></li>");
document.write("        <li><a href='185.html'><font size=4><font color=darkPurple><b>185</b></font> - <font color=darkGreen>﻿शुद्ध-द्रव्‍यार्थिक-नय</font></font></a></li>");
document.write("        <li><a href='186.html'><font size=4><font color=darkPurple><b>186</b></font> - <font color=darkBlue>﻿अशुद्ध-द्रव्‍यार्थिक-नय</font></font></a></li>");
document.write("        <li><a href='187.html'><font size=4><font color=darkPurple><b>187</b></font> - <font color=darkGreen>﻿अन्‍वय-द्रव्‍यार्थिक-नय</font></font></a></li>");
document.write("        <li><a href='188.html'><font size=4><font color=darkPurple><b>188</b></font> - <font color=darkBlue>﻿स्‍वद्रव्‍यादिग्राहक द्रव्‍यार्थिक-नय</font></font></a></li>");
document.write("        <li><a href='189.html'><font size=4><font color=darkPurple><b>189</b></font> - <font color=darkGreen>﻿परद्रव्‍यादिग्राहक द्रव्‍यार्थिक-नय</font></font></a></li>");
document.write("        <li><a href='190.html'><font size=4><font color=darkPurple><b>190</b></font> - <font color=darkBlue>﻿परमभाव-ग्राहक द्रव्‍यार्थिक-नय</font></font></a></li>");
document.write("        <li><a href='191.html'><font size=4><font color=darkPurple><b>191</b></font> - <font color=darkGreen>﻿पर्यायार्थिक-नय</font></font></a></li>");
document.write("        <li><a href='192.html'><font size=4><font color=darkPurple><b>192</b></font> - <font color=darkBlue>﻿अनादि-नित्‍य पर्यायार्थिक-नय</font></font></a></li>");
document.write("        <li><a href='193.html'><font size=4><font color=darkPurple><b>193</b></font> - <font color=darkGreen>﻿सादि-नित्‍य पर्यायार्थिक-नय</font></font></a></li>");
document.write("        <li><a href='194.html'><font size=4><font color=darkPurple><b>194</b></font> - <font color=darkBlue>﻿शुद्ध पर्यायार्थिक-नय</font></font></a></li>");
document.write("        <li><a href='195.html'><font size=4><font color=darkPurple><b>195</b></font> - <font color=darkGreen>﻿अशुद्ध पर्यायार्थिक-नय</font></font></a></li>");
document.write("        <li><a href='196.html'><font size=4><font color=darkPurple><b>196</b></font> - <font color=darkBlue>﻿नैगम-नय</font></font></a></li>");
document.write("        <li><a href='197.html'><font size=4><font color=darkPurple><b>197</b></font> - <font color=darkGreen>﻿संग्रह-नय</font></font></a></li>");
document.write("        <li><a href='198.html'><font size=4><font color=darkPurple><b>198</b></font> - <font color=darkBlue>﻿व्‍यवहार-नय</font></font></a></li>");
document.write("        <li><a href='199.html'><font size=4><font color=darkPurple><b>199</b></font> - <font color=darkGreen>﻿ऋजुसूत्र-नय</font></font></a></li>");
document.write("        <li><a href='200.html'><font size=4><font color=darkPurple><b>200</b></font> - <font color=darkBlue>﻿शब्‍द-नय</font></font></a></li>");
document.write("        <li><a href='201.html'><font size=4><font color=darkPurple><b>201</b></font> - <font color=darkGreen>﻿समभिरूढ-नय</font></font></a></li>");
document.write("        <li><a href='202.html'><font size=4><font color=darkPurple><b>202</b></font> - <font color=darkBlue>﻿एवंभूत-नय</font></font></a></li>");
document.write("        <li><a href='204.html'><font size=4><font color=darkPurple><b>204</b></font> - <font color=darkGreen>﻿निश्‍चय-नय</font></font></a></li>");
document.write("        <li><a href='205.html'><font size=4><font color=darkPurple><b>205</b></font> - <font color=darkBlue>﻿व्‍यवहार-नय</font></font></a></li>");
document.write("        <li><a href='206.html'><font size=4><font color=darkPurple><b>206</b></font> - <font color=darkGreen>﻿सद्भूत व्‍यवहार-नय</font></font></a></li>");
document.write("        <li><a href='207.html'><font size=4><font color=darkPurple><b>207</b></font> - <font color=darkBlue>﻿असद्भूत व्‍यवहार-नय</font></font></a></li>");
document.write("        <li><a href='208.html'><font size=4><font color=darkPurple><b>208</b></font> - <font color=darkGreen>﻿उपचरित-असद्भूत व्‍यवहार-नय</font></font></a></li>");
document.write("        <li><a href='209.html'><font size=4><font color=darkPurple><b>209</b></font> - <font color=darkBlue>﻿सद्भूत व्‍यवहार-नय</font></font></a></li>");
document.write("        <li><a href='210.html'><font size=4><font color=darkPurple><b>210</b></font> - <font color=darkGreen>﻿असद्भूत व्‍यवहार-नय</font></font></a></li>");
document.write("        <li><a href='211.html'><font size=4><font color=darkPurple><b>211</b></font> - <font color=darkBlue>﻿उपचार पृथक् नय नहीं</font></font></a></li>");
document.write("        <li><a href='212.html'><font size=4><font color=darkPurple><b>212</b></font> - <font color=darkGreen>﻿उपचार कब ?</font></font></a></li>");
document.write("        <li><a href='213.html'><font size=4><font color=darkPurple><b>213</b></font> - <font color=darkBlue>﻿सम्‍बन्‍ध के प्रकार</font></font></a></li>");
document.write("        <li><a href='216.html'><font size=4><br><font size=5 color=black><b>﻿अध्यात्म-नय </b></font><br><br><font color=darkPurple><b>216</b></font> - <font color=darkGreen>﻿विषय</font></font></a></li>");
document.write("        <li><a href='217.html'><font size=4><font color=darkPurple><b>217</b></font> - <font color=darkBlue>﻿निश्‍चय-नय के प्रकार</font></font></a></li>");
document.write("        <li><a href='218.html'><font size=4><font color=darkPurple><b>218</b></font> - <font color=darkGreen>﻿शुद्धनिश्‍चय-नय</font></font></a></li>");
document.write("        <li><a href='219.html'><font size=4><font color=darkPurple><b>219</b></font> - <font color=darkBlue>﻿अशुद्ध निश्‍चय-नय</font></font></a></li>");
document.write("        <li><a href='220.html'><font size=4><font color=darkPurple><b>220</b></font> - <font color=darkGreen>﻿व्‍यवहारनय के प्रकार</font></font></a></li>");
document.write("        <li><a href='221.html'><font size=4><font color=darkPurple><b>221</b></font> - <font color=darkBlue>﻿सद्भूत व्‍यवहार-नय</font></font></a></li>");
document.write("        <li><a href='222.html'><font size=4><font color=darkPurple><b>222</b></font> - <font color=darkGreen>﻿असद्भूत व्‍यवहार-नय</font></font></a></li>");
document.write("        <li><a href='223.html'><font size=4><font color=darkPurple><b>223</b></font> - <font color=darkBlue>﻿सद्भूत व्‍यवहार-नय</font></font></a></li>");
document.write("        <li><a href='224.html'><font size=4><font color=darkPurple><b>224</b></font> - <font color=darkGreen>﻿उपचरित सद्भूत व्‍यवहार-नय</font></font></a></li>");
document.write("        <li><a href='225.html'><font size=4><font color=darkPurple><b>225</b></font> - <font color=darkBlue>﻿अनुपचरित सद्भूत व्‍यवहार-नय</font></font></a></li>");
document.write("        <li><a href='226.html'><font size=4><font color=darkPurple><b>226</b></font> - <font color=darkGreen>﻿असद्भूत व्‍यवहार-नय के प्रकार</font></font></a></li>");
document.write("        <li><a href='227.html'><font size=4><font color=darkPurple><b>227</b></font> - <font color=darkBlue>﻿उपचरितासद्भूत व्‍यवहार-नय</font></font></a></li>");
document.write("        <li><a href='228.html'><font size=4><font color=darkPurple><b>228</b></font> - <font color=darkGreen>﻿अनुपचरितासद्भूत व्‍यवहार-नय</font></font></a></li>");
document.write("</ul></div>");
