document.write("<div id=सिद्धांत-बोधिनी class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='001.html'><font size=4><font color=darkPurple><b>001</b></font> - <font color=darkBlue>﻿मंगलाचरण</font></font></a></li>");
document.write("        <li><a href='002.html'><font size=4><font color=darkPurple><b>002</b></font> - <font color=darkGreen>﻿जीव में प्रथमोपशम सम्यग्दर्शन को प्राप्त करने की योग्यता बताते है</font></font></a></li>");
document.write("        <li><a href='003.html'><font size=4><font color=darkPurple><b>003</b></font> - <font color=darkBlue>﻿जीव के सम्यक्त्वोत्पत्ति से पूर्व मिथ्यात्व गुणस्थान में होने वाली पांच लब्धियां</font></font></a></li>");
document.write("        <li><a href='004.html'><font size=4><font color=darkPurple><b>004</b></font> - <font color=darkGreen>﻿क्षयोपशम लब्धि का स्वरुप</font></font></a></li>");
document.write("        <li><a href='005.html'><font size=4><font color=darkPurple><b>005</b></font> - <font color=darkBlue>﻿विशुद्धि लब्धि का स्वरूप</font></font></a></li>");
document.write("        <li><a href='006.html'><font size=4><font color=darkPurple><b>006</b></font> - <font color=darkGreen>﻿देशना लब्धि का स्वरुप</font></font></a></li>");
document.write("        <li><a href='007.html'><font size=4><font color=darkPurple><b>007</b></font> - <font color=darkBlue>﻿प्रायोग्य लब्धि का स्वरुप</font></font></a></li>");
document.write("        <li><a href='008.html'><font size=4><font color=darkPurple><b>008</b></font> - <font color=darkGreen>﻿प्रथमोपशम सम्यक्त्व  ग्रहण करने की योग्यता का प्रतिपादन</font></font></a></li>");
document.write("        <li><a href='009.html'><font size=4><font color=darkPurple><b>009</b></font> - <font color=darkBlue>﻿प्रथमोपशम सम्यक्त्व के अभिमुख हुए जीव के स्थिति बंध योग्य परिणाम निम्न सूत्र में  बताये गए है</font></font></a></li>");
document.write("        <li><a href='010.html'><font size=4><font color=darkPurple><b>010</b></font> - <font color=darkGreen>﻿प्रायोग्य-लब्धि काल में प्रकृति-बंधापसरण</font></font></a></li>");
document.write("        <li><a href='011-015.html'><font size=4><font color=darkPurple><b>011-015</b></font> - <font color=darkBlue>﻿चौतीस प्रकृति बन्धापसरणों (व्युच्छेद) का ५ गाथाओं में वर्णन</font></font></a></li>");
document.write("        <li><a href='016-017-018.html'><font size=4><font color=darkPurple><b>016-017-018</b></font> - <font color=darkGreen>﻿नर, तिर्यंच और देवगति में, रत्नादि ६ पृथिवियों और सनत्कुमार आदि दश कल्पों में और आनतकल्प आदि में बंधपसरणों के निर्देश -</font></font></a></li>");
document.write("        <li><a href='019.html'><font size=4><font color=darkPurple><b>019</b></font> - <font color=darkBlue>﻿सातवे नरकपृथिवी में बन्धापसरण</font></font></a></li>");
document.write("        <li><a href='020.html'><font size=4><font color=darkPurple><b>020</b></font> - <font color=darkGreen>﻿मनुष्य और तिर्यंचगति में प्रथमोपशम सम्यक्त्व के अभिमुख मिथ्यादृष्टि जीव के द्वारा बध्यमान प्रकृतिया</font></font></a></li>");
document.write("        <li><a href='021.html'><font size=4><font color=darkPurple><b>021</b></font> - <font color=darkBlue>﻿अप्रमत्त गुणस्थान में बंधने वाली २८ प्रकृतियाँ</font></font></a></li>");
document.write("        <li><a href='022.html'><font size=4><font color=darkPurple><b>022</b></font> - <font color=darkGreen>﻿प्रथमोपशसम्यक्तव के अभिमुख देव और नारकी (छट्टी पृथिवी तक) द्वारा बढ़ी कर्म प्रकृतियाँ</font></font></a></li>");
document.write("        <li><a href='023.html'><font size=4><font color=darkPurple><b>023</b></font> - <font color=darkBlue>﻿सातवी पृथ्वी के  नारकी द्वारा  बंध प्रकृतियाँ</font></font></a></li>");
document.write("        <li><a href='024.html'><font size=4><font color=darkPurple><b>024</b></font> - <font color=darkGreen>﻿सम्यक्त्व के अभिमुख मिथिदृष्टि जीव के स्थिति-अनुभाग बंध के भेद</font></font></a></li>");
document.write("        <li><a href='025.html'><font size=4><font color=darkPurple><b>025</b></font> - <font color=darkBlue>﻿सम्यक्त्व के अभिमुख मिथिदृष्टि जीव के प्रदेशबंध के विभाग</font></font></a></li>");
document.write("        <li><a href='026.html'><font size=4>026</font></a></li>");
document.write("        <li><a href='027.html'><font size=4><font color=darkPurple><b>027</b></font> - <font color=darkBlue>﻿उक्त तीन महादण्डकों में अपुनरुक्त प्रकृतियाँ</font></font></a></li>");
document.write("        <li><a href='028.html'><font size=4><font color=darkPurple><b>028</b></font> - <font color=darkGreen>﻿प्रथमोपशम सम्यक्त्व के अभिमुख विशुद्ध मिथ्यादृष्टि के प्रकृति-स्थिति अनुभाग और प्रदेशों  का उदय</font></font></a></li>");
document.write("        <li><a href='029-030.html'><font size=4><font color=darkPurple><b>029-030</b></font> - <font color=darkBlue>﻿प्रथमोपशम सम्यक्त्व के अभिमुख विशुद्ध मिथ्यादृष्टि के उदय प्रकृति संबंधी स्थिति, अनुभाग तथा प्रदेशों की उदय-उदीरणा का कथन</font></font></a></li>");
document.write("        <li><a href='31.html'><font size=4><font color=darkPurple><b>31</b></font> - <font color=darkGreen>﻿प्रकृतियों के सत्त्व का कथन</font></font></a></li>");
document.write("        <li><a href='32.html'><font size=4><font color=darkPurple><b>32</b></font> - <font color=darkBlue>﻿सत्त्व प्रकृतियों के स्थिति-अनुभाग और  प्रदेश बंध </font></font></a></li>");
document.write("        <li><a href='33.html'><font size=4><font color=darkPurple><b>33</b></font> - <font color=darkGreen>﻿पंचम-करण लब्धि</font></font></a></li>");
document.write("        <li><a href='34.html'><font size=4><font color=darkPurple><b>34</b></font> - <font color=darkBlue>﻿तीनों करणों का काल अल्पबहुत्व सहित</font></font></a></li>");
document.write("        <li><a href='35.html'><font size=4><font color=darkPurple><b>35</b></font> - <font color=darkGreen>﻿प्रथम करण को अध:करण कहने का कारण</font></font></a></li>");
document.write("        <li><a href='36.html'><font size=4><font color=darkPurple><b>36</b></font> - <font color=darkBlue>﻿अपूर्वकरण और अनिवृत्तिकरण के स्वरुप का निरूपण</font></font></a></li>");
document.write("        <li><a href='37.html'><font size=4><font color=darkPurple><b>37</b></font> - <font color=darkGreen>﻿अध:प्रवृत्तकरण संबंधी विशेष (निम्न ५ गाथा) कथन</font></font></a></li>");
document.write("        <li><a href='38.html'><font size=4>38</font></a></li>");
document.write("        <li><a href='39.html'><font size=4>39</font></a></li>");
document.write("        <li><a href='40.html'><font size=4>40</font></a></li>");
document.write("        <li><a href='41.html'><font size=4>41</font></a></li>");
document.write("        <li><a href='42.html'><font size=4><font color=darkPurple><b>42</b></font> - <font color=darkBlue>﻿अध: प्रवृत्त करण संबंधी अनुकृष्टि एवं अल्पबहुत्व अनुयोग-द्वार</font></font></a></li>");
document.write("        <li><a href='43.html'><font size=4>43</font></a></li>");
document.write("        <li><a href='44.html'><font size=4>44</font></a></li>");
document.write("</ul></div>");
