document.write("<div id=आर्यिका-ज्ञानमती class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='001.html'><font size=4><font color=darkPurple><b>001</b></font> - <font color=darkBlue>﻿देवों की पूजा आदि से आप महान नहीं हैं</font></font></a></li>");
document.write("        <li><a href='002.html'><font size=4><font color=darkPurple><b>002</b></font> - <font color=darkGreen>﻿विग्रह आदि महोदय से भी आप महान नहीं हैं</font></font></a></li>");
document.write("        <li><a href='003.html'><font size=4><font color=darkPurple><b>003</b></font> - <font color=darkBlue>﻿तीर्थंकरत्व हेतु से भी आप महान नहीं हैं</font></font></a></li>");
document.write("        <li><a href='004.html'><font size=4><font color=darkPurple><b>004</b></font> - <font color=darkGreen>﻿दोषों तथा आवरणों का पूर्णतया अभाव संभव है</font></font></a></li>");
document.write("        <li><a href='005.html'><font size=4><font color=darkPurple><b>005</b></font> - <font color=darkBlue>﻿सर्वज्ञ की व्यवस्था</font></font></a></li>");
document.write("        <li><a href='006.html'><font size=4><font color=darkPurple><b>006</b></font> - <font color=darkGreen>﻿आप ही निर्दोष सर्वज्ञ हैं</font></font></a></li>");
document.write("        <li><a href='007.html'><font size=4><font color=darkPurple><b>007</b></font> - <font color=darkBlue>﻿सर्वथा एकांतवाद प्रमाण से बाधित है</font></font></a></li>");
document.write("        <li><a href='008.html'><font size=4><font color=darkPurple><b>008</b></font> - <font color=darkGreen>﻿एकांत में शुभ-अशुभ आदि नहीं बनते</font></font></a></li>");
document.write("        <li><a href='009.html'><font size=4><font color=darkPurple><b>009</b></font> - <font color=darkBlue>﻿भावैकांत की मान्यता में दोष</font></font></a></li>");
document.write("        <li><a href='010.html'><font size=4><font color=darkPurple><b>010</b></font> - <font color=darkGreen>﻿प्रागभाव-प्रध्वंसाभाव को न मानने में दोष</font></font></a></li>");
document.write("        <li><a href='011.html'><font size=4><font color=darkPurple><b>011</b></font> - <font color=darkBlue>﻿अन्योन्याभाव-अत्यंताभाव को न मानने में दोष</font></font></a></li>");
document.write("        <li><a href='012.html'><font size=4><font color=darkPurple><b>012</b></font> - <font color=darkGreen>﻿अभावैकान्त की मान्यता में दोष</font></font></a></li>");
document.write("        <li><a href='013.html'><font size=4><font color=darkPurple><b>013</b></font> - <font color=darkBlue>﻿एकांतरूप भावाभाव और अवक्तव्य में दोष</font></font></a></li>");
document.write("        <li><a href='014.html'><font size=4><font color=darkPurple><b>014</b></font> - <font color=darkGreen>﻿भाव-अभाव आदि निर्दोष कैसे हैं ?</font></font></a></li>");
document.write("        <li><a href='015.html'><font size=4><font color=darkPurple><b>015</b></font> - <font color=darkBlue>﻿सत् असत् निर्दोष कैसे हैं ?</font></font></a></li>");
document.write("        <li><a href='016.html'><font size=4><font color=darkPurple><b>016</b></font> - <font color=darkGreen>﻿उभय और अवक्तव्य कथन निर्दोष कैसे हैं ?</font></font></a></li>");
document.write("        <li><a href='017.html'><font size=4><font color=darkPurple><b>017</b></font> - <font color=darkBlue>﻿भावधर्म अभाव के साथ रहता है</font></font></a></li>");
document.write("        <li><a href='018.html'><font size=4><font color=darkPurple><b>018</b></font> - <font color=darkGreen>﻿अभाव भाव के साथ रहता है</font></font></a></li>");
document.write("        <li><a href='019.html'><font size=4><font color=darkPurple><b>019</b></font> - <font color=darkBlue>﻿वस्तु भावाभावात्मक है</font></font></a></li>");
document.write("        <li><a href='020.html'><font size=4><font color=darkPurple><b>020</b></font> - <font color=darkGreen>﻿शेष भंग भी नय विवक्षा से बनेंगे</font></font></a></li>");
document.write("        <li><a href='021.html'><font size=4><font color=darkPurple><b>021</b></font> - <font color=darkBlue>﻿वस्तु एक रूप नहीं है</font></font></a></li>");
document.write("        <li><a href='022.html'><font size=4><font color=darkPurple><b>022</b></font> - <font color=darkGreen>﻿प्रत्येक धर्म का अर्थ पृथक् है</font></font></a></li>");
document.write("        <li><a href='023.html'><font size=4><font color=darkPurple><b>023</b></font> - <font color=darkBlue>﻿अन्य धर्मों में भी सप्तभंगी प्रक्रिया करना</font></font></a></li>");
document.write("        <li><a href='024.html'><font size=4><font color=darkPurple><b>024</b></font> - <font color=darkGreen>﻿अद्वैत एकांत में दोष</font></font></a></li>");
document.write("        <li><a href='025.html'><font size=4><font color=darkPurple><b>025</b></font> - <font color=darkBlue>﻿अद्वैत में शुभ-अशुभ आदि द्वैत नहीं बनते </font></font></a></li>");
document.write("        <li><a href='026.html'><font size=4><font color=darkPurple><b>026</b></font> - <font color=darkGreen>﻿अद्वैत में द्वैत आ जाता है</font></font></a></li>");
document.write("        <li><a href='027.html'><font size=4><font color=darkPurple><b>027</b></font> - <font color=darkBlue>﻿अद्वैत के बिना द्वैत कैसे ?</font></font></a></li>");
document.write("        <li><a href='028.html'><font size=4><font color=darkPurple><b>028</b></font> - <font color=darkGreen>﻿पृथक्त्वैकांत नहीं बनता</font></font></a></li>");
document.write("        <li><a href='029.html'><font size=4><font color=darkPurple><b>029</b></font> - <font color=darkBlue>﻿बौद्ध की पृथक्त्व मान्यता में दोष</font></font></a></li>");
document.write("        <li><a href='030.html'><font size=4><font color=darkPurple><b>030</b></font> - <font color=darkGreen>﻿क्या ज्ञान ज्ञेय से सर्वथा भिन्न है</font></font></a></li>");
document.write("        <li><a href='031.html'><font size=4><font color=darkPurple><b>031</b></font> - <font color=darkBlue>﻿बौद्ध के यहाँ वचन किसको कहते हैं ?</font></font></a></li>");
document.write("        <li><a href='032.html'><font size=4><font color=darkPurple><b>032</b></font> - <font color=darkGreen>﻿अद्वैत पृथक्त्व एकान्त में दोष</font></font></a></li>");
document.write("        <li><a href='033.html'><font size=4><font color=darkPurple><b>033</b></font> - <font color=darkBlue>﻿अद्वैत और पृथक्त्व सच्चे भी हैं</font></font></a></li>");
document.write("        <li><a href='034.html'><font size=4><font color=darkPurple><b>034</b></font> - <font color=darkGreen>﻿सभी वस्तुएँ एकत्व और पृथक्त्व रूप केसे हैं ?</font></font></a></li>");
document.write("        <li><a href='035.html'><font size=4><font color=darkPurple><b>035</b></font> - <font color=darkBlue>﻿सत् में ही विवक्षा और अविवक्षा होती है</font></font></a></li>");
document.write("        <li><a href='036.html'><font size=4><font color=darkPurple><b>036</b></font> - <font color=darkGreen>﻿एक वस्तु में भेद और अभेद दोनों केसे होंगे ?</font></font></a></li>");
document.write("        <li><a href='037.html'><font size=4><font color=darkPurple><b>037</b></font> - <font color=darkBlue>﻿वस्तु को सर्वथा नित्य मानने में दोष</font></font></a></li>");
document.write("        <li><a href='038.html'><font size=4><font color=darkPurple><b>038</b></font> - <font color=darkGreen>﻿प्रमाण और कारकों के नित्य होने में विक्रिया केसी ?</font></font></a></li>");
document.write("        <li><a href='039.html'><font size=4><font color=darkPurple><b>039</b></font> - <font color=darkBlue>﻿सर्वथा सत् रूप कार्य उत्पन्न केसे होगा ?</font></font></a></li>");
document.write("        <li><a href='040.html'><font size=4><font color=darkPurple><b>040</b></font> - <font color=darkGreen>﻿नित्य एकांत में पुण्य पापादि भी असंभव हैं</font></font></a></li>");
document.write("        <li><a href='041.html'><font size=4><font color=darkPurple><b>041</b></font> - <font color=darkBlue>﻿क्षणिक एकांत भी असंभव है</font></font></a></li>");
document.write("        <li><a href='042.html'><font size=4><font color=darkPurple><b>042</b></font> - <font color=darkGreen>﻿कार्य सर्वथा असत् से केसे होगा ?</font></font></a></li>");
document.write("        <li><a href='043.html'><font size=4><font color=darkPurple><b>043</b></font> - <font color=darkBlue>﻿क्षणिक एकांत में कार्यकारण भाव असंभव है</font></font></a></li>");
document.write("        <li><a href='044.html'><font size=4><font color=darkPurple><b>044</b></font> - <font color=darkGreen>﻿बौद्ध भिन्न-भिन्न कार्यक्षणों में एकत्व को संवृति से मानता है</font></font></a></li>");
document.write("        <li><a href='045.html'><font size=4><font color=darkPurple><b>045</b></font> - <font color=darkBlue>﻿बौद्ध के यहाँ चतुष्कोटि विकल्प अवक्तव्य है</font></font></a></li>");
document.write("        <li><a href='046.html'><font size=4><font color=darkPurple><b>046</b></font> - <font color=darkGreen>﻿एकांत से अवक्तव्य मान्यता में दोष</font></font></a></li>");
document.write("        <li><a href='047.html'><font size=4><font color=darkPurple><b>047</b></font> - <font color=darkBlue>﻿असत् का निषेध होता है क्या ?</font></font></a></li>");
document.write("        <li><a href='048.html'><font size=4><font color=darkPurple><b>048</b></font> - <font color=darkGreen>﻿अवस्तु ही अवक्तव्य है</font></font></a></li>");
document.write("        <li><a href='049.html'><font size=4><font color=darkPurple><b>049</b></font> - <font color=darkBlue>﻿सभी धर्मों से रहित को कहा नहीं जा सकता</font></font></a></li>");
document.write("        <li><a href='050.html'><font size=4><font color=darkPurple><b>050</b></font> - <font color=darkGreen>﻿आप बौद्ध वस्तु को अवाच्य क्यों मानते हो ?</font></font></a></li>");
document.write("        <li><a href='051.html'><font size=4><font color=darkPurple><b>051</b></font> - <font color=darkBlue>﻿सर्वथा क्षणिक में कृतनाश आदि दोष आते हैं</font></font></a></li>");
document.write("        <li><a href='052.html'><font size=4><font color=darkPurple><b>052</b></font> - <font color=darkGreen>﻿नाश को निर्हेतुक मानने में दोष</font></font></a></li>");
document.write("        <li><a href='053.html'><font size=4><font color=darkPurple><b>053</b></font> - <font color=darkBlue>﻿बौद्ध ने हेतु को विसदृश कार्य के लिए माना है</font></font></a></li>");
document.write("        <li><a href='054.html'><font size=4><font color=darkPurple><b>054</b></font> - <font color=darkGreen>﻿बौद्ध के यहाँ स्कंधादी में उत्पादादि नहीं बनते हैं</font></font></a></li>");
document.write("        <li><a href='055.html'><font size=4><font color=darkPurple><b>055</b></font> - <font color=darkBlue>﻿नित्य क्षणिक का उभय एकांत सदोष है</font></font></a></li>");
document.write("        <li><a href='056.html'><font size=4><font color=darkPurple><b>056</b></font> - <font color=darkGreen>﻿नित्य और क्षणिक स्याद्वाद में निर्दोष हैं</font></font></a></li>");
document.write("        <li><a href='057.html'><font size=4><font color=darkPurple><b>057</b></font> - <font color=darkBlue>﻿उत्पाद, व्यय, ध्रौव्य की व्यवस्था</font></font></a></li>");
document.write("        <li><a href='058.html'><font size=4><font color=darkPurple><b>058</b></font> - <font color=darkGreen>﻿उत्पाद आदि अभिन्न हैं</font></font></a></li>");
document.write("        <li><a href='059.html'><font size=4><font color=darkPurple><b>059</b></font> - <font color=darkBlue>﻿एक द्रव्य के नाश आदि में भिन्न भाव होते है</font></font></a></li>");
document.write("        <li><a href='060.html'><font size=4><font color=darkPurple><b>060</b></font> - <font color=darkGreen>﻿वस्तु तत्त्व त्रयात्मक है</font></font></a></li>");
document.write("        <li><a href='061.html'><font size=4><font color=darkPurple><b>061</b></font> - <font color=darkBlue>﻿क्या कार्य कारण आदि सर्वथा भिन्न हैं ?</font></font></a></li>");
document.write("        <li><a href='062.html'><font size=4><font color=darkPurple><b>062</b></font> - <font color=darkGreen>﻿वैशेषिक के सर्वथा भिन्नैकांत में दोष</font></font></a></li>");
document.write("        <li><a href='063.html'><font size=4><font color=darkPurple><b>063</b></font> - <font color=darkBlue>﻿वैशेषिक को देश-काल भेद भी मानना चाहिए</font></font></a></li>");
document.write("        <li><a href='064.html'><font size=4><font color=darkPurple><b>064</b></font> - <font color=darkGreen>﻿समवाय से वृत्ति मानने में दोष</font></font></a></li>");
document.write("        <li><a href='065.html'><font size=4><font color=darkPurple><b>065</b></font> - <font color=darkBlue>﻿सामान्य समवाय एक-एक हैं</font></font></a></li>");
document.write("        <li><a href='066.html'><font size=4><font color=darkPurple><b>066</b></font> - <font color=darkGreen>﻿सामान्य समवाय भी परस्पर में भिन्न हैं</font></font></a></li>");
document.write("        <li><a href='067.html'><font size=4><font color=darkPurple><b>067</b></font> - <font color=darkBlue>﻿परमाणु की अन्यरूप परिणति न मानने में दोष</font></font></a></li>");
document.write("        <li><a href='068.html'><font size=4><font color=darkPurple><b>068</b></font> - <font color=darkGreen>﻿कार्य भ्रांत है तो कारण भी भ्रांत है</font></font></a></li>");
document.write("        <li><a href='069.html'><font size=4><font color=darkPurple><b>069</b></font> - <font color=darkBlue>﻿सांख्य के यहाँ कार्यकारणादि में एकत्व ही है</font></font></a></li>");
document.write("        <li><a href='070.html'><font size=4><font color=darkPurple><b>070</b></font> - <font color=darkGreen>﻿सर्वथा भिन्न-अभिन्न की उभय और अवाच्य भी सदोष है</font></font></a></li>");
document.write("        <li><a href='071.html'><font size=4><font color=darkPurple><b>071</b></font> - <font color=darkBlue>﻿कथंचित् कार्य-कारण आदि का भेद-अभेद ठीक है</font></font></a></li>");
document.write("        <li><a href='072.html'><font size=4><font color=darkPurple><b>072</b></font> - <font color=darkGreen>﻿</font></font></a></li>");
document.write("        <li><a href='073.html'><font size=4><font color=darkPurple><b>073</b></font> - <font color=darkBlue>﻿धर्म, धर्मी सर्वथा आपेक्षिक या अनापेक्षिक ही नहीं है</font></font></a></li>");
document.write("        <li><a href='074.html'><font size=4><font color=darkPurple><b>074</b></font> - <font color=darkGreen>﻿आपेक्षिक-अनापेक्षिक का उभय एवं अवाच्य एकांत से नहीं घटता</font></font></a></li>");
document.write("        <li><a href='075.html'><font size=4><font color=darkPurple><b>075</b></font> - <font color=darkBlue>﻿आपेक्षिक-अनापेक्षिक की अनेकांत व्यवस्था</font></font></a></li>");
document.write("        <li><a href='076.html'><font size=4><font color=darkPurple><b>076</b></font> - <font color=darkGreen>﻿सर्वथा हेतु सिद्ध या आगम सिद्ध तत्त्व बाधित है</font></font></a></li>");
document.write("        <li><a href='077.html'><font size=4><font color=darkPurple><b>077</b></font> - <font color=darkBlue>﻿हेतु के और आगम के उभय एवं अवाच्य भी सदोष हैं</font></font></a></li>");
document.write("        <li><a href='078.html'><font size=4><font color=darkPurple><b>078</b></font> - <font color=darkGreen>﻿हेतु और आगम का अनेकांत</font></font></a></li>");
document.write("        <li><a href='079.html'><font size=4><font color=darkPurple><b>079</b></font> - <font color=darkBlue>﻿सर्वथा अंतरंग अर्थ मानना सदोष है</font></font></a></li>");
document.write("        <li><a href='080.html'><font size=4><font color=darkPurple><b>080</b></font> - <font color=darkGreen>﻿ज्ञान मात्र मानने से साध्य-साधन भी नहीं बनेंगे</font></font></a></li>");
document.write("        <li><a href='081.html'><font size=4><font color=darkPurple><b>081</b></font> - <font color=darkBlue>﻿सर्वथा बहिरंग अर्थ ही है ऐसा कहना भी सदोष है</font></font></a></li>");
document.write("        <li><a href='082.html'><font size=4><font color=darkPurple><b>082</b></font> - <font color=darkGreen>﻿अंतरंग और बहिरंग अर्थ का उभय और अवाच्य भी सदोष हैं</font></font></a></li>");
document.write("        <li><a href='083.html'><font size=4><font color=darkPurple><b>083</b></font> - <font color=darkBlue>﻿ज्ञान पदार्थ और बाह्य पदार्थ दोनों ही सिद्ध हैं</font></font></a></li>");
document.write("        <li><a href='084.html'><font size=4><font color=darkPurple><b>084</b></font> - <font color=darkGreen>﻿जीव शब्द बाह्य अर्थ से सहित है</font></font></a></li>");
document.write("        <li><a href='085.html'><font size=4><font color=darkPurple><b>085</b></font> - <font color=darkBlue>﻿संज्ञा रूप हेतु निर्दोष है </font></font></a></li>");
document.write("        <li><a href='086.html'><font size=4><font color=darkPurple><b>086</b></font> - <font color=darkGreen>﻿विज्ञानाद्वैतवादी का समाधान</font></font></a></li>");
document.write("        <li><a href='087.html'><font size=4><font color=darkPurple><b>087</b></font> - <font color=darkBlue>﻿ज्ञान और शब्द की प्रमाणता कैसे है ?</font></font></a></li>");
document.write("        <li><a href='088.html'><font size=4><font color=darkPurple><b>088</b></font> - <font color=darkGreen>﻿क्या भाग्य से ही सभी कार्य सिद्ध हो सकते हैं ?</font></font></a></li>");
document.write("        <li><a href='089.html'><font size=4><font color=darkPurple><b>089</b></font> - <font color=darkBlue>﻿क्या एकांत से पुरुषार्थ से ही कार्य सिद्ध होते हैं ?</font></font></a></li>");
document.write("        <li><a href='090.html'><font size=4><font color=darkPurple><b>090</b></font> - <font color=darkGreen>﻿भाग्य-पुरुषार्थ के उभय एवं अवाच्य का खंडन</font></font></a></li>");
document.write("        <li><a href='091.html'><font size=4><font color=darkPurple><b>091</b></font> - <font color=darkBlue>﻿भाग्य और पुरुषार्थ का अनेकांत</font></font></a></li>");
document.write("        <li><a href='092.html'><font size=4><font color=darkPurple><b>092</b></font> - <font color=darkGreen>﻿क्या पर को सुख-दु:ख देने से ही पुण्य-पाप बंध निश्चित है ?</font></font></a></li>");
document.write("        <li><a href='093.html'><font size=4><font color=darkPurple><b>093</b></font> - <font color=darkBlue>﻿क्या स्वयं में दु:ख-सुख से पुण्य-पाप होता है ?</font></font></a></li>");
document.write("        <li><a href='094.html'><font size=4><font color=darkPurple><b>094</b></font> - <font color=darkGreen>﻿पुण्य-पाप का उभय एवं अवक्तव्य भी एकांत से सदोष है</font></font></a></li>");
document.write("        <li><a href='095.html'><font size=4><font color=darkPurple><b>095</b></font> - <font color=darkBlue>﻿पुन: पुण्य-पाप का बंध कैसे होता है ?</font></font></a></li>");
document.write("        <li><a href='096.html'><font size=4><font color=darkPurple><b>096</b></font> - <font color=darkGreen>﻿क्या अज्ञान से बंध और अल्पज्ञान से मोक्ष होता है ?</font></font></a></li>");
document.write("        <li><a href='097.html'><font size=4><font color=darkPurple><b>097</b></font> - <font color=darkBlue>﻿अज्ञान, अल्पज्ञान से बंध-मोक्ष का उभय और अवक्तव्य नहीं बनता है</font></font></a></li>");
document.write("        <li><a href='098.html'><font size=4><font color=darkPurple><b>098</b></font> - <font color=darkGreen>﻿अज्ञान से बंध एवं अल्पज्ञान से मोक्ष की सुंदर व्यवस्था</font></font></a></li>");
document.write("        <li><a href='099.html'><font size=4><font color=darkPurple><b>099</b></font> - <font color=darkBlue>﻿कर्मबंध के अनुसार संसार विचित्र है</font></font></a></li>");
document.write("        <li><a href='100.html'><font size=4><font color=darkPurple><b>100</b></font> - <font color=darkGreen>﻿शुद्धि-अशुद्धि शक्तियाँ कैसी हैं</font></font></a></li>");
document.write("        <li><a href='101.html'><font size=4><font color=darkPurple><b>101</b></font> - <font color=darkBlue>﻿प्रमाण का लक्षण और भेद</font></font></a></li>");
document.write("        <li><a href='102.html'><font size=4><font color=darkPurple><b>102</b></font> - <font color=darkGreen>﻿प्रमाणों का फल क्या है ?</font></font></a></li>");
document.write("        <li><a href='103.html'><font size=4><font color=darkPurple><b>103</b></font> - <font color=darkBlue>﻿‘स्यात्’ शब्द का महत्व</font></font></a></li>");
document.write("        <li><a href='104.html'><font size=4><font color=darkPurple><b>104</b></font> - <font color=darkGreen>﻿स्याद्वाद का स्वरूप</font></font></a></li>");
document.write("        <li><a href='105.html'><font size=4><font color=darkPurple><b>105</b></font> - <font color=darkBlue>﻿स्याद्वाद और केवलज्ञान में क्या अंतर है ?</font></font></a></li>");
document.write("        <li><a href='106.html'><font size=4><font color=darkPurple><b>106</b></font> - <font color=darkGreen>﻿नय और हेतु का लक्षण</font></font></a></li>");
document.write("        <li><a href='107.html'><font size=4><font color=darkPurple><b>107</b></font> - <font color=darkBlue>﻿द्रव्य का स्वरूप</font></font></a></li>");
document.write("        <li><a href='108.html'><font size=4><font color=darkPurple><b>108</b></font> - <font color=darkGreen>﻿मिथ्यानय-सम्यकनय का लक्षण</font></font></a></li>");
document.write("        <li><a href='109.html'><font size=4><font color=darkPurple><b>109</b></font> - <font color=darkBlue>﻿वस्तु को विधि आदि के द्वारा कहते है</font></font></a></li>");
document.write("        <li><a href='110.html'><font size=4><font color=darkPurple><b>110</b></font> - <font color=darkGreen>﻿उभयात्मक वस्तु को एक रूप कहना मिथ्या है</font></font></a></li>");
document.write("        <li><a href='111.html'><font size=4><font color=darkPurple><b>111</b></font> - <font color=darkBlue>﻿वचन का वास्तविक स्वभाव क्या है ?</font></font></a></li>");
document.write("        <li><a href='112.html'><font size=4><font color=darkPurple><b>112</b></font> - <font color=darkGreen>﻿स्यात्कार ही अभिप्रेत को प्राप्त कराने वाला है</font></font></a></li>");
document.write("        <li><a href='113.html'><font size=4><font color=darkPurple><b>113</b></font> - <font color=darkBlue>﻿स्याद्वाद की सम्यक् व्यवस्था</font></font></a></li>");
document.write("        <li><a href='114.html'><font size=4><font color=darkPurple><b>114</b></font> - <font color=darkGreen>﻿आप्त मीमांसा करने का उद्देश्य</font></font></a></li>");
document.write("</ul></div>");
