document.write("<div id=ब्र-यशपाल class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='001.html'><font size=4><font color=darkPurple><b>001</b></font> - <font color=darkBlue>﻿जीव अधिकार - ग्रंथकार का मंगलाचरण एवं उद्देश्य</font></font></a></li>");
document.write("        <li><a href='002-003-004.html'><font size=4><font color=darkPurple><b>002-003-004</b></font> - <font color=darkGreen>﻿जीव एवं अजीव तत्त्वों को जानने का फल</font></font></a></li>");
document.write("        <li><a href='005.html'><font size=4><font color=darkPurple><b>005</b></font> - <font color=darkBlue>﻿निजस्वभाव को जानने का फल</font></font></a></li>");
document.write("        <li><a href='006.html'><font size=4><font color=darkPurple><b>006</b></font> - <font color=darkGreen>﻿आत्मा का लक्षण उपयोग और उसके भेद</font></font></a></li>");
document.write("        <li><a href='007.html'><font size=4><font color=darkPurple><b>007</b></font> - <font color=darkBlue>﻿दर्शन के भेद एवं उसका लक्षण</font></font></a></li>");
document.write("        <li><a href='008-009.html'><font size=4><font color=darkPurple><b>008-009</b></font> - <font color=darkGreen>﻿ज्ञान के भेद एवं उसका लक्षण</font></font></a></li>");
document.write("        <li><a href='010.html'><font size=4><font color=darkPurple><b>010</b></font> - <font color=darkBlue>﻿केवलज्ञान व केवलदर्शन के उत्पत्ति में कारण</font></font></a></li>");
document.write("        <li><a href='011.html'><font size=4><font color=darkPurple><b>011</b></font> - <font color=darkGreen>﻿दर्शन और ज्ञान की उत्पत्ति का क्रम</font></font></a></li>");
document.write("        <li><a href='012.html'><font size=4><font color=darkPurple><b>012</b></font> - <font color=darkBlue>﻿मिथ्याज्ञान और सम्यग्ज्ञान के कारण</font></font></a></li>");
document.write("        <li><a href='013.html'><font size=4><font color=darkPurple><b>013</b></font> - <font color=darkGreen>﻿मिथ्यात्व का स्वरूप और कार्य</font></font></a></li>");
document.write("        <li><a href='014.html'><font size=4><font color=darkPurple><b>014</b></font> - <font color=darkBlue>﻿दर्शनमोहनीय कर्म के तीन भेद</font></font></a></li>");
document.write("        <li><a href='015.html'><font size=4><font color=darkPurple><b>015</b></font> - <font color=darkGreen>﻿मिथ्यात्व का स्वरूप</font></font></a></li>");
document.write("        <li><a href='016.html'><font size=4><font color=darkPurple><b>016</b></font> - <font color=darkBlue>﻿सम्यक्त्व का स्वरूप</font></font></a></li>");
document.write("        <li><a href='017-018.html'><font size=4><font color=darkPurple><b>017-018</b></font> - <font color=darkGreen>﻿सम्यक्त्व के भेद और उनमें कारण-कार्यपना</font></font></a></li>");
document.write("        <li><a href='019.html'><font size=4><font color=darkPurple><b>019</b></font> - <font color=darkBlue>﻿आत्मा का ज्ञानप्रमाणपना और ज्ञान का सर्वगतत्व</font></font></a></li>");
document.write("        <li><a href='020.html'><font size=4><font color=darkPurple><b>020</b></font> - <font color=darkGreen>﻿आत्मा से ज्ञान को अधिक मानने पर आपत्ति</font></font></a></li>");
document.write("        <li><a href='021.html'><font size=4><font color=darkPurple><b>021</b></font> - <font color=darkBlue>﻿ज्ञेयक्षिप्त ज्ञान की व्यापकता</font></font></a></li>");
document.write("        <li><a href='022.html'><font size=4><font color=darkPurple><b>022</b></font> - <font color=darkGreen>﻿ज्ञेय को जानता हुआ ज्ञान ज्ञेयरूप नहीं होता</font></font></a></li>");
document.write("        <li><a href='023.html'><font size=4><font color=darkPurple><b>023</b></font> - <font color=darkBlue>﻿ज्ञान, दूरवर्ती पदार्थ को भी स्वभाव से जानता है</font></font></a></li>");
document.write("        <li><a href='024.html'><font size=4><font color=darkPurple><b>024</b></font> - <font color=darkGreen>﻿ज्ञान, स्वभाव से ही स्व-पर प्रकाशक है</font></font></a></li>");
document.write("        <li><a href='025.html'><font size=4><font color=darkPurple><b>025</b></font> - <font color=darkBlue>﻿क्षायोपशमिक एवं क्षायिक ज्ञान का स्वरूप</font></font></a></li>");
document.write("        <li><a href='026.html'><font size=4><font color=darkPurple><b>026</b></font> - <font color=darkGreen>﻿केवलज्ञान की सत्-असत् विषय में प्रवृत्ति</font></font></a></li>");
document.write("        <li><a href='027.html'><font size=4><font color=darkPurple><b>027</b></font> - <font color=darkBlue>﻿सत्-असत् पदार्थों का खुलासा </font></font></a></li>");
document.write("        <li><a href='028.html'><font size=4><font color=darkPurple><b>028</b></font> - <font color=darkGreen>﻿भूत-भावी पदार्थों को जानने का स्वरूप</font></font></a></li>");
document.write("        <li><a href='029-030.html'><font size=4><font color=darkPurple><b>029-030</b></font> - <font color=darkBlue>﻿सब पदार्थों में केवलज्ञान के युगपत प्रवृत्त न होने पर दोषापत्ति</font></font></a></li>");
document.write("        <li><a href='031.html'><font size=4><font color=darkPurple><b>031</b></font> - <font color=darkGreen>﻿भव्यात्मा ही परमात्मा के स्वरूप को स्वीकारता है</font></font></a></li>");
document.write("        <li><a href='032.html'><font size=4><font color=darkPurple><b>032</b></font> - <font color=darkBlue>﻿निज शुद्धात्मा का स्वरूप एवं उसके श्रद्धान का फल</font></font></a></li>");
document.write("        <li><a href='033.html'><font size=4><font color=darkPurple><b>033</b></font> - <font color=darkGreen>﻿आत्मसाधक का एवं आत्मा का स्वरूप</font></font></a></li>");
document.write("        <li><a href='034.html'><font size=4><font color=darkPurple><b>034</b></font> - <font color=darkBlue>﻿श्रुतज्ञान से भी केवलज्ञान के समान आत्मबोध की प्राप्ति</font></font></a></li>");
document.write("        <li><a href='035.html'><font size=4><font color=darkPurple><b>035</b></font> - <font color=darkGreen>﻿सम्यक्चारित्र की उत्पत्ति का काल</font></font></a></li>");
document.write("        <li><a href='036.html'><font size=4><font color=darkPurple><b>036</b></font> - <font color=darkBlue>﻿कषाय से स्वभावच्युत आत्मा के व्रत नहीं</font></font></a></li>");
document.write("        <li><a href='037.html'><font size=4><font color=darkPurple><b>037</b></font> - <font color=darkGreen>﻿आत्मरमणता से पापों का पलायन</font></font></a></li>");
document.write("        <li><a href='038.html'><font size=4><font color=darkPurple><b>038</b></font> - <font color=darkBlue>﻿आत्मा के ध्यान से कर्मों से छुटकारा</font></font></a></li>");
document.write("        <li><a href='039.html'><font size=4><font color=darkPurple><b>039</b></font> - <font color=darkGreen>﻿आत्मध्यान से विमुख योगी का स्वरूप</font></font></a></li>");
document.write("        <li><a href='040.html'><font size=4><font color=darkPurple><b>040</b></font> - <font color=darkBlue>﻿निश्चयचारित्र का स्वरूप</font></font></a></li>");
document.write("        <li><a href='041.html'><font size=4><font color=darkPurple><b>041</b></font> - <font color=darkGreen>﻿व्यवहाररत्नत्रय का स्वरूप</font></font></a></li>");
document.write("        <li><a href='042.html'><font size=4><font color=darkPurple><b>042</b></font> - <font color=darkBlue>﻿रत्नत्रय परिणत आत्मा ही मोक्षमार्ग है</font></font></a></li>");
document.write("        <li><a href='043.html'><font size=4><font color=darkPurple><b>043</b></font> - <font color=darkGreen>﻿आत्मा, स्वयं दर्शन-ज्ञान-चारित्र है</font></font></a></li>");
document.write("        <li><a href='044.html'><font size=4><font color=darkPurple><b>044</b></font> - <font color=darkBlue>﻿निज शुद्धात्मा की उपासना ही निर्वाणसुख का उपाय</font></font></a></li>");
document.write("        <li><a href='045.html'><font size=4><font color=darkPurple><b>045</b></font> - <font color=darkGreen>﻿आत्मस्वरूप की अनुभूति का उपाय</font></font></a></li>");
document.write("        <li><a href='046.html'><font size=4><font color=darkPurple><b>046</b></font> - <font color=darkBlue>﻿केवलज्ञान, आत्मा का उत्तम स्वरूप</font></font></a></li>");
document.write("        <li><a href='047.html'><font size=4><font color=darkPurple><b>047</b></font> - <font color=darkGreen>﻿अणुात्र राग भी पाप का बंधक</font></font></a></li>");
document.write("        <li><a href='048.html'><font size=4><font color=darkPurple><b>048</b></font> - <font color=darkBlue>﻿परमेष्ठी की उपासना से कर्मक्षय नहीं होता </font></font></a></li>");
document.write("        <li><a href='049.html'><font size=4><font color=darkPurple><b>049</b></font> - <font color=darkGreen>﻿आस्रव रोकने/संवर का एकमेव उपाय</font></font></a></li>");
document.write("        <li><a href='050.html'><font size=4><font color=darkPurple><b>050</b></font> - <font color=darkBlue>﻿परद्रव्योपासक जीव का स्वरूप</font></font></a></li>");
document.write("        <li><a href='051.html'><font size=4><font color=darkPurple><b>051</b></font> - <font color=darkGreen>﻿ध्याता, ध्येय के अनुसार हो जाता है</font></font></a></li>");
document.write("        <li><a href='052.html'><font size=4><font color=darkPurple><b>052</b></font> - <font color=darkBlue>﻿ध्येयरूप विविक्तात्मा/शुद्धात्मा का स्वरूप</font></font></a></li>");
document.write("        <li><a href='053.html'><font size=4><font color=darkPurple><b>053</b></font> - <font color=darkGreen>﻿आत्मा में स्वभाव से वर्णादि का अभाव</font></font></a></li>");
document.write("        <li><a href='054.html'><font size=4><font color=darkPurple><b>054</b></font> - <font color=darkBlue>﻿शरीरसंयोग से वर्णादिक शुद्धात्मा के कहे जाते हैं</font></font></a></li>");
document.write("        <li><a href='055-056.html'><font size=4><font color=darkPurple><b>055-056</b></font> - <font color=darkGreen>﻿औदयिक भावों को जीव का स्वभाव मानने से आपत्ति</font></font></a></li>");
document.write("        <li><a href='057.html'><font size=4><font color=darkPurple><b>057</b></font> - <font color=darkBlue>﻿गुणस्थानादि जीव नहीं हैं</font></font></a></li>");
document.write("        <li><a href='058.html'><font size=4><font color=darkPurple><b>058</b></font> - <font color=darkGreen>﻿क्षायोपशमिक ज्ञानादि भाव शुद्धजीव का स्वरूप नहीं</font></font></a></li>");
document.write("        <li><a href='059.html'><font size=4><font color=darkPurple><b>059</b></font> - <font color=darkBlue>﻿निज शुद्धात्मा के ध्यान से मुक्ति</font></font></a></li>");
document.write("</ul></div>");
