document.write("<div id=सर्वार्थसिद्धि class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='001.html'><font size=4><br><font size=5 color=black><b>﻿अधिकार-१ (जीवाधिकार) </b></font><br><br><font color=darkPurple><b>001</b></font> - <font color=darkBlue>﻿सम्यग्दर्शनज्ञानचारित्राणि मोक्षमार्गः॥१॥</font></font></a></li>");
document.write("        <li><a href='002.html'><font size=4><font color=darkPurple><b>002</b></font> - <font color=darkGreen>﻿तत्त्वार्थश्रद्धानं सम्यग्दर्शनम्॥२॥</font></font></a></li>");
document.write("        <li><a href='003.html'><font size=4><font color=darkPurple><b>003</b></font> - <font color=darkBlue>﻿तन्निसर्गादधिगमाद्वा॥३॥</font></font></a></li>");
document.write("        <li><a href='004.html'><font size=4><font color=darkPurple><b>004</b></font> - <font color=darkGreen>﻿जीवजीवास्रवबन्धसंवरनिर्जरामोक्षास्तत्त्वम्॥४॥</font></font></a></li>");
document.write("        <li><a href='005.html'><font size=4><font color=darkPurple><b>005</b></font> - <font color=darkBlue>﻿नामस्थापनाद्रव्यभाव तस्तन्न्यासः॥५॥</font></font></a></li>");
document.write("        <li><a href='006.html'><font size=4><font color=darkPurple><b>006</b></font> - <font color=darkGreen>﻿प्रमाणनयैरधिगमः॥६॥</font></font></a></li>");
document.write("        <li><a href='007.html'><font size=4><font color=darkPurple><b>007</b></font> - <font color=darkBlue>﻿निर्देशस्वामित्वसाधनाधिकरणस्थितिविधानतः॥७॥</font></font></a></li>");
document.write("        <li><a href='008.html'><font size=4><font color=darkPurple><b>008</b></font> - <font color=darkGreen>﻿सत्संख्याक्षेत्रस्पर्शनकालान्तरभावाल्पबहुत्वैश्‍च॥८॥</font></font></a></li>");
document.write("        <li><a href='009.html'><font size=4><font color=darkPurple><b>009</b></font> - <font color=darkBlue>﻿मतिश्रुतावधिमनःपर्ययकेवलानि ज्ञानम्॥९॥</font></font></a></li>");
document.write("        <li><a href='010.html'><font size=4><font color=darkPurple><b>010</b></font> - <font color=darkGreen>﻿तत्प्रमाणे॥१०॥</font></font></a></li>");
document.write("        <li><a href='011.html'><font size=4><font color=darkPurple><b>011</b></font> - <font color=darkBlue>﻿आद्ये परोक्षम्॥११॥</font></font></a></li>");
document.write("        <li><a href='012.html'><font size=4><font color=darkPurple><b>012</b></font> - <font color=darkGreen>﻿प्रत्यक्षमन्यत्॥१२॥</font></font></a></li>");
document.write("        <li><a href='013.html'><font size=4><font color=darkPurple><b>013</b></font> - <font color=darkBlue>﻿मतिः स्मृतिः संज्ञा चिन्ताsभिनिबोध इत्यानर्थान्तरम्॥१३॥</font></font></a></li>");
document.write("        <li><a href='014.html'><font size=4><font color=darkPurple><b>014</b></font> - <font color=darkGreen>﻿तदिन्द्रयानिन्द्रिय निमित्तम्॥१४॥</font></font></a></li>");
document.write("        <li><a href='015.html'><font size=4><font color=darkPurple><b>015</b></font> - <font color=darkBlue>﻿अवग्रहेहावाय धारणाः॥१५॥</font></font></a></li>");
document.write("        <li><a href='016.html'><font size=4><font color=darkPurple><b>016</b></font> - <font color=darkGreen>﻿बहुबहुविधक्षिप्रानिःसृतानुक्तध्रुवाणां सेतराणाम्‌॥१६॥</font></font></a></li>");
document.write("        <li><a href='017.html'><font size=4><font color=darkPurple><b>017</b></font> - <font color=darkBlue>﻿अर्थस्य॥१७॥</font></font></a></li>");
document.write("        <li><a href='018.html'><font size=4><font color=darkPurple><b>018</b></font> - <font color=darkGreen>﻿व्यञ्जनस्यावग्रहः॥१८॥</font></font></a></li>");
document.write("        <li><a href='019.html'><font size=4><font color=darkPurple><b>019</b></font> - <font color=darkBlue>﻿न चक्षुरनिन्द्रियाभ्याम्॥१९॥</font></font></a></li>");
document.write("        <li><a href='020.html'><font size=4><font color=darkPurple><b>020</b></font> - <font color=darkGreen>﻿श्रुतं मतिपूर्वं द्वयनेकद्वादशभेदम्‌॥२०॥</font></font></a></li>");
document.write("        <li><a href='021.html'><font size=4><font color=darkPurple><b>021</b></font> - <font color=darkBlue>﻿भवप्रत्ययोऽवधिर्देवनारकाणाम्॥२१॥</font></font></a></li>");
document.write("        <li><a href='022.html'><font size=4><font color=darkPurple><b>022</b></font> - <font color=darkGreen>﻿क्षयोपशमनिमित्तः षड्विकल्पः शेषाणाम्॥२२॥</font></font></a></li>");
document.write("        <li><a href='023.html'><font size=4><font color=darkPurple><b>023</b></font> - <font color=darkBlue>﻿ऋजुविपुलमती मनःपर्ययः॥२३॥</font></font></a></li>");
document.write("        <li><a href='024.html'><font size=4><font color=darkPurple><b>024</b></font> - <font color=darkGreen>﻿विशुद्धयप्रतिपाताभ्यां तद्विशेषः॥२४॥</font></font></a></li>");
document.write("        <li><a href='025.html'><font size=4><font color=darkPurple><b>025</b></font> - <font color=darkBlue>﻿विशुद्धिक्षेत्रस्वामिविषयेभ्योऽवधिमनःपर्यययोः॥२५॥</font></font></a></li>");
document.write("        <li><a href='026.html'><font size=4><font color=darkPurple><b>026</b></font> - <font color=darkGreen>﻿मतिश्रुतयोर्निबन्धो द्रव्येष्वसर्वपर्यायेषु॥२६॥</font></font></a></li>");
document.write("        <li><a href='027.html'><font size=4><font color=darkPurple><b>027</b></font> - <font color=darkBlue>﻿रूपिष्ववधेः॥२७॥</font></font></a></li>");
document.write("        <li><a href='028.html'><font size=4><font color=darkPurple><b>028</b></font> - <font color=darkGreen>﻿तदनन्तभागे मनःपर्ययस्य॥२८॥</font></font></a></li>");
document.write("        <li><a href='029.html'><font size=4><font color=darkPurple><b>029</b></font> - <font color=darkBlue>﻿सर्वद्रव्यपर्यायेषु केवलस्य॥२९॥</font></font></a></li>");
document.write("        <li><a href='030.html'><font size=4><font color=darkPurple><b>030</b></font> - <font color=darkGreen>﻿एकादीनि भाज्यानि युगपदेकस्मिन्नाचतुर्भ्यः॥३०॥</font></font></a></li>");
document.write("        <li><a href='031.html'><font size=4><font color=darkPurple><b>031</b></font> - <font color=darkBlue>﻿मतिश्रुतावधयो विपर्ययश्‍च॥३१॥</font></font></a></li>");
document.write("        <li><a href='032.html'><font size=4><font color=darkPurple><b>032</b></font> - <font color=darkGreen>﻿सदसतोरविशेषाद्यदृच्छोपलब्धेरुन्मत्तवत्॥३२॥</font></font></a></li>");
document.write("        <li><a href='033.html'><font size=4><font color=darkPurple><b>033</b></font> - <font color=darkBlue>﻿नैगमसंग्रहव्यवहारर्जुसूत्रशब्दसमभिरूढैवंभूता नयाः॥३३॥</font></font></a></li>");
document.write("        <li><a href='034.html'><font size=4><br><font size=5 color=black><b>﻿अधिकार-२ (जीवाधिकार) </b></font><br><br><font color=darkPurple><b>034</b></font> - <font color=darkGreen>﻿औपशमिकक्षायिकौ भावौ मिश्रश्च जीवस्य स्वतत्त्वमौदयिकपारिणामिकौ च॥१॥</font></font></a></li>");
document.write("        <li><a href='035.html'><font size=4><font color=darkPurple><b>035</b></font> - <font color=darkBlue>﻿द्विनवाष्टादशैकविंशतित्रिभेदा यथाक्रमम्॥२॥</font></font></a></li>");
document.write("        <li><a href='036.html'><font size=4><font color=darkPurple><b>036</b></font> - <font color=darkGreen>﻿सम्यक्त्वचारित्रे॥३॥</font></font></a></li>");
document.write("        <li><a href='037.html'><font size=4><font color=darkPurple><b>037</b></font> - <font color=darkBlue>﻿ज्ञानदर्शनदानलाभभोगोपभोगवीर्याणि च॥४॥</font></font></a></li>");
document.write("        <li><a href='038.html'><font size=4><font color=darkPurple><b>038</b></font> - <font color=darkGreen>﻿ज्ञानाज्ञानदर्शन लब्धयश्‍चतुस्त्रित्रि पञ्चभेदाः सम्यक्त्वचारित्र संयमासंयमाश्‍च॥५॥</font></font></a></li>");
document.write("        <li><a href='039.html'><font size=4><font color=darkPurple><b>039</b></font> - <font color=darkBlue>﻿गतिकषायलिंग-मिथ्यादर्शनाज्ञानासंयतासिद्धलेश्याश्‍चतुश्‍चतुस्त्र्यैकैकैकैक-षड्भेदाः॥६॥</font></font></a></li>");
document.write("        <li><a href='040.html'><font size=4><font color=darkPurple><b>040</b></font> - <font color=darkGreen>﻿जीवभव्याभव्यत्वानि च॥७॥</font></font></a></li>");
document.write("        <li><a href='041.html'><font size=4><font color=darkPurple><b>041</b></font> - <font color=darkBlue>﻿उपयोगो लक्षणम्॥८॥</font></font></a></li>");
document.write("        <li><a href='042.html'><font size=4><font color=darkPurple><b>042</b></font> - <font color=darkGreen>﻿स द्विविधोऽष्ट-चतुर्भेदः॥९॥</font></font></a></li>");
document.write("        <li><a href='043.html'><font size=4><font color=darkPurple><b>043</b></font> - <font color=darkBlue>﻿संसारिणो मुक्ताश्‍च॥१०॥</font></font></a></li>");
document.write("        <li><a href='044.html'><font size=4><font color=darkPurple><b>044</b></font> - <font color=darkGreen>﻿समनस्काsमनस्काः॥११॥</font></font></a></li>");
document.write("        <li><a href='045.html'><font size=4><font color=darkPurple><b>045</b></font> - <font color=darkBlue>﻿संसारिणस्त्रसस्थावराः॥१२॥</font></font></a></li>");
document.write("        <li><a href='046.html'><font size=4><font color=darkPurple><b>046</b></font> - <font color=darkGreen>﻿पृथिव्यप्तेजो वायु-वनस्पतयः स्थावराः॥१३॥</font></font></a></li>");
document.write("        <li><a href='047.html'><font size=4><font color=darkPurple><b>047</b></font> - <font color=darkBlue>﻿द्वीन्द्रियादयस्त्रसाः॥१४॥</font></font></a></li>");
document.write("        <li><a href='048.html'><font size=4><font color=darkPurple><b>048</b></font> - <font color=darkGreen>﻿पंचेद्रियाणि॥१५॥</font></font></a></li>");
document.write("        <li><a href='049.html'><font size=4><font color=darkPurple><b>049</b></font> - <font color=darkBlue>﻿द्विविधानि॥१६॥</font></font></a></li>");
document.write("        <li><a href='050.html'><font size=4><font color=darkPurple><b>050</b></font> - <font color=darkGreen>﻿निर्वृत्त्युपकरणे द्रव्येन्द्रियम्‌॥१७॥</font></font></a></li>");
document.write("        <li><a href='051.html'><font size=4><font color=darkPurple><b>051</b></font> - <font color=darkBlue>﻿लब्ध्युपयोगो भावेन्द्रियम्॥१८॥</font></font></a></li>");
document.write("        <li><a href='052.html'><font size=4><font color=darkPurple><b>052</b></font> - <font color=darkGreen>﻿स्पर्शन-रसन-घ्राण-चक्षुःश्रोत्राणि॥१९॥</font></font></a></li>");
document.write("        <li><a href='053.html'><font size=4><font color=darkPurple><b>053</b></font> - <font color=darkBlue>﻿स्पर्श-रस-गन्ध-वर्ण-शब्दास्तदर्थाः॥२०॥</font></font></a></li>");
document.write("        <li><a href='054.html'><font size=4><font color=darkPurple><b>054</b></font> - <font color=darkGreen>﻿श्रुतमनिन्द्रियस्य॥२१॥</font></font></a></li>");
document.write("        <li><a href='055.html'><font size=4><font color=darkPurple><b>055</b></font> - <font color=darkBlue>﻿वनस्पत्यन्तानामेकम्॥२२॥</font></font></a></li>");
document.write("        <li><a href='056.html'><font size=4><font color=darkPurple><b>056</b></font> - <font color=darkGreen>﻿कृमि-पिपीलिका-भ्रमर-मनुष्यादीनामेकैकवृद्धानि॥२३॥</font></font></a></li>");
document.write("        <li><a href='057.html'><font size=4><font color=darkPurple><b>057</b></font> - <font color=darkBlue>﻿संज्ञिनः समनस्काः॥२४॥</font></font></a></li>");
document.write("        <li><a href='058.html'><font size=4><font color=darkPurple><b>058</b></font> - <font color=darkGreen>﻿विग्रहगतौ कर्मयोगः॥२५॥</font></font></a></li>");
document.write("        <li><a href='059.html'><font size=4><font color=darkPurple><b>059</b></font> - <font color=darkBlue>﻿अनुश्रेणिः गतिः॥२६॥</font></font></a></li>");
document.write("        <li><a href='060.html'><font size=4><font color=darkPurple><b>060</b></font> - <font color=darkGreen>﻿अविग्रहा जीवस्य॥२७॥</font></font></a></li>");
document.write("        <li><a href='061.html'><font size=4><font color=darkPurple><b>061</b></font> - <font color=darkBlue>﻿विग्रहवती च संसारिणः प्राक् चतुर्भ्यः॥२८॥</font></font></a></li>");
document.write("        <li><a href='062.html'><font size=4><font color=darkPurple><b>062</b></font> - <font color=darkGreen>﻿एकसमयाsविग्रहा॥२९॥</font></font></a></li>");
document.write("        <li><a href='063.html'><font size=4><font color=darkPurple><b>063</b></font> - <font color=darkBlue>﻿एकं द्वौ त्रीन्वानाहारकः॥३०॥</font></font></a></li>");
document.write("        <li><a href='064.html'><font size=4><font color=darkPurple><b>064</b></font> - <font color=darkGreen>﻿सम्मूर्च्छन-गर्भॊपपादा जन्म॥३१॥</font></font></a></li>");
document.write("        <li><a href='065.html'><font size=4><font color=darkPurple><b>065</b></font> - <font color=darkBlue>﻿सचित्तशीतसंवृताः सेतरा मिश्राश्‍चैकशस्तद्योनयः॥३२॥</font></font></a></li>");
document.write("        <li><a href='066.html'><font size=4><font color=darkPurple><b>066</b></font> - <font color=darkGreen>﻿जरायुजाण्डजपोतानां गर्भः॥३३॥</font></font></a></li>");
document.write("        <li><a href='067.html'><font size=4><font color=darkPurple><b>067</b></font> - <font color=darkBlue>﻿देवनारकाणामुपपादः॥३४॥</font></font></a></li>");
document.write("        <li><a href='068.html'><font size=4><font color=darkPurple><b>068</b></font> - <font color=darkGreen>﻿शेषाणां सम्मूर्च्छनं॥३५॥</font></font></a></li>");
document.write("        <li><a href='069.html'><font size=4><font color=darkPurple><b>069</b></font> - <font color=darkBlue>﻿औदारिक-वैक्रियिकाहारक-तैजस-कार्मणानि शरीराणि॥३६॥</font></font></a></li>");
document.write("        <li><a href='070.html'><font size=4><font color=darkPurple><b>070</b></font> - <font color=darkGreen>﻿परं परं सूक्ष्मम्॥३७॥</font></font></a></li>");
document.write("        <li><a href='071.html'><font size=4><font color=darkPurple><b>071</b></font> - <font color=darkBlue>﻿प्रदेशतोऽसंख्येयगुणं प्राक् तैजसात्॥३८॥</font></font></a></li>");
document.write("        <li><a href='072.html'><font size=4><font color=darkPurple><b>072</b></font> - <font color=darkGreen>﻿अनन्तगुणे परे॥३९॥</font></font></a></li>");
document.write("        <li><a href='073.html'><font size=4><font color=darkPurple><b>073</b></font> - <font color=darkBlue>﻿अप्रतीघाते॥४०॥</font></font></a></li>");
document.write("        <li><a href='074.html'><font size=4><font color=darkPurple><b>074</b></font> - <font color=darkGreen>﻿अनादिसंबन्धे च॥४१॥</font></font></a></li>");
document.write("        <li><a href='075.html'><font size=4><font color=darkPurple><b>075</b></font> - <font color=darkBlue>﻿सर्वस्य॥४२॥</font></font></a></li>");
document.write("        <li><a href='076.html'><font size=4><font color=darkPurple><b>076</b></font> - <font color=darkGreen>﻿तदादीनि भाज्यानि युगपदेकस्मिन्नाचतुर्भ्यः॥४३॥</font></font></a></li>");
document.write("        <li><a href='077.html'><font size=4><font color=darkPurple><b>077</b></font> - <font color=darkBlue>﻿निरूपभोगमन्त्यम्॥४४।</font></font></a></li>");
document.write("        <li><a href='078.html'><font size=4><font color=darkPurple><b>078</b></font> - <font color=darkGreen>﻿गर्भसम्मूर्च्छनजमा्द्यम्‌॥४५॥</font></font></a></li>");
document.write("        <li><a href='079.html'><font size=4><font color=darkPurple><b>079</b></font> - <font color=darkBlue>﻿औपपादिकं वैक्रियिकम्‌॥४६॥</font></font></a></li>");
document.write("        <li><a href='080.html'><font size=4><font color=darkPurple><b>080</b></font> - <font color=darkGreen>﻿लब्धिप्रत्ययं च॥४७॥</font></font></a></li>");
document.write("        <li><a href='081.html'><font size=4><font color=darkPurple><b>081</b></font> - <font color=darkBlue>﻿तैजसमपि॥४८॥</font></font></a></li>");
document.write("        <li><a href='082.html'><font size=4><font color=darkPurple><b>082</b></font> - <font color=darkGreen>﻿शुभं विशुद्धमव्याघाति चाहारकं प्रमत्तसंयतस्यैव॥४९॥</font></font></a></li>");
document.write("        <li><a href='083.html'><font size=4><font color=darkPurple><b>083</b></font> - <font color=darkBlue>﻿नारकसंमूर्च्छिनो नपुंसकानि॥५०॥</font></font></a></li>");
document.write("        <li><a href='084.html'><font size=4><font color=darkPurple><b>084</b></font> - <font color=darkGreen>﻿न देवाः॥५१॥</font></font></a></li>");
document.write("        <li><a href='085.html'><font size=4><font color=darkPurple><b>085</b></font> - <font color=darkBlue>﻿शेषास्त्रिवेदाः॥५२॥</font></font></a></li>");
document.write("        <li><a href='086.html'><font size=4><font color=darkPurple><b>086</b></font> - <font color=darkGreen>﻿औपपादिक चरमोत्तम-देहाऽसंख्येय-वर्षायुषोsनपवर्त्यायुषः॥५३॥</font></font></a></li>");
document.write("        <li><a href='087.html'><font size=4><br><font size=5 color=black><b>﻿अधिकार-३ (जीवाधिकार) </b></font><br><br><font color=darkPurple><b>087</b></font> - <font color=darkBlue>﻿रत्न-शर्करा-बालुका-पंक-धूम-तमो-महातमः प्रभा भूमयो घनाम्बुवाताकाश प्रतिष्ठाः सप्ताsधोऽधः॥१॥</font></font></a></li>");
document.write("        <li><a href='088.html'><font size=4><font color=darkPurple><b>088</b></font> - <font color=darkGreen>﻿तासु त्रिंशत्पंचविंशति पंचदशदश-त्रि-पंचोनैक-नरक-शतसहस्राणि पंच चैव यथाक्रमम्॥२॥</font></font></a></li>");
document.write("        <li><a href='089.html'><font size=4><font color=darkPurple><b>089</b></font> - <font color=darkBlue>﻿नारका नित्याsशुभतर-लेश्या-परिणामदेह-वेदना-विक्रियाः॥३॥</font></font></a></li>");
document.write("        <li><a href='090.html'><font size=4><font color=darkPurple><b>090</b></font> - <font color=darkGreen>﻿परस्परोदीरित-दुःखाः॥४॥</font></font></a></li>");
document.write("        <li><a href='091.html'><font size=4><font color=darkPurple><b>091</b></font> - <font color=darkBlue>﻿संक्लिष्टासुरोदीरित-दुःखाश्‍च प्राक् चतुर्थ्याः॥५॥</font></font></a></li>");
document.write("        <li><a href='092.html'><font size=4><font color=darkPurple><b>092</b></font> - <font color=darkGreen>﻿तेष्वेक-त्रि-सप्त-दश-सप्तदश-द्वाविंशति-त्रयस्त्रिंशत्सागरोपमा सत्त्वानां परा स्थितिः॥६॥</font></font></a></li>");
document.write("        <li><a href='093.html'><font size=4><font color=darkPurple><b>093</b></font> - <font color=darkBlue>﻿जम्बूद्वीप-लवणोदादयः शुभनामानो द्वीप-समुद्रा॥७॥</font></font></a></li>");
document.write("        <li><a href='094.html'><font size=4><font color=darkPurple><b>094</b></font> - <font color=darkGreen>﻿द्विर्द्विर्विष्कम्भाः पूर्वपूर्वपरिक्षेपिणो वलयाकृतयः॥८॥</font></font></a></li>");
document.write("        <li><a href='095.html'><font size=4><font color=darkPurple><b>095</b></font> - <font color=darkBlue>﻿तन्मध्ये मेरुनाभिर्वृत्तो योजनशतसहस्रविषकम्भो जम्बूद्वीपः॥९॥</font></font></a></li>");
document.write("        <li><a href='096.html'><font size=4><font color=darkPurple><b>096</b></font> - <font color=darkGreen>﻿भरतहैमवत-हरि-विदेह-रम्यकहैरण्यवतैरावतवर्षाः क्षेत्राणि॥१०॥</font></font></a></li>");
document.write("        <li><a href='097.html'><font size=4><font color=darkPurple><b>097</b></font> - <font color=darkBlue>﻿तद्विभाजिनः पूर्वापरायता हिमवन्महाहिमवन्निषध-नील-रुक्मि-शिखरिणो वर्षधर-पर्वताः॥११॥</font></font></a></li>");
document.write("        <li><a href='098.html'><font size=4><font color=darkPurple><b>098</b></font> - <font color=darkGreen>﻿हेमार्जुन-तपनीय वैडूर्य-रजत हेममयाः॥१२॥</font></font></a></li>");
document.write("        <li><a href='099.html'><font size=4><font color=darkPurple><b>099</b></font> - <font color=darkBlue>﻿मणि-विचित्र-पार्श्‍वा उपरि मूले च तुल्यविस्ताराः॥१३॥</font></font></a></li>");
document.write("        <li><a href='09.html'><font size=4>09</font></a></li>");
document.write("        <li><a href='miss.html'><font size=4>miss</font></a></li>");
document.write("        <li><a href='100.html'><font size=4><font color=darkPurple><b>100</b></font> - <font color=darkGreen>﻿पद्ममहापद्मतिगिञ्छकेशरि महापुण्डरीकपुण्डरीका-हृदास्तेषामुपरि॥१४॥</font></font></a></li>");
document.write("        <li><a href='101.html'><font size=4><font color=darkPurple><b>101</b></font> - <font color=darkBlue>﻿प्रथमो योजन-सहस्रायामस्तदर्द्धविषकम्भो ह्रदः।॥१५॥</font></font></a></li>");
document.write("        <li><a href='102.html'><font size=4><font color=darkPurple><b>102</b></font> - <font color=darkGreen>﻿दशयोजनावगाहः॥१६॥</font></font></a></li>");
document.write("        <li><a href='103.html'><font size=4><font color=darkPurple><b>103</b></font> - <font color=darkBlue>﻿तन्मध्ये योजनं पुष्करम्॥१७॥</font></font></a></li>");
document.write("        <li><a href='104.html'><font size=4><font color=darkPurple><b>104</b></font> - <font color=darkGreen>﻿तद्द्विगुण-द्विगुणा ह्रदाः पुष्कराणि च॥१८॥</font></font></a></li>");
document.write("        <li><a href='105.html'><font size=4><font color=darkPurple><b>105</b></font> - <font color=darkBlue>﻿तन्निवासिन्यो देव्यः श्री-ह्री-धृति-कीर्ति-बुद्धि-लक्ष्म्यः पल्योपमस्थितयः ससामानिक परिषत्काः॥१९॥</font></font></a></li>");
document.write("        <li><a href='106.html'><font size=4><font color=darkPurple><b>106</b></font> - <font color=darkGreen>﻿गंगासिन्धु रोहिद्रोहितास्या-हरिद्धरिकान्ता सीतासीतोदा-नारीनरकान्ता सुवर्णरूप्यकूला रक्तारक्तोदाः सरितस्तन्मध्यगाः॥२०॥</font></font></a></li>");
document.write("        <li><a href='107.html'><font size=4><font color=darkPurple><b>107</b></font> - <font color=darkBlue>﻿द्वयोर्द्वयोः पूर्वाः पूर्वगाः॥२१॥</font></font></a></li>");
document.write("        <li><a href='108.html'><font size=4><font color=darkPurple><b>108</b></font> - <font color=darkGreen>﻿शेषास्त्वपरगाः॥२२॥</font></font></a></li>");
document.write("        <li><a href='109.html'><font size=4><font color=darkPurple><b>109</b></font> - <font color=darkBlue>﻿चतुर्दशनदीसहस्रपरिवृता गंगासिन्ध्वादयो नद्यः॥२३॥</font></font></a></li>");
document.write("        <li><a href='110.html'><font size=4><font color=darkPurple><b>110</b></font> - <font color=darkGreen>﻿भरतः षड्विंशति-पंचयोजनशत-विस्तारः षट्चैकोनविंशतिभागा-योजनस्य॥२४॥</font></font></a></li>");
document.write("        <li><a href='111.html'><font size=4><font color=darkPurple><b>111</b></font> - <font color=darkBlue>﻿तद्द्विगुण द्विगुणविस्तारा वर्षधरवर्षा विदेहान्ताः॥२५॥</font></font></a></li>");
document.write("        <li><a href='112.html'><font size=4><font color=darkPurple><b>112</b></font> - <font color=darkGreen>﻿उत्तरा दक्षिण-तुल्याः ॥२६॥</font></font></a></li>");
document.write("        <li><a href='113.html'><font size=4><font color=darkPurple><b>113</b></font> - <font color=darkBlue>﻿भरतैरावतयोर्वृद्धिह्रासौ षट्‍समयाभ्यामुत्सर्पिण्यवसर्पिणीभ्याम्‌ ॥२७॥</font></font></a></li>");
document.write("        <li><a href='114.html'><font size=4><font color=darkPurple><b>114</b></font> - <font color=darkGreen>﻿ताभ्यामपरा भूमयोsवस्थिताः॥२८॥</font></font></a></li>");
document.write("        <li><a href='115.html'><font size=4><font color=darkPurple><b>115</b></font> - <font color=darkBlue>﻿एकद्वित्रिपल्योपम-स्थितयो हैमवतक हारिवर्षक दैवकुरुवकाः॥२९॥</font></font></a></li>");
document.write("        <li><a href='116.html'><font size=4><font color=darkPurple><b>116</b></font> - <font color=darkGreen>﻿तथोत्तराः॥३०॥</font></font></a></li>");
document.write("        <li><a href='117.html'><font size=4><font color=darkPurple><b>117</b></font> - <font color=darkBlue>﻿विदेहेषु संख्येयकालाः॥३१॥</font></font></a></li>");
document.write("        <li><a href='118.html'><font size=4><font color=darkPurple><b>118</b></font> - <font color=darkGreen>﻿भरतस्य विष्कम्भो जम्बूद्वीपस्य नवतिशतभागः॥३२॥</font></font></a></li>");
document.write("        <li><a href='119.html'><font size=4><font color=darkPurple><b>119</b></font> - <font color=darkBlue>﻿द्विर्धातकीखण्डे॥३३॥</font></font></a></li>");
document.write("        <li><a href='120.html'><font size=4><font color=darkPurple><b>120</b></font> - <font color=darkGreen>﻿पुष्करार्द्धे च॥३४॥</font></font></a></li>");
document.write("        <li><a href='121.html'><font size=4><font color=darkPurple><b>121</b></font> - <font color=darkBlue>﻿प्राङ् मानुषोत्तरान्मनुष्याः॥३५॥</font></font></a></li>");
document.write("        <li><a href='122.html'><font size=4><font color=darkPurple><b>122</b></font> - <font color=darkGreen>﻿आर्या म्लेच्छाश्‍च॥३६॥</font></font></a></li>");
document.write("        <li><a href='123.html'><font size=4><font color=darkPurple><b>123</b></font> - <font color=darkBlue>﻿भरतैरावतविदेहाः कर्मभूमयोऽन्यत्र देवकुरूत्तरकुरुभ्यः॥३७॥</font></font></a></li>");
document.write("        <li><a href='124.html'><font size=4><font color=darkPurple><b>124</b></font> - <font color=darkGreen>﻿नृस्थितीपरावरे त्रिपल्योपमान्तर्मुहूर्ते॥३८॥</font></font></a></li>");
document.write("        <li><a href='125.html'><font size=4><font color=darkPurple><b>125</b></font> - <font color=darkBlue>﻿तिर्यग्योनिजानां च॥३९॥</font></font></a></li>");
document.write("        <li><a href='126.html'><font size=4><br><font size=5 color=black><b>﻿अधिकार-४ (जीवाधिकार) </b></font><br><br><font color=darkPurple><b>126</b></font> - <font color=darkGreen>﻿देवाश्चतुर्णिकाया:॥१॥</font></font></a></li>");
document.write("        <li><a href='127.html'><font size=4><font color=darkPurple><b>127</b></font> - <font color=darkBlue>आदितस्त्रिषु पीतान्तलेश्या:॥२॥</font></font></a></li>");
document.write("        <li><a href='128.html'><font size=4><font color=darkPurple><b>128</b></font> - <font color=darkGreen>दशाष्ट-पञ्च-द्वादश-विकल्पा कल्पोपपन्न पर्यन्ता:॥३॥</font></font></a></li>");
document.write("        <li><a href='129.html'><font size=4><font color=darkPurple><b>129</b></font> - <font color=darkBlue>इंद्र-सामानिक-त्रायस्ंित्रश-पारिषदात्मरक्ष-लोकपालानीक-प्रकीर्णकाभियोग्यकिल्विषिकाश्चैकश:॥४॥</font></font></a></li>");
document.write("        <li><a href='130.html'><font size=4><font color=darkPurple><b>130</b></font> - <font color=darkGreen>त्रायिंस्त्रश-लोकपाल-वज्र्या व्यंतरज्योतिष्का:॥५॥</font></font></a></li>");
document.write("        <li><a href='131.html'><font size=4><font color=darkPurple><b>131</b></font> - <font color=darkBlue>पूर्वयोद्र्वीन्द्रा:॥६॥</font></font></a></li>");
document.write("        <li><a href='132.html'><font size=4><font color=darkPurple><b>132</b></font> - <font color=darkGreen>काय-प्रवीचारा आ ऐशानात्॥७॥</font></font></a></li>");
document.write("        <li><a href='133.html'><font size=4><font color=darkPurple><b>133</b></font> - <font color=darkBlue>शेषा: स्पर्श-रूप-शब्द-मन: प्रवीचारा:॥८॥</font></font></a></li>");
document.write("        <li><a href='134.html'><font size=4><font color=darkPurple><b>134</b></font> - <font color=darkGreen>परेऽप्रवीचारा:॥९॥</font></font></a></li>");
document.write("        <li><a href='135.html'><font size=4><font color=darkPurple><b>135</b></font> - <font color=darkBlue>भवन-वासिनोऽसुरनाग-विद्युत्सुपर्णाग्निवातस्तनितोदधि-द्वीप-दिक्कुमारा:॥१०॥</font></font></a></li>");
document.write("        <li><a href='136.html'><font size=4><font color=darkPurple><b>136</b></font> - <font color=darkGreen>व्यन्तरा: किन्नर-विंपुरुष-महोरग-गन्धर्व-यक्ष-राक्षस-भूत-पिशाचा:॥११॥</font></font></a></li>");
document.write("        <li><a href='137.html'><font size=4><font color=darkPurple><b>137</b></font> - <font color=darkBlue>ज्योतिष्का: सूर्याचन्द्रमसौ ग्रह-नक्षत्र-प्रकीर्णक-तारकाश्च॥१२॥</font></font></a></li>");
document.write("        <li><a href='138.html'><font size=4><font color=darkPurple><b>138</b></font> - <font color=darkGreen>मेरु-प्रदक्षिणा नित्यगतयो नृलोके॥१३॥</font></font></a></li>");
document.write("        <li><a href='139.html'><font size=4><font color=darkPurple><b>139</b></font> - <font color=darkBlue>तत्कृत: काल विभाग:॥१४॥</font></font></a></li>");
document.write("        <li><a href='140.html'><font size=4><font color=darkPurple><b>140</b></font> - <font color=darkGreen>बहिरवस्थिता:॥१५॥</font></font></a></li>");
document.write("        <li><a href='141.html'><font size=4><font color=darkPurple><b>141</b></font> - <font color=darkBlue>वैमानिका:॥१६॥</font></font></a></li>");
document.write("        <li><a href='142.html'><font size=4><font color=darkPurple><b>142</b></font> - <font color=darkGreen>कल्पोपपन्ना: कल्पातीताश्च॥१७॥</font></font></a></li>");
document.write("        <li><a href='143.html'><font size=4><font color=darkPurple><b>143</b></font> - <font color=darkBlue>उपर्युपरि॥१८॥</font></font></a></li>");
document.write("        <li><a href='144.html'><font size=4><font color=darkPurple><b>144</b></font> - <font color=darkGreen>सौधर्मेशान-सानत्कुमार-माहेन्द्र-ब्रह्म-ब्रह्मोत्तर-लान्तव-कापिष्ट-शुक्र-महाशुक्र-शतार-सहस्रारेष्वानतप्राणत-योरारणाच्युतयोर्नवसु गै्रवेयकेषु विजय-वैजयन्त जयन्तापराजितेषु सर्वार्थ-सिद्धौ च॥१९॥</font></font></a></li>");
document.write("        <li><a href='145.html'><font size=4><font color=darkPurple><b>145</b></font> - <font color=darkBlue>स्थिति-प्रभाव-सुख-द्युति-लेश्याविशुद्धीन्द्रियावधि-विषय-तोऽधिका:॥२०॥</font></font></a></li>");
document.write("        <li><a href='146.html'><font size=4><font color=darkPurple><b>146</b></font> - <font color=darkGreen>गति-शरीर-परिग्रहाभिमानतो हीना:॥२१॥</font></font></a></li>");
document.write("        <li><a href='147.html'><font size=4><font color=darkPurple><b>147</b></font> - <font color=darkBlue>पीत-पद्म-शुक्ल-लेश्या द्वि-त्रि-शेषेषु॥२२॥</font></font></a></li>");
document.write("        <li><a href='148.html'><font size=4><font color=darkPurple><b>148</b></font> - <font color=darkGreen>प्राग्ग्रैवेयकेभ्य: कल्पा:॥२३॥</font></font></a></li>");
document.write("        <li><a href='149.html'><font size=4><font color=darkPurple><b>149</b></font> - <font color=darkBlue>ब्रह्म-लोकालया लौकान्तिका:॥२४॥</font></font></a></li>");
document.write("        <li><a href='150.html'><font size=4><font color=darkPurple><b>150</b></font> - <font color=darkGreen>सारस्वतादित्य वन्ह्यरुण-गर्दतोय-तुषिताव्या-बाधारिष्टाश्च॥२५॥</font></font></a></li>");
document.write("        <li><a href='151.html'><font size=4><font color=darkPurple><b>151</b></font> - <font color=darkBlue>विजयादिषु द्वि-चरमा:॥२६॥</font></font></a></li>");
document.write("        <li><a href='152.html'><font size=4><font color=darkPurple><b>152</b></font> - <font color=darkGreen>औपपादिक-मनुष्येभ्य: शेषास्तिर्यग्योनय:॥२७॥</font></font></a></li>");
document.write("        <li><a href='153.html'><font size=4><font color=darkPurple><b>153</b></font> - <font color=darkBlue>स्थितिरसुर-नाग-सुपर्ण-द्वीपशेषाणां-सागरोपम-त्रिपल्योपमाद्र्धहीन-मिता:॥२८॥</font></font></a></li>");
document.write("        <li><a href='154.html'><font size=4><font color=darkPurple><b>154</b></font> - <font color=darkGreen>सौधर्मेशानयो: सागरोपमेऽधिके॥२९॥</font></font></a></li>");
document.write("        <li><a href='155.html'><font size=4><font color=darkPurple><b>155</b></font> - <font color=darkBlue>सानत्कुमार-माहेन्द्रयो: सप्त॥३०॥</font></font></a></li>");
document.write("        <li><a href='156.html'><font size=4><font color=darkPurple><b>156</b></font> - <font color=darkGreen>त्रिसप्त-नवैकादश-त्रयोदश-पञ्चदशभिरधिकानि तु॥३१॥</font></font></a></li>");
document.write("        <li><a href='157.html'><font size=4><font color=darkPurple><b>157</b></font> - <font color=darkBlue>आरणाच्युता-दूध्र्वमेवैकेन नवसु ग्रैवेयकेषु विजयादिषु सर्वार्थसिद्धौ च॥३२॥</font></font></a></li>");
document.write("        <li><a href='158.html'><font size=4><font color=darkPurple><b>158</b></font> - <font color=darkGreen>अपरा पल्योपममधिकम्॥३३॥</font></font></a></li>");
document.write("        <li><a href='159.html'><font size=4><font color=darkPurple><b>159</b></font> - <font color=darkBlue>परत: परत: पूर्वा पूर्वाऽनन्तरा॥३४॥</font></font></a></li>");
document.write("        <li><a href='160.html'><font size=4><font color=darkPurple><b>160</b></font> - <font color=darkGreen>नारकाणां च द्वितीयादिषु॥३५॥</font></font></a></li>");
document.write("        <li><a href='161.html'><font size=4><font color=darkPurple><b>161</b></font> - <font color=darkBlue>दश-वर्षसहस्राणि प्रथमायाम्॥३६॥</font></font></a></li>");
document.write("        <li><a href='162.html'><font size=4><font color=darkPurple><b>162</b></font> - <font color=darkGreen>भवनेषु च॥३७॥</font></font></a></li>");
document.write("        <li><a href='163.html'><font size=4><font color=darkPurple><b>163</b></font> - <font color=darkBlue>व्यन्तराणां च॥३८॥</font></font></a></li>");
document.write("        <li><a href='164.html'><font size=4><font color=darkPurple><b>164</b></font> - <font color=darkGreen>परा पल्योपममधिकम्॥३९॥</font></font></a></li>");
document.write("        <li><a href='165.html'><font size=4><font color=darkPurple><b>165</b></font> - <font color=darkBlue>ज्योतिष्काणां च॥४०॥</font></font></a></li>");
document.write("        <li><a href='166.html'><font size=4><font color=darkPurple><b>166</b></font> - <font color=darkGreen>तदष्टभागोऽपरा॥४१॥</font></font></a></li>");
document.write("        <li><a href='167.html'><font size=4><font color=darkPurple><b>167</b></font> - <font color=darkBlue>लौकान्तिकानामष्टौ सागरोपमाणि सर्वेषाम्॥४२॥</font></font></a></li>");
document.write("        <li><a href='181.html'><font size=4><font color=darkPurple><b>181</b></font> - <font color=darkGreen>एकप्रदेशादिषु भाज्य: पुद्गलानाम्॥१४॥</font></font></a></li>");
document.write("        <li><a href='182.html'><font size=4><font color=darkPurple><b>182</b></font> - <font color=darkBlue>असंख्येय-भागादिषु जीवानाम्॥१५॥</font></font></a></li>");
document.write("        <li><a href='183.html'><font size=4><font color=darkPurple><b>183</b></font> - <font color=darkGreen>प्रदेश-संहार-विसर्पाभ्यां प्रदीपवत्॥१६॥</font></font></a></li>");
document.write("        <li><a href='184.html'><font size=4><font color=darkPurple><b>184</b></font> - <font color=darkBlue>गति-स्थित्युपग्रहौ धर्माधर्मयोरुपकार:॥१७॥</font></font></a></li>");
document.write("        <li><a href='185.html'><font size=4><font color=darkPurple><b>185</b></font> - <font color=darkGreen>आकाशस्या-वगाह:॥१८॥</font></font></a></li>");
document.write("        <li><a href='186.html'><font size=4><font color=darkPurple><b>186</b></font> - <font color=darkBlue>शरीरवाङ्मन:-प्राणापाना पुद्गलानाम्॥१९॥</font></font></a></li>");
document.write("        <li><a href='187.html'><font size=4><font color=darkPurple><b>187</b></font> - <font color=darkGreen>सुख-दु:ख-जीवितमरणोपग्रहाश्च॥२०॥</font></font></a></li>");
document.write("        <li><a href='188.html'><font size=4><font color=darkPurple><b>188</b></font> - <font color=darkBlue>परस्परोपग्रहो जीवानाम्॥२१॥</font></font></a></li>");
document.write("        <li><a href='189.html'><font size=4><font color=darkPurple><b>189</b></font> - <font color=darkGreen>वर्तना-परिणाम-क्रिया-परत्वापरत्वे च कालस्य॥२२॥</font></font></a></li>");
document.write("        <li><a href='190.html'><font size=4><font color=darkPurple><b>190</b></font> - <font color=darkBlue>स्पर्श-रस-गंध-वर्णवन्त: पुद्गला:॥२३॥</font></font></a></li>");
document.write("        <li><a href='191.html'><font size=4><font color=darkPurple><b>191</b></font> - <font color=darkGreen>शब्द-बंध-सौक्ष्म्य-स्थौल्य-संस्थान-भेद-तमश्छायातपोद्योतवन्तश्च॥२४॥</font></font></a></li>");
document.write("        <li><a href='192.html'><font size=4><font color=darkPurple><b>192</b></font> - <font color=darkBlue>अणव: स्कन्धाश्च॥२५॥</font></font></a></li>");
document.write("        <li><a href='193.html'><font size=4><font color=darkPurple><b>193</b></font> - <font color=darkGreen>भेद-संघातेभ्य उत्पद्यन्ते॥२६॥</font></font></a></li>");
document.write("        <li><a href='194.html'><font size=4><font color=darkPurple><b>194</b></font> - <font color=darkBlue>भेदादणु:॥२७॥</font></font></a></li>");
document.write("        <li><a href='195.html'><font size=4><font color=darkPurple><b>195</b></font> - <font color=darkGreen>भेद-संघाताभ्यां चाक्षुष:॥२८॥</font></font></a></li>");
document.write("        <li><a href='196.html'><font size=4><font color=darkPurple><b>196</b></font> - <font color=darkBlue>सद् द्रव्य-लक्षणम्॥२९॥</font></font></a></li>");
document.write("        <li><a href='197.html'><font size=4><font color=darkPurple><b>197</b></font> - <font color=darkGreen>उत्पाद-व्यय-ध्रौव्य-युत्तं सत्॥३०॥</font></font></a></li>");
document.write("        <li><a href='198.html'><font size=4><font color=darkPurple><b>198</b></font> - <font color=darkBlue>तद्भावाव्ययं नित्यम्॥३१॥</font></font></a></li>");
document.write("        <li><a href='199.html'><font size=4><font color=darkPurple><b>199</b></font> - <font color=darkGreen>अर्पितानर्पितसिद्धे:॥३२॥</font></font></a></li>");
document.write("        <li><a href='200.html'><font size=4><font color=darkPurple><b>200</b></font> - <font color=darkBlue>स्निग्ध-रूक्षत्वाद्बंध:॥३३॥</font></font></a></li>");
document.write("        <li><a href='201.html'><font size=4><font color=darkPurple><b>201</b></font> - <font color=darkGreen>न जघन्य-गुणानाम्॥३४॥</font></font></a></li>");
document.write("        <li><a href='202.html'><font size=4><font color=darkPurple><b>202</b></font> - <font color=darkBlue>गुणसाम्ये सदृशानाम्॥३५॥</font></font></a></li>");
document.write("        <li><a href='203.html'><font size=4><font color=darkPurple><b>203</b></font> - <font color=darkGreen>द्व्यधिकादि गुणानां तु॥३६॥</font></font></a></li>");
document.write("        <li><a href='205.html'><font size=4><font color=darkPurple><b>205</b></font> - <font color=darkBlue>गुण-पर्ययवद् द्रव्यम्॥३८॥</font></font></a></li>");
document.write("        <li><a href='207.html'><font size=4><font color=darkPurple><b>207</b></font> - <font color=darkGreen>सोऽनन्तसमय:॥४०॥</font></font></a></li>");
document.write("        <li><a href='208.html'><font size=4><font color=darkPurple><b>208</b></font> - <font color=darkBlue>द्रव्याश्रया निर्गुणा गुणा:॥४१॥</font></font></a></li>");
document.write("        <li><a href='209.html'><font size=4><font color=darkPurple><b>209</b></font> - <font color=darkGreen>तद्भाव: परिणाम:॥४२॥</font></font></a></li>");
document.write("        <li><a href='210.html'><font size=4><br><font size=5 color=black><b>﻿अधिकार-६ (आस्रवाधिकार) </b></font><br><br><font color=darkPurple><b>210</b></font> - <font color=darkBlue>﻿काय-वाङ्मन: कर्म-योग: ॥१॥</font></font></a></li>");
document.write("        <li><a href='211.html'><font size=4><font color=darkPurple><b>211</b></font> - <font color=darkGreen>﻿स आस्रव: ॥२॥</font></font></a></li>");
document.write("        <li><a href='212.html'><font size=4><font color=darkPurple><b>212</b></font> - <font color=darkBlue>﻿शुभ: पुण्यस्याशुभ: पापस्य ॥३॥</font></font></a></li>");
document.write("        <li><a href='213.html'><font size=4><font color=darkPurple><b>213</b></font> - <font color=darkGreen>﻿सकषायाकषाययो: साम्परायिकेर्यापथयो: ॥४॥</font></font></a></li>");
document.write("        <li><a href='214.html'><font size=4><font color=darkPurple><b>214</b></font> - <font color=darkBlue>﻿इन्द्रिय-कषायाव्रत-क्रिया: पंच-चतु:-पंच-पंचविंशति-संख्या: पूर्वस्य भेदा: ॥५॥</font></font></a></li>");
document.write("        <li><a href='215.html'><font size=4><font color=darkPurple><b>215</b></font> - <font color=darkGreen>﻿तीव्र-मंद-ज्ञाताज्ञात-भावाधिकरण-वीर्य-विशेषेभ्यस्तद्विशेष: ॥६॥</font></font></a></li>");
document.write("        <li><a href='216.html'><font size=4><font color=darkPurple><b>216</b></font> - <font color=darkBlue>﻿अधिकरणं जीवाजीवा: ॥७॥</font></font></a></li>");
document.write("        <li><a href='217.html'><font size=4><font color=darkPurple><b>217</b></font> - <font color=darkGreen>﻿आद्यं संरम्भ-समारम्भारम्भयोग कृत-कारितानुमत-कषाय-विशेषैस्त्रिस्त्रिस्त्रि-श्चतुश्चैकश: ॥८॥</font></font></a></li>");
document.write("        <li><a href='219.html'><font size=4><font color=darkPurple><b>219</b></font> - <font color=darkBlue>﻿तत्प्रदोष-निह्नव-मात्सर्यान्तरायासादनोपघाता ज्ञान-दर्शनावरणयो:॥१०॥</font></font></a></li>");
document.write("        <li><a href='220.html'><font size=4><font color=darkPurple><b>220</b></font> - <font color=darkGreen>﻿दु:ख-शोक-तापाक्रन्दन-वध-परिदेवनान्यात्म-परोभय-स्थानान्यसद्वेद्यस्य ॥११॥</font></font></a></li>");
document.write("        <li><a href='221.html'><font size=4><font color=darkPurple><b>221</b></font> - <font color=darkBlue>भूत-व्रत्यनुकम्पादान-सराग-संयमादि-योग: क्षांति: शौचमिति सद्वेद्यस्य॥१२॥</font></font></a></li>");
document.write("        <li><a href='222.html'><font size=4><font color=darkPurple><b>222</b></font> - <font color=darkGreen>केवलि-श्रुत-संघ-धर्मदेवावर्णवादो दर्शनमोहस्य॥१३॥</font></font></a></li>");
document.write("        <li><a href='223.html'><font size=4><font color=darkPurple><b>223</b></font> - <font color=darkBlue>कषायोदयात्तीव्र-परिणामश्चारित्र-मोहस्य॥१४॥</font></font></a></li>");
document.write("        <li><a href='224.html'><font size=4><font color=darkPurple><b>224</b></font> - <font color=darkGreen>बह्वारम्भ-परिग्रहत्वं नारकस्यायुष:॥१५॥</font></font></a></li>");
document.write("        <li><a href='225.html'><font size=4><font color=darkPurple><b>225</b></font> - <font color=darkBlue>माया तैर्यग्योनस्य॥१६॥</font></font></a></li>");
document.write("        <li><a href='226.html'><font size=4><font color=darkPurple><b>226</b></font> - <font color=darkGreen>अल्पारम्भ परिग्रहत्वं मानुषस्य॥१७॥</font></font></a></li>");
document.write("        <li><a href='227.html'><font size=4><font color=darkPurple><b>227</b></font> - <font color=darkBlue>स्वभाव-मार्दवं च॥१८॥</font></font></a></li>");
document.write("        <li><a href='228.html'><font size=4><font color=darkPurple><b>228</b></font> - <font color=darkGreen>नि:शील-व्रतित्वं च सर्वेषाम्॥१९॥</font></font></a></li>");
document.write("        <li><a href='229.html'><font size=4><font color=darkPurple><b>229</b></font> - <font color=darkBlue>सरागसंयम-संयमा-संयमाकामनिर्जराबालतपांसि देवस्य॥२०॥</font></font></a></li>");
document.write("        <li><a href='230.html'><font size=4><font color=darkPurple><b>230</b></font> - <font color=darkGreen>सम्यक्त्वं च॥२१॥</font></font></a></li>");
document.write("        <li><a href='231.html'><font size=4><font color=darkPurple><b>231</b></font> - <font color=darkBlue>योगवक्रता विसंवादनं चाशुभस्य नाम्न:॥२२॥</font></font></a></li>");
document.write("        <li><a href='232.html'><font size=4><font color=darkPurple><b>232</b></font> - <font color=darkGreen>तद्विपरीतं शुभस्य॥२३॥</font></font></a></li>");
document.write("        <li><a href='233.html'><font size=4><font color=darkPurple><b>233</b></font> - <font color=darkBlue>दर्शनविशुद्धिर्विनयसम्पन्नता-शील-व्रतेष्वनतीचारोऽभीक्ष्ण-ज्ञानोपयोगसंवेगौ शक्तितस्त्याग-तपसी साधुसमाधिर्वैयावृत्य-करणमर्हदाचार्य-बहुश्रुत-प्रवचन-भक्तिरावश्यकापरिहाणिर्मार्ग-प्रभावना-प्रवचनवत्सलत्वमिति तीर्थकरत्वस्य॥२४॥</font></font></a></li>");
document.write("        <li><a href='234.html'><font size=4><font color=darkPurple><b>234</b></font> - <font color=darkGreen>परात्म-निन्दा-प्रशंसे सदसद्गुणोच्छादनोद्भावने च नीचैर्गोत्रस्य॥२५॥</font></font></a></li>");
document.write("        <li><a href='235.html'><font size=4><font color=darkPurple><b>235</b></font> - <font color=darkBlue>तद्विपर्ययो नीचैर्वृत्त्यनुत्सेकौ चोत्तरस्य॥२६॥</font></font></a></li>");
document.write("        <li><a href='236.html'><font size=4><font color=darkPurple><b>236</b></font> - <font color=darkGreen>विघ्नकरण-मन्तरायस्य॥२७॥</font></font></a></li>");
document.write("        <li><a href='237.html'><font size=4><br><font size=5 color=black><b>﻿अधिकार-७ (आस्रवाधिकार) </b></font><br><br><font color=darkPurple><b>237</b></font> - <font color=darkBlue>﻿हिंसाऽनृत-स्तेयाब्रह्म-परिग्रहेभ्यो विरतिव्र्रतम्॥१॥</font></font></a></li>");
document.write("        <li><a href='238.html'><font size=4><font color=darkPurple><b>238</b></font> - <font color=darkGreen>देश सर्वतोगुण-महती॥२॥</font></font></a></li>");
document.write("        <li><a href='239.html'><font size=4><font color=darkPurple><b>239</b></font> - <font color=darkBlue>तत्स्थैर्यार्थं भावना: पञ्च-पञ्च॥३॥</font></font></a></li>");
document.write("        <li><a href='240.html'><font size=4><font color=darkPurple><b>240</b></font> - <font color=darkGreen>वाङ्मनोगुप्तीर्यादाननिक्षेपण-समित्यालोकित-पान-भोजनानि पञ्च॥४॥</font></font></a></li>");
document.write("        <li><a href='241.html'><font size=4><font color=darkPurple><b>241</b></font> - <font color=darkBlue>क्रोध-लोभ-भीरुत्व-हास्य-प्रत्याख्यानान्यनुवीचि-भाषणं च पञ्च॥५॥</font></font></a></li>");
document.write("        <li><a href='242.html'><font size=4><font color=darkPurple><b>242</b></font> - <font color=darkGreen>शून्यागार-विमोचितावास-परोपरोधाकरण-भैक्ष्यशुद्धि-सधर्मावि-संवादा: पञ्च॥६॥</font></font></a></li>");
document.write("        <li><a href='243.html'><font size=4><font color=darkPurple><b>243</b></font> - <font color=darkBlue>स्त्रीरागकथा श्रवण-तन्मनोहरांग निरीक्षण पूर्व-रतानुस्मरण-वृष्येष्टरस-स्वशरीरसंस्कारत्यागा: पञ्च॥७॥</font></font></a></li>");
document.write("        <li><a href='244.html'><font size=4><font color=darkPurple><b>244</b></font> - <font color=darkGreen>मनोज्ञामनोज्ञेन्द्रिय-विषय-राग-द्वेष वर्जनानि पञ्च॥८॥</font></font></a></li>");
document.write("        <li><a href='245.html'><font size=4><font color=darkPurple><b>245</b></font> - <font color=darkBlue>हिंसादिष्विहामुत्रापायावद्यदर्शनम्॥९॥</font></font></a></li>");
document.write("        <li><a href='246.html'><font size=4><font color=darkPurple><b>246</b></font> - <font color=darkGreen>दु:खमेव वा॥१०॥</font></font></a></li>");
document.write("        <li><a href='247.html'><font size=4><font color=darkPurple><b>247</b></font> - <font color=darkBlue>मैत्री-प्रमोद-कारुण्य-माध्यस्थानि च सत्त्व-गुणाधिक-क्लिश्यमानाविनेयेषु॥११॥</font></font></a></li>");
document.write("        <li><a href='248.html'><font size=4><font color=darkPurple><b>248</b></font> - <font color=darkGreen>जगत्काय-स्वभावौ वा संवेगवैराग्यार्थम्॥१२॥</font></font></a></li>");
document.write("        <li><a href='249.html'><font size=4><font color=darkPurple><b>249</b></font> - <font color=darkBlue>प्रमत्तयोगात्प्राण-व्यपरोपणं हिंसा॥१३॥</font></font></a></li>");
document.write("        <li><a href='250.html'><font size=4><font color=darkPurple><b>250</b></font> - <font color=darkGreen>असदभिधानमनृतम्॥१४॥</font></font></a></li>");
document.write("        <li><a href='251.html'><font size=4><font color=darkPurple><b>251</b></font> - <font color=darkBlue>अदत्तादानं स्तेयम्॥१५॥</font></font></a></li>");
document.write("        <li><a href='252.html'><font size=4><font color=darkPurple><b>252</b></font> - <font color=darkGreen>मैथुनम-ब्रह्म॥१६॥</font></font></a></li>");
document.write("        <li><a href='253.html'><font size=4><font color=darkPurple><b>253</b></font> - <font color=darkBlue>मूच्र्छा परिग्रह:॥१७॥</font></font></a></li>");
document.write("        <li><a href='254.html'><font size=4><font color=darkPurple><b>254</b></font> - <font color=darkGreen>नि:शल्यो व्रती॥१८॥</font></font></a></li>");
document.write("        <li><a href='255.html'><font size=4><font color=darkPurple><b>255</b></font> - <font color=darkBlue>अगार्यनगारश्च॥१९॥</font></font></a></li>");
document.write("        <li><a href='256.html'><font size=4><font color=darkPurple><b>256</b></font> - <font color=darkGreen>अणुव्रतोऽगारी॥२०॥</font></font></a></li>");
document.write("        <li><a href='257.html'><font size=4><font color=darkPurple><b>257</b></font> - <font color=darkBlue>दिग्देशानर्थदण्ड-विरति-सामायिक-प्रोषधोपवासोपभोग-परिभोग-परिमाणातिथि-संविभागव्रतसम्पन्नश्च॥२१॥</font></font></a></li>");
document.write("        <li><a href='258.html'><font size=4><font color=darkPurple><b>258</b></font> - <font color=darkGreen>मारणान्तिकीं सल्लेखनां जोषिता॥२२॥</font></font></a></li>");
document.write("        <li><a href='259.html'><font size=4><font color=darkPurple><b>259</b></font> - <font color=darkBlue>शंका-कांक्षाविचिकित्सान्यदृष्टि-प्रशंसा-संस्तवा: सम्यग्दृष्टेरती-चारा:॥२३॥</font></font></a></li>");
document.write("        <li><a href='260.html'><font size=4><font color=darkPurple><b>260</b></font> - <font color=darkGreen>व्रत-शीलेषु पञ्च पञ्च यथाक्रमम्॥२४।</font></font></a></li>");
document.write("        <li><a href='261.html'><font size=4><font color=darkPurple><b>261</b></font> - <font color=darkBlue>बंधवध-च्छेदाति-भारारोपणान्नपान-निरोधा:॥२५॥</font></font></a></li>");
document.write("        <li><a href='262.html'><font size=4><font color=darkPurple><b>262</b></font> - <font color=darkGreen>मिथ्योपदेश-रहोभ्याख्यान-कूटलेखक्रिया-न्यासापहार-साकारमन्त्रभेदा:॥२६॥</font></font></a></li>");
document.write("        <li><a href='263.html'><font size=4><font color=darkPurple><b>263</b></font> - <font color=darkBlue>स्तेनप्रयोग-तदाहृतादानविरुद्धराज्यातिक्रम-हीनाधिकमानोन्मान-प्रतिरूपक-व्यवहारा:॥२७॥</font></font></a></li>");
document.write("        <li><a href='264.html'><font size=4><font color=darkPurple><b>264</b></font> - <font color=darkGreen>परविवाह करणेत्वरिका-परिगृहीतापरिगृहीता-गमनानङ्गक्रीडा-कामतीव्राभिनिवेशा:॥२८॥</font></font></a></li>");
document.write("        <li><a href='265.html'><font size=4><font color=darkPurple><b>265</b></font> - <font color=darkBlue>क्षेत्रवास्तु-हिरण्यसुवर्ण-धन-धान्य-दासीदास-कुप्य-प्रमाणातिक्रमा:॥२९॥</font></font></a></li>");
document.write("        <li><a href='266.html'><font size=4><font color=darkPurple><b>266</b></font> - <font color=darkGreen>﻿ऊर्ध्वाधस्तिर्यग्व्यतिक्रमक्षेत्रवृद्धि-स्मृत्यंतराधानानि ॥३०॥</font></font></a></li>");
document.write("        <li><a href='267.html'><font size=4><font color=darkPurple><b>267</b></font> - <font color=darkBlue>आनयन-प्रेष्यप्रयोग-शब्दरूपानुपात-पुद्गलक्षेपा:॥३१॥</font></font></a></li>");
document.write("        <li><a href='268.html'><font size=4><font color=darkPurple><b>268</b></font> - <font color=darkGreen>कन्दर्प-कौत्कुच्य-मौखर्यासमीक्ष्याधि-करणोपभोगपरिभोगानर्थक्यानि॥३२॥</font></font></a></li>");
document.write("        <li><a href='269.html'><font size=4><font color=darkPurple><b>269</b></font> - <font color=darkBlue>योग दु:प्रणिधानानादर-स्मृत्यनु-पस्थानानि॥३३॥</font></font></a></li>");
document.write("        <li><a href='270.html'><font size=4><font color=darkPurple><b>270</b></font> - <font color=darkGreen>अप्रत्यवेक्षिताप्रमार्जितोत्सर्गादानसंस्तरोपक्रमणा-नादरस्मृत्यनुप-स्थानानि॥३४॥</font></font></a></li>");
document.write("        <li><a href='271.html'><font size=4><font color=darkPurple><b>271</b></font> - <font color=darkBlue>सचित्त-संबंधसम्मिश्रा-भिषवदु:पक्वाहारा:॥३५॥</font></font></a></li>");
document.write("        <li><a href='272.html'><font size=4><font color=darkPurple><b>272</b></font> - <font color=darkGreen>सचित्त-निक्षेपापिधानपरव्यपदेश-मात्सर्यकालातिक्रमा:॥३६॥</font></font></a></li>");
document.write("        <li><a href='273.html'><font size=4><font color=darkPurple><b>273</b></font> - <font color=darkBlue>जीवित-मरणाशंसा-मित्रानुराग-सुखानुबंध-निदानानि॥३७॥</font></font></a></li>");
document.write("        <li><a href='274.html'><font size=4><font color=darkPurple><b>274</b></font> - <font color=darkGreen>अनुग्रहार्थं स्वस्यातिसर्गो दानम्॥३८॥</font></font></a></li>");
document.write("        <li><a href='275.html'><font size=4><font color=darkPurple><b>275</b></font> - <font color=darkBlue>विधि-द्रव्य-दातृ-पात्र-विशेषात्तद्विशेष:॥३९॥</font></font></a></li>");
document.write("        <li><a href='276.html'><font size=4><br><font size=5 color=black><b>﻿अधिकार-८ (बंधाधिकार) </b></font><br><br><font color=darkPurple><b>276</b></font> - <font color=darkGreen>﻿मिथ्यादर्शनाविरति-प्रमाद-कषाय-योगा बन्धहेतव: ॥१॥</font></font></a></li>");
document.write("        <li><a href='277.html'><font size=4><font color=darkPurple><b>277</b></font> - <font color=darkBlue>﻿सकषायत्वाज्जीव: कर्मणो योग्यान् पुद्गलानादत्ते स बंध: ॥२॥</font></font></a></li>");
document.write("        <li><a href='278.html'><font size=4><font color=darkPurple><b>278</b></font> - <font color=darkGreen>﻿प्रकृति स्थित्यनुभाग-प्रदेशास्तद्विधय: ॥३॥</font></font></a></li>");
document.write("        <li><a href='279.html'><font size=4><font color=darkPurple><b>279</b></font> - <font color=darkBlue>﻿आद्यो ज्ञान-दर्शनावरणवेदनीय-मोहनीयायुर्नाम-गोत्रान्तराया: ॥४॥</font></font></a></li>");
document.write("        <li><a href='280.html'><font size=4><font color=darkPurple><b>280</b></font> - <font color=darkGreen>﻿पञ्च-नव-द्व्यष्टावशति-चतुद्र्विचत्वारिंशद्द्वि-पञ्च भेदा यथाक्रमम् ॥५॥</font></font></a></li>");
document.write("        <li><a href='281.html'><font size=4><font color=darkPurple><b>281</b></font> - <font color=darkBlue>﻿मतिश्रुतावधि-मन:पर्यय केवलानाम् ॥६॥</font></font></a></li>");
document.write("        <li><a href='282.html'><font size=4><font color=darkPurple><b>282</b></font> - <font color=darkGreen>﻿चक्षुरचक्षुरवधिकेवलानां निद्रा-निद्रानिद्रा-प्रचला-प्रचलाप्रचला-स्त्यानगृद्धयश्च ॥७॥</font></font></a></li>");
document.write("        <li><a href='283.html'><font size=4><font color=darkPurple><b>283</b></font> - <font color=darkBlue>﻿सदसद्वेद्ये ॥८॥</font></font></a></li>");
document.write("        <li><a href='284.html'><font size=4><font color=darkPurple><b>284</b></font> - <font color=darkGreen>﻿दर्शनचारित्र-मोहनीयाकषाय-कषायवेदनीयाख्यास्त्रिद्वि-नव-षोडशभेदा: सम्यक्त्व-मिथ्यात्व-तदुभयान्यकषाय-कषायौ हास्यरत्यरति-शोक-भय-जुगुप्सा-स्त्री-पुन्नपुंसक-वेदा अनन्तानुबंध्य-प्रत्याख्यान-प्रत्याख्यान-संज्वलन-विकल्पाश्चैकश: क्रोध-मान-माया-लोभा: ॥९॥</font></font></a></li>");
document.write("        <li><a href='285.html'><font size=4><font color=darkPurple><b>285</b></font> - <font color=darkBlue>﻿नारकतैर्यग्योन-मानुष-दैवानि ॥१०॥</font></font></a></li>");
document.write("        <li><a href='286.html'><font size=4><font color=darkPurple><b>286</b></font> - <font color=darkGreen>﻿गति-जाति-शरीराङ्गोपाङ्गनिर्माण-बंधन-संघात-संस्थान-संहनन-स्पर्श-रस-गंध-वर्णानुपूव्र्यगुरुलघूपघात-परघातातपोद्योतोच्छ्वास-विहायोगतय: प्रत्येक-शरीर-त्रस-सुभग-सुस्वर-शुभ-सूक्ष्म-पर्याप्ति-स्थिरादेय यश: कीर्ति-सेतराणि तीर्थकरत्वं च ॥११॥</font></font></a></li>");
document.write("        <li><a href='287.html'><font size=4><font color=darkPurple><b>287</b></font> - <font color=darkBlue>﻿उच्चैर्नीचैश्च ॥१२॥</font></font></a></li>");
document.write("        <li><a href='288.html'><font size=4><font color=darkPurple><b>288</b></font> - <font color=darkGreen>﻿दान-लाभ-भोगोपभोग-वीर्याणाम् ॥१३॥</font></font></a></li>");
document.write("        <li><a href='289.html'><font size=4><font color=darkPurple><b>289</b></font> - <font color=darkBlue>﻿आदितस्तिसृणा-मंतरायस्य च त्रिंशत्सागरोपमकोटीकोट्य: परा स्थिति: ॥१४॥</font></font></a></li>");
document.write("        <li><a href='290.html'><font size=4><font color=darkPurple><b>290</b></font> - <font color=darkGreen>सप्तति-र्मोहनीयस्य॥१५॥</font></font></a></li>");
document.write("        <li><a href='291.html'><font size=4><font color=darkPurple><b>291</b></font> - <font color=darkBlue>वशतिर्नाम-गोत्रयो:॥११६॥</font></font></a></li>");
document.write("        <li><a href='292.html'><font size=4><font color=darkPurple><b>292</b></font> - <font color=darkGreen>﻿त्रयस्त्रिंशत्सागरोपमाण्यायुष: ॥१७॥</font></font></a></li>");
document.write("        <li><a href='293.html'><font size=4><font color=darkPurple><b>293</b></font> - <font color=darkBlue>अपरा द्वादश मुहूर्ता वेदनीयस्य॥१८॥</font></font></a></li>");
document.write("        <li><a href='294.html'><font size=4><font color=darkPurple><b>294</b></font> - <font color=darkGreen>नाम-गोत्रयोरष्टौ॥१९॥</font></font></a></li>");
document.write("        <li><a href='295.html'><font size=4><font color=darkPurple><b>295</b></font> - <font color=darkBlue>शेषाणामन्तर्मुहूर्ता॥२०॥</font></font></a></li>");
document.write("        <li><a href='296.html'><font size=4><font color=darkPurple><b>296</b></font> - <font color=darkGreen>विपाकोऽनुभव:॥२१॥</font></font></a></li>");
document.write("        <li><a href='297.html'><font size=4><font color=darkPurple><b>297</b></font> - <font color=darkBlue>स यथानाम्॥२२॥</font></font></a></li>");
document.write("        <li><a href='298.html'><font size=4><font color=darkPurple><b>298</b></font> - <font color=darkGreen>ततश्च निर्जरा॥२३॥</font></font></a></li>");
document.write("        <li><a href='299.html'><font size=4><font color=darkPurple><b>299</b></font> - <font color=darkBlue>नाम-प्रत्यया: सर्वतो योग-विशेषात्-सूक्ष्मैकक्षेत्रावगाह-स्थिता: सर्वात्म-प्रदेशेष्वनन्तानन्त-प्रदेशा:॥२४॥</font></font></a></li>");
document.write("        <li><a href='300.html'><font size=4><font color=darkPurple><b>300</b></font> - <font color=darkGreen>सद्वेद्यशुभायुर्नाम-गोत्राणि पुण्यम्॥२५॥</font></font></a></li>");
document.write("        <li><a href='301.html'><font size=4><font color=darkPurple><b>301</b></font> - <font color=darkBlue>अतोऽन्यत्पापम्॥२६॥</font></font></a></li>");
document.write("        <li><a href='302.html'><font size=4><br><font size=5 color=black><b>﻿अधिकार-९ (संवर-निर्जराधिकार) </b></font><br><br><font color=darkPurple><b>302</b></font> - <font color=darkGreen>﻿आस्रव-निरोध: संवर:॥१॥</font></font></a></li>");
document.write("        <li><a href='303.html'><font size=4><font color=darkPurple><b>303</b></font> - <font color=darkBlue>स गुप्ति-समिति-धर्मानुप्रेक्षा-परीषहजय-चारित्रै:॥२॥</font></font></a></li>");
document.write("        <li><a href='304.html'><font size=4><font color=darkPurple><b>304</b></font> - <font color=darkGreen>तपसा निर्जरा च॥३॥</font></font></a></li>");
document.write("        <li><a href='305.html'><font size=4><font color=darkPurple><b>305</b></font> - <font color=darkBlue>सम्यग्योगनिग्रहो गुप्ति:॥४॥</font></font></a></li>");
document.write("        <li><a href='306.html'><font size=4><font color=darkPurple><b>306</b></font> - <font color=darkGreen>ईर्याभाषैषणा-दाननिक्षेपोत्सर्गा: समितय:॥५॥</font></font></a></li>");
document.write("        <li><a href='307.html'><font size=4><font color=darkPurple><b>307</b></font> - <font color=darkBlue>उत्तमक्षमा-मार्दवार्जव-सत्य-शौच-संयमतपस्त्यागा-किञ्चन्य-ब्रह्मचर्याणि धर्म:॥६॥</font></font></a></li>");
document.write("        <li><a href='308.html'><font size=4><font color=darkPurple><b>308</b></font> - <font color=darkGreen>अनित्याशरण-संसारैकत्वान्य-त्वाशुच्यास्रवसंवर-निर्जरा-लोक-बोधिदुर्लभ-धर्म-स्वाख्यातत्त्वानु-चिन्तन-मनुप्रेक्षा:॥७॥</font></font></a></li>");
document.write("        <li><a href='309.html'><font size=4><font color=darkPurple><b>309</b></font> - <font color=darkBlue>मार्गाच्यवन-निर्जरार्थं परिषोढव्या: परीषहा:॥८॥</font></font></a></li>");
document.write("        <li><a href='310.html'><font size=4><font color=darkPurple><b>310</b></font> - <font color=darkGreen>क्षुत्पिपासा-शीतोष्णदंश-मशक-नाग्न्यारति-स्त्री-चर्या-निषद्या-शय्याक्रोशवधयाचनालाभ-रोग-तृणस्पर्श-मल-सत्कारपुरस्कार-प्रज्ञाज्ञानादर्शनानि॥९॥</font></font></a></li>");
document.write("        <li><a href='311.html'><font size=4><font color=darkPurple><b>311</b></font> - <font color=darkBlue>सूक्ष्मसाम्पराय-छद्मस्थवीत-रागयोश्चतुर्दश॥१०॥</font></font></a></li>");
document.write("        <li><a href='312.html'><font size=4><font color=darkPurple><b>312</b></font> - <font color=darkGreen>एकादश जिने॥११॥</font></font></a></li>");
document.write("        <li><a href='313.html'><font size=4><font color=darkPurple><b>313</b></font> - <font color=darkBlue>बादर-साम्पराये सर्वे॥१२॥</font></font></a></li>");
document.write("        <li><a href='314.html'><font size=4><font color=darkPurple><b>314</b></font> - <font color=darkGreen>ज्ञानावरणे प्रज्ञाज्ञाने॥१३॥</font></font></a></li>");
document.write("        <li><a href='315.html'><font size=4><font color=darkPurple><b>315</b></font> - <font color=darkBlue>दर्शन-मोहान्तराययोरदर्शनालाभौ॥१४॥</font></font></a></li>");
document.write("        <li><a href='316.html'><font size=4><font color=darkPurple><b>316</b></font> - <font color=darkGreen>चारित्रमोहे नाग्न्यारति-स्त्री-निषद्या-क्रोश-याचना-सत्कारपुरस्कारा:॥१५॥</font></font></a></li>");
document.write("        <li><a href='317.html'><font size=4><font color=darkPurple><b>317</b></font> - <font color=darkBlue>वेदनीये शेषा:॥१६॥</font></font></a></li>");
document.write("        <li><a href='318.html'><font size=4><font color=darkPurple><b>318</b></font> - <font color=darkGreen>एकादयो भाज्या युगपदेक-स्मिन्नैकोनविंशते:॥१७॥</font></font></a></li>");
document.write("        <li><a href='319.html'><font size=4><font color=darkPurple><b>319</b></font> - <font color=darkBlue>सामायिकच्छेदोपस्थापना-परिहारविशुद्धि-सूक्ष्मसाम्पराय-यथाख्यात-मितिचारित्रम्॥१८॥</font></font></a></li>");
document.write("        <li><a href='320.html'><font size=4><font color=darkPurple><b>320</b></font> - <font color=darkGreen>अनशनावमौदर्य-वृत्तिपरिसंख्यान-रस-परित्याग-विविक्तशय्यासन-कायक्लेशा बाह्यं तप:॥१९॥</font></font></a></li>");
document.write("        <li><a href='321.html'><font size=4><font color=darkPurple><b>321</b></font> - <font color=darkBlue>प्रायश्चित्त-विनय-वैयावृत्त्य-स्वाध्याय-व्युत्सर्ग-ध्यानान्युत्तरम्॥२०॥</font></font></a></li>");
document.write("        <li><a href='322.html'><font size=4><font color=darkPurple><b>322</b></font> - <font color=darkGreen>नवचतुर्दश-पञ्च द्विभेदा यथाक्रमं प्राग्ध्यानात्॥२१॥</font></font></a></li>");
document.write("        <li><a href='323.html'><font size=4><font color=darkPurple><b>323</b></font> - <font color=darkBlue>आलोचना-प्रतिक्रमण-तदुभय-विवेक-व्युत्सर्ग-तपश्छेदपरिहारो-पस्थापना:॥२२॥</font></font></a></li>");
document.write("        <li><a href='324.html'><font size=4><font color=darkPurple><b>324</b></font> - <font color=darkGreen>ज्ञान-दर्शन-चारित्रोपचारा:॥२३॥</font></font></a></li>");
document.write("        <li><a href='325.html'><font size=4><font color=darkPurple><b>325</b></font> - <font color=darkBlue>आचार्योपाध्याय-तपस्वि-शैक्ष्य-ग्लान-गण-कुल-संघ-साधु-मनोज्ञानाम्॥२४॥</font></font></a></li>");
document.write("        <li><a href='326.html'><font size=4><font color=darkPurple><b>326</b></font> - <font color=darkGreen>वाचना-पृच्छनानुप्रेक्षाम्नाय-धर्मोपदेशा:॥२५॥</font></font></a></li>");
document.write("        <li><a href='327.html'><font size=4><font color=darkPurple><b>327</b></font> - <font color=darkBlue>बाह्याभ्यन्तरो-पध्यो:॥२६॥</font></font></a></li>");
document.write("        <li><a href='328.html'><font size=4><font color=darkPurple><b>328</b></font> - <font color=darkGreen>उत्तम-संहननस्यैकाग्र-चिन्ता-निरोधो ध्यानमान्त-र्मुहूर्तात्॥२७॥</font></font></a></li>");
document.write("        <li><a href='329.html'><font size=4><font color=darkPurple><b>329</b></font> - <font color=darkBlue>आत्र्त-रौद्र-धम्र्य-शुक्लानि॥२८॥</font></font></a></li>");
document.write("        <li><a href='330.html'><font size=4><font color=darkPurple><b>330</b></font> - <font color=darkGreen>परे मोक्षहेतू॥२९॥</font></font></a></li>");
document.write("        <li><a href='331.html'><font size=4><font color=darkPurple><b>331</b></font> - <font color=darkBlue>आर्तममनोज्ञस्य संप्रयोगे तद्विप्रयोगाय स्मृति-समन्वाहार:॥३०॥</font></font></a></li>");
document.write("        <li><a href='332.html'><font size=4><font color=darkPurple><b>332</b></font> - <font color=darkGreen>विपरीतं मनोज्ञस्य॥३१॥</font></font></a></li>");
document.write("        <li><a href='333.html'><font size=4><font color=darkPurple><b>333</b></font> - <font color=darkBlue>वेदनायाश्च॥३२॥</font></font></a></li>");
document.write("        <li><a href='334.html'><font size=4><font color=darkPurple><b>334</b></font> - <font color=darkGreen>﻿निदानं च ॥३३॥</font></font></a></li>");
document.write("        <li><a href='335.html'><font size=4><font color=darkPurple><b>335</b></font> - <font color=darkBlue>﻿तदविरतदेशविरतप्रमत्तसंयतानां ॥३४॥</font></font></a></li>");
document.write("        <li><a href='336.html'><font size=4><font color=darkPurple><b>336</b></font> - <font color=darkGreen>हिंसानृत-स्तेय-विषयसंरक्षणेभ्यो रौद्रमविरत-देशविरतयो:॥३५॥</font></font></a></li>");
document.write("        <li><a href='337.html'><font size=4><font color=darkPurple><b>337</b></font> - <font color=darkBlue>﻿आज्ञापाय-विपाक-संस्थान-विचयाय धर्म्यम् ॥३६॥</font></font></a></li>");
document.write("        <li><a href='338.html'><font size=4><font color=darkPurple><b>338</b></font> - <font color=darkGreen>शुक्ले चाद्ये पूर्व-विद:॥३७॥</font></font></a></li>");
document.write("        <li><a href='339.html'><font size=4><font color=darkPurple><b>339</b></font> - <font color=darkBlue>परे केवलिन:॥३८॥</font></font></a></li>");
document.write("        <li><a href='340.html'><font size=4><font color=darkPurple><b>340</b></font> - <font color=darkGreen>पृथ्क्त्वैकत्ववितर्व-सूक्ष्म-क्रियाप्रतिपाति-व्युपरतक्रियानिवर्तीनि॥३९॥</font></font></a></li>");
document.write("        <li><a href='341.html'><font size=4><font color=darkPurple><b>341</b></font> - <font color=darkBlue>त्र्येकयोग-काययोगायोगानाम्॥४०॥</font></font></a></li>");
document.write("        <li><a href='342.html'><font size=4><font color=darkPurple><b>342</b></font> - <font color=darkGreen>﻿एकाश्रये सवितर्कवीचारे पूर्वे॥४१॥</font></font></a></li>");
document.write("        <li><a href='343.html'><font size=4><font color=darkPurple><b>343</b></font> - <font color=darkBlue>अवीचारं द्वितीयम्॥४२॥</font></font></a></li>");
document.write("        <li><a href='344.html'><font size=4><font color=darkPurple><b>344</b></font> - <font color=darkGreen>﻿वितर्क: श्रुतम् ॥४३॥</font></font></a></li>");
document.write("        <li><a href='345.html'><font size=4><font color=darkPurple><b>345</b></font> - <font color=darkBlue>वीचारोऽर्थव्यंजन-योगसंक्रान्ति:॥४४॥</font></font></a></li>");
document.write("        <li><a href='346.html'><font size=4><font color=darkPurple><b>346</b></font> - <font color=darkGreen>सम्यग्दृष्टि-श्रावक-विरता-नन्तवियोजक-दर्शनमोह-क्षपकोपशम-कोपशांत-मोहक्षपक-क्षीणमोह-जिना: क्रमशोऽसंख्येय-गुण-निर्जरा:॥४५॥</font></font></a></li>");
document.write("        <li><a href='347.html'><font size=4><font color=darkPurple><b>347</b></font> - <font color=darkBlue>﻿पुलाक-वकुश-कुशील-निर्ग्रन्थ-स्नातका निर्ग्रंथा: ॥४६॥</font></font></a></li>");
document.write("        <li><a href='348.html'><font size=4><font color=darkPurple><b>348</b></font> - <font color=darkGreen>संयम-श्रुत-प्रतिसेवना-तीर्थलिङ्ग-लेश्योपपाद-स्थान-विकल्पत: साध्या:॥४७॥</font></font></a></li>");
document.write("        <li><a href='349.html'><font size=4><br><font size=5 color=black><b>﻿अधिकार-१० (मोक्षाधिकार) </b></font><br><br><font color=darkPurple><b>349</b></font> - <font color=darkBlue>﻿मोहक्षयाज्ज्ञान-दर्शनावरणान्तराय-क्षयाच्च केवलम्॥१॥</font></font></a></li>");
document.write("        <li><a href='350.html'><font size=4><font color=darkPurple><b>350</b></font> - <font color=darkGreen>बन्धहेत्वभाव-निर्जराभ्यां कृत्स्न-कर्म-विप्रमोक्षो मोक्ष:॥२॥</font></font></a></li>");
document.write("        <li><a href='351.html'><font size=4><font color=darkPurple><b>351</b></font> - <font color=darkBlue>औपशमिकादि-भव्यत्वानां च॥३॥</font></font></a></li>");
document.write("        <li><a href='352.html'><font size=4><font color=darkPurple><b>352</b></font> - <font color=darkGreen>अन्यत्र केवलसम्यक्त्व-ज्ञान-दर्शन-सिद्धत्वेभ्य:॥४॥</font></font></a></li>");
document.write("        <li><a href='353.html'><font size=4><font color=darkPurple><b>353</b></font> - <font color=darkBlue>﻿तदनन्तरमूर्ध्वं गच्छत्या-लोकान्तात्॥५॥</font></font></a></li>");
document.write("        <li><a href='354.html'><font size=4><font color=darkPurple><b>354</b></font> - <font color=darkGreen>पूर्वप्रयोगादसङ्गत्वाद्-बन्धच्छेदात्तथागतिपरिणामाच्च॥६॥</font></font></a></li>");
document.write("        <li><a href='355.html'><font size=4><font color=darkPurple><b>355</b></font> - <font color=darkBlue>आविद्धकुलालचक्रवद्-व्यपगतलेपालाबुवदेरण्डबीजवदग्निशिखावच्च॥७॥</font></font></a></li>");
document.write("        <li><a href='356.html'><font size=4><font color=darkPurple><b>356</b></font> - <font color=darkGreen>धर्मास्तिकायाभावात्॥८॥</font></font></a></li>");
document.write("        <li><a href='357.html'><font size=4><font color=darkPurple><b>357</b></font> - <font color=darkBlue>क्षेत्र-काल-गति-लिङ्ग-तीर्थचारित्र-प्रत्येकबुद्धबोधित-ज्ञानावगाहनान्तर-संख्याल्पबहुत्वत: साध्या:॥९॥</font></font></a></li>");
document.write("        <li><a href='37.html'><font size=4>37</font></a></li>");
document.write("        <li><a href='miss.html'><font size=4>miss</font></a></li>");
document.write("        <li><a href='39.html'><font size=4>39</font></a></li>");
document.write("        <li><a href='miss.html'><font size=4>miss</font></a></li>");
document.write("</ul></div>");
document.write("<div id=राजवार्तिक class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='001.html'><font size=4><br><font size=5 color=black><b>﻿अधिकार-१ (जीवाधिकार) </b></font><br><br><font color=darkPurple><b>001</b></font> - <font color=darkGreen>﻿सम्यग्दर्शनज्ञानचारित्राणि मोक्षमार्गः॥१॥</font></font></a></li>");
document.write("        <li><a href='002.html'><font size=4><font color=darkPurple><b>002</b></font> - <font color=darkBlue>﻿तत्त्वार्थश्रद्धानं सम्यग्दर्शनम्॥२॥</font></font></a></li>");
document.write("        <li><a href='006.html'><font size=4><font color=darkPurple><b>006</b></font> - <font color=darkGreen>﻿प्रमाणनयैरधिगमः॥६॥</font></font></a></li>");
document.write("        <li><a href='008.html'><font size=4><font color=darkPurple><b>008</b></font> - <font color=darkBlue>﻿सत्संख्याक्षेत्रस्पर्शनकालान्तरभावाल्पबहुत्वैश्‍च॥८॥</font></font></a></li>");
document.write("        <li><a href='009.html'><font size=4><font color=darkPurple><b>009</b></font> - <font color=darkGreen>﻿मतिश्रुतावधिमनःपर्ययकेवलानि ज्ञानम्॥९॥</font></font></a></li>");
document.write("        <li><a href='012.html'><font size=4><font color=darkPurple><b>012</b></font> - <font color=darkBlue>﻿प्रत्यक्षमन्यत्॥१२॥</font></font></a></li>");
document.write("        <li><a href='020.html'><font size=4><font color=darkPurple><b>020</b></font> - <font color=darkGreen>﻿श्रुतं मतिपूर्वं द्वयनेकद्वादशभेदम्‌॥२०॥</font></font></a></li>");
document.write("        <li><a href='030.html'><font size=4><font color=darkPurple><b>030</b></font> - <font color=darkBlue>﻿एकादीनि भाज्यानि युगपदेकस्मिन्नाचतुर्भ्यः॥३०॥</font></font></a></li>");
document.write("        <li><a href='040.html'><font size=4><font color=darkPurple><b>040</b></font> - <font color=darkGreen>﻿जीवभव्याभव्यत्वानि च॥७॥</font></font></a></li>");
document.write("        <li><a href='041.html'><font size=4><font color=darkPurple><b>041</b></font> - <font color=darkBlue>﻿उपयोगो लक्षणम्॥८॥</font></font></a></li>");
document.write("        <li><a href='048.html'><font size=4><font color=darkPurple><b>048</b></font> - <font color=darkGreen>﻿पंचेद्रियाणि॥१५॥</font></font></a></li>");
document.write("        <li><a href='051.html'><font size=4><font color=darkPurple><b>051</b></font> - <font color=darkBlue>﻿लब्ध्युपयोगो भावेन्द्रियम्॥१८॥</font></font></a></li>");
document.write("        <li><a href='055.html'><font size=4><font color=darkPurple><b>055</b></font> - <font color=darkGreen>﻿वनस्पत्यन्तानामेकम्॥२२॥</font></font></a></li>");
document.write("        <li><a href='066.html'><font size=4><font color=darkPurple><b>066</b></font> - <font color=darkBlue>﻿जरायुजाण्डजपोतानां गर्भः॥३३॥</font></font></a></li>");
document.write("        <li><a href='082.html'><font size=4><font color=darkPurple><b>082</b></font> - <font color=darkGreen>﻿शुभं विशुद्धमव्याघाति चाहारकं प्रमत्तसंयतस्यैव॥४९॥</font></font></a></li>");
document.write("        <li><a href='086.html'><font size=4><font color=darkPurple><b>086</b></font> - <font color=darkBlue>﻿औपपादिक चरमोत्तम-देहाऽसंख्येय-वर्षायुषोsनपवर्त्यायुषः॥५३॥</font></font></a></li>");
document.write("        <li><a href='124.html'><font size=4><font color=darkPurple><b>124</b></font> - <font color=darkGreen>﻿नृस्थितीपरावरे त्रिपल्योपमान्तर्मुहूर्ते॥३८॥</font></font></a></li>");
document.write("        <li><a href='167.html'><font size=4><font color=darkPurple><b>167</b></font> - <font color=darkBlue>लौकान्तिकानामष्टौ सागरोपमाणि सर्वेषाम्॥४२॥</font></font></a></li>");
document.write("        <li><a href='168.html'><font size=4><br><font size=5 color=black><b>﻿अधिकार-५ (अजीवाधिकार) </b></font><br><br><font color=darkPurple><b>168</b></font> - <font color=darkGreen>﻿अजीव-काया-धर्माधर्माकाश-पुद्गला:॥१॥</font></font></a></li>");
document.write("        <li><a href='169.html'><font size=4><font color=darkPurple><b>169</b></font> - <font color=darkBlue>द्रव्याणि॥२॥</font></font></a></li>");
document.write("        <li><a href='175.html'><font size=4><font color=darkPurple><b>175</b></font> - <font color=darkGreen>असंख्येया: प्रदेशा धर्माधर्मैकजीवानाम्॥८॥</font></font></a></li>");
document.write("        <li><a href='176.html'><font size=4><font color=darkPurple><b>176</b></font> - <font color=darkBlue>आकाशस्यानन्ता:॥९॥</font></font></a></li>");
document.write("        <li><a href='186.html'><font size=4><font color=darkPurple><b>186</b></font> - <font color=darkGreen>शरीरवाङ्मन:-प्राणापाना पुद्गलानाम्॥१९॥</font></font></a></li>");
document.write("        <li><a href='189.html'><font size=4><font color=darkPurple><b>189</b></font> - <font color=darkBlue>वर्तना-परिणाम-क्रिया-परत्वापरत्वे च कालस्य॥२२॥</font></font></a></li>");
document.write("        <li><a href='192.html'><font size=4><font color=darkPurple><b>192</b></font> - <font color=darkGreen>अणव: स्कन्धाश्च॥२५॥</font></font></a></li>");
document.write("        <li><a href='211.html'><font size=4><font color=darkPurple><b>211</b></font> - <font color=darkBlue>﻿स आस्रव: ॥२॥</font></font></a></li>");
document.write("        <li><a href='233.html'><font size=4><font color=darkPurple><b>233</b></font> - <font color=darkGreen>दर्शनविशुद्धिर्विनयसम्पन्नता-शील-व्रतेष्वनतीचारोऽभीक्ष्ण-ज्ञानोपयोगसंवेगौ शक्तितस्त्याग-तपसी साधुसमाधिर्वैयावृत्य-करणमर्हदाचार्य-बहुश्रुत-प्रवचन-भक्तिरावश्यकापरिहाणिर्मार्ग-प्रभावना-प्रवचनवत्सलत्वमिति तीर्थकरत्वस्य॥२४॥</font></font></a></li>");
document.write("        <li><a href='241.html'><font size=4><font color=darkPurple><b>241</b></font> - <font color=darkBlue>क्रोध-लोभ-भीरुत्व-हास्य-प्रत्याख्यानान्यनुवीचि-भाषणं च पञ्च॥५॥</font></font></a></li>");
document.write("        <li><a href='250.html'><font size=4><font color=darkPurple><b>250</b></font> - <font color=darkGreen>असदभिधानमनृतम्॥१४॥</font></font></a></li>");
document.write("        <li><a href='258.html'><font size=4><font color=darkPurple><b>258</b></font> - <font color=darkBlue>मारणान्तिकीं सल्लेखनां जोषिता॥२२॥</font></font></a></li>");
document.write("        <li><a href='259.html'><font size=4><font color=darkPurple><b>259</b></font> - <font color=darkGreen>शंका-कांक्षाविचिकित्सान्यदृष्टि-प्रशंसा-संस्तवा: सम्यग्दृष्टेरती-चारा:॥२३॥</font></font></a></li>");
document.write("        <li><a href='263.html'><font size=4><font color=darkPurple><b>263</b></font> - <font color=darkBlue>स्तेनप्रयोग-तदाहृतादानविरुद्धराज्यातिक्रम-हीनाधिकमानोन्मान-प्रतिरूपक-व्यवहारा:॥२७॥</font></font></a></li>");
document.write("        <li><a href='264.html'><font size=4><font color=darkPurple><b>264</b></font> - <font color=darkGreen>परविवाह करणेत्वरिका-परिगृहीतापरिगृहीता-गमनानङ्गक्रीडा-कामतीव्राभिनिवेशा:॥२८॥</font></font></a></li>");
document.write("        <li><a href='265.html'><font size=4><font color=darkPurple><b>265</b></font> - <font color=darkBlue>क्षेत्रवास्तु-हिरण्यसुवर्ण-धन-धान्य-दासीदास-कुप्य-प्रमाणातिक्रमा:॥२९॥</font></font></a></li>");
document.write("        <li><a href='266.html'><font size=4><font color=darkPurple><b>266</b></font> - <font color=darkGreen>﻿ऊर्ध्वाधस्तिर्यग्व्यतिक्रमक्षेत्रवृद्धि-स्मृत्यंतराधानानि ॥३०॥</font></font></a></li>");
document.write("        <li><a href='267.html'><font size=4><font color=darkPurple><b>267</b></font> - <font color=darkBlue>आनयन-प्रेष्यप्रयोग-शब्दरूपानुपात-पुद्गलक्षेपा:॥३१॥</font></font></a></li>");
document.write("        <li><a href='268.html'><font size=4><font color=darkPurple><b>268</b></font> - <font color=darkGreen>कन्दर्प-कौत्कुच्य-मौखर्यासमीक्ष्याधि-करणोपभोगपरिभोगानर्थक्यानि॥३२॥</font></font></a></li>");
document.write("        <li><a href='272.html'><font size=4><font color=darkPurple><b>272</b></font> - <font color=darkBlue>सचित्त-निक्षेपापिधानपरव्यपदेश-मात्सर्यकालातिक्रमा:॥३६॥</font></font></a></li>");
document.write("        <li><a href='276.html'><font size=4><br><font size=5 color=black><b>﻿अधिकार-८ (बंधाधिकार) </b></font><br><br><font color=darkPurple><b>276</b></font> - <font color=darkGreen>﻿मिथ्यादर्शनाविरति-प्रमाद-कषाय-योगा बन्धहेतव: ॥१॥</font></font></a></li>");
document.write("        <li><a href='281.html'><font size=4><font color=darkPurple><b>281</b></font> - <font color=darkBlue>﻿मतिश्रुतावधि-मन:पर्यय केवलानाम् ॥६॥</font></font></a></li>");
document.write("        <li><a href='284.html'><font size=4><font color=darkPurple><b>284</b></font> - <font color=darkGreen>﻿दर्शनचारित्र-मोहनीयाकषाय-कषायवेदनीयाख्यास्त्रिद्वि-नव-षोडशभेदा: सम्यक्त्व-मिथ्यात्व-तदुभयान्यकषाय-कषायौ हास्यरत्यरति-शोक-भय-जुगुप्सा-स्त्री-पुन्नपुंसक-वेदा अनन्तानुबंध्य-प्रत्याख्यान-प्रत्याख्यान-संज्वलन-विकल्पाश्चैकश: क्रोध-मान-माया-लोभा: ॥९॥</font></font></a></li>");
document.write("        <li><a href='286.html'><font size=4><font color=darkPurple><b>286</b></font> - <font color=darkBlue>﻿गति-जाति-शरीराङ्गोपाङ्गनिर्माण-बंधन-संघात-संस्थान-संहनन-स्पर्श-रस-गंध-वर्णानुपूव्र्यगुरुलघूपघात-परघातातपोद्योतोच्छ्वास-विहायोगतय: प्रत्येक-शरीर-त्रस-सुभग-सुस्वर-शुभ-सूक्ष्म-पर्याप्ति-स्थिरादेय यश: कीर्ति-सेतराणि तीर्थकरत्वं च ॥११॥</font></font></a></li>");
document.write("        <li><a href='304.html'><font size=4><font color=darkPurple><b>304</b></font> - <font color=darkGreen>तपसा निर्जरा च॥३॥</font></font></a></li>");
document.write("        <li><a href='308.html'><font size=4><font color=darkPurple><b>308</b></font> - <font color=darkBlue>अनित्याशरण-संसारैकत्वान्य-त्वाशुच्यास्रवसंवर-निर्जरा-लोक-बोधिदुर्लभ-धर्म-स्वाख्यातत्त्वानु-चिन्तन-मनुप्रेक्षा:॥७॥</font></font></a></li>");
document.write("        <li><a href='310.html'><font size=4><font color=darkPurple><b>310</b></font> - <font color=darkGreen>क्षुत्पिपासा-शीतोष्णदंश-मशक-नाग्न्यारति-स्त्री-चर्या-निषद्या-शय्याक्रोशवधयाचनालाभ-रोग-तृणस्पर्श-मल-सत्कारपुरस्कार-प्रज्ञाज्ञानादर्शनानि॥९॥</font></font></a></li>");
document.write("        <li><a href='312.html'><font size=4><font color=darkPurple><b>312</b></font> - <font color=darkBlue>एकादश जिने॥११॥</font></font></a></li>");
document.write("        <li><a href='323.html'><font size=4><font color=darkPurple><b>323</b></font> - <font color=darkGreen>आलोचना-प्रतिक्रमण-तदुभय-विवेक-व्युत्सर्ग-तपश्छेदपरिहारो-पस्थापना:॥२२॥</font></font></a></li>");
document.write("        <li><a href='324.html'><font size=4><font color=darkPurple><b>324</b></font> - <font color=darkBlue>ज्ञान-दर्शन-चारित्रोपचारा:॥२३॥</font></font></a></li>");
document.write("        <li><a href='328.html'><font size=4><font color=darkPurple><b>328</b></font> - <font color=darkGreen>उत्तम-संहननस्यैकाग्र-चिन्ता-निरोधो ध्यानमान्त-र्मुहूर्तात्॥२७॥</font></font></a></li>");
document.write("        <li><a href='337.html'><font size=4><font color=darkPurple><b>337</b></font> - <font color=darkBlue>﻿आज्ञापाय-विपाक-संस्थान-विचयाय धर्म्यम् ॥३६॥</font></font></a></li>");
document.write("        <li><a href='338.html'><font size=4><font color=darkPurple><b>338</b></font> - <font color=darkGreen>शुक्ले चाद्ये पूर्व-विद:॥३७॥</font></font></a></li>");
document.write("        <li><a href='339.html'><font size=4><font color=darkPurple><b>339</b></font> - <font color=darkBlue>परे केवलिन:॥३८॥</font></font></a></li>");
document.write("        <li><a href='340.html'><font size=4><font color=darkPurple><b>340</b></font> - <font color=darkGreen>पृथ्क्त्वैकत्ववितर्व-सूक्ष्म-क्रियाप्रतिपाति-व्युपरतक्रियानिवर्तीनि॥३९॥</font></font></a></li>");
document.write("        <li><a href='341.html'><font size=4><font color=darkPurple><b>341</b></font> - <font color=darkBlue>त्र्येकयोग-काययोगायोगानाम्॥४०॥</font></font></a></li>");
document.write("        <li><a href='346.html'><font size=4><font color=darkPurple><b>346</b></font> - <font color=darkGreen>सम्यग्दृष्टि-श्रावक-विरता-नन्तवियोजक-दर्शनमोह-क्षपकोपशम-कोपशांत-मोहक्षपक-क्षीणमोह-जिना: क्रमशोऽसंख्येय-गुण-निर्जरा:॥४५॥</font></font></a></li>");
document.write("        <li><a href='357.html'><font size=4><font color=darkPurple><b>357</b></font> - <font color=darkBlue>क्षेत्र-काल-गति-लिङ्ग-तीर्थचारित्र-प्रत्येकबुद्धबोधित-ज्ञानावगाहनान्तर-संख्याल्पबहुत्वत: साध्या:॥९॥</font></font></a></li>");
document.write("</ul></div>");
