
$( document ).ready(function() {
  $('.teekakaar').change(function() {
    window.location.href = $(this).val()
  })
})
function toggleTeeka(teeka) {
  $('#teeka'+teeka).toggle();
  if($('.teeka'+teeka).css('color')=='rgb(255, 0, 0)') {
    $('.teeka'+teeka).css('color', 'green')
  }else{
    $('.teeka'+teeka).css('color', 'red')
  }
}
function toggleSTeeka(teeka) {
  $('#steeka'+teeka).toggle();
  if($('#stitle'+teeka).css('color')=='rgb(255, 0, 0)') {
    $('#stitle'+teeka).css('color', 'green')
  }else{
    $('#stitle'+teeka).css('color', 'red')
  }
}
$( document ).ready(function() {
  mySel=$('select#select-native-0')
    $optgrp=$('<optgroup label="﻿अधिकार-१ (जीवाधिकार)">')
       $optgrp.append("<option value='001.html'><b>001</b> - ﻿सम्यग्दर्शनज्ञानचारित्राणि मोक्षमार्गः॥१॥</option>");
       $optgrp.append("<option value='002.html'><b>002</b> - ﻿तत्त्वार्थश्रद्धानं सम्यग्दर्शनम्॥२॥</option>");
       $optgrp.append("<option value='003.html'><b>003</b> - ﻿तन्निसर्गादधिगमाद्वा॥३॥</option>");
       $optgrp.append("<option value='004.html'><b>004</b> - ﻿जीवजीवास्रवबन्धसंवरनिर्जरामोक्षास्तत्त्वम्॥४॥</option>");
       $optgrp.append("<option value='005.html'><b>005</b> - ﻿नामस्थापनाद्रव्यभाव तस्तन्न्यासः॥५॥</option>");
       $optgrp.append("<option value='006.html'><b>006</b> - ﻿प्रमाणनयैरधिगमः॥६॥</option>");
       $optgrp.append("<option value='007.html'><b>007</b> - ﻿निर्देशस्वामित्वसाधनाधिकरणस्थितिविधानतः॥७॥</option>");
       $optgrp.append("<option value='008.html'><b>008</b> - ﻿सत्संख्याक्षेत्रस्पर्शनकालान्तरभावाल्पबहुत्वैश्‍च॥८॥</option>");
       $optgrp.append("<option value='009.html'><b>009</b> - ﻿मतिश्रुतावधिमनःपर्ययकेवलानि ज्ञानम्॥९॥</option>");
       $optgrp.append("<option value='010.html'><b>010</b> - ﻿तत्प्रमाणे॥१०॥</option>");
       $optgrp.append("<option value='011.html'><b>011</b> - ﻿आद्ये परोक्षम्॥११॥</option>");
       $optgrp.append("<option value='012.html'><b>012</b> - ﻿प्रत्यक्षमन्यत्॥१२॥</option>");
       $optgrp.append("<option value='013.html'><b>013</b> - ﻿मतिः स्मृतिः संज्ञा चिन्ताsभिनिबोध इत्यानर्थान्तरम्॥१३॥</option>");
       $optgrp.append("<option value='014.html'><b>014</b> - ﻿तदिन्द्रयानिन्द्रिय निमित्तम्॥१४॥</option>");
       $optgrp.append("<option value='015.html'><b>015</b> - ﻿अवग्रहेहावाय धारणाः॥१५॥</option>");
       $optgrp.append("<option value='016.html'><b>016</b> - ﻿बहुबहुविधक्षिप्रानिःसृतानुक्तध्रुवाणां सेतराणाम्‌॥१६॥</option>");
       $optgrp.append("<option value='017.html'><b>017</b> - ﻿अर्थस्य॥१७॥</option>");
       $optgrp.append("<option value='018.html'><b>018</b> - ﻿व्यञ्जनस्यावग्रहः॥१८॥</option>");
       $optgrp.append("<option value='019.html'><b>019</b> - ﻿न चक्षुरनिन्द्रियाभ्याम्॥१९॥</option>");
       $optgrp.append("<option value='020.html'><b>020</b> - ﻿श्रुतं मतिपूर्वं द्वयनेकद्वादशभेदम्‌॥२०॥</option>");
       $optgrp.append("<option value='021.html'><b>021</b> - ﻿भवप्रत्ययोऽवधिर्देवनारकाणाम्॥२१॥</option>");
       $optgrp.append("<option value='022.html'><b>022</b> - ﻿क्षयोपशमनिमित्तः षड्विकल्पः शेषाणाम्॥२२॥</option>");
       $optgrp.append("<option value='023.html'><b>023</b> - ﻿ऋजुविपुलमती मनःपर्ययः॥२३॥</option>");
       $optgrp.append("<option value='024.html'><b>024</b> - ﻿विशुद्धयप्रतिपाताभ्यां तद्विशेषः॥२४॥</option>");
       $optgrp.append("<option value='025.html'><b>025</b> - ﻿विशुद्धिक्षेत्रस्वामिविषयेभ्योऽवधिमनःपर्यययोः॥२५॥</option>");
       $optgrp.append("<option value='026.html'><b>026</b> - ﻿मतिश्रुतयोर्निबन्धो द्रव्येष्वसर्वपर्यायेषु॥२६॥</option>");
       $optgrp.append("<option value='027.html'><b>027</b> - ﻿रूपिष्ववधेः॥२७॥</option>");
       $optgrp.append("<option value='028.html'><b>028</b> - ﻿तदनन्तभागे मनःपर्ययस्य॥२८॥</option>");
       $optgrp.append("<option value='029.html'><b>029</b> - ﻿सर्वद्रव्यपर्यायेषु केवलस्य॥२९॥</option>");
       $optgrp.append("<option value='030.html'><b>030</b> - ﻿एकादीनि भाज्यानि युगपदेकस्मिन्नाचतुर्भ्यः॥३०॥</option>");
       $optgrp.append("<option value='031.html'><b>031</b> - ﻿मतिश्रुतावधयो विपर्ययश्‍च॥३१॥</option>");
       $optgrp.append("<option value='032.html'><b>032</b> - ﻿सदसतोरविशेषाद्यदृच्छोपलब्धेरुन्मत्तवत्॥३२॥</option>");
       $optgrp.append("<option value='033.html'><b>033</b> - ﻿नैगमसंग्रहव्यवहारर्जुसूत्रशब्दसमभिरूढैवंभूता नयाः॥३३॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿अधिकार-२ (जीवाधिकार)">')
       $optgrp.append("<option value='034.html'><b>034</b> - ﻿औपशमिकक्षायिकौ भावौ मिश्रश्च जीवस्य स्वतत्त्वमौदयिकपारिणामिकौ च॥१॥</option>");
       $optgrp.append("<option value='035.html'><b>035</b> - ﻿द्विनवाष्टादशैकविंशतित्रिभेदा यथाक्रमम्॥२॥</option>");
       $optgrp.append("<option value='036.html'><b>036</b> - ﻿सम्यक्त्वचारित्रे॥३॥</option>");
       $optgrp.append("<option value='037.html'><b>037</b> - ﻿ज्ञानदर्शनदानलाभभोगोपभोगवीर्याणि च॥४॥</option>");
       $optgrp.append("<option value='038.html'><b>038</b> - ﻿ज्ञानाज्ञानदर्शन लब्धयश्‍चतुस्त्रित्रि पञ्चभेदाः सम्यक्त्वचारित्र संयमासंयमाश्‍च॥५॥</option>");
       $optgrp.append("<option value='039.html'><b>039</b> - ﻿गतिकषायलिंग-मिथ्यादर्शनाज्ञानासंयतासिद्धलेश्याश्‍चतुश्‍चतुस्त्र्यैकैकैकैक-षड्भेदाः॥६॥</option>");
       $optgrp.append("<option value='040.html'><b>040</b> - ﻿जीवभव्याभव्यत्वानि च॥७॥</option>");
       $optgrp.append("<option value='041.html'><b>041</b> - ﻿उपयोगो लक्षणम्॥८॥</option>");
       $optgrp.append("<option value='042.html'><b>042</b> - ﻿स द्विविधोऽष्ट-चतुर्भेदः॥९॥</option>");
       $optgrp.append("<option value='043.html'><b>043</b> - ﻿संसारिणो मुक्ताश्‍च॥१०॥</option>");
       $optgrp.append("<option value='044.html'><b>044</b> - ﻿समनस्काsमनस्काः॥११॥</option>");
       $optgrp.append("<option value='045.html'><b>045</b> - ﻿संसारिणस्त्रसस्थावराः॥१२॥</option>");
       $optgrp.append("<option value='046.html'><b>046</b> - ﻿पृथिव्यप्तेजो वायु-वनस्पतयः स्थावराः॥१३॥</option>");
       $optgrp.append("<option value='047.html'><b>047</b> - ﻿द्वीन्द्रियादयस्त्रसाः॥१४॥</option>");
       $optgrp.append("<option value='048.html'><b>048</b> - ﻿पंचेद्रियाणि॥१५॥</option>");
       $optgrp.append("<option value='049.html'><b>049</b> - ﻿द्विविधानि॥१६॥</option>");
       $optgrp.append("<option value='050.html'><b>050</b> - ﻿निर्वृत्त्युपकरणे द्रव्येन्द्रियम्‌॥१७॥</option>");
       $optgrp.append("<option value='051.html'><b>051</b> - ﻿लब्ध्युपयोगो भावेन्द्रियम्॥१८॥</option>");
       $optgrp.append("<option value='052.html'><b>052</b> - ﻿स्पर्शन-रसन-घ्राण-चक्षुःश्रोत्राणि॥१९॥</option>");
       $optgrp.append("<option value='053.html'><b>053</b> - ﻿स्पर्श-रस-गन्ध-वर्ण-शब्दास्तदर्थाः॥२०॥</option>");
       $optgrp.append("<option value='054.html'><b>054</b> - ﻿श्रुतमनिन्द्रियस्य॥२१॥</option>");
       $optgrp.append("<option value='055.html'><b>055</b> - ﻿वनस्पत्यन्तानामेकम्॥२२॥</option>");
       $optgrp.append("<option value='056.html'><b>056</b> - ﻿कृमि-पिपीलिका-भ्रमर-मनुष्यादीनामेकैकवृद्धानि॥२३॥</option>");
       $optgrp.append("<option value='057.html'><b>057</b> - ﻿संज्ञिनः समनस्काः॥२४॥</option>");
       $optgrp.append("<option value='058.html'><b>058</b> - ﻿विग्रहगतौ कर्मयोगः॥२५॥</option>");
       $optgrp.append("<option value='059.html'><b>059</b> - ﻿अनुश्रेणिः गतिः॥२६॥</option>");
       $optgrp.append("<option value='060.html'><b>060</b> - ﻿अविग्रहा जीवस्य॥२७॥</option>");
       $optgrp.append("<option value='061.html'><b>061</b> - ﻿विग्रहवती च संसारिणः प्राक् चतुर्भ्यः॥२८॥</option>");
       $optgrp.append("<option value='062.html'><b>062</b> - ﻿एकसमयाsविग्रहा॥२९॥</option>");
       $optgrp.append("<option value='063.html'><b>063</b> - ﻿एकं द्वौ त्रीन्वानाहारकः॥३०॥</option>");
       $optgrp.append("<option value='064.html'><b>064</b> - ﻿सम्मूर्च्छन-गर्भोपपादा जन्म॥३१॥</option>");
       $optgrp.append("<option value='065.html'><b>065</b> - ﻿सचित्तशीतसंवृताः सेतरा मिश्राश्‍चैकशस्तद्योनयः॥३२॥</option>");
       $optgrp.append("<option value='066.html'><b>066</b> - ﻿जरायुजाण्डजपोतानां गर्भः॥३३॥</option>");
       $optgrp.append("<option value='067.html'><b>067</b> - ﻿देवनारकाणामुपपादः॥३४॥</option>");
       $optgrp.append("<option value='068.html'><b>068</b> - ﻿शेषाणां सम्मूर्च्छनं॥३५॥</option>");
       $optgrp.append("<option value='069.html'><b>069</b> - ﻿औदारिक-वैक्रियिकाहारक-तैजस-कार्मणानि शरीराणि॥३६॥</option>");
       $optgrp.append("<option value='070.html'><b>070</b> - ﻿परं परं सूक्ष्मम्॥३७॥</option>");
       $optgrp.append("<option value='071.html'><b>071</b> - ﻿प्रदेशतोऽसंख्येयगुणं प्राक् तैजसात्॥३८॥</option>");
       $optgrp.append("<option value='072.html'><b>072</b> - ﻿अनन्तगुणे परे॥३९॥</option>");
       $optgrp.append("<option value='073.html'><b>073</b> - ﻿अप्रतीघाते॥४०॥</option>");
       $optgrp.append("<option value='074.html'><b>074</b> - ﻿अनादिसंबन्धे च॥४१॥</option>");
       $optgrp.append("<option value='075.html'><b>075</b> - ﻿सर्वस्य॥४२॥</option>");
       $optgrp.append("<option value='076.html'><b>076</b> - ﻿तदादीनि भाज्यानि युगपदेकस्मिन्नाचतुर्भ्यः॥४३॥</option>");
       $optgrp.append("<option value='077.html'><b>077</b> - ﻿निरूपभोगमन्त्यम्॥४४।</option>");
       $optgrp.append("<option value='078.html'><b>078</b> - ﻿गर्भसम्मूर्च्छनजमा्द्यम्‌॥४५॥</option>");
       $optgrp.append("<option value='079.html'><b>079</b> - ﻿औपपादिकं वैक्रियिकम्‌॥४६॥</option>");
       $optgrp.append("<option value='080.html'><b>080</b> - ﻿लब्धिप्रत्ययं च॥४७॥</option>");
       $optgrp.append("<option value='081.html'><b>081</b> - ﻿तैजसमपि॥४८॥</option>");
       $optgrp.append("<option value='082.html'><b>082</b> - ﻿शुभं विशुद्धमव्याघाति चाहारकं प्रमत्तसंयतस्यैव॥४९॥</option>");
       $optgrp.append("<option value='083.html'><b>083</b> - ﻿नारकसंमूर्च्छिनो नपुंसकानि॥५०॥</option>");
       $optgrp.append("<option value='084.html'><b>084</b> - ﻿न देवाः॥५१॥</option>");
       $optgrp.append("<option value='085.html'><b>085</b> - ﻿शेषास्त्रिवेदाः॥५२॥</option>");
       $optgrp.append("<option value='086.html'><b>086</b> - ﻿औपपादिक चरमोत्तम-देहाऽसंख्येय-वर्षायुषोsनपवर्त्यायुषः॥५३॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿अधिकार-३ (जीवाधिकार)">')
       $optgrp.append("<option value='087.html'><b>087</b> - ﻿रत्न-शर्करा-बालुका-पंक-धूम-तमो-महातमः प्रभा भूमयो घनाम्बुवाताकाश प्रतिष्ठाः सप्ताsधोऽधः॥१॥</option>");
       $optgrp.append("<option value='088.html'><b>088</b> - ﻿तासु त्रिंशत्पंचविंशति पंचदशदश-त्रि-पंचोनैक-नरक-शतसहस्राणि पंच चैव यथाक्रमम्॥२॥</option>");
       $optgrp.append("<option value='089.html'><b>089</b> - ﻿नारका नित्याsशुभतर-लेश्या-परिणामदेह-वेदना-विक्रियाः॥३॥</option>");
       $optgrp.append("<option value='09 miss.html'><b>09 miss</b></option>");
       $optgrp.append("<option value='090.html'><b>090</b> - ﻿परस्परोदीरित-दुःखाः॥४॥</option>");
       $optgrp.append("<option value='091.html'><b>091</b> - ﻿संक्लिष्टासुरोदीरित-दुःखाश्‍च प्राक् चतुर्थ्याः॥५॥</option>");
       $optgrp.append("<option value='092.html'><b>092</b> - ﻿तेष्वेक-त्रि-सप्त-दश-सप्तदश-द्वाविंशति-त्रयस्त्रिंशत्सागरोपमा सत्त्वानां परा स्थितिः॥६॥</option>");
       $optgrp.append("<option value='093.html'><b>093</b> - ﻿जम्बूद्वीप-लवणोदादयः शुभनामानो द्वीप-समुद्रा॥७॥</option>");
       $optgrp.append("<option value='094.html'><b>094</b> - ﻿द्विर्द्विर्विष्कम्भाः पूर्वपूर्वपरिक्षेपिणो वलयाकृतयः॥८॥</option>");
       $optgrp.append("<option value='095.html'><b>095</b> - ﻿तन्मध्ये मेरुनाभिर्वृत्तो योजनशतसहस्रविष्कम्भो जम्बूद्वीपः॥९॥</option>");
       $optgrp.append("<option value='096.html'><b>096</b> - ﻿भरतहैमवत-हरि-विदेह-रम्यकहैरण्यवतैरावतवर्षाः क्षेत्राणि॥१०॥</option>");
       $optgrp.append("<option value='097.html'><b>097</b> - ﻿तद्विभाजिनः पूर्वापरायता हिमवन्महाहिमवन्निषध-नील-रुक्मि-शिखरिणो वर्षधर-पर्वताः॥११॥</option>");
       $optgrp.append("<option value='098.html'><b>098</b> - ﻿हेमार्जुन-तपनीय वैडूर्य-रजत हेममयाः॥१२॥</option>");
       $optgrp.append("<option value='099.html'><b>099</b> - ﻿मणि-विचित्र-पार्श्‍वा उपरि मूले च तुल्यविस्ताराः॥१३॥</option>");
       $optgrp.append("<option value='100.html'><b>100</b> - ﻿पद्ममहापद्मतिगिञ्छकेशरि महापुण्डरीकपुण्डरीका-हृदास्तेषामुपरि॥१४॥</option>");
       $optgrp.append("<option value='101.html'><b>101</b> - ﻿प्रथमो योजन-सहस्रायामस्तदर्द्धविष्कम्भो ह्रदः।॥१५॥</option>");
       $optgrp.append("<option value='102.html'><b>102</b> - ﻿दशयोजनावगाहः॥१६॥</option>");
       $optgrp.append("<option value='103.html'><b>103</b> - ﻿तन्मध्ये योजनं पुष्करम्॥१७॥</option>");
       $optgrp.append("<option value='104.html'><b>104</b> - ﻿तद् द्विगुण-द्विगुणा ह्रदाः पुष्कराणि च॥१८॥</option>");
       $optgrp.append("<option value='105.html'><b>105</b> - ﻿तन्निवासिन्यो देव्यः श्री-ह्री-धृति-कीर्ति-बुद्धि-लक्ष्म्यः पल्योपमस्थितयः ससामानिक परिषत्काः ॥१९॥</option>");
       $optgrp.append("<option value='106.html'><b>106</b> - ﻿गंगासिन्धु रोहिद्रोहितास्या-हरिद्धरिकान्ता सीतासीतोदा-नारीनरकान्ता सुवर्णरूप्यकूला रक्तारक्तोदाः सरितस्तन्मध्यगाः ॥२०॥</option>");
       $optgrp.append("<option value='107.html'><b>107</b> - ﻿द्वयोर्द्वयोः पूर्वाः पूर्वगाः॥२१॥</option>");
       $optgrp.append("<option value='108.html'><b>108</b> - ﻿शेषास्त्वपरगाः॥२२॥</option>");
       $optgrp.append("<option value='109.html'><b>109</b> - ﻿चतुर्दशनदीसहस्रपरिवृता गंगासिन्ध्वादयो नद्यः॥२३॥</option>");
       $optgrp.append("<option value='110.html'><b>110</b> - ﻿भरतः षड्विंशति-पंचयोजनशत-विस्तारः षट्चैकोनविंशतिभागा-योजनस्य ॥२४॥</option>");
       $optgrp.append("<option value='111.html'><b>111</b> - ﻿तद् द्विगुण द्विगुणविस्तारा वर्षधरवर्षा विदेहान्ताः॥२५॥</option>");
       $optgrp.append("<option value='112.html'><b>112</b> - ﻿उत्तरा दक्षिण-तुल्याः ॥२६॥</option>");
       $optgrp.append("<option value='113.html'><b>113</b> - ﻿भरतैरावतयोर्वृद्धिह्रासौ षट्‍समयाभ्यामुत्सर्पिण्यवसर्पिणीभ्याम्‌ ॥२७॥</option>");
       $optgrp.append("<option value='114.html'><b>114</b> - ﻿ताभ्यामपरा भूमयोsवस्थिताः॥२८॥</option>");
       $optgrp.append("<option value='115.html'><b>115</b> - ﻿एकद्वित्रिपल्योपम-स्थितयो हैमवतक हारिवर्षक दैवकुरुवकाः॥२९॥</option>");
       $optgrp.append("<option value='116.html'><b>116</b> - ﻿तथोत्तराः॥३०॥</option>");
       $optgrp.append("<option value='117.html'><b>117</b> - ﻿विदेहेषु संख्येयकालाः॥३१॥</option>");
       $optgrp.append("<option value='118.html'><b>118</b> - ﻿भरतस्य विष्कम्भो जम्बूद्वीपस्य नवतिशतभागः॥३२॥</option>");
       $optgrp.append("<option value='119.html'><b>119</b> - ﻿द्विर्धातकीखण्डे॥३३॥</option>");
       $optgrp.append("<option value='120.html'><b>120</b> - ﻿पुष्करार्द्धे च॥३४॥</option>");
       $optgrp.append("<option value='121.html'><b>121</b> - ﻿प्राङ् मानुषोत्तरान्मनुष्याः॥३५॥</option>");
       $optgrp.append("<option value='122.html'><b>122</b> - ﻿आर्या म्लेच्छाश्‍च॥३६॥</option>");
       $optgrp.append("<option value='123.html'><b>123</b> - ﻿भरतैरावतविदेहाः कर्मभूमयोऽन्यत्र देवकुरूत्तरकुरुभ्यः॥३७॥</option>");
       $optgrp.append("<option value='124.html'><b>124</b> - ﻿नृस्थितीपरावरे त्रिपल्योपमान्तर्मुहूर्ते॥३८॥</option>");
       $optgrp.append("<option value='125.html'><b>125</b> - ﻿तिर्यग्योनिजानां च॥३९॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿अधिकार-४ (जीवाधिकार)">')
       $optgrp.append("<option value='126.html'><b>126</b> - ﻿देवाश्चतुर्णिकाया: ॥१॥</option>");
       $optgrp.append("<option value='127.html'><b>127</b> - ﻿आदितस्त्रिषु पीतान्तलेश्या: ॥२॥</option>");
       $optgrp.append("<option value='128.html'><b>128</b> - ﻿दशाष्ट-पञ्च-द्वादश-विकल्पा कल्पोपपन्न पर्यन्ता: ॥३॥</option>");
       $optgrp.append("<option value='129.html'><b>129</b> - ﻿इंद्र-सामानिक-त्रायस्त्रिंश-पारिषदात्मरक्ष-लोकपालानीक-प्रकीर्णकाभियोग्यकिल्विषिकाश्चैकश: ॥४॥</option>");
       $optgrp.append("<option value='130.html'><b>130</b> - ﻿त्रायस्त्रिंश-लोकपाल-वर्ज्या व्यंतरज्योतिष्का: ॥५॥</option>");
       $optgrp.append("<option value='131.html'><b>131</b> - ﻿पूर्वयोर्द्वीन्द्राः ॥६॥</option>");
       $optgrp.append("<option value='132.html'><b>132</b> - ﻿काय-प्रवीचारा आ ऐशानात् ॥७॥</option>");
       $optgrp.append("<option value='133.html'><b>133</b> - ﻿शेषा: स्पर्श-रूप-शब्द-मन: प्रवीचारा: ॥८॥</option>");
       $optgrp.append("<option value='134.html'><b>134</b> - ﻿परेऽप्रवीचारा: ॥९॥</option>");
       $optgrp.append("<option value='135.html'><b>135</b> - ﻿भवन-वासिनोऽसुरनाग-विद्युत्सुपर्णाग्निवातस्तनितोदधि-द्वीप-दिक्कुमारा: ॥१०॥</option>");
       $optgrp.append("<option value='136.html'><b>136</b> - ﻿व्यन्तरा: किन्नर-किम्पुरुष-महोरग-गन्धर्व-यक्ष-राक्षस-भूत-पिशाचा: ॥११॥</option>");
       $optgrp.append("<option value='137.html'><b>137</b> - ﻿ज्योतिष्का: सूर्याचन्द्रमसौ ग्रह-नक्षत्र-प्रकीर्णक-तारकाश्च ॥१२॥</option>");
       $optgrp.append("<option value='138.html'><b>138</b> - ﻿मेरु-प्रदक्षिणा नित्यगतयो नृलोके ॥१३॥</option>");
       $optgrp.append("<option value='139.html'><b>139</b> - ﻿तत्कृत: काल विभाग: ॥१४॥</option>");
       $optgrp.append("<option value='140.html'><b>140</b> - ﻿बहिरवस्थिता: ॥१५॥</option>");
       $optgrp.append("<option value='141.html'><b>141</b> - ﻿वैमानिका: ॥१६॥</option>");
       $optgrp.append("<option value='142.html'><b>142</b> - ﻿कल्पोपपन्ना: कल्पातीताश्च ॥१७॥</option>");
       $optgrp.append("<option value='143.html'><b>143</b> - ﻿उपर्युपरि ॥१८॥</option>");
       $optgrp.append("<option value='144.html'><b>144</b> - ﻿सौधर्मेशान-सानत्कुमार-माहेन्द्र-ब्रह्म-ब्रह्मोत्तर-लान्तव-कापिष्ट-शुक्र-महाशुक्र-शतार-सहस्रारेष्वानतप्राणत-योरारणाच्युतयोर्नवसु ग्रैवेयकेषु विजय-वैजयन्त जयन्तापराजितेषु सर्वार्थ-सिद्धौ च ॥१९॥</option>");
       $optgrp.append("<option value='145.html'><b>145</b> - ﻿स्थिति-प्रभाव-सुख-द्युति-लेश्याविशुद्धीन्द्रियावधि-विषय-तोऽधिका: ॥२०॥</option>");
       $optgrp.append("<option value='146.html'><b>146</b> - ﻿गति-शरीर-परिग्रहाभिमानतो हीना: ॥२१॥</option>");
       $optgrp.append("<option value='147.html'><b>147</b> - ﻿पीत-पद्म-शुक्ल-लेश्या द्वि-त्रि-शेषेषु ॥२२॥</option>");
       $optgrp.append("<option value='148.html'><b>148</b> - ﻿प्राग्ग्रैवेयकेभ्य: कल्पा: ॥२३॥</option>");
       $optgrp.append("<option value='149.html'><b>149</b> - ﻿ब्रह्म-लोकालया लौकान्तिका: ॥२४॥</option>");
       $optgrp.append("<option value='150.html'><b>150</b> - ﻿सारस्वतादित्य वह्न्यरुण-गर्दतोय-तुषिताव्या-बाधारिष्टाश्च ॥२५॥</option>");
       $optgrp.append("<option value='151.html'><b>151</b> - ﻿विजयादिषु द्वि-चरमा: ॥२६॥</option>");
       $optgrp.append("<option value='152.html'><b>152</b> - ﻿औपपादिक-मनुष्येभ्य: शेषास्तिर्यग्योनय: ॥२७॥</option>");
       $optgrp.append("<option value='153.html'><b>153</b> - ﻿स्थितिरसुर-नाग-सुपर्ण-द्वीपशेषाणां-सागरोपम-त्रिपल्योपमार्द्धहीन-मिता: ॥२८॥</option>");
       $optgrp.append("<option value='154.html'><b>154</b> - ﻿सौधर्मेशानयो: सागरोपमेऽधिके ॥२९॥</option>");
       $optgrp.append("<option value='155.html'><b>155</b> - ﻿सानत्कुमार-माहेन्द्रयो: सप्त ॥३०॥</option>");
       $optgrp.append("<option value='156.html'><b>156</b> - ﻿त्रिसप्त-नवैकादश-त्रयोदश-पञ्चदशभिरधिकानि तु ॥३१॥</option>");
       $optgrp.append("<option value='157.html'><b>157</b> - ﻿आरणाच्युता-दूर्ध्वमेकैकेन नवसु ग्रैवेयकेषु विजयादिषु सर्वार्थसिद्धौ च ॥३२॥</option>");
       $optgrp.append("<option value='158.html'><b>158</b> - ﻿अपरा पल्योपममधिकम् ॥३३॥</option>");
       $optgrp.append("<option value='159.html'><b>159</b> - ﻿परत: परत: पूर्वा पूर्वाऽनन्तरा ॥३४॥</option>");
       $optgrp.append("<option value='160.html'><b>160</b> - ﻿नारकाणां च द्वितीयादिषु ॥३५॥</option>");
       $optgrp.append("<option value='161.html'><b>161</b> - ﻿दश-वर्षसहस्राणि प्रथमायाम् ॥३६॥</option>");
       $optgrp.append("<option value='162.html'><b>162</b> - ﻿भवनेषु च ॥३७॥</option>");
       $optgrp.append("<option value='163.html'><b>163</b> - ﻿व्यन्तराणां च ॥३८॥</option>");
       $optgrp.append("<option value='164.html'><b>164</b> - ﻿परा पल्योपममधिकम् ॥३९॥</option>");
       $optgrp.append("<option value='165.html'><b>165</b> - ﻿ज्योतिष्काणां च ॥४०॥</option>");
       $optgrp.append("<option value='166.html'><b>166</b> - ﻿तदष्टभागोऽपरा ॥४१॥</option>");
       $optgrp.append("<option value='167.html'><b>167</b> - ﻿लौकान्तिकानामष्टौ सागरोपमाणि सर्वेषाम् ॥४२॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿अधिकार-५ (अजीवाधिकार)">')
       $optgrp.append("<option value='168.html'><b>168</b> - ﻿अजीव-काया-धर्माधर्माकाश-पुद्गला: ॥१॥</option>");
       $optgrp.append("<option value='169.html'><b>169</b> - ﻿द्रव्याणि ॥२॥</option>");
       $optgrp.append("<option value='170.html'><b>170</b> - ﻿जीवाश्च ॥३॥</option>");
       $optgrp.append("<option value='171.html'><b>171</b> - ﻿नित्यावस्थितान्यरूपाणि ॥४॥</option>");
       $optgrp.append("<option value='172.html'><b>172</b> - ﻿रूपिण: पुद्ग्रला: ॥५॥</option>");
       $optgrp.append("<option value='173.html'><b>173</b> - ﻿आ आकाशादेक-द्रव्याणि ॥६॥</option>");
       $optgrp.append("<option value='174.html'><b>174</b> - ﻿निष्क्रियाणि च ॥७॥</option>");
       $optgrp.append("<option value='175.html'><b>175</b> - ﻿असंख्येया: प्रदेशा धर्माधर्मैकजीवानाम् ॥८॥</option>");
       $optgrp.append("<option value='176.html'><b>176</b> - ﻿आकाशस्यानन्ता: ॥९॥</option>");
       $optgrp.append("<option value='177.html'><b>177</b> - ﻿संख्येयासंख्येयाश्च पुद्गलानाम् ॥१०॥</option>");
       $optgrp.append("<option value='178.html'><b>178</b> - ﻿नाणो: ॥११॥</option>");
       $optgrp.append("<option value='179.html'><b>179</b> - ﻿लोकाकाशेऽवगाह: ॥१२॥</option>");
       $optgrp.append("<option value='180.html'><b>180</b> - ﻿धर्माधर्मयो: कृत्स्ने ॥१३॥</option>");
       $optgrp.append("<option value='181.html'><b>181</b> - ﻿एकप्रदेशादिषु भाज्य: पुद्गलानाम् ॥१४॥</option>");
       $optgrp.append("<option value='182.html'><b>182</b> - ﻿असंख्येय-भागादिषु जीवानाम् ॥१५॥</option>");
       $optgrp.append("<option value='183.html'><b>183</b> - ﻿प्रदेश-संहार-विसर्पाभ्यां प्रदीपवत् ॥१६॥</option>");
       $optgrp.append("<option value='184.html'><b>184</b> - ﻿गति-स्थित्युपग्रहौ धर्माधर्मयोरुपकार: ॥१७॥</option>");
       $optgrp.append("<option value='185.html'><b>185</b> - ﻿आकाशस्या-वगाह: ॥१८॥</option>");
       $optgrp.append("<option value='186.html'><b>186</b> - ﻿शरीरवाङ्मन:-प्राणापाना पुद्गलानाम् ॥१९॥</option>");
       $optgrp.append("<option value='187.html'><b>187</b> - ﻿सुख-दु:ख-जीवितमरणोपग्रहाश्च ॥२०॥</option>");
       $optgrp.append("<option value='188.html'><b>188</b> - ﻿परस्परोपग्रहो जीवानाम् ॥२१॥</option>");
       $optgrp.append("<option value='189.html'><b>189</b> - ﻿वर्तना-परिणाम-क्रिया-परत्वापरत्वे च कालस्य ॥२२॥</option>");
       $optgrp.append("<option value='190.html'><b>190</b> - ﻿स्पर्श-रस-गंध-वर्णवन्त: पुद्गला: ॥२३॥</option>");
       $optgrp.append("<option value='191.html'><b>191</b> - ﻿शब्द-बंध-सौक्ष्म्य-स्थौल्य-संस्थान-भेद-तमश्छायातपोद्योतवन्तश्च ॥२४॥</option>");
       $optgrp.append("<option value='192.html'><b>192</b> - ﻿अणव: स्कन्धाश्च ॥२५॥</option>");
       $optgrp.append("<option value='193.html'><b>193</b> - ﻿भेद-संघातेभ्य उत्पद्यन्ते ॥२६॥</option>");
       $optgrp.append("<option value='194.html'><b>194</b> - ﻿भेदादणु: ॥२७॥</option>");
       $optgrp.append("<option value='195.html'><b>195</b> - ﻿भेद-संघाताभ्यां चाक्षुष: ॥२८॥</option>");
       $optgrp.append("<option value='196.html'><b>196</b> - ﻿सद् द्रव्य-लक्षणम् ॥२९॥</option>");
       $optgrp.append("<option value='197.html'><b>197</b> - ﻿उत्पाद-व्यय-ध्रौव्य-युक्तं सत् ॥३०॥</option>");
       $optgrp.append("<option value='198.html'><b>198</b> - ﻿तद्भावाव्ययं नित्यम् ॥३१॥</option>");
       $optgrp.append("<option value='199.html'><b>199</b> - ﻿अर्पितानर्पितसिद्धे: ॥३२॥</option>");
       $optgrp.append("<option value='200.html'><b>200</b> - ﻿स्निग्ध-रूक्षत्वाद् बन्धः ॥३३॥</option>");
       $optgrp.append("<option value='201.html'><b>201</b> - ﻿न जघन्य-गुणानाम् ॥३४॥</option>");
       $optgrp.append("<option value='202.html'><b>202</b> - ﻿गुणसाम्ये सदृशानाम् ॥३५॥</option>");
       $optgrp.append("<option value='203.html'><b>203</b> - ﻿द्वयधिकादि गुणानां तु ॥३६॥</option>");
       $optgrp.append("<option value='205.html'><b>205</b> - ﻿गुण-पर्ययवद् द्रव्यम् ॥३८॥</option>");
       $optgrp.append("<option value='207.html'><b>207</b> - ﻿सोऽनन्तसमय: ॥४०॥</option>");
       $optgrp.append("<option value='208.html'><b>208</b> - ﻿द्रव्याश्रया निर्गुणा गुणा: ॥४१॥</option>");
       $optgrp.append("<option value='209.html'><b>209</b> - ﻿तद्भाव: परिणाम: ॥४२॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿अधिकार-६ (आस्रवाधिकार)">')
       $optgrp.append("<option value='210.html'><b>210</b> - ﻿काय-वाङ्मन: कर्म-योग: ॥१॥</option>");
       $optgrp.append("<option value='211.html'><b>211</b> - ﻿स आस्रव: ॥२॥</option>");
       $optgrp.append("<option value='212.html'><b>212</b> - ﻿शुभ: पुण्यस्याशुभ: पापस्य ॥३॥</option>");
       $optgrp.append("<option value='213.html'><b>213</b> - ﻿सकषायाकषाययो: साम्परायिकेर्यापथयो: ॥४॥</option>");
       $optgrp.append("<option value='214.html'><b>214</b> - ﻿इन्द्रिय-कषायाव्रत-क्रिया: पंच-चतु:-पंच-पंचविंशति-संख्या: पूर्वस्य भेदा: ॥५॥</option>");
       $optgrp.append("<option value='215.html'><b>215</b> - ﻿तीव्र-मंद-ज्ञाताज्ञात-भावाधिकरण-वीर्य-विशेषेभ्यस्तद्विशेष: ॥६॥</option>");
       $optgrp.append("<option value='216.html'><b>216</b> - ﻿अधिकरणं जीवाजीवा: ॥७॥</option>");
       $optgrp.append("<option value='217.html'><b>217</b> - ﻿आद्यं संरम्भ-समारम्भारम्भयोग कृत-कारितानुमत-कषाय-विशेषैस्त्रिस्त्रिस्त्रि-श्चतुश्चैकश: ॥८॥</option>");
       $optgrp.append("<option value='219.html'><b>219</b> - ﻿तत्प्रदोष-निह्नव-मात्सर्यान्तरायासादनोपघाता ज्ञान-दर्शनावरणयो: ॥१०॥</option>");
       $optgrp.append("<option value='220.html'><b>220</b> - ﻿दु:ख-शोक-तापाक्रन्दन-वध-परिदेवनान्यात्म-परोभय-स्थानान्यसद्वेद्यस्य ॥११॥</option>");
       $optgrp.append("<option value='221.html'><b>221</b> - ﻿भूत-व्रत्यनुकम्पादान-सराग-संयमादि-योग: क्षांति: शौचमिति सद्वेद्यस्य ॥१२॥</option>");
       $optgrp.append("<option value='222.html'><b>222</b> - ﻿केवलि-श्रुत-संघ-धर्मदेवावर्णवादो दर्शनमोहस्य ॥१३॥</option>");
       $optgrp.append("<option value='223.html'><b>223</b> - ﻿कषायोदयात्तीव्र-परिणामश्चारित्र-मोहस्य ॥१४॥</option>");
       $optgrp.append("<option value='224.html'><b>224</b> - ﻿बह्वारम्भ-परिग्रहत्वं नारकस्यायुष: ॥१५॥</option>");
       $optgrp.append("<option value='225.html'><b>225</b> - ﻿माया तैर्यग्योनस्य ॥१६॥</option>");
       $optgrp.append("<option value='226.html'><b>226</b> - ﻿अल्पारम्भ परिग्रहत्वं मानुषस्य ॥१७॥</option>");
       $optgrp.append("<option value='227.html'><b>227</b> - ﻿स्वभाव-मार्दवं च ॥१८॥</option>");
       $optgrp.append("<option value='228.html'><b>228</b> - ﻿नि:शील-व्रतत्वं च सर्वेषाम् ॥१९॥</option>");
       $optgrp.append("<option value='229.html'><b>229</b> - ﻿सरागसंयम-संयमा-संयमाकामनिर्जराबालतपांसि दैवस्य ॥२०॥</option>");
       $optgrp.append("<option value='230.html'><b>230</b> - ﻿सम्यक्त्वं च ॥२१॥</option>");
       $optgrp.append("<option value='231.html'><b>231</b> - ﻿योगवक्रता विसंवादनं चाशुभस्य नाम्न: ॥२२॥</option>");
       $optgrp.append("<option value='232.html'><b>232</b> - ﻿तद्विपरीतं शुभस्य ॥२३॥</option>");
       $optgrp.append("<option value='233.html'><b>233</b> - ﻿दर्शनविशुद्धिर्विनयसम्पन्नता-शील-व्रतेष्वनतीचारोऽभीक्ष्ण-ज्ञानोपयोगसंवेगौ शक्तितस्त्याग-तपसी साधुसमाधिर्वैयावृत्य-करणमर्हदाचार्य-बहुश्रुत-प्रवचन-भक्तिरावश्यकापरिहाणिर्मार्ग-प्रभावना-प्रवचनवत्सलत्वमिति तीर्थकरत्वस्य ॥२४॥</option>");
       $optgrp.append("<option value='234.html'><b>234</b> - ﻿परात्म-निन्दा-प्रशंसे सदसद् गुणोच्छादनोद्भावने च नीचैर्गोत्रस्य ॥२५॥</option>");
       $optgrp.append("<option value='235.html'><b>235</b> - ﻿तद्विपर्ययो नीचैर्वृत्त्यनुत्सेकौ चोत्तरस्य ॥२६॥</option>");
       $optgrp.append("<option value='236.html'><b>236</b> - ﻿विघ्नकरण-मन्तरायस्य ॥२७॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿अधिकार-७ (आस्रवाधिकार)">')
       $optgrp.append("<option value='237.html'><b>237</b> - ﻿हिंसाऽनृत-स्तेयाब्रह्म-परिग्रहेभ्यो विरतिर्व्रतम् ॥१॥</option>");
       $optgrp.append("<option value='238.html'><b>238</b> - ﻿देश सर्वतोsणु-महती ॥२॥</option>");
       $optgrp.append("<option value='239.html'><b>239</b> - ﻿तत्स्थैर्यार्थं भावना: पञ्च-पञ्च ॥३॥</option>");
       $optgrp.append("<option value='240.html'><b>240</b> - ﻿वाङ्मनोगुप्तीर्यादाननिक्षेपण-समित्यालोकित-पान-भोजनानि पञ्च ॥४॥</option>");
       $optgrp.append("<option value='241.html'><b>241</b> - ﻿क्रोध-लोभ-भीरुत्व-हास्य-प्रत्याख्यानान्यनुवीचि-भाषणं च पञ्च ॥५॥</option>");
       $optgrp.append("<option value='242.html'><b>242</b> - ﻿शून्यागार-विमोचितावास-परोपरोधाकरण-भैक्ष्यशुद्धि-सधर्मावि-संवादा: पञ्च ॥६॥</option>");
       $optgrp.append("<option value='243.html'><b>243</b> - ﻿स्त्रीरागकथा श्रवण-तन्मनोहरांग निरीक्षण पूर्व-रतानुस्मरण-वृष्येष्टरस-स्वशरीरसंस्कारत्यागा: पञ्च ॥७॥</option>");
       $optgrp.append("<option value='244.html'><b>244</b> - ﻿मनोज्ञामनोज्ञेन्द्रिय-विषय-राग-द्वेष वर्जनानि पञ्च ॥८॥</option>");
       $optgrp.append("<option value='245.html'><b>245</b> - ﻿हिंसादिष्विहामुत्रापायावद्यदर्शनम् ॥९॥</option>");
       $optgrp.append("<option value='246.html'><b>246</b> - ﻿दु:खमेव वा ॥१०॥</option>");
       $optgrp.append("<option value='247.html'><b>247</b> - ﻿मैत्री-प्रमोद-कारुण्य-माध्यस्थानि च सत्त्व-गुणाधिक-क्लिश्यमानाविनेयेषु ॥११॥</option>");
       $optgrp.append("<option value='248.html'><b>248</b> - ﻿जगत्काय-स्वभावौ वा संवेगवैराग्यार्थम् ॥१२॥</option>");
       $optgrp.append("<option value='249.html'><b>249</b> - ﻿प्रमत्तयोगात्प्राण-व्यपरोपणं हिंसा ॥१३॥</option>");
       $optgrp.append("<option value='250.html'><b>250</b> - ﻿असदभिधानमनृतम् ॥१४॥</option>");
       $optgrp.append("<option value='251.html'><b>251</b> - ﻿अदत्तादानं स्तेयम् ॥१५॥</option>");
       $optgrp.append("<option value='252.html'><b>252</b> - ﻿मैथुनम-ब्रह्म ॥१६॥</option>");
       $optgrp.append("<option value='253.html'><b>253</b> - ﻿मूर्च्छा परिग्रह: ॥१७॥</option>");
       $optgrp.append("<option value='254.html'><b>254</b> - ﻿नि:शल्यो व्रती ॥१८॥</option>");
       $optgrp.append("<option value='255.html'><b>255</b> - ﻿अगार्यनगारश्च ॥१९॥</option>");
       $optgrp.append("<option value='256.html'><b>256</b> - ﻿अणुव्रतोऽगारी ॥२०॥</option>");
       $optgrp.append("<option value='257.html'><b>257</b> - ﻿दिग्देशानर्थदण्ड-विरति-सामायिक-प्रोषधोपवासोपभोग-परिभोग-परिमाणातिथि-संविभागव्रतसम्पन्नश्च ॥२१॥</option>");
       $optgrp.append("<option value='258.html'><b>258</b> - ﻿मारणान्तिकीं सल्लेखनां जोषिता ॥२२॥</option>");
       $optgrp.append("<option value='259.html'><b>259</b> - ﻿शंका-कांक्षाविचिकित्सान्यदृष्टि-प्रशंसा-संस्तवा: सम्यग्दृष्टेरती-चारा: ॥२३॥</option>");
       $optgrp.append("<option value='260.html'><b>260</b> - ﻿व्रत-शीलेषु पञ्च पञ्च यथाक्रमम् ॥२४॥</option>");
       $optgrp.append("<option value='261.html'><b>261</b> - ﻿बंधवध-च्छेदाति-भारारोपणान्नपान-निरोधा: ॥२५॥</option>");
       $optgrp.append("<option value='262.html'><b>262</b> - ﻿मिथ्योपदेश-रहोभ्याख्यान-कूटलेखक्रिया-न्यासापहार-साकारमन्त्रभेदा: ॥२६॥</option>");
       $optgrp.append("<option value='263.html'><b>263</b> - ﻿स्तेनप्रयोग-तदाहृतादानविरुद्धराज्यातिक्रम-हीनाधिकमानोन्मान-प्रतिरूपक-व्यवहारा: ॥२७॥</option>");
       $optgrp.append("<option value='264.html'><b>264</b> - ﻿परविवाह करणेत्वरिका-परिगृहीतापरिगृहीता-गमनानङ्गक्रीडा-कामतीव्राभिनिवेशा: ॥२८॥</option>");
       $optgrp.append("<option value='265.html'><b>265</b> - ﻿क्षेत्रवास्तु-हिरण्यसुवर्ण-धन-धान्य-दासीदास-कुप्य-प्रमाणातिक्रमा: ॥२९॥</option>");
       $optgrp.append("<option value='266.html'><b>266</b> - ﻿ऊर्ध्वाधस्तिर्यग्व्यतिक्रमक्षेत्रवृद्धि-स्मृत्यंतराधानानि ॥३०॥</option>");
       $optgrp.append("<option value='267.html'><b>267</b> - ﻿आनयन-प्रेष्यप्रयोग-शब्दरूपानुपात-पुद्गलक्षेपा: ॥३१॥</option>");
       $optgrp.append("<option value='268.html'><b>268</b> - ﻿कन्दर्प-कौत्कुच्य-मौखर्यासमीक्ष्याधि-करणोपभोगपरिभोगानर्थक्यानि ॥३२॥</option>");
       $optgrp.append("<option value='269.html'><b>269</b> - ﻿योग दु:प्रणिधानानादर-स्मृत्यनु-पस्थानानि ॥३३॥</option>");
       $optgrp.append("<option value='270.html'><b>270</b> - ﻿अप्रत्यवेक्षिताप्रमार्जितोत्सर्गादानसंस्तरोपक्रमणा-नादरस्मृत्यनुप-स्थानानि ॥३४॥</option>");
       $optgrp.append("<option value='271.html'><b>271</b> - ﻿सचित्त-संबंधसम्मिश्रा-भिषवदु:पक्वाहारा: ॥३५॥</option>");
       $optgrp.append("<option value='272.html'><b>272</b> - ﻿सचित्त-निक्षेपापिधानपरव्यपदेश-मात्सर्यकालातिक्रमा: ॥३६॥</option>");
       $optgrp.append("<option value='273.html'><b>273</b> - ﻿जीवित-मरणाशंसा-मित्रानुराग-सुखानुबंध-निदानानि ॥३७॥</option>");
       $optgrp.append("<option value='274.html'><b>274</b> - ﻿अनुग्रहार्थं स्वस्यातिसर्गो दानम् ॥३८॥</option>");
       $optgrp.append("<option value='275.html'><b>275</b> - ﻿विधि-द्रव्य-दातृ-पात्र-विशेषात्तद्विशेष: ॥३९॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿अधिकार-८ (बंधाधिकार)">')
       $optgrp.append("<option value='276.html'><b>276</b> - ﻿मिथ्यादर्शनाविरति-प्रमाद-कषाय-योगा बन्धहेतव: ॥१॥</option>");
       $optgrp.append("<option value='277.html'><b>277</b> - ﻿सकषायत्वाज्जीव: कर्मणो योग्यान् पुद्गलानादत्ते स बंध: ॥२॥</option>");
       $optgrp.append("<option value='278.html'><b>278</b> - ﻿प्रकृति स्थित्यनुभव-प्रदेशास्तद्विधय: ॥३॥</option>");
       $optgrp.append("<option value='279.html'><b>279</b> - ﻿आद्यो ज्ञान-दर्शनावरणवेदनीय-मोहनीयायुर्नाम-गोत्रान्तराया: ॥४॥</option>");
       $optgrp.append("<option value='280.html'><b>280</b> - ﻿पञ्च-नव-द्वयष्टाविंशति-चतुर्-द्विचत्वारिंशद्-द्वि-पञ्च-भेदा-यथाक्रमम् ॥५॥</option>");
       $optgrp.append("<option value='281.html'><b>281</b> - ﻿मतिश्रुतावधि-मन:पर्यय केवलानाम् ॥६॥</option>");
       $optgrp.append("<option value='282.html'><b>282</b> - ﻿चक्षुरचक्षुरवधिकेवलानां निद्रा-निद्रानिद्रा-प्रचला-प्रचलाप्रचला-स्त्यानगृद्धयश्च ॥७॥</option>");
       $optgrp.append("<option value='283.html'><b>283</b> - ﻿सदसद्वेद्ये ॥८॥</option>");
       $optgrp.append("<option value='284.html'><b>284</b> - ﻿दर्शनचारित्र-मोहनीयाकषाय-कषायवेदनीयाख्यास्त्रिद्वि-नव-षोडशभेदा: सम्यक्त्व-मिथ्यात्व-तदुभयान्यकषाय-कषायौ हास्यरत्यरति-शोक-भय-जुगुप्सा-स्त्री-पुन्नपुंसक-वेदा अनन्तानुबंध्य-प्रत्याख्यान-प्रत्याख्यान-संज्वलन-विकल्पाश्चैकश: क्रोध-मान-माया-लोभा: ॥९॥</option>");
       $optgrp.append("<option value='285.html'><b>285</b> - ﻿नारकतैर्यग्योन-मानुष-दैवानि ॥१०॥</option>");
       $optgrp.append("<option value='286.html'><b>286</b> - ﻿गति-जाति-शरीराङ्गोपाङ्गनिर्माण-बंधन-संघात-संस्थान-संहनन-स्पर्श-रस-गंध-वर्णानुपूर्व्यागुरुलघूपघात-परघातातपोद्योतोच्छ्वास-विहायोगतय: प्रत्येक-शरीर-त्रस-सुभग-सुस्वर-शुभ-सूक्ष्म-पर्याप्ति-स्थिरादेय यश: कीर्ति-सेतराणि तीर्थकरत्वं च ॥११॥</option>");
       $optgrp.append("<option value='287.html'><b>287</b> - ﻿उच्चैर्नीचैश्च ॥१२॥</option>");
       $optgrp.append("<option value='288.html'><b>288</b> - ﻿दान-लाभ-भोगोपभोग-वीर्याणाम् ॥१३॥</option>");
       $optgrp.append("<option value='289.html'><b>289</b> - ﻿आदितस्तिसृणा-मंतरायस्य च त्रिंशत्सागरोपमकोटीकोट्य: परा स्थिति: ॥१४॥</option>");
       $optgrp.append("<option value='290.html'><b>290</b> - ﻿सप्तति-र्मोहनीयस्य ॥१५॥</option>");
       $optgrp.append("<option value='291.html'><b>291</b> - ﻿विंशतिर्नाम-गोत्रयो: ॥११६॥</option>");
       $optgrp.append("<option value='292.html'><b>292</b> - ﻿त्रयस्त्रिंशत्सागरोपमाण्यायुष: ॥१७॥</option>");
       $optgrp.append("<option value='293.html'><b>293</b> - ﻿अपरा द्वादश मुहूर्ता वेदनीयस्य ॥१८॥</option>");
       $optgrp.append("<option value='294.html'><b>294</b> - ﻿नाम-गोत्रयोरष्टौ ॥१९॥</option>");
       $optgrp.append("<option value='295.html'><b>295</b> - ﻿शेषाणामन्तर्मुहूर्ता ॥२०॥</option>");
       $optgrp.append("<option value='296.html'><b>296</b> - ﻿विपाकोऽनुभव: ॥२१॥</option>");
       $optgrp.append("<option value='297.html'><b>297</b> - ﻿स यथानाम् ॥२२॥</option>");
       $optgrp.append("<option value='298.html'><b>298</b> - ﻿ततश्च निर्जरा ॥२३॥</option>");
       $optgrp.append("<option value='299.html'><b>299</b> - ﻿नाम-प्रत्यया: सर्वतो योग-विशेषात्-सूक्ष्मैकक्षेत्रावगाह-स्थिता: सर्वात्म-प्रदेशेष्वनन्तानन्त-प्रदेशा: ॥२४॥</option>");
       $optgrp.append("<option value='300.html'><b>300</b> - ﻿सद्वेद्यशुभायुर्नाम-गोत्राणि पुण्यम् ॥२५॥</option>");
       $optgrp.append("<option value='301.html'><b>301</b> - ﻿अतोऽन्यत्पापम् ॥२६॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿अधिकार-९ (संवर-निर्जराधिकार)">')
       $optgrp.append("<option value='302.html'><b>302</b> - ﻿आस्रव-निरोध: संवर: ॥१॥</option>");
       $optgrp.append("<option value='303.html'><b>303</b> - ﻿स गुप्ति-समिति-धर्मानुप्रेक्षा-परीषहजय-चारित्रै: ॥२॥</option>");
       $optgrp.append("<option value='304.html'><b>304</b> - ﻿तपसा निर्जरा च ॥३॥</option>");
       $optgrp.append("<option value='305.html'><b>305</b> - ﻿सम्यग्योगनिग्रहो गुप्ति: ॥४॥</option>");
       $optgrp.append("<option value='306.html'><b>306</b> - ﻿ईर्याभाषैषणा-दाननिक्षेपोत्सर्गा: समितय: ॥५॥</option>");
       $optgrp.append("<option value='307.html'><b>307</b> - ﻿उत्तमक्षमा-मार्दवार्जव-सत्य-शौच-संयमतपस्त्यागा-किञ्चन्य-ब्रह्मचर्याणि धर्म: ॥६॥</option>");
       $optgrp.append("<option value='308.html'><b>308</b> - ﻿अनित्याशरण-संसारैकत्वान्य-त्वाशुच्यास्रवसंवर-निर्जरा-लोक-बोधिदुर्लभ-धर्म-स्वाख्यातत्त्वानु-चिन्तन-मनुप्रेक्षा: ॥७॥</option>");
       $optgrp.append("<option value='309.html'><b>309</b> - ﻿मार्गाच्यवन-निर्जरार्थं परिषोढव्या: परीषहा: ॥८॥</option>");
       $optgrp.append("<option value='310.html'><b>310</b> - ﻿क्षुत्पिपासा-शीतोष्णदंश-मशक-नाग्न्यारति-स्त्री-चर्या-निषद्या-शय्याक्रोशवधयाचनालाभ-रोग-तृणस्पर्श-मल-सत्कारपुरस्कार-प्रज्ञाज्ञानादर्शनानि ॥९॥</option>");
       $optgrp.append("<option value='311.html'><b>311</b> - ﻿सूक्ष्मसाम्पराय-छद्मस्थवीत-रागयोश्चतुर्दश ॥१०॥</option>");
       $optgrp.append("<option value='312.html'><b>312</b> - ﻿एकादश जिने ॥११॥</option>");
       $optgrp.append("<option value='313.html'><b>313</b> - ﻿बादर-साम्पराये सर्वे ॥१२॥</option>");
       $optgrp.append("<option value='314.html'><b>314</b> - ﻿ज्ञानावरणे प्रज्ञाज्ञाने ॥१३॥</option>");
       $optgrp.append("<option value='315.html'><b>315</b> - ﻿दर्शन-मोहान्तराययोरदर्शनालाभौ ॥१४॥</option>");
       $optgrp.append("<option value='316.html'><b>316</b> - ﻿चारित्रमोहे नाग्न्यारति-स्त्री-निषद्या-क्रोश-याचना-सत्कारपुरस्कारा: ॥१५॥</option>");
       $optgrp.append("<option value='317.html'><b>317</b> - ﻿वेदनीये शेषा: ॥१६॥</option>");
       $optgrp.append("<option value='318.html'><b>318</b> - ﻿एकादयो भाज्या युगपदेक-स्मिन्नैकोनविंशते: ॥१७॥</option>");
       $optgrp.append("<option value='319.html'><b>319</b> - ﻿सामायिकच्छेदोपस्थापना-परिहारविशुद्धि-सूक्ष्मसाम्पराय-यथाख्यात-मितिचारित्रम् ॥१८॥</option>");
       $optgrp.append("<option value='320.html'><b>320</b> - ﻿अनशनावमौदर्य-वृत्तिपरिसंख्यान-रस-परित्याग-विविक्तशय्यासन-कायक्लेशा बाह्यं तप: ॥१९॥</option>");
       $optgrp.append("<option value='321.html'><b>321</b> - ﻿प्रायश्चित्त-विनय-वैयावृत्त्य-स्वाध्याय-व्युत्सर्ग-ध्यानान्युत्तरम् ॥२०॥</option>");
       $optgrp.append("<option value='322.html'><b>322</b> - ﻿नवचतुर्दश-पञ्च द्विभेदा यथाक्रमं प्राग्ध्यानात् ॥२१॥</option>");
       $optgrp.append("<option value='323.html'><b>323</b> - ﻿आलोचना-प्रतिक्रमण-तदुभय-विवेक-व्युत्सर्ग-तपश्छेदपरिहारो-पस्थापना: ॥२२॥</option>");
       $optgrp.append("<option value='324.html'><b>324</b> - ﻿ज्ञान-दर्शन-चारित्रोपचारा: ॥२३॥</option>");
       $optgrp.append("<option value='325.html'><b>325</b> - ﻿आचार्योपाध्याय-तपस्वि-शैक्ष्य-ग्लान-गण-कुल-संघ-साधु-मनोज्ञानाम् ॥२४॥</option>");
       $optgrp.append("<option value='326.html'><b>326</b> - ﻿वाचना-पृच्छनानुप्रेक्षाम्नाय-धर्मोपदेशा: ॥२५॥</option>");
       $optgrp.append("<option value='327.html'><b>327</b> - ﻿बाह्याभ्यन्तरोपध्यो: ॥२६॥</option>");
       $optgrp.append("<option value='328.html'><b>328</b> - ﻿उत्तम-संहननस्यैकाग्र-चिन्ता-निरोधो ध्यानमान्त-र्मुहूर्तात्॥२७॥</option>");
       $optgrp.append("<option value='329.html'><b>329</b> - ﻿आर्त्त-रौद्र-धर्म्य-शुक्लानि ॥२८॥</option>");
       $optgrp.append("<option value='330.html'><b>330</b> - ﻿परे मोक्षहेतू ॥२९॥</option>");
       $optgrp.append("<option value='331.html'><b>331</b> - ﻿आर्तममनोज्ञस्य संप्रयोगे तद्विप्रयोगाय स्मृति-समन्वाहार: ॥३०॥</option>");
       $optgrp.append("<option value='332.html'><b>332</b> - ﻿विपरीतं मनोज्ञस्य ॥३१॥</option>");
       $optgrp.append("<option value='333.html'><b>333</b> - ﻿वेदनायाश्च ॥३२॥</option>");
       $optgrp.append("<option value='334.html'><b>334</b> - ﻿निदानं च ॥३३॥</option>");
       $optgrp.append("<option value='335.html'><b>335</b> - ﻿तदविरतदेशविरतप्रमत्तसंयतानां ॥३४॥</option>");
       $optgrp.append("<option value='336.html'><b>336</b> - ﻿हिंसानृत-स्तेय-विषयसंरक्षणेभ्यो रौद्रमविरत-देशविरतयो: ॥३५॥</option>");
       $optgrp.append("<option value='337.html'><b>337</b> - ﻿आज्ञापाय-विपाक-संस्थान-विचयाय धर्म्यम् ॥३६॥</option>");
       $optgrp.append("<option value='338.html'><b>338</b> - ﻿शुक्ले चाद्ये पूर्व-विद:॥३७॥</option>");
       $optgrp.append("<option value='339.html'><b>339</b> - ﻿परे केवलिन: ॥३८॥</option>");
       $optgrp.append("<option value='340.html'><b>340</b> - ﻿पृथक्त्वैकत्व-वितर्क-सूक्ष्मक्रिया-प्रतिपाति-व्युपरत-क्रिर्यानिवर्तीनि ॥३९॥</option>");
       $optgrp.append("<option value='341.html'><b>341</b> - ﻿त्र्येकयोग-काययोगायोगानाम् ॥४०॥</option>");
       $optgrp.append("<option value='342.html'><b>342</b> - ﻿एकाश्रये सवितर्कवीचारे पूर्वे ॥४१॥</option>");
       $optgrp.append("<option value='343.html'><b>343</b> - ﻿अवीचारं द्वितीयम् ॥४२॥</option>");
       $optgrp.append("<option value='344.html'><b>344</b> - ﻿वितर्क: श्रुतम् ॥४३॥</option>");
       $optgrp.append("<option value='345.html'><b>345</b> - ﻿वीचारोऽर्थव्यंजन-योगसंक्रान्ति: ॥४४॥</option>");
       $optgrp.append("<option value='346.html'><b>346</b> - ﻿सम्यग्दृष्टि-श्रावक-विरता-नन्तवियोजक-दर्शनमोह-क्षपकोपशम-कोपशांत-मोहक्षपक-क्षीणमोह-जिना: क्रमशोऽसंख्येय-गुण-निर्जरा: ॥४५॥</option>");
       $optgrp.append("<option value='347.html'><b>347</b> - ﻿पुलाक-वकुश-कुशील-निर्ग्रन्थ-स्नातका निर्ग्रंथा: ॥४६॥</option>");
       $optgrp.append("<option value='348.html'><b>348</b> - ﻿संयम-श्रुत-प्रतिसेवना-तीर्थलिङ्ग-लेश्योपपाद-स्थान-विकल्पत: साध्या: ॥४७॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿अधिकार-१० (मोक्षाधिकार)">')
       $optgrp.append("<option value='349.html'><b>349</b> - ﻿मोहक्षयाज्ज्ञान-दर्शनावरणान्तराय-क्षयाच्च केवलम् ॥१॥</option>");
       $optgrp.append("<option value='350.html'><b>350</b> - ﻿बन्धहेत्वभाव-निर्जराभ्यां कृत्स्न-कर्म-विप्रमोक्षो मोक्ष: ॥२॥</option>");
       $optgrp.append("<option value='351.html'><b>351</b> - ﻿औपशमिकादि-भव्यत्वानां च ॥३॥</option>");
       $optgrp.append("<option value='352.html'><b>352</b> - ﻿अन्यत्र केवलसम्यक्त्व-ज्ञान-दर्शन-सिद्धत्वेभ्य: ॥४॥</option>");
       $optgrp.append("<option value='353.html'><b>353</b> - ﻿तदनन्तरमूर्ध्वं गच्छत्या-लोकान्तात् ॥५॥</option>");
       $optgrp.append("<option value='354.html'><b>354</b> - ﻿पूर्वप्रयोगादसङ्गत्वाद्-बन्धच्छेदात्तथागतिपरिणामाच्च ॥६॥</option>");
       $optgrp.append("<option value='355.html'><b>355</b> - ﻿आविद्धकुलालचक्रवद्-व्यपगतलेपालाबुवदेरण्डबीजवदग्निशिखावच्च ॥७॥</option>");
       $optgrp.append("<option value='356.html'><b>356</b> - ﻿धर्मास्तिकायाभावात् ॥८॥</option>");
       $optgrp.append("<option value='357.html'><b>357</b> - ﻿क्षेत्र-काल-गति-लिङ्ग-तीर्थचारित्र-प्रत्येकबुद्धबोधित-ज्ञानावगाहनान्तर-संख्याल्पबहुत्वत: साध्या: ॥९॥</option>");
       $optgrp.append("<option value='37 miss.html'><b>37 miss</b></option>");
       $optgrp.append("<option value='39 miss.html'><b>39 miss</b></option>");
    mySel.append($optgrp);
  mySel.selectmenu();
  mySel.selectmenu('refresh', true);
})
$( document ).ready(function() {
  mySel=$('select#select-native-1')
    $optgrp=$('<optgroup label="﻿अधिकार-१ (जीवाधिकार)">')
       $optgrp.append("<option value='001.html'><b>001</b> - ﻿सम्यग्दर्शनज्ञानचारित्राणि मोक्षमार्गः॥१॥</option>");
       $optgrp.append("<option value='002.html'><b>002</b> - ﻿तत्त्वार्थश्रद्धानं सम्यग्दर्शनम्॥२॥</option>");
       $optgrp.append("<option value='006.html'><b>006</b> - ﻿प्रमाणनयैरधिगमः॥६॥</option>");
       $optgrp.append("<option value='008.html'><b>008</b> - ﻿सत्संख्याक्षेत्रस्पर्शनकालान्तरभावाल्पबहुत्वैश्‍च॥८॥</option>");
       $optgrp.append("<option value='009.html'><b>009</b> - ﻿मतिश्रुतावधिमनःपर्ययकेवलानि ज्ञानम्॥९॥</option>");
       $optgrp.append("<option value='012.html'><b>012</b> - ﻿प्रत्यक्षमन्यत्॥१२॥</option>");
       $optgrp.append("<option value='020.html'><b>020</b> - ﻿श्रुतं मतिपूर्वं द्वयनेकद्वादशभेदम्‌॥२०॥</option>");
       $optgrp.append("<option value='030.html'><b>030</b> - ﻿एकादीनि भाज्यानि युगपदेकस्मिन्नाचतुर्भ्यः॥३०॥</option>");
       $optgrp.append("<option value='040.html'><b>040</b> - ﻿जीवभव्याभव्यत्वानि च॥७॥</option>");
       $optgrp.append("<option value='041.html'><b>041</b> - ﻿उपयोगो लक्षणम्॥८॥</option>");
       $optgrp.append("<option value='048.html'><b>048</b> - ﻿पंचेद्रियाणि॥१५॥</option>");
       $optgrp.append("<option value='051.html'><b>051</b> - ﻿लब्ध्युपयोगो भावेन्द्रियम्॥१८॥</option>");
       $optgrp.append("<option value='055.html'><b>055</b> - ﻿वनस्पत्यन्तानामेकम्॥२२॥</option>");
       $optgrp.append("<option value='066.html'><b>066</b> - ﻿जरायुजाण्डजपोतानां गर्भः॥३३॥</option>");
       $optgrp.append("<option value='082.html'><b>082</b> - ﻿शुभं विशुद्धमव्याघाति चाहारकं प्रमत्तसंयतस्यैव॥४९॥</option>");
       $optgrp.append("<option value='086.html'><b>086</b> - ﻿औपपादिक चरमोत्तम-देहाऽसंख्येय-वर्षायुषोsनपवर्त्यायुषः॥५३॥</option>");
       $optgrp.append("<option value='124.html'><b>124</b> - ﻿नृस्थितीपरावरे त्रिपल्योपमान्तर्मुहूर्ते॥३८॥</option>");
       $optgrp.append("<option value='167.html'><b>167</b> - ﻿लौकान्तिकानामष्टौ सागरोपमाणि सर्वेषाम् ॥४२॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿अधिकार-५ (अजीवाधिकार)">')
       $optgrp.append("<option value='168.html'><b>168</b> - ﻿अजीव-काया-धर्माधर्माकाश-पुद्गला: ॥१॥</option>");
       $optgrp.append("<option value='169.html'><b>169</b> - ﻿द्रव्याणि ॥२॥</option>");
       $optgrp.append("<option value='175.html'><b>175</b> - ﻿असंख्येया: प्रदेशा धर्माधर्मैकजीवानाम् ॥८॥</option>");
       $optgrp.append("<option value='176.html'><b>176</b> - ﻿आकाशस्यानन्ता: ॥९॥</option>");
       $optgrp.append("<option value='186.html'><b>186</b> - ﻿शरीरवाङ्मन:-प्राणापाना पुद्गलानाम् ॥१९॥</option>");
       $optgrp.append("<option value='189.html'><b>189</b> - ﻿वर्तना-परिणाम-क्रिया-परत्वापरत्वे च कालस्य ॥२२॥</option>");
       $optgrp.append("<option value='192.html'><b>192</b> - ﻿अणव: स्कन्धाश्च ॥२५॥</option>");
       $optgrp.append("<option value='211.html'><b>211</b> - ﻿स आस्रव: ॥२॥</option>");
       $optgrp.append("<option value='233.html'><b>233</b> - ﻿दर्शनविशुद्धिर्विनयसम्पन्नता-शील-व्रतेष्वनतीचारोऽभीक्ष्ण-ज्ञानोपयोगसंवेगौ शक्तितस्त्याग-तपसी साधुसमाधिर्वैयावृत्य-करणमर्हदाचार्य-बहुश्रुत-प्रवचन-भक्तिरावश्यकापरिहाणिर्मार्ग-प्रभावना-प्रवचनवत्सलत्वमिति तीर्थकरत्वस्य ॥२४॥</option>");
       $optgrp.append("<option value='241.html'><b>241</b> - ﻿क्रोध-लोभ-भीरुत्व-हास्य-प्रत्याख्यानान्यनुवीचि-भाषणं च पञ्च ॥५॥</option>");
       $optgrp.append("<option value='250.html'><b>250</b> - ﻿असदभिधानमनृतम् ॥१४॥</option>");
       $optgrp.append("<option value='258.html'><b>258</b> - ﻿मारणान्तिकीं सल्लेखनां जोषिता ॥२२॥</option>");
       $optgrp.append("<option value='259.html'><b>259</b> - ﻿शंका-कांक्षाविचिकित्सान्यदृष्टि-प्रशंसा-संस्तवा: सम्यग्दृष्टेरती-चारा: ॥२३॥</option>");
       $optgrp.append("<option value='263.html'><b>263</b> - ﻿स्तेनप्रयोग-तदाहृतादानविरुद्धराज्यातिक्रम-हीनाधिकमानोन्मान-प्रतिरूपक-व्यवहारा: ॥२७॥</option>");
       $optgrp.append("<option value='264.html'><b>264</b> - ﻿परविवाह करणेत्वरिका-परिगृहीतापरिगृहीता-गमनानङ्गक्रीडा-कामतीव्राभिनिवेशा: ॥२८॥</option>");
       $optgrp.append("<option value='265.html'><b>265</b> - ﻿क्षेत्रवास्तु-हिरण्यसुवर्ण-धन-धान्य-दासीदास-कुप्य-प्रमाणातिक्रमा: ॥२९॥</option>");
       $optgrp.append("<option value='266.html'><b>266</b> - ﻿ऊर्ध्वाधस्तिर्यग्व्यतिक्रमक्षेत्रवृद्धि-स्मृत्यंतराधानानि ॥३०॥</option>");
       $optgrp.append("<option value='267.html'><b>267</b> - ﻿आनयन-प्रेष्यप्रयोग-शब्दरूपानुपात-पुद्गलक्षेपा: ॥३१॥</option>");
       $optgrp.append("<option value='268.html'><b>268</b> - ﻿कन्दर्प-कौत्कुच्य-मौखर्यासमीक्ष्याधि-करणोपभोगपरिभोगानर्थक्यानि ॥३२॥</option>");
       $optgrp.append("<option value='272.html'><b>272</b> - ﻿सचित्त-निक्षेपापिधानपरव्यपदेश-मात्सर्यकालातिक्रमा: ॥३६॥</option>");
  mySel.append($optgrp);
    $optgrp=$('<optgroup label="﻿अधिकार-८ (बंधाधिकार)">')
       $optgrp.append("<option value='276.html'><b>276</b> - ﻿मिथ्यादर्शनाविरति-प्रमाद-कषाय-योगा बन्धहेतव: ॥१॥</option>");
       $optgrp.append("<option value='281.html'><b>281</b> - ﻿मतिश्रुतावधि-मन:पर्यय केवलानाम् ॥६॥</option>");
       $optgrp.append("<option value='284.html'><b>284</b> - ﻿दर्शनचारित्र-मोहनीयाकषाय-कषायवेदनीयाख्यास्त्रिद्वि-नव-षोडशभेदा: सम्यक्त्व-मिथ्यात्व-तदुभयान्यकषाय-कषायौ हास्यरत्यरति-शोक-भय-जुगुप्सा-स्त्री-पुन्नपुंसक-वेदा अनन्तानुबंध्य-प्रत्याख्यान-प्रत्याख्यान-संज्वलन-विकल्पाश्चैकश: क्रोध-मान-माया-लोभा: ॥९॥</option>");
       $optgrp.append("<option value='286.html'><b>286</b> - ﻿गति-जाति-शरीराङ्गोपाङ्गनिर्माण-बंधन-संघात-संस्थान-संहनन-स्पर्श-रस-गंध-वर्णानुपूर्व्यागुरुलघूपघात-परघातातपोद्योतोच्छ्वास-विहायोगतय: प्रत्येक-शरीर-त्रस-सुभग-सुस्वर-शुभ-सूक्ष्म-पर्याप्ति-स्थिरादेय यश: कीर्ति-सेतराणि तीर्थकरत्वं च ॥११॥</option>");
       $optgrp.append("<option value='304.html'><b>304</b> - ﻿तपसा निर्जरा च ॥३॥</option>");
       $optgrp.append("<option value='308.html'><b>308</b> - ﻿अनित्याशरण-संसारैकत्वान्य-त्वाशुच्यास्रवसंवर-निर्जरा-लोक-बोधिदुर्लभ-धर्म-स्वाख्यातत्त्वानु-चिन्तन-मनुप्रेक्षा: ॥७॥</option>");
       $optgrp.append("<option value='310.html'><b>310</b> - ﻿क्षुत्पिपासा-शीतोष्णदंश-मशक-नाग्न्यारति-स्त्री-चर्या-निषद्या-शय्याक्रोशवधयाचनालाभ-रोग-तृणस्पर्श-मल-सत्कारपुरस्कार-प्रज्ञाज्ञानादर्शनानि ॥९॥</option>");
       $optgrp.append("<option value='312.html'><b>312</b> - ﻿एकादश जिने ॥११॥</option>");
       $optgrp.append("<option value='323.html'><b>323</b> - ﻿आलोचना-प्रतिक्रमण-तदुभय-विवेक-व्युत्सर्ग-तपश्छेदपरिहारो-पस्थापना: ॥२२॥</option>");
       $optgrp.append("<option value='324.html'><b>324</b> - ﻿ज्ञान-दर्शन-चारित्रोपचारा: ॥२३॥</option>");
       $optgrp.append("<option value='328.html'><b>328</b> - ﻿उत्तम-संहननस्यैकाग्र-चिन्ता-निरोधो ध्यानमान्त-र्मुहूर्तात्॥२७॥</option>");
       $optgrp.append("<option value='337.html'><b>337</b> - ﻿आज्ञापाय-विपाक-संस्थान-विचयाय धर्म्यम् ॥३६॥</option>");
       $optgrp.append("<option value='338.html'><b>338</b> - ﻿शुक्ले चाद्ये पूर्व-विद:॥३७॥</option>");
       $optgrp.append("<option value='339.html'><b>339</b> - ﻿परे केवलिन: ॥३८॥</option>");
       $optgrp.append("<option value='340.html'><b>340</b> - ﻿पृथक्त्वैकत्व-वितर्क-सूक्ष्मक्रिया-प्रतिपाति-व्युपरत-क्रिर्यानिवर्तीनि ॥३९॥</option>");
       $optgrp.append("<option value='341.html'><b>341</b> - ﻿त्र्येकयोग-काययोगायोगानाम् ॥४०॥</option>");
       $optgrp.append("<option value='346.html'><b>346</b> - ﻿सम्यग्दृष्टि-श्रावक-विरता-नन्तवियोजक-दर्शनमोह-क्षपकोपशम-कोपशांत-मोहक्षपक-क्षीणमोह-जिना: क्रमशोऽसंख्येय-गुण-निर्जरा: ॥४५॥</option>");
       $optgrp.append("<option value='357.html'><b>357</b> - ﻿क्षेत्र-काल-गति-लिङ्ग-तीर्थचारित्र-प्रत्येकबुद्धबोधित-ज्ञानावगाहनान्तर-संख्याल्पबहुत्वत: साध्या: ॥९॥</option>");
    mySel.append($optgrp);
  mySel.selectmenu();
  mySel.selectmenu('refresh', true);
})
