document.write("<div id=पं-आशाधरजी class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='01.html'><font size=4><font color=darkPurple><b>01</b></font> - <font color=darkBlue>﻿मंगलाचरण</font></font></a></li>");
document.write("        <li><a href='02.html'><font size=4><font color=darkPurple><b>02</b></font> - <font color=darkGreen>﻿आत्‍मा को स्‍वयं ही स्‍वरूप की उपलब्धि कैसे?</font></font></a></li>");
document.write("        <li><a href='03.html'><font size=4><font color=darkPurple><b>03</b></font> - <font color=darkBlue>﻿अवृत से व्रत धारण श्रेष्ठ</font></font></a></li>");
document.write("        <li><a href='04.html'><font size=4><font color=darkPurple><b>04</b></font> - <font color=darkGreen>﻿व्रत से स्वर्ग-मोक्ष की प्राप्ति</font></font></a></li>");
document.write("        <li><a href='05.html'><font size=4><font color=darkPurple><b>05</b></font> - <font color=darkBlue>﻿स्वर्ग सुख का वर्णन</font></font></a></li>");
document.write("        <li><a href='06.html'><font size=4><font color=darkPurple><b>06</b></font> - <font color=darkGreen>﻿इन्द्रिय सुख-दुःख कल्पना जन्य</font></font></a></li>");
document.write("        <li><a href='07.html'><font size=4><font color=darkPurple><b>07</b></font> - <font color=darkBlue>﻿मोह ही अज्ञान</font></font></a></li>");
document.write("        <li><a href='08.html'><font size=4><font color=darkPurple><b>08</b></font> - <font color=darkGreen>﻿मोही जीव की पहचान</font></font></a></li>");
document.write("        <li><a href='09.html'><font size=4><font color=darkPurple><b>09</b></font> - <font color=darkBlue>﻿संसार का स्वरूप</font></font></a></li>");
document.write("        <li><a href='10.html'><font size=4><font color=darkPurple><b>10</b></font> - <font color=darkGreen>﻿दूसरों को दुखी करने से स्वयं दुःख की प्राप्ति</font></font></a></li>");
document.write("        <li><a href='11.html'><font size=4><font color=darkPurple><b>11</b></font> - <font color=darkBlue>﻿अज्ञान से राग-द्वेष द्वारा संसार परिभ्रमण</font></font></a></li>");
document.write("        <li><a href='12.html'><font size=4><font color=darkPurple><b>12</b></font> - <font color=darkGreen>﻿संसार में दुःख</font></font></a></li>");
document.write("        <li><a href='13.html'><font size=4><font color=darkPurple><b>13</b></font> - <font color=darkBlue>﻿संसार में सुख की कल्पना व्यर्थ</font></font></a></li>");
document.write("        <li><a href='14.html'><font size=4><font color=darkPurple><b>14</b></font> - <font color=darkGreen>﻿मोही जीव आने वाली विपत्तियों को भी नहीं देखता</font></font></a></li>");
document.write("        <li><a href='15.html'><font size=4><font color=darkPurple><b>15</b></font> - <font color=darkBlue>﻿मोही धन को काल (प्राण) से भी अधिक चाहता है </font></font></a></li>");
document.write("        <li><a href='16.html'><font size=4><font color=darkPurple><b>16</b></font> - <font color=darkGreen>﻿धन-कमाने की इच्छा - मोह</font></font></a></li>");
document.write("        <li><a href='17.html'><font size=4><font color=darkPurple><b>17</b></font> - <font color=darkBlue>﻿भोग-उपभोग दुःख के कारण</font></font></a></li>");
document.write("        <li><a href='18.html'><font size=4><font color=darkPurple><b>18</b></font> - <font color=darkGreen>﻿शरीर दुःख का कारण</font></font></a></li>");
document.write("        <li><a href='19.html'><font size=4><font color=darkPurple><b>19</b></font> - <font color=darkBlue>﻿शरीर के उपकार में आत्मा का अपकार</font></font></a></li>");
document.write("        <li><a href='20.html'><font size=4><font color=darkPurple><b>20</b></font> - <font color=darkGreen>﻿ध्यान से सभी इष्ट की प्राप्ति</font></font></a></li>");
document.write("        <li><a href='21.html'><font size=4><font color=darkPurple><b>21</b></font> - <font color=darkBlue>﻿आत्मा का स्वरूप</font></font></a></li>");
document.write("        <li><a href='22.html'><font size=4><font color=darkPurple><b>22</b></font> - <font color=darkGreen>﻿मन और इन्द्रियों को वश में कर ध्यान करें</font></font></a></li>");
document.write("        <li><a href='23.html'><font size=4><font color=darkPurple><b>23</b></font> - <font color=darkBlue>﻿वैयावृत्ति की प्रेरणा</font></font></a></li>");
document.write("        <li><a href='24.html'><font size=4><font color=darkPurple><b>24</b></font> - <font color=darkGreen>﻿ध्यान द्वारा कर्मों की निर्जरा</font></font></a></li>");
document.write("        <li><a href='25.html'><font size=4><font color=darkPurple><b>25</b></font> - <font color=darkBlue>﻿आत्मा में आत्मा द्वारा आत्मा का ध्यान</font></font></a></li>");
document.write("        <li><a href='26.html'><font size=4><font color=darkPurple><b>26</b></font> - <font color=darkGreen>﻿ममत्व भाव बंध का करण, अत: हेय</font></font></a></li>");
document.write("        <li><a href='27.html'><font size=4><font color=darkPurple><b>27</b></font> - <font color=darkBlue>﻿भेद-ज्ञान की प्रेरणा</font></font></a></li>");
document.write("        <li><a href='28.html'><font size=4><font color=darkPurple><b>28</b></font> - <font color=darkGreen>﻿देह के सम्बन्ध को दुःख का करण जानकर छोडो </font></font></a></li>");
document.write("        <li><a href='29.html'><font size=4><font color=darkPurple><b>29</b></font> - <font color=darkBlue>﻿देह से भिन्नता</font></font></a></li>");
document.write("        <li><a href='30.html'><font size=4><font color=darkPurple><b>30</b></font> - <font color=darkGreen>﻿भोगों की इच्छा व्यर्थ</font></font></a></li>");
document.write("        <li><a href='31.html'><font size=4><font color=darkPurple><b>31</b></font> - <font color=darkBlue>﻿जीव मोह को आसानी से क्यों नहीं छोड़ता</font></font></a></li>");
document.write("        <li><a href='32.html'><font size=4><font color=darkPurple><b>32</b></font> - <font color=darkGreen>﻿अपनी भलाई में लगाने की प्रेरणा</font></font></a></li>");
document.write("        <li><a href='33.html'><font size=4><font color=darkPurple><b>33</b></font> - <font color=darkBlue>﻿स्व-पर के भेद को जानना - मोक्ष का कारण</font></font></a></li>");
document.write("        <li><a href='34.html'><font size=4><font color=darkPurple><b>34</b></font> - <font color=darkGreen>﻿अपना गुरु आप ही है</font></font></a></li>");
document.write("        <li><a href='35.html'><font size=4><font color=darkPurple><b>35</b></font> - <font color=darkBlue>﻿पर ज्ञान का कारण नहीं, निमित्त-मात्र होता है</font></font></a></li>");
document.write("        <li><a href='36.html'><font size=4><font color=darkPurple><b>36</b></font> - <font color=darkGreen>﻿एकान्त में क्षोभ-रहित होकर आत्मा में स्थित रहने का उपदेश</font></font></a></li>");
document.write("        <li><a href='37.html'><font size=4><font color=darkPurple><b>37</b></font> - <font color=darkBlue>﻿आत्मानुभवी के लक्षण</font></font></a></li>");
document.write("        <li><a href='38.html'><font size=4><font color=darkPurple><b>38</b></font> - <font color=darkGreen>﻿आत्मा में रत रहने वाले को विषय भोग अरुचिकर</font></font></a></li>");
document.write("        <li><a href='39.html'><font size=4><font color=darkPurple><b>39</b></font> - <font color=darkBlue>﻿योगी के लिए समस्त संसार एक इंद्रजाल</font></font></a></li>");
document.write("        <li><a href='40.html'><font size=4><font color=darkPurple><b>40</b></font> - <font color=darkGreen>﻿योगी एकान्त-प्रिय होता है</font></font></a></li>");
document.write("        <li><a href='41.html'><font size=4><font color=darkPurple><b>41</b></font> - <font color=darkBlue>﻿आत्म-स्वरूप में स्थिर के सभी व्यवहार गौण</font></font></a></li>");
document.write("        <li><a href='42.html'><font size=4><font color=darkPurple><b>42</b></font> - <font color=darkGreen>﻿योगी विकल्पातीत होता है</font></font></a></li>");
document.write("        <li><a href='43.html'><font size=4><font color=darkPurple><b>43</b></font> - <font color=darkBlue>﻿पर के संस्कार के त्याग का उपदेश</font></font></a></li>");
document.write("        <li><a href='44.html'><font size=4><font color=darkPurple><b>44</b></font> - <font color=darkGreen>﻿पर पदार्थों से अस्संग ध्यान से निर्जरा</font></font></a></li>");
document.write("        <li><a href='45.html'><font size=4><font color=darkPurple><b>45</b></font> - <font color=darkBlue>﻿अपने आपके लिए ही उद्यम का उपदेश</font></font></a></li>");
document.write("        <li><a href='46.html'><font size=4><font color=darkPurple><b>46</b></font> - <font color=darkGreen>﻿अज्ञानी को कर्म नहीं छोड़ते</font></font></a></li>");
document.write("        <li><a href='47.html'><font size=4><font color=darkPurple><b>47</b></font> - <font color=darkBlue>﻿आत्म-ध्यान से सुख की प्राप्ति</font></font></a></li>");
document.write("        <li><a href='48.html'><font size=4><font color=darkPurple><b>48</b></font> - <font color=darkGreen>﻿ध्यान का फल</font></font></a></li>");
document.write("        <li><a href='49.html'><font size=4><font color=darkPurple><b>49</b></font> - <font color=darkBlue>﻿मुमुक्षुओं को सम्यग्ज्ञान की भावना का उपदेश</font></font></a></li>");
document.write("        <li><a href='50.html'><font size=4><font color=darkPurple><b>50</b></font> - <font color=darkGreen>﻿जीव-पुद्गल भिन्नता ही सारभूत</font></font></a></li>");
document.write("        <li><a href='51.html'><font size=4><font color=darkPurple><b>51</b></font> - <font color=darkBlue>﻿उपसंहार और टीकाकार द्वारा प्रशस्ति</font></font></a></li>");
document.write("</ul></div>");
