document.write("<div id=पं-सदासुखदासजी class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='001.html'><font size=4><font color=darkPurple><b>001</b></font> - <font color=darkBlue>﻿मंगलाचरण</font></font></a></li>");
document.write("        <li><a href='002.html'><font size=4><font color=darkPurple><b>002</b></font> - <font color=darkGreen>﻿आराधनाओं के नाम और स्वरूप</font></font></a></li>");
document.write("        <li><a href='003.html'><font size=4><font color=darkPurple><b>003</b></font> - <font color=darkBlue>﻿दो प्रकार की आराधना</font></font></a></li>");
document.write("        <li><a href='004.html'><font size=4><font color=darkPurple><b>004</b></font> - <font color=darkGreen>﻿दो प्रकार की आराधना का हे</font></font></a></li>");
document.write("        <li><a href='005.html'><font size=4><font color=darkPurple><b>005</b></font> - <font color=darkBlue>﻿आगे सम्यक्‌त्व के बिना जो ज्ञान है, वह अज्ञान है – ऐसा कहते हैं–</font></font></a></li>");
document.write("        <li><a href='006.html'><font size=4><font color=darkPurple><b>006</b></font> - <font color=darkGreen>﻿अब चारित्र-आराधना में गर्भित तप आराधना को दिखाते हैं–</font></font></a></li>");
document.write("        <li><a href='007.html'><font size=4><font color=darkPurple><b>007</b></font> - <font color=darkBlue>﻿अब कहते हैं कि अविरत सम्यग्द्रष्टि के भी तपश्चरण महान उपकारी नहीं होता है –</font></font></a></li>");
document.write("        <li><a href='008.html'><font size=4><font color=darkPurple><b>008</b></font> - <font color=darkGreen>﻿चारित्राराधना में सभी आराधनाएँ गर्भित हैं -</font></font></a></li>");
document.write("</ul></div>");
