document.write("<div id=आर्यिका-ज्ञानमती class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='01.html'><font size=4><br><font size=5 color=black><b>﻿मंगलाचरण </b></font><br><br><font color=darkPurple><b>01</b></font> - <font color=darkBlue>﻿मंगलाचरण</font></font></a></li>");
document.write("        <li><a href='02.html'><font size=4><br><font size=5 color=black><b>﻿छह-द्रव्य अधिकार </b></font><br><br><font color=darkPurple><b>02</b></font> - <font color=darkGreen>﻿जीव द्रव्य के नव अधिकार</font></font></a></li>");
document.write("        <li><a href='03.html'><font size=4><font color=darkPurple><b>03</b></font> - <font color=darkBlue>﻿जीवत्व का लक्षण</font></font></a></li>");
document.write("        <li><a href='04.html'><font size=4><font color=darkPurple><b>04</b></font> - <font color=darkGreen>﻿उपयोग का वर्णन</font></font></a></li>");
document.write("        <li><a href='05.html'><font size=4><font color=darkPurple><b>05</b></font> - <font color=darkBlue>﻿ज्ञानोपयोग के भेद</font></font></a></li>");
document.write("        <li><a href='06.html'><font size=4><font color=darkPurple><b>06</b></font> - <font color=darkGreen>﻿उभयनय से उपयोग का लक्षण</font></font></a></li>");
document.write("        <li><a href='07.html'><font size=4><font color=darkPurple><b>07</b></font> - <font color=darkBlue>﻿जीव अमूर्तिक है</font></font></a></li>");
document.write("        <li><a href='08.html'><font size=4><font color=darkPurple><b>08</b></font> - <font color=darkGreen>﻿जीव कर्ता है</font></font></a></li>");
document.write("        <li><a href='09.html'><font size=4><font color=darkPurple><b>09</b></font> - <font color=darkBlue>﻿जीव भोक्ता है</font></font></a></li>");
document.write("        <li><a href='10.html'><font size=4><font color=darkPurple><b>10</b></font> - <font color=darkGreen>﻿जीव स्वदेह बराबर है</font></font></a></li>");
document.write("        <li><a href='11.html'><font size=4><font color=darkPurple><b>11</b></font> - <font color=darkBlue>﻿जीव संसारी है</font></font></a></li>");
document.write("        <li><a href='12.html'><font size=4><font color=darkPurple><b>12</b></font> - <font color=darkGreen>﻿चौदह जीव समास</font></font></a></li>");
document.write("        <li><a href='13.html'><font size=4><font color=darkPurple><b>13</b></font> - <font color=darkBlue>﻿उभयनय से संसारी जीव का स्वरूप</font></font></a></li>");
document.write("        <li><a href='14.html'><font size=4><font color=darkPurple><b>14</b></font> - <font color=darkGreen>﻿सिद्ध और ऊर्ध्वगमन का स्वरूप</font></font></a></li>");
document.write("        <li><a href='15.html'><font size=4><font color=darkPurple><b>15</b></font> - <font color=darkBlue>﻿अजीव द्रव्य और उनमें मूर्तिक-अमूर्तिक द्रव्य</font></font></a></li>");
document.write("        <li><a href='16.html'><font size=4><font color=darkPurple><b>16</b></font> - <font color=darkGreen>﻿पुद्गल द्रव्य की विभाव व्यंजन पर्यायें</font></font></a></li>");
document.write("        <li><a href='17.html'><font size=4><font color=darkPurple><b>17</b></font> - <font color=darkBlue>﻿धर्म द्रव्य का स्वरूप</font></font></a></li>");
document.write("        <li><a href='18.html'><font size=4><font color=darkPurple><b>18</b></font> - <font color=darkGreen>﻿अधर्म द्रव्य का स्वरूप</font></font></a></li>");
document.write("        <li><a href='19.html'><font size=4><font color=darkPurple><b>19</b></font> - <font color=darkBlue>﻿आकाश द्रव्य का स्वरूप</font></font></a></li>");
document.write("        <li><a href='20.html'><font size=4><font color=darkPurple><b>20</b></font> - <font color=darkGreen>﻿लोकाकाश-अलोकाकाश का स्वरूप</font></font></a></li>");
document.write("        <li><a href='21.html'><font size=4><font color=darkPurple><b>21</b></font> - <font color=darkBlue>﻿कालद्रव्य का स्वरूप</font></font></a></li>");
document.write("        <li><a href='22.html'><font size=4><font color=darkPurple><b>22</b></font> - <font color=darkGreen>﻿काल द्रव्य की संख्या</font></font></a></li>");
document.write("        <li><a href='23.html'><font size=4><font color=darkPurple><b>23</b></font> - <font color=darkBlue>﻿द्रव्य और अस्तिकाय के भेद</font></font></a></li>");
document.write("        <li><a href='24.html'><font size=4><font color=darkPurple><b>24</b></font> - <font color=darkGreen>﻿अस्तिकाय का स्वरूप और नाम की सार्थकता</font></font></a></li>");
document.write("        <li><a href='25.html'><font size=4><font color=darkPurple><b>25</b></font> - <font color=darkBlue>﻿द्रव्यों की प्रदेश संख्या</font></font></a></li>");
document.write("        <li><a href='26.html'><font size=4><font color=darkPurple><b>26</b></font> - <font color=darkGreen>﻿पुद्गल का परमाणु अस्तिकाय है</font></font></a></li>");
document.write("        <li><a href='27.html'><font size=4><font color=darkPurple><b>27</b></font> - <font color=darkBlue>﻿प्रदेश का लक्षण और उसकी योग्यता</font></font></a></li>");
document.write("        <li><a href='28.html'><font size=4><br><font size=5 color=black><b>﻿सात-तत्त्व अधिकार </b></font><br><br><font color=darkPurple><b>28</b></font> - <font color=darkGreen>﻿सात तत्त्व</font></font></a></li>");
document.write("        <li><a href='29.html'><font size=4><font color=darkPurple><b>29</b></font> - <font color=darkBlue>﻿भावास्रव और द्रव्यास्रव</font></font></a></li>");
document.write("        <li><a href='30.html'><font size=4><font color=darkPurple><b>30</b></font> - <font color=darkGreen>﻿भावास्रव के भेद</font></font></a></li>");
document.write("        <li><a href='31.html'><font size=4><font color=darkPurple><b>31</b></font> - <font color=darkBlue>﻿द्रव्यास्रव का स्वरूप और भेद</font></font></a></li>");
document.write("        <li><a href='32.html'><font size=4><font color=darkPurple><b>32</b></font> - <font color=darkGreen>﻿भावबंध और द्रव्यबंध</font></font></a></li>");
document.write("        <li><a href='33.html'><font size=4><font color=darkPurple><b>33</b></font> - <font color=darkBlue>﻿बन्ध के भेद और कारण</font></font></a></li>");
document.write("        <li><a href='34.html'><font size=4><font color=darkPurple><b>34</b></font> - <font color=darkGreen>﻿भावसंवर और द्रव्यसंवर का स्वरूप</font></font></a></li>");
document.write("        <li><a href='35.html'><font size=4><font color=darkPurple><b>35</b></font> - <font color=darkBlue>﻿भावसंवर के भेद</font></font></a></li>");
document.write("        <li><a href='36.html'><font size=4><font color=darkPurple><b>36</b></font> - <font color=darkGreen>﻿निर्जरा का स्वरूप</font></font></a></li>");
document.write("        <li><a href='37.html'><font size=4><font color=darkPurple><b>37</b></font> - <font color=darkBlue>﻿मोक्ष का स्वरूप और उसके भेद</font></font></a></li>");
document.write("        <li><a href='38.html'><font size=4><font color=darkPurple><b>38</b></font> - <font color=darkGreen>﻿पुण्य और पाप पदार्थ</font></font></a></li>");
document.write("        <li><a href='39.html'><font size=4><br><font size=5 color=black><b>﻿मोक्ष-अधिकार </b></font><br><br><font color=darkPurple><b>39</b></font> - <font color=darkBlue>﻿व्यवहार और निश्चय मोक्ष मार्ग</font></font></a></li>");
document.write("        <li><a href='40.html'><font size=4><font color=darkPurple><b>40</b></font> - <font color=darkGreen>﻿आत्मा ही निश्चयनय से मोक्ष मार्ग है</font></font></a></li>");
document.write("        <li><a href='41.html'><font size=4><font color=darkPurple><b>41</b></font> - <font color=darkBlue>﻿व्यवहार सम्यग्दर्शन</font></font></a></li>");
document.write("        <li><a href='42.html'><font size=4><font color=darkPurple><b>42</b></font> - <font color=darkGreen>﻿सम्यग्ज्ञान का स्वरूप</font></font></a></li>");
document.write("        <li><a href='43.html'><font size=4><font color=darkPurple><b>43</b></font> - <font color=darkBlue>﻿दर्शनोपयोग का स्वरूप</font></font></a></li>");
document.write("        <li><a href='44.html'><font size=4><font color=darkPurple><b>44</b></font> - <font color=darkGreen>﻿दर्शन और ज्ञान का क्रम</font></font></a></li>");
document.write("        <li><a href='45.html'><font size=4><font color=darkPurple><b>45</b></font> - <font color=darkBlue>﻿व्यवहार सम्यक्चारित्र और उसके भेद</font></font></a></li>");
document.write("        <li><a href='46.html'><font size=4><font color=darkPurple><b>46</b></font> - <font color=darkGreen>﻿निश्चयचारित्र का लक्षण</font></font></a></li>");
document.write("        <li><a href='47.html'><font size=4><font color=darkPurple><b>47</b></font> - <font color=darkBlue>﻿ध्यानाभ्यास की प्ररेणा</font></font></a></li>");
document.write("        <li><a href='48.html'><font size=4><font color=darkPurple><b>48</b></font> - <font color=darkGreen>﻿ध्यान का उपाय</font></font></a></li>");
document.write("        <li><a href='49.html'><font size=4><font color=darkPurple><b>49</b></font> - <font color=darkBlue>﻿ध्यान के योग्य मंत्र</font></font></a></li>");
document.write("        <li><a href='50.html'><font size=4><font color=darkPurple><b>50</b></font> - <font color=darkGreen>﻿अरिहंत परमेष्ठी का लक्षण</font></font></a></li>");
document.write("        <li><a href='51.html'><font size=4><font color=darkPurple><b>51</b></font> - <font color=darkBlue>﻿सिद्ध परमेष्ठी का स्वरूप</font></font></a></li>");
document.write("        <li><a href='52.html'><font size=4><font color=darkPurple><b>52</b></font> - <font color=darkGreen>﻿आचार्य परमेष्ठी का स्वरूप</font></font></a></li>");
document.write("        <li><a href='53.html'><font size=4><font color=darkPurple><b>53</b></font> - <font color=darkBlue>﻿उपाध्याय परमेष्ठी का स्वरूप</font></font></a></li>");
document.write("        <li><a href='54.html'><font size=4><font color=darkPurple><b>54</b></font> - <font color=darkGreen>﻿साधु परमेष्ठी का स्वरूप</font></font></a></li>");
document.write("        <li><a href='55.html'><font size=4><font color=darkPurple><b>55</b></font> - <font color=darkBlue>﻿निश्चयध्यान का लक्षण</font></font></a></li>");
document.write("        <li><a href='56.html'><font size=4><font color=darkPurple><b>56</b></font> - <font color=darkGreen>﻿परमध्यान का लक्षण</font></font></a></li>");
document.write("        <li><a href='57.html'><font size=4><font color=darkPurple><b>57</b></font> - <font color=darkBlue>﻿ध्यान का कारण</font></font></a></li>");
document.write("        <li><a href='58.html'><font size=4><font color=darkPurple><b>58</b></font> - <font color=darkGreen>﻿ग्रन्थकर्ता का लघुता प्रकाशन</font></font></a></li>");
document.write("</ul></div>");
