document.write("<div id=श्रीमद्-प्रभाचन्द्र class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='000_मंगलाचरण.html'><font size=4><font color=darkPurple><b>000_मंगलाचरण</b></font> - <font color=darkBlue>﻿मंगलाचरण</font></font></a></li>");
document.write("        <li><a href='001.html'><font size=4><font color=darkPurple><b>001</b></font> - <font color=darkGreen>﻿मंगलाचरण</font></font></a></li>");
document.write("        <li><a href='002.html'><font size=4>002</font></a></li>");
document.write("</ul></div>");
document.write("<div id=क्षु-मनोहरजी-वर्णी class='dropdown dropdown-tip dropdown-scroll'>");
document.write("  <ul class=dropdown-menu>");
document.write("        <li><a href='000_मंगलाचरण.html'><font size=4><font color=darkPurple><b>000_मंगलाचरण</b></font> - <font color=darkGreen>﻿मंगलाचरण</font></font></a></li>");
document.write("        <li><a href='02.html'><font size=4>02</font></a></li>");
document.write("</ul></div>");
